Ontotext-AD/graphdb-workbench

- package.json
Currently we deploy the whole application code along with the libraries. That's why we publish only the src folder. Next step is to clean up the code and create bundles from it using webpack. Then we would need to publish just the dist folder with the created bundles.
> Define which directory should be published in npm registry

- karma.conf.js
- sonar-project.properties
Without this the coverage report was misleading.
Configured sonar to analyze styles and pages instead of just the java
script (excluding libraries)
> Reconfigured coverage to include sources without tests

- .travis.yml
- package-lock.json
- scripts/run-cypress-tests.sh
- src/index.html
- src/js/angular/import/templates/filesTable.html
- src/js/angular/import/templates/settingsModal.html
- src/js/angular/import/templates/textSnippet.html
- src/js/angular/import/templates/urlImport.html
- src/pages/import.html
- test-cypress/fixtures/example.json
- test-cypress/fixtures/repo-template.json
- test-cypress/integration/import/import.server.files.spec.js
- test-cypress/integration/import/import.user.data.spec.js
- test-cypress/integration/repository/repository-commands.spec.js
- test-cypress/steps/import-steps.js
- test-cypress/support/commands.js
- test-cypress/support/index.js
- test-cypress/support/repository-commands.js
Added import-steps file with static utility functions for working with the user and server import pages.
Added several classes in the import templates to simplify selectors in Cypress and ease the testing.
Additional changes:
- Changed retry count to 1 instead of 2.
- Tried to stabilize the selectRepo command
- Moved coveralls step in after_scrip section in Travis config. Sometimes the coveralls service is down which breaks any build in the meantime.
> Stabilizing import tests + code reorganization & simplification

- .editorconfig
- .gitignore
- cypress.json
- package-lock.json
- package.json
- scripts/run-cypress-tests.sh
- src/js/angular/sparql/directives/sparql-tab.directive.js
- src/js/angular/sparql/templates/modal/query-sample.html
- src/js/angular/sparql/templates/query-editor.html
- src/pages/sparql.html
- test-cypress/fixtures/queries/add-statement.txt
- test-cypress/fixtures/queries/construct-query.sparql
- test-cypress/fixtures/queries/prefix-query.sparql
- test-cypress/fixtures/url-import-template.json
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/plugins/index.js
- test-cypress/support/commands.js
- test-cypress/support/import-commands.js
- test-cypress/support/index.js
- test-cypress/support/repository-commands.js
* The specification now makes use of the repo creation and deletion via REST commands
* Simplified selectors and functions
* Added proper checks
Added Cypress command for URL importing via REST call.
Moved the RDF snippet import command to import-commands.js
Added a few selectors in the sparql templates for easier selection in
the Cypress tests.
> Rewrote SPARQL page specifications

- src/pages/webapi.html
- test-cypress/integration/help/rest-api.spec.js
- test-cypress/support/commands.js
Tested the presence of Swagger's iframe, GraphDB and RDF4J sections and the operations for each controller.
Added custom command for encapsulating iframes content due to Cypress inability to work with them out of the box. The command will yield the frame's body and allow further chaining of commands and assertions.
> Added Cypress tests for the Swagger documentation page

- src/pages/namespaces.html
No namespaces in repository message should not be based on filtered namespaces. Search to filter namespaces should be always visible.
> GDB-3817 No namespaces warning fix

- src/js/angular/core/templates/core-errors.html
- src/js/angular/sparql/templates/query-editor.html
- src/pages/namespaces.html
- test-cypress/integration/home/workbench.home.spec.js
- test-cypress/integration/import/import.user.data.spec.js
- test-cypress/integration/monitor/monitor.queries.spec.js
- test-cypress/integration/monitor/monitor.resources.spec.js
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/integration/setup/autocomplete.spec.js
- test-cypress/integration/setup/namespaces.spec.js
- test-cypress/integration/setup/rdf-rank.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/steps/home-steps.js
- test-cypress/steps/import-steps.js
- test-cypress/support/repository-commands.js
- Replaced `parentsUntil().last()` with `closest()` or simply `parent()`
- Updated the check in repositories default tests to simply check that the repo is not selected instead of not having a selected repo. For some reason, sometimes in Travis there is a selected repo or the repo dropdown is not yet fully loaded and the old check for no selected repo was failing.
- Added increased timeout in `getModal()` functions to allow the dialog to fully appear without any  angular animations in progress. It should not be needed but it seems in Travis animations are slow.
- Updated saved query tests to forcefully click the action buttons because Cypress sometimes determines them as not visible (having 0x0 dimensions) although they are visible and clickable and the checks for these pass before …
> Fixing flaky Cypress tests

- test-cypress/steps/import-steps.js
Animation library applies set of status classes around the base animated class. In this case the base animated class is `fade` and the animation lib applies classes like `in-add`, `in-add-active`, `in-remove`, 
`in-remove-active`. When animation is complete it seems that just `fade in` classes remains.
> Fix test for not finding import button in modal dialog

- test-cypress/integration/sparql/sparql.menu.spec.js
Sometimes the test fails because the dropdown menu button is not fully visualized most likely because the results are not yet rendered
> Added wait before verifying the SPARQL download menu

- .travis.yml
The previous restriction allowed builds only when the target branch = master or a tag with specific name pushed.
Now every tag would be allowed too.
> Updated Travis config to allow PR builds to feature branches.

- webpack.config.common.js
Styles bootstrap and font-awesome were exposed in dist for access from openrefine module which is deployed with GDB
> Fix missing styles for ontorefine in GDB

- webpack.config.common.js
Styles bootstrap and font-awesome were exposed in dist for access from openrefine module which is deployed with GDB
> GDB-3909 Expose styles for access from openrefine module

- webpack.config.common.js
Bundle font-awesome using its installation package in node_modules because it's unavailable in src anymore.
> Properly bundle font-awesome

- test-cypress/integration/setup/connectors-lucene.spec.js
Seems that there are two elements with class creating-connector-dialog and sometimes the wrong is checked for visibility. From jenkins:
_This element '<div.modal-header.creating-connector-dialog>' is not visible because its parent '<div.ng-hide>' has CSS property: 'display: none'_
Tune the selector with the parent class. We are looking for the element in the modal.
> GDB-3936 Flaky connector test

- src/js/angular/explore/controllers.js
- test-cypress/integration/explore/graphs.overview.spec.js
The library uses an older version of the jquery library which used to pass the xhr as first argument to the success callback. With the latest version thou, the first argument is the response data itself and that fact forces the yasr to falback the response rendering to the raw view plugin instead of the table view. This is due to inability to locate the response headers used internally to resolve the view type.
Fixed by inverting the arguments when pass them down to yasr.
Also extended tests to detect the proper view is rendered.
Jira: https://ontotext.atlassian.net/browse/GDB-3939
> GDB-3939 yasr expect xhr argument to be first when call setResponse

- src/pages/graphs-visualizations.html
Loading node details in visual graph loads also an image if present. ng-show tries to fetch the image even there is none. Replaced with ng-if to remove this element at all.
> GDB-3924 Fix error no image in visual graph

- src/js/angular/clustermanagement/app.js
- src/js/angular/graphexplore/app.js
- src/js/angular/resources/app.js
- src/vendor.js
Found that the d3 was referenced only in clustermanagement, graphexplore and resources modules, so the import was moved only for those modules and removed from the vendor's bundle. This way it won't be preloaded unnecessarily but only when it's needed.
Jira: https://ontotext.atlassian.net/browse/GDB-3891
> Optimize d3 library loading

- test-cypress/integration/explore/similarity.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/support/sparql-commands.js
* Forced click on saved query link. I think it's safe to force it there as other validations are successful before: opened popover, present link with the query name title.
* Removed some code duplications.
* Verify sparql query value directly through codemirror api instead through the editor's UI as it's not easy to detect when the editor has finished the rendering which makes the tests flaky.
* Force mouseover event in saved queries popover to show the action bar. Current implementation of the saved queries popup always render the action bar next to each query item but it's just hidden with opacity: 0. So IMO it's safe to force it here.
> Cypress tests stabilization

- .travis.yml
Due to some issues with the authorization token sonarcloud fails with
`ERROR: Error during SonarQube Scanner execution
ERROR: Not authorized. Please check the properties sonar.login and sonar.password.`
https://travis-ci.community/t/sonarcloud-fails-to-authorize/5845
> Sonar will not break the build

- src/app.js
- src/css/rdf-details-side-panel.css
- src/pages/domainRangeInfo.html
- src/pages/graphs-visualizations.html
- src/pages/rdfClassHierarchyInfo.html
* The tooltip from angular-ui-bootstrap is configured once when it's loaded.
* The angular-pageslide-directive which was updated to its latest version 2.2.0 seems to have dropped the support for ps-custom-top parameter. Fixed by setting the top position within the stylesheet.
Ticket: https://ontotext.atlassian.net/browse/GDB-4050
> Fix ui related issues

- .travis.yml
Removed token property from .travis.yml as it's not needed and seems to break the task.
> Enable sonar analysis again

- test-cypress/cypress.json
- test-cypress/package.json
- test-cypress/support/index.js
Updated retries plugin, added 2 retries on test fail in order to identify flaky tests vs not working tests, added config to keep less tests in memory (may fix a hang that happens sometimes)
> Retry failed tests, reduced tests in memory

- test-cypress/integration/import/onto-refine.spec.js
Skip refine test which fail because of external reconciliation service. Cannot find a quick fix.
> Skip refine test

- src/app.js
- src/js/angular/security/app.js
Currently the interceptor is attached when you access one of the user endpoints (login, user*). This means that the interceptor is attached when you hit the login endpoint  after securityInit is triggered (in security initialization). This is error prone since if you do not hit the login page for some reason (error during security init), the interceptor will not be attached.
> GDB-4123 Register unauthorized interceptor in core

- webpack.config.dev.js
When executing queries from onto-refine rdf-bridge endpoint is hit. This should be proxied also in workbench dev mode.
> GDB-4127 Proxy rdf-bridge properly

- src/js/angular/repositories/controllers.js
Added message in confirmation pop up window on edit repository, saying "For the changes to take effect, restart of GraphDB needed".
> GDB-4113 Added message in confirmation pop up window on edit repository

- src/js/angular/controllers.js
- src/js/angular/core/interceptors/unauthorized.interceptor.js
- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/rest/security.rest.service.js
- src/js/angular/security/templates/user.html
- src/template.html
- test/export/controllers.spec.js
- test/resource/controllers.spec.js
- test/security/controllers.spec.js
- test/security/services.spec.js
- webpack.config.dev.js
When security is on and we do not have valid principal and auth token (current user session), try to authenticate with kerberos. Send a request during security initialization to GDB to get currently authenticated user if present and if it is authenticated with negotiate header leave security to negotiate mechanism. This means leave the browser set the 'Authorization' header obtained from kerberos.
This mimics in the workbench automatic user login. In these cases logout for the user is not visible. 
Redirect to login when authentication fails.
A cookie 'auth.negotiate' is kept because we need to know that when we have principal but no auth token, this is because authentication is left to negotiate mechanism.
> Gdb 4053 respect negotiate authentication

- package-lock.json
- package.json
- src/css/yasr.custom.css
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/export/controllers.js
- src/js/angular/import/controllers.js
- src/js/angular/import/templates/urlImport.html
- src/js/angular/utils/file-types.js
- src/js/lib/yasr.bundled.js
- test-cypress/package-lock.json
- test-cypress/package.json
Render application/x-sparqlstar-results+json results that contain JSON with triple entities in YASR table view.
- Use YASR editor from Ontotext-AD/YASR-Ontotext#2
- Change YASR accept header to acceptHeaderSelect: "application/x-sparqlstar-results+json.."
- Execute Select query over RDF* data and see the results with triples in the YASR table in SPARQL view
- Export results in JSON*  and TSV*
> GDB-4248 Extend YASR table view to render SPARQL* Tuple results

- test-cypress/package-lock.json
- test-cypress/package.json
Force new minimist version to fix vulnerability issues, cypress depends on a vulnerable version and new cypress also, so cannot be upgraded
> GDB-4386  Force minimist 1.2.5 on test-cypress

- package-lock.json
- package.json
- test-cypress/package-lock.json
- test-cypress/package.json
Force resolution execution in package.json breaks package installation, remove it and bump version for release
> GDB-4386 remove force resolution from test-cypress/package.json and prepare versions for release

- src/js/angular/core/directives/fit-text.directive.js
- src/js/angular/explore/app.js
- src/js/angular/explore/fit-text.directive.js
- src/pages/explore.html
The directive manipulates the font size of DOM elements that they fill the width of a parent element. Desired max and min font size can be passed as argument, or get from source. Works with window resize, dynamic recalculates font size on parent changes. Line heights and display property are preserved.
Related to GDB-4400 Resource view: Reduce the font of nested triples in the resource view
> GDB-4400 Provides font auto resize to match parent directive

- src/js/angular/ontorefine/app.js
Provides messaging between OntoRefine iframe and it's parent window
Related to GDB-4848 OntoRefine: No save before exit confirmation when there are unsaved changes
> GDB-4848 OntoRefine: Mapper exit confirmation when unsaved changes

- src/js/angular/core/directives/queryeditor/query-editor.controller.js
If sesameType "graphdb:OntopRepository" of active repository is detected #sameAs button is disabled, currentQuery.sameAs and nocount are set to true. On explain and update "Explain not supported for Virtual repositories." and "Updates are not supported for Virtual repositories." messages are shown to the user.
> GDB-5019 Stop count queries, updates and disable sameAs for Virtual repositories

- src/js/angular/controllers.js
- src/js/angular/core/directives/queryeditor/query-editor.controller.js
- src/js/angular/core/services/repositories.service.js
- src/js/angular/core/templates/core-errors.html
Added check for Virtual repositories in some views that need write access to them. If such repository is detected, proper message is shown to the user, saying "Some functionalities are not available because repository <repo_name> is read-only virtual repository" and are listed such repos, which are not Virtual. Removed unnecessary added listener on repositoryIsSet in query-editor.controller.js
> GDB-5021 Check for repository of type Ontop in "Autocomplete", "RDF Rank", "Connectors" and "Import" views

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
Based on check if query is CONSTRUCT and repo is of type Ontop,  comments are removed from original query.
> GDB-5083 Construct queries with comments, containing CONSTRUCT or WHERE in them throw an error on execution

- .gitignore
- scripts/run-cypress-tests.sh
- test-cypress/integration/explore/similarity.spec.js
- test-cypress/integration/setup/jdbc.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/support/index.js
- test-cypress/support/sparql-commands.js
Made cypress tests pass on Mac (pressing command instead of control key).
Various improvements to the cypress test run script:
- External developers can download GraphDB Free and put the zip in a directory to run the tests
- Downloads from our Nexus will be cached in .downloads
- GraphDB will be extracted in a dynamic temporary directory and will be stopped on exit and the directory deleted
> GDB-5263: Added cypress env for modifierKey ({cmd} on mac, {ctrl} elsewhere) and added improvements to the run-cypress-tests.sh script

- webpack.config.common.js
The version transformation for the css file was missing from webpack configuration.
> GDB-5350 RDF resource box does not render correctly

- test-cypress/integration/sparql/sparql.menu.spec.js
Queries in SPARQL editor use `\n` as new line character regardless of OS. When comparing with text from a fixture, it's new line chars must be converted to `\n` only.
> GDB-5261 Refactor workbench tests to be OS independent

- src/css/bootstrap-graphdb-theme.css
- src/css/rdf-resource-search.css
- src/js/angular/core/directives.js
- src/js/angular/core/directives/rdfresourcesearch/rdf-resource-search.directive.js
- src/js/angular/core/directives/rdfresourcesearch/templates/rdfResourceSearchTemplate.html
- src/js/angular/core/templates/search-resource-input.html
- src/pages/home.html
- src/template.html
- test-cypress/integration/home/workbench.home.spec.js
- test-cypress/steps/home-steps.js
- Search box position is now fixed (won't move with status items)
- Can be closed with 'escape' or click outside
- Added option to choose search type with radio buttons
- If using radio buttons, choice is persisted in local storage
- Changed default 'text' label to 'table'
- Added option to persist the search (input and suggest) in local store
- Added clear button to clear input and persisted search data
- Various css fixes (z-index, width)
- Fixed issue when prefix is selected, suggests are removed. New search is now initiated, and focus is set on input
> GDB-5340 Fix usability issues with search RDF box

- src/js/angular/autocomplete/controllers.js
- src/js/angular/controllers.js
- src/js/angular/core/directives.js
- src/js/angular/core/directives/rdfresourcesearch/rdf-resource-search.directive.js
- src/js/angular/core/services/autocomplete-status.service.js
- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/similarity/controllers/similarity-list.controller.js
- src/js/angular/utils/local-storage-adapter.js
- test/autocomplete/autocomplete.spec.js
Added a `autocompleteStatus` service which sets the autocomplete enabled status to local storage.
The service also monitors local storage for change (supporting different tabs) and broadcasts the status on change.
Added watchers for all search resource inputs.
> GDB-5367 Refresh autocomplete status in rdf search box

- Jenkinsfile
Send branches as string to sonar cube, as otherwise it throws error when the branch is a number
> Branches as string to sonar

- src/js/lib/yasqe.bundled.js
Added check for "punc" element, when getCompleteToken is taken from Code Mirror.
> All special characters are considered as "punc" token from YASQUE. 

- src/js/angular/controllers.js
Removed unnecessary check for license status in home controller, because it's already called in $scope.$on("$routeChangeSuccess" of the main controller.
> GDB-6459 Moved getting the repository size out of a block with check for valid license. Getting the repository size should not be related to license.

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
which removes brackets and serial commas from IRIs when used to create ids for links and markers, because elements with ids that contain such are not valid XHTML and cause a host problems when trying to style individual elements.
> GDB-6462 Created removeSpecialChars function, 

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
when used to create ids for links and markers, because elements with ids that contain such are not valid XHTML and cause a host problems when trying to style individual elements.
> GDB-6462 Created removeSpecialChars function, which removes brackets and serial commas from IRIs,

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Visual graph visualizes all valid IRIs by design, no matter if they are actually existing in the repository.  If they are not existing, then a pop-up message shows. The message is now changed to:
This node either does not exist or has no visible connections. Check your Graph Settings if you expect such. Thus it is more descriptive.
> GDB-6402 The visual graph can display non-existent data

- src/js/angular/plugins/controllers.js
A message is generated whenever a plugin is toggled from a follower node. 
A follower should not be able to toggle the plugins. The back-end code throws an exception, which leads to infinite loading at the front-end.
I have handled the exception from the back-end and added a toastr message for the user.
> GDB-6729 - changes to plugin state lead to infinite loading

- src/js/angular/core/interceptors/unauthorized.interceptor.js
- 409 status was returned from GraphDB when token is expired
- this has changed and now GraphDB returns 401 and 409 is returned from other API call
> GDB-6774 Remove handling of 409 status in unauthorized interceptor

- src/js/angular/clustermanagement/controllers.js
- src/pages/cluster-management/clusterInfo.html
- changed on window click event handler to check if click is outside the node tooltip
- if click is inside, should not close the tooltip
> GDB-6870 Improve cluster nodes tooltip behaviour

- src/js/angular/clustermanagement/controllers.js
- the call to find which the current node is, was made only once which causes problems when using ext proxy
- changed to re-fetch current node if there is a leader change
> GDB-6968 Fetch current node not recognized when using ext proxy

- src/js/angular/clustermanagement/controllers.js
- the cluster would continuously send requests fo status even if previous requests are not finished
- changed to check if there is no request in progress before making new
> GDB-9669 Lower the number of requests for cluster status

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/cluster-drawing.service.js
- src/js/angular/clustermanagement/directives.js
- since the labels are inside an foreignObject with set height, it would not show overflowing text
- set overflow to visible for foreign objects inside legend
> GDB-6990 Fix cluster legend text being cut

- src/js/angular/repositories/controllers.js
- test/repositories/controllers.spec.js
- when adding/removing locations they are not refetched/reloaded
- added locations reload in timer function
- added locations reload to add/remove actions
- the locations are reloaded in the service only when there is change
- amended tests to expect another request for locations
> GDB-7021 Fix add remove locations needing page refresh

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- the Code Mirror gutter that holds the error icon is below the wrap lines gutter and this prevents the error message to show on icon hover
- hooked to CM update event and set the error icon gutter z-index to 10, so it is above other gutters
> GDB-7011 Fix SPARQL editor error message not showing on hover

- src/js/angular/core/directives/languageselector/language-selector.directive.js
- src/js/angular/core/services/repositories.service.js
- src/js/angular/repositories/controllers.js
- src/js/angular/rest/locations.rest.service.js
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/package.json
- test-cypress/plugins/index.js
- test-cypress/support/index.js
- test/repositories/controllers.spec.js
- the problem is that when navigating away from a page, the currently running requests are forcefully aborted, but the http client promises remain unresolved/unrejected
- passed a timeout promise to the locations request which is resolved on repositories' page destroy handler, which causes the request to fail and reject the promises
- also added cypress-terminal-report and configured it to also log the console on failed tests
- also fixed a problem with a NPE in the language selector directive which became clear after adding the report plugin
> GDB-7061 Fix failing cypress tests in repositories spec

- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/security/controllers.js
The login form is not shown after the login expires.
When the login has expired and you load the root of the workbench, the unauthorized interceptor is activated and redirects to /login. This redirect causes an important request to be canceled. The request to /rest/security/all is responsible for setting up security parameters on the workbench. Without those parameters the form is not shown.
Added a new function to jwtAuth service which checks if the security is initialized and if not, it triggers initialization. Added a call to this new function in the LoginCtrl.
> GDB-7145 Fix login form not showing after login expired

- src/js/angular/controllers.js
When you switch users in the workbench, the username in the status bar is not changed until refresh.
The problem is that for the status bar, the security principal is fetched only once and cached, thus showing the same user when switching without closing the tab.
Wrapped fetching of the security principal in a function which is now called on every `securityInit` event trigger. This event is emitted on security initialization which might change the principal.
> GDB-7146 Fix showing wrong user when login

- src/pages/sparql.html
GDB-7168-WB Download data not working for certain queries - changed POST request method to GET in the download form.
> GDB-7168-WB Download data not working for certain queries

- package.json
- src/css/shepherd-custom.css
- src/js/angular/guides/directives.js
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/guides.service.js
- src/js/angular/guides/steps/core/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
- src/vendor.js
WHAT:
Added base services of guide functionality
WHY:
We would like to create guides that helps our client to investigate what can do with GraphDB.
HOW:
Adds lib shephred (https://shepherdjs.dev/docs/). We will use it to create guides.
Implements ShepherdService to wrapp shephred library.
Implements GuidesService with base functionality.
Implements a directive guideSelector which will be used to mark dom elements that the guides used.
> GDB-7271:Implement guide services

- src/js/angular/autocomplete/plugin.js
- src/js/angular/clustermanagement/plugin.js
- src/js/angular/core/services.js
- src/js/angular/explore/plugin.js
- src/js/angular/export/plugin.js
- src/js/angular/externalsync/plugin.js
- src/js/angular/graphexplore/plugin.js
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/steps/complex/main-menu/plugin.js
- src/js/angular/guides/steps/core/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
- src/js/angular/import/plugin.js
- src/js/angular/jdbc/plugin.js
- src/js/angular/namespaces/plugin.js
- src/js/angular/plugins/plugin.js
- src/js/angular/queries/plugin.js
- src/js/angular/rdfrank/plugin.js
- src/js/angular/repositories/plugin.js
- src/js/angular/resources/plugin.js
- src/js/angular/security/plugin.js
- src/js/angular/settings/plugin.js
- src/js/angular/similarity/plugin.js
- src/js/angular/sparql-template/plugin.js
- src/js/angular/sparql/plugin.js
- src/js/angular/stats/plugin.js
- src/template.html
WHAT:
Added 'click-main-menu' guide plugin.
WHY:
It can used as part of other guide plugin when have interaction with main menu.
HOW:
Registers 'click-main-menu' plugin to 'guide.step' plugins.
Additional changes:
Extends guide service with new functions.
Added specific guide selector to all menus and sub menus.
Added html support to popover dialog. Translate service is configured to escape HTML entities as <,> etc. and this breaks processing dialog content as html. Fixed as unescapes escaped characters of translated content.
> GDB-7337: Implements click on main menu plugin

- src/i18n/locale-en.json
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/guides.service.js
- src/js/angular/guides/steps/complex/enable-autocomplete/plugin.js
- src/js/angular/guides/steps/core/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
- src/pages/autocomplete.html
WHAT:
Added 'enable-autocomplete' guide plugin.
WHY:
It can used as part of guides.
HOW:
Registers 'enable-autocomplete' plugin to 'guide.step' plugins.
Additional changes:
Refactor function _pauseGuide of ShepherdService.
Symplify implementations of functions "_getPreviousButtonAction" and "_getNextButtonAction".
Added support if elemen of a step is clickable and user click on it guide will show next step automatically.
> GDB-7311: Added enable autocomplete index

- src/js/angular/core/directives.js
- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
- src/js/angular/guides/steps/complex/visual-graph/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
- src/pages/graphs-visualizations.html
GDB-7310 - Fixes import rdf file. Button was not clickable. GDB-7312 - Disabling keyboard events, zoom and dragging of a node when a guide is active. Disabling search when fill "Search RDF resources" input and press "Enter" button when a guide is active. GDB-7312 - Fixes issue with buttons of visual graph toolbar.
- fixes isActive function of ShepherService
- added check if node is visible in awaitAlphaDropD3 function.
> GDB-7292 fixes and improvements

- src/js/angular/repositories/controllers.js
Changed in controllers.js, $scope.editRepoHttp = function (), passing the repo as object as it was passing only its id.
> GDB-7306-Add/remove FTS indexes after repo config restart.

- src/pages/rdfClassHierarchyInfo.html
Switched off auto close pageslide component when click outside panel.
> GDB-7489: User Guide break when the user clicks outside info panel

- src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
- src/js/angular/guides/steps/complex/table-graph/plugin.js
Fixed GDB-7471. Changed position of the steps to be on left class hierarchy side.
Fixed GDB-7474. The selector of the step pointed the header of the table with query results. There is not enough space for the dialog that's why it is shown under the table header row. The selector is changed to points to the body of the table.
> Class hierarchy issues

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/guides.service.js
- src/js/angular/guides/steps/complex/visual-graph/plugin.js
- src/js/angular/guides/steps/core/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
Disabled processing of mouse event on visual graph when guide is started. Added implementation in "visual-graph-expand" "visual-graph-properties" plugins to process those events when guide is started. Additional work:
Fixed eslint issues.
> GDB-7487: User Guide blocks the workbench if the user double clicks

- src/css/shepherd-custom.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/guides/guides.service.js
- src/js/angular/guides/steps/complex/visual-graph/plugin.js
- src/js/angular/guides/steps/complex/welcome/plugin.js
- Also add translatedGuideName and translatedGuideDescription to options automatically on guide start
- Also added skipGenericMessage option to focus property in visual graph block
- Also added missing French translation for autocomplete error message
> GDB-7531: Added "welcome" easy guide block

- src/pages/graphs-visualizations.html
Fixed sidepanel.show.preferred.predicates to sidepanel.show.preferred.predicates.only in graphs-visualizations.html so it can be properly translated.
> GDB-7527-Missing label in Visual graph

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/controllers.js
- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/guides.service.js
- src/js/angular/guides/steps/complex/select-repository/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
Fixed. 
- GDB-7538
- There was a bug when a guide is on step to choose a repository and user click on any menu item of any repository, the dropdown wouldn't close. The problem was that we stop dropdown to be closed when a guide is active, this is because of other bug "GDB-7450: User Guide crashes on repo select step". Fixed, when the step is shown we add a class "autoCloseOff" to dropdown. This class will block closing of dropdown when user click outside dropdown. This class will be removed when user click on "Next" button or some menu item.
> GDB-7501: User Guide can't be rerun if more than one repo exists

- src/js/angular/guides/tour-lib-services/shepherd.service.js
Some steps have attached listeners when they are shown. Those listeners are removed when the steps are closed. The problem was that when guide canceled the Shepherd library not call this "hide()" function automatically. Added functionality to call "hide()" function when guide is canceled.
> GDB-7552: User Guide continues after being closed and unlocks the 

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Replace encodeURI() with encodeURIComponent() in graphs-visualizatios.controller.js, because encodeURI() does not support special characters like "+", "&", "@" and etc.
> GDB-6721 Special characters in the IRI make it non-resolvable from the visual graph

- src/js/angular/clustermanagement/controllers.js
Since we do not replicate locations, there is a problem when the current leader tries to add a node and does not have the locations of the nodes that are part of the cluster. If they do not exist on the current leader, they are not presented on the Nodes list when adding a node. 
Changed the implementation to use the nodes in the cluster model instead of the locations when creating the nodes list.
> GDB-7587 Current group cluster nodes are not shown when adding a node

- src/js/angular/plugins/controllers.js
What?
There is "Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed..." in console when plugin page is opened.
Why?
Periodically plugin controller refreshes available plugins and filter them. All plugins which match search term are pushed to "matchedElements" array, but this array not cleaned before used it, this caused duplicate error.
How?
The array is cleared before add plugins to it.
> GDB-7610: Plugins view gives periodic errors in the console

- README.md
- src/css/explore.css
- src/css/new-sparql.css
- src/css/workbench-custom.css
- src/css/yasr.custom.css
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/explore/controllers.js
- src/js/angular/similarity/controllers/similarity-list.controller.js
- src/js/angular/utils/yasr-utils.js
- src/js/lib/yasr.bundled.js
- src/pages/explore.html
- src/pages/jdbc-create.html
- src/pages/similarity-indexes.html
- src/pages/sparql-template-create.html
- src/pages/sparql.html
- src/vendor.js
GDB-6815: Resource view on mobile
What?
There was wrong calculation of table size when page is loaded on mobile.
Why?
"colResizable-1.4.js" library is used for column size calculation. It don't do its job properly on mobile.
How?
- Added functionality to switch off column resizing when screen width is small. Affected pages are:
- explore
- create jdbc
- similarity, create similarity
- SPARQL query
- SPARQL template create
> GDB-6815_Resource_view_on_mobile

- README.md
- src/css/explore.css
- src/css/new-sparql.css
- src/css/workbench-custom.css
- src/css/yasr.custom.css
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/explore/controllers.js
- src/js/angular/similarity/controllers/similarity-list.controller.js
- src/js/angular/utils/yasr-utils.js
- src/js/lib/yasr.bundled.js
- src/pages/explore.html
- src/pages/jdbc-create.html
- src/pages/similarity-indexes.html
- src/pages/sparql-template-create.html
- src/pages/sparql.html
- src/vendor.js
What?
There was wrong calculation of table size when page is loaded on mobile.
Why?
"colResizable-1.4.js" library is used for column size calculation. It don't do its job properly on mobile.
How?
- Added functionality to switch off column resizing when screen width is small. Affected pages are:
- explore
- create jdbc
- similarity, create similarity
- SPARQL query
- SPARQL template create
> GDB-6815: Resource view on mobile

- src/js/angular/guides/guide-utils.js
- src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
What?
User guides crashes when return to step which have got a query executed.
Why?
When a guide is active and "/sparql" view is loaded/reloaded a new query tab is opened. When a guide goes to step "execute-sparql-query" the guide functionality set the query before new tab is opened, runs the query and wait for specific result, but executed query is wrong so result is wrong and the guide crashes.
How?
Added waiting for no result text element which is shown when new tab is opened. When new tab is opened sets the query and execute it.
> GDB-7537: User Guide crashes on step 47 when returning to SPARQL editor

- src/pages/home.html
When GraphDB is behind a reverse proxy and there is a context path the Interactive guides page will fail to load.
> GDB-7614: Interactive guides page fails

- src/css/new-sparql.css
- src/css/workbench-custom.css
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- src/pages/explore.html
- src/pages/jdbc-create.html
- src/pages/similarity-indexes.html
- src/pages/sparql-template-create.html
What?
Explore, jdbc-create, similarity-indexes, sparql-template-create views are align center
Why?
With implementation of GDB-6815 issue style "width: fit-content;" was added to the views. This style fixes calculation of views width by ysque libraries, but brokes them when are opened with big resolution.
How?
Added media query which add the style only for small resolutions.
> GDB-7629: broken views

- src/js/angular/export/controllers.js
* Changed method angular.copy with lodash cloneDeep as it's benchmark in speed is better.
> GDB-7692 Graphs Overview View crashes/ loads really slowly when trying to show a lot of graphs

- .gitignore
- package-lock.json
- package.json
- src/js/angular/rest/sparql.rest.service.js
- src/js/angular/sparql-editor/controllers.js
- src/pages/sparql-editor.html
- test-cypress/integration/sparql-editor/actions/save-query.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/steps/application-steps.js
- test-cypress/steps/yasgui-steps.js
Integrate the save query action from the ontotext yasgui component.
Save query action exists in current implementation in the GDB WB. It allows the user to complete the query name and the query itself, to select if the query will be private or public and save it.
* The ontotext yasgui component now supports the save query action. This changes in this MR are related with the integration of the save action. See also the related branch https://github.com/Ontotext-AD/ontotext-yasgui/pull/39
Additional:
* Install latest ontotext yasgui component version and fix error message show after save query failing request
> GDB-7783 integrate the save query action

- package.json
- src/js/angular/rest/mappers/saved-query-response-mapper.js
- src/js/angular/rest/sparql.rest.service.js
- src/js/angular/sparql-editor/controllers.js
- src/pages/sparql-editor.html
- test-cypress/integration/sparql-editor/actions/show-saved-queries.spec.js
- test-cypress/steps/yasgui-steps.js
Introduce a show saved queries action.
Save query action exists in current implementation in the GDB WB. It allows the user to load and see the available saved queries then for each query additional actions can be performed, e.g. select, edit, delete.
* Add custom button in the yasqe buttons extension point. The button rises an event for loading of the saved queries. Handling of this event is responsibility of the client who then must set the queries list in the config. Setting the queries in the config triggers the popup to appear.
* Add a saved queries popup which implements the visualization of the saved queries list. Each saved query is represented as a link and can be selected via click which then opens the query in a new yasgui tab. The dialog can be closed via click outside.
* …
> GDB-7784 integrate show saved queries action

- package-lock.json
- package.json
- src/js/angular/rest/mappers/saved-query-mapper.js
- src/js/angular/sparql-editor/controllers.js
- test-cypress/integration/sparql-editor/saved-query/share-query.spec.js
- test-cypress/steps/yasgui/saved-query.js
- test-cypress/steps/yasgui/share-saved-query-dialog.js
- test-cypress/steps/yasgui/yasgui-steps.js
Allow the client to open a query model in a new or existing tab depending on if there is already existing tab with the same name and query.
The client would needs to open a shared query in editor tab, be it a new or existing one.
* Analyze the url parameters and if there is a savedQueryName parameter then try to load the saved query and open it in the editor.
> GDB-7785 Introduce ability to open shared saved query

- src/js/angular/core/directives/queryeditor/sparql-tab.directive.js
* Changes in html template so tab.name could be read and displayed on screen.
> GDB-7586 SPARQL editor tabs do not encode symbols properly

- src/js/angular/rest/mappers/saved-query-mapper.js
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/sparql-editor/share-query-link.service.js
- src/js/angular/utils/route-constants.js
- src/pages/sparql-editor.html
- test-cypress/integration/sparql-editor/actions/share-query.spec.js
- test-cypress/steps/yasgui/share-saved-query-dialog.js
- test-cypress/steps/yasgui/yasqe-steps.js
Allow the client to get a shareable link for the currently opened query and open it.
The WB has this feature.
* Introduced the share query action in the editor and handling the events from it.
* Implemented resolver for the shared query url parameters allowing to open and init a sparql editor tab based on these parameters.
> GDB-7786 Introduce share query action

- package-lock.json
- package.json
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/utils/query-types.js
- test-cypress/integration/sparql-editor/actions/execute-query.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/steps/yasgui/yasqe-steps.js
Handle queryExecuted and add proper http headers to the request
Add http GDB specific http headers before query request.
GDB expects certain http headers to be sent with each query request like: x-graphdb-track-alias, X-GraphDB-Repository-Location, X-Requested-With, etc.
* Handled executeQuery event from ontotext-yasgui and added needed headers.
* Added some documentation.
> GDB-7890 Handle queryExecuted and add proper http headers to the request

- package-lock.json
- package.json
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/utils/yasgui-utils.js
- src/main.js
- src/pages/explore.html
- src/pages/sparql-editor.html
- test-cypress/integration/sparql-editor/actions/expand-results-over-sameas.spec.js
- test-cypress/integration/sparql-editor/actions/include-inferred-statements.spec.js
- test-cypress/integration/sparql-editor/yasr/download-as.spec.js
- test-cypress/integration/sparql/sparql-language-change.spec.js
- test-cypress/steps/yasgui/yasqe-steps.js
- test-cypress/steps/yasgui/yasr-steps.js
What?
Adds a "Download as" dropdown.
Why?
The clients of WB want to download the result of an executed query in different formats.
How?
Updates version of ontotext-yasgui component.
Added handler for downloadAs event and implement download file according downloadAs event data.
Removes 'yasr.css' and './css/yasr.custom.css' from global import.
> GDB-7891 yasr download results in different format

- package-lock.json
- package.json
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/utils/yasgui-utils.js
- src/models/ontotext-yasgui/event-data-type.js
- src/models/ontotext-yasgui/event-data.js
- src/models/ontotext-yasgui/notification-message-type.js
- src/models/ontotext-yasgui/yasr-plugin-name.js
- src/pages/sparql-editor.html
Changes implementation of notification when an url of result link is copied into clipboard.
There is a new implementation of event fired by "ontotext-yasgui" when an url link is copied.
Updates the version of "ontotext-yasgui". Register a notification event handler in "ontotext-yasgui" output event emitter.
Added models for:
- EventData - event data model for all events fired by "ontotext-yasgui";
- EventDataType - describes all possible events which can be fired by "ontotext-yasgui";
- NotificationMessageType - describes all possible notification message types: "success", "warning", "error";
- YasrPluginName - describes the names of yasr plugins.
> Refactors copy resource link success message.

- src/js/angular/repositories/ontop-repo.directive.js
When creating ontop repository, tooltips for some fields are not shown and console is full of errors
The generation of the keys for the tooltip labels is wrong the function throws an error
- fix the function which generates tooltip translation labels' keys
> GDB-8005 Fix translation labels generation in ontop create view

- src/js/angular/repositories/ontop-repo.directive.js
Cherry-pick from 2.2 branch
When creating ontop repository, tooltips for some fields are not shown and console is full of errors
The generation of the keys for the tooltip labels is wrong the function throws an error
- fix the function which generates tooltip translation labels' keys
> Cherry-pick GDB-8005 Fix translation labels generation in ontop create view

- src/css/jmx.css
Colors for disk storage chart are a bit different from others
The fill-opacity style is different for some reason
- add a css rule to set the fill-opacity to 0.5 as other charts
> GDB-7948 Fix monitoring view bar-chart colors

- package-lock.json
- package.json
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/utils/yasgui-utils.js
- src/models/ontotext-yasgui/count-query-request-event.js
- src/models/ontotext-yasgui/count-query-response-event.js
- src/models/ontotext-yasgui/download-as-event.js
- src/models/ontotext-yasgui/event-data-type.js
- src/models/ontotext-yasgui/notification-message-event.js
- src/models/ontotext-yasgui/query-request-event.js
- src/pages/sparql-editor.html
- test-cypress/fixtures/namespaces/ontotext-generated-namespace.json
- test-cypress/fixtures/queries/empty-query-response.json
- test-cypress/integration/sparql-editor/actions/expand-results-over-sameas.spec.js
- test-cypress/integration/sparql-editor/actions/include-inferred-statements.spec.js
- test-cypress/integration/sparql-editor/yasr/pagination.spec.js
- test-cypress/steps/yasgui/pagination-steps.js
- test-cypress/steps/yasgui/yasr-steps.js
- test-cypress/stubs/namespace-stubs.js
- test-cypress/stubs/yasgui/query-stubs.js
Added pagination to yasr component.
Some queries returns a lot of results. To show all of it we need a lot of resource and visualization will be slow.
- Updates "ontotext-yasgui-web-component".
- Refactoring query event. It is registered in output handlers.
> GDB-7954: Add pagination control to all yasr plugins

- src/js/angular/guides/tour-lib-services/shepherd.service.js
Update guides tooltips to use the new directive
Guides tooltips were not updated before, because they are created in JS and were missed
- changed tooltips to use gdb-tooltip directive
> GDB-7844 Update guides to use new tooltip library

- package-lock.json
- package.json
- src/js/angular/sparql-editor/controllers.js
- src/models/ontotext-yasgui/notification-message-type.js
Added a new type "info" of notification messages emitted by ontotext-yasgui-web-component.
When user try to open a new tab, but query is running, then a notification of type info have to be shown.
Extends "notificationMessageHandler" to support info messages.
Increase version of "ontotext-yasgui-web-component".
> GDB-8023: extends ontotext-yasgui notification handler

- package.json
- src/js/angular/sparql-editor/controllers.js
Stops execution of a query when:
- try to execute explain plan query for update query;
- try to execute update query on virtual repository
- Explain plan query can be executed only for construct or select queries;
- Virtual repository can't be updated.
- Adds isVirtualRepository to ontotext-yasgui-web-component configuration.
- Updates version of ontotext-yasgui-web-component. Then new version supports this new requirements.
> GDB-8020: stop execution of query

- src/js/lib/yasr.bundled.js
- test-cypress/integration/sparql/sparql-language-change.spec.js
When user changes the language the label of download dropdown is changed as expected, but when execute a query label is on wrong language.
- "Download As" dropdown html (as string) is defined in separate module "extensions.js". Inside the module there is translation of dropdown label, but it uses the default language when page is loaded. This module is used when dropdown is created after every execution of query.
- When user changes the language there is code which find dropdown and change it label according selected language and that's why label is correct.
- When user run a query results and the dropdown are recreated. Recreation of "Download As" use the external module described above and label is translate on language when the page is loaded.
Refactored translation module to hold …
> GDB-8100: UI language switch does not take effect immediately

- package-lock.json
- package.json
- src/js/angular/sparql-editor/controllers.js
- src/js/services/ontotext-yasgui-web-component.service.js
- test-cypress/integration/sparql-editor/saved-query/abort-query.spec.js
- test-cypress/steps/yasgui/yasgui-steps.js
- test-cypress/steps/yasgui/yasqe-steps.js
Added ability to abort a query. When the user clicks on "Run" button, an "Abort query" button will be displayed. If the user click on this button, the running query will be aborted.
WB has such functionality. This functionality will give to the users opportunity to canceled long-running queries.
- Increases "ontotext-yasgui-web-component" version.
- Implements function "onAbortQuery".
> GDB-8115: Implement abort query button

- src/css/yasr.custom.css
- src/js/lib/yasr.bundled.js
- test-cypress/integration/sparql/sparql-result-formating.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/steps/sparql-steps.js
When IRIs in SPARQL results are shown and don’t fit in the available column size they aren’t wrapped to the next line. This varies between browsers and versions.
Browsers have different defaults about word-wrapping.  
Updates YASR bundled js file that include follow changes:
Added word break rules depends on result binding type. 
- For IRIs and blank nodes:
- adds word-wrap: break-word to all cell with IRI content;
- inserts <wbr> at strategic places: after :, /, -, _ but treat sequences of those as one thing, e.g. http://<wbr>example…
- set attribute lang="xx" on the element
- For literals:
- adds word-wrap: break-word to all cell with literal content;
- added hyphens: auto (+ -moz- and -webkit- prefixed version) to all cell with literal content;
- if the literal has a language tag;
- …
> GDB-8129: Long IRIs are cut from the SPARQL results view

- src/js/angular/controllers.js
Saved SPARQL queries not loaded when user logged in.
The authentication headers are still not set correctly when a request that loads saved queries is called and the $unauthorizedInterceptor rejects the request.
> GDB-8091: Saved queries are not displayed on the welcome page

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
When I execute a query from "Saved SPARQL queries" in Welcome page, then "sparql" page is loaded with the query and a confirm dialog is opened. When the dialog is closed no matter how: "Yes", "Cancel" or "x" button and refresh the page dialog is opened again.
When execute a saved query is from Welcome page the url that triggers "sparql" view be opened contains a parameter "execute". This parameter triggers the opening of a confirmation dialog.
Added code that removes "execute" parameter from the url when dialog is closed.
> GDB-8232: executing a saved query from the welcome page

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
When I execute a query from "Saved SPARQL queries" in Welcome page, then "sparql" page is loaded with the query and a confirm dialog is opened. When the dialog is closed no matter how: "Yes", "Cancel" or "x" button and refresh the page dialog is opened again.
When execute a saved query is from Welcome page the url that triggers "sparql" view be opened contains a parameter "execute". This parameter triggers the opening of a confirmation dialog.
Added code that removes "execute" parameter from the url when dialog is closed.
> GDB-8232: Cherry-pick from 2.2

- src/js/lib/yasr.bundled.js
- test-cypress/integration/sparql/sparql-result-formating.spec.js
- When you run a query that returns a result with a language tag, the display of the result is wrong. For example:
- if some literal has an "en" tag, then "@ensup>" will be displayed;
- if some literal has an "en-GB" tag, then the html of the literal is "@en-<wbr>GBsup>";
Before displaying the results, we insert a <wbr> after special characters (_:/-) to ensure that the result will not be an overflow cell element. The problem occurred because the literals that has language tag contains "/" (an of the special characters which we process). As result the html of the processing literal is "<sup>@en/<wbr>sup>".
Updates yasr.bundled.js.
Updates test to cover described scenarios.
> Cherry-pick from 2.2 GDB-8129: Unexpected tag after language tag

- src/js/lib/yasr.bundled.js
- test-cypress/fixtures/sparql/history-response.json
- test-cypress/integration/sparql/sparql-result-formating.spec.js
- test-cypress/stubs/query-stubs.js
If a cell of sparql results table displays value of type bnode, the bnode value is on next line than the prefix "_:".
The functionality that process formatting of bnode adds this unwanted tag.
Updates yasr.bundled.js (Removes adding of wbr tag bnode formatting functionality). Additional work:
- add test to cover this case.
> GDB-8129: Removes wbr tag from cells displayed bnode type result

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/sparql/plugin.js
- test-cypress/integration/home/workbench.home.spec.js
- test-cypress/steps/home-steps.js
When load "sparql" view by "Welcome page saved queries", "Saved queries" or "Get URL to current query" functionality a new tab is opened with filled query. When the tab is closed and page is reloaded, the tab appears again.
The url of sparql view contains parameters that activates functionality that opens a new tab, loads a query and fill it into the opened tab.
Removes all parameters when page is loaded.
> GDB-8232: Removes all parameters when page is loaded.

- src/js/angular/repositories/controllers.js
- src/js/angular/repositories/ontop-repo.directive.js
- test-cypress/integration/repository/repositories.spec.js
Upon editing a repository, the additional Onto properties are not displayed correct. Instead, [object Object] is shown in the text area.
The server returns an object which is not parsed and is set in the textbox. The initial talk was for the UI to receive a string so there is no need to parse it, but this has changed.
- added function to convert additional properties values to string
> GDB-8252 Fix displaying of additional Ontop properties

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/controllers.js
- src/pages/cluster-management/clusterInfo.html
- test-cypress/fixtures/locale-en.json
Changed the DELETED message to the one in backend. Also changed the evaluation if add or remove node buttons should appear from currentNode.nodeState === NodeState.LEADER -> currentLeader, because leader is needed to process this request.
> Gdb 8332 missing options to add remove cluster nodes

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/controllers.js
- src/pages/cluster-management/clusterInfo.html
- test-cypress/fixtures/locale-en.json
Changed the DELETED message to the one in backend. Also changed the evaluation if add or remove node buttons should appear from currentNode.nodeState === NodeState.LEADER -> currentLeader, because leader is needed to process this request.
Cherry-pick from the master
> Gdb 8332 missing options to add remove cluster nodes 2.2

- src/css/new-sparql.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- src/models/sparql/sparql-query-error-info.js
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/sparql/sparql-error-handling.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/steps/sparql-steps.js
When exception is thrown after executing of sparql query, the workbench shows the error. But if the error is too big the error area is too long. Most of the users do not need to see the entire message.
WB displays all error messages no matter of its length.
Added functionality that checks error message length and if it is too long a small part of message is displayed accompanied by a 'Show full error message' button to expand it. When the button is clicked all error will be displayed accompanied by a 'Show less error message' button to show less part of message.
> GDB-8437: introduce a way to expand error messages in GraphDB workbench

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- test-cypress/integration/sparql/sparql-error-handling.spec.js
- test-cypress/stubs/query-stubs.js
- webpack.config.common.js
- webpack.config.dev.js
- webpack.config.prod.js
- There was a warning message:
```
unable to locate 'src/guides' at '/home/boyan/Git/graphdb-workbench/src/guides'
```
when open a page of workbench.
- There was a warning message:
```
DevTools failed to load source map: Could not load content for http://localhost:7200/main.35e30fd1f1326e91ed6c.bundle.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```
in the Chrome console when opens a page in production.
- There was legacy configuration of webpack copy plugin from "user interactive guide" functionality.
- During the build process sources are skipped but there are references to the sources into minified files. At the end of every one file has something like "//# sourceMappingURL=184.ed3e402118e64c17a70b.bundle.js.map". This causes Chrome to try loading the source file.
- …
> GDB-8395: Workbench throwing console warnings for invalid JSON

- src/js/angular/core/directives/yasgui-component/templates/yasgui-component.html
- src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/jdbc/app.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/sparql-editor/app.js
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/sparql-template/app.js
- src/js/angular/sparql-template/controllers.js
- src/pages/jdbc-create.html
- src/pages/sparql-template-create.html
- test-cypress/integration/explore/similarity.spec.js
- test-cypress/integration/setup/jdbc-create.spec.js
- test-cypress/integration/sparql-editor/yasr/table-plugin.spec.js
- test-cypress/steps/setup/jdbc-create-steps.js
- test-cypress/steps/setup/sparql-create-update-steps.js
- test-cypress/support/repository-commands.js
Refactoring jdbc templates
- Change sparql template view to use yasgui directive instead component directly.
- Change jdbc template view to use yasgui directive instead component directly.
The Yasgui directive was introduced that wrap most of needed configurations of ontotext-yasgui-we-component
- Change the templates and the controllers to use the directive.
- added flag "failOnStatusCode" to delete repository command. It prevents the tests to failed if something is wrong if repository can't delete. This method is used after each test, it is not part of the test, it just should clean backend server after the test.
- Extends yasgui-component.directive.js
- Moves visual button configuration to the view from the directive.
> Refactoring jdbc and sparql-templates views

- src/js/angular/clustermanagement/controllers.js
… (#968)
* GDB-8369 Ascertaining whether the error is a 403 and calls getError(error.data, error.status) if it is
* GDB-8369 use handleAddRemoveErrors() to reformat the message
* GDB-8369 Rename handleAddRemoveErrors() to handleErrors()
(cherry picked from commit 8b6fc50ab52a3ee9a500438ca95e28bd23c73ca1)
> GDB-8369 Cherry pick GDB-8369 into 2.2

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/cluster-drawing.service.js
- src/js/angular/clustermanagement/controllers.js
- src/js/angular/clustermanagement/directives.js
- src/js/angular/clustermanagement/plugin.js
- src/pages/cluster-management/clusterInfo.html
Allow access to cluster view from the menu or by url to all authenticated users and restrict actions to admin users only
All authenticated users should have access to the cluster view and only admin users should be able to perform actions
- added a check to see if user has admin access to create a cluster and changed view
- added ng-if to action buttons to hide them is user is not admin
- changed main menu item role to ROLE_USER to allow all authenticated users to see it
> GDB-8442 Allow access to cluster view for all authenticated users

- package-lock.json
- package.json
- src/css/create-similarity-index.css
- src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
- src/js/angular/models/similarity/similarity-index-info.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/pages/create-index.html
Changes implementation of switching between "yasqe" and "yasr" 'ontotext-yasgui-web-component' render mode.
For performance reason.
The old implementation modifies the configuration of the 'ontotext-yasgui-web-component', which leads to the destruction of the component and the creation of a new one with the new configuration. The new one uses method of component, that changes the render mode without destroying of component.
> GDB-7732: Refactoring of query execution.

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/similarity/controllers/create-index.controller.js
- src/pages/create-index.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/explore/similarity-index.spec.js
- test-cypress/integration/explore/similarity.spec.js
- test-cypress/integration/setup/jdbc-create.spec.js
- test-cypress/steps/explore/similarity-index-create-steps.js
- test-cypress/steps/explore/similarity-indexes-steps.js
- test-cypress/steps/modal-dialog-steps.js
What
Added functionality to prevent changing the repository or location without user confirmation.
Why
- Similarity indexes are specific to each repository, so when a similarity index is open for editing, the repository should not be changed. If this occurs, the user should be notified.
- If a similarity index is open for editing, or if the create similarity index form is open and the user makes changes in the form but tries to change the location without saving the changes, they should be notified about the unsaved changes.
How
Added a listener for changes in the repository. Added a listener for changes in the location. Implemented confirmation prompts if any of these events occur.
> GDB-7732: Added change repository listener and dirty check functionality

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
GDB-8043: reformat the message of error 431 when trying to download json result of a very large query
> GDB-8043 Reformat the message of error 431 when trying to download json result of a very large query

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/js/angular/rest/rdf4j.repositories.rest.service.js
- src/models/repository/repository.js
- src/pages/sparql.html
Reimplemented the sparql results download as functionality to go trough a post request instead of get
The old implementation used to send a get request with form data containing the sparql query string which happened to break the browser limit for get request size.
* Removed the old form used for sending request data needed for the download and replaced with an actual http.post request and saved result according to provided file type.
> GDB-8610 reimplemented the sparql results download as functionality

- package-lock.json
- package.json
- src/css/create-similarity-index.css
- src/css/lib/ontotext-yasgui-web-component.css
- src/css/sparql-editor.css
- src/i18n/locale-en.json
- src/js/angular/sparql-editor/plugin.js
- src/pages/sparql-editor.html
- test-cypress/integration/resource/resource.spec.js
Fixes the page heading which used to show wrong label and had missing info button, fixed the yasr results height and various other styling issues in the yasgui.
The look and feel of the sparql view needs to be improved and to be more aligned with the old one.
* Fix the yasr results table height wrongly applied globally instead only to results rendered in the similarity index creation page.
* Removed obsolete sparql view heading label and use the original one.
* Add back the proper heading to the sparql view.
* Fix multiple styling issues in the sparql view: properly position and resize the toolbar buttons, properly align the yasgui components when changing the layout, reposition the keyboard shortcuts trigger button to fit properly in the yasqe window, etc.
> GDB-8602 sparql view visual improvements

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
Changed the "headers" configuration function that serves request headers. The old implementation applied the headers in two steps:
1. The "headers" configuration function returned static headers only, those headers that didn't change.
2. Before a query is executed, a "query" event is fired. We had a listener for that event and updated the headers with calculated dynamic values.
In the new implementation, the logic of the second step has been merged into the first one.
- The "headers" function is called every time wen a query is executed, so calculated values are alveis up to its dependences.
-The "headers" function is called every time a query is executed, ensuring that calculated values are always up-to-date.
- Simplifies the process of applying headers.
- Reduces code dependencies, …
> GDB-8516: Updated function "headers" configuration.

- src/js/angular/sparql-editor/controllers.js
- src/pages/sparql-editor.html
Sparql view should not be empty when there is no active repository.
When there is no selected active repository the sparql view is not initialized correctly as it was in the old sparql view. The old implementation used to show a list with the available repositories for the user to select from. Aside from that the yasgui component threw an error because it was unconditionally included in the view while its config was missing in the case of missing repository.
Added check for the yasgui config object before including it in the view. Also added the generic core-errors directive which used to render the repositories list as in the old implementation.
> GDB-8620 sparql view should not be empty when there is no active repository

- src/css/bootstrap-graphdb-theme.css
- src/css/sparql-editor.css
Properly align yasgui components.
Yasgui container was made position: relative in order to be able to move it slightly up to the page heading so that to look like the other workbench views. This broke the layout in other ways.
Applied positioning outside-in to prevent inner components misalignment.
> GDB-8635 fix sparql editor view layout to prevent misalignment of various components

- src/js/angular/guides/tour-lib-services/shepherd.service.js
What
Changes position of the user guide skip button
Why
We need to improve the consistency and adhere to the user experience where it needs to always be obvious where to expect such buttons to appear and what will be their order.
How
The skip button has been moved on the left side.
> Changes position of the user guide skip button

- src/pages/explore.html
- When clicking on the resource name in the Resource view, an error is displayed instead of the resource source.
- The button “sameAs” is smaller than the others;
- A mistake occurred during view refactoring. The value of the link's href attribute was resolved as a string instead of a reference to an object;
- The icon's size was not properly set.
- The issue is resolved by correcting the object reference;
- The size of icon has been increased.
> GDB-8631: Malfunctions after integrate the new YASGUI component in yasr only mode in the resource view

- src/js/angular/models/sparql/tab-query-model.js
- src/js/angular/sparql-editor/controllers.js
- test-cypress/integration/resource/resource.spec.js
When clicking on the title of a triple resource in the resource view, a new tab opens in the SPARQL view with an empty tab name. The tab name must be "Unnamed <next number>"
The addTab function in YASGUI takes a second argument, which is the configuration for the new tab. This configuration includes the tab name. When the configuration is missing, YASGUI generates a tab name. In our case, from WB, we pass an empty string as the tab name configuration, which YASGUI treats as a valid name and uses it.
The default value of the tab name configuration has been changed to be undefined instead of an empty string.
> GDB-8641: Empty tab when execute RDF* query via resource view

- package-lock.json
- package.json
When the closeOtherTabs function is called, all other tabs are closed, but the YASQE and YASR sections of the active tab are dismissed. Only the tab with the tab name is left.
There was a bug in ontotext-yasgui-web-component.
The version of ontotext-yasgui-web-component has been incremented.
> GDB-8194: Tab is not visible when execute "Close other tabs" command.

- src/js/angular/import/controllers.js
- test-cypress/steps/import-steps.js
Added support for additional file formats
To enhance the import feature's compatibility and usability, this commit introduces support for several new file formats, including 'xml', 'rdfs', 'ndjsonld', 'ndjson', and 'jsonl'.
Updated the 'controllers.js' file to include the newly supported formats in the 'fileFormats' array, ensuring that the import feature can now handle these formats seamlessly. This expansion of supported formats increases the versatility of the import functionality.
> GDB-8280 Add missing extensions to import file selector

- src/js/angular/security/templates/user.html
Fixing the color of the info message icons to be consistent in all views.
When the WB theme was changed, the info icons on these views were missed and they were presented with the old text-primary color whereas the new color used for the info icons is the text-tertiary
* Changed the icons color
> GDB-8676 fixing the color of the info message icons

- src/template.html
Add background to status bar
When you scroll through the page the top status bar is floating with the scroll but as it doesn't have a background in many parts of the page it is not visible
- added bg-white css class to the status bar element which will set the background color to white
> GDB-7116 Add white background to status bar

- src/css/clustermanagement.css
- src/pages/cluster-management/clusterInfo.html
Fix visualization of the logo in the sidebar in the cluster view
The logo is shown with a white background, because the stylesheet has a generic selector for svg which sets the fill to white
- made the selector more specific for all the svgs that are in the cluster view
> GDB-8788 Fix GDB logo shown with white background in cluster view

- src/js/angular/aclmanagement/controllers.js
- src/js/angular/aclmanagement/model.js
- test-cypress/integration/setup/aclmanagement.spec.js
- test-cypress/steps/setup/acl-management-steps.js
Implemented the edit ACL rule operation
* By requirement users should be able to edit rules from the ACL list.
* Implemented the action for editing rule.
* Made the default values for subject, predicate, object, context to be '*'.
> GDB-8755 edit existing ACL rule

- src/js/angular/rest/security.rest.service.js
Removed . from fixedEncodeURIComponent function which replaces chars from path params
This causes . to be encoded and spring security has problem with that
- removed . from regex
> GDB-8425 Fix user manipulations with special chars in firefox

- src/js/angular/core/directives/operations-statuses-monitor/operations-statuses-monitor.directive.js
There is a redundant backend call to fetch running operations information when security is enabled, and the user is not logged in.
The check for security status and user login is not implemented.
A Check to verify user authentication has been added before sending the request.
> GDB-8826: Stop refreshing the operations status when security is enabled and the user is logged out.

- src/js/angular/aclmanagement/plugin.js
Allow only authenticated admin users to have access to ACL management page when security is ON.
ACL management is a task for data administrators (a.k.a. admin users in the GDB).
Changed the role of of the user which can see the ACL management menu to role ROLE_ADMIN.
> GDB-8753 Only authenticated admin users can have access to ACL management page when security is ON

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/aclmanagement/model.js
- src/js/angular/rest/mappers/aclmanagement-mapper.js
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/setup/aclmanagement/revert-rules.spec.js
- test-cypress/integration/setup/aclmanagement/update-rules.spec.js
- test-cypress/steps/application-steps.js
* Prevent save/revert ACL when there are no changes in the ACL model.
* Prevent leaving the page when there are changes in the ACL model. Doing this will raise confirmation dialog for the user to choose to stay on the page or to leave and loose his data.
This is an UX improvement that makes the work in the ACL management page more friendly and error prone.
Added a modelIsDirty flag that is set on each operation. The flag is used to control the actions visibility and to show confirmation dialog when the user tries to leave the page before saving the changes in the model.
> GDB-8757 Prevent some operations and leaving the page when ACL model is changed

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/aclmanagement/model.js
- test-cypress/integration/setup/aclmanagement/create-rule.spec.js
A unique validation for ACL rules has been implemented.
- Only the first rule will ever be matched;
- Managing duplicate rules in multiple positions can be challenging.
- If you want to delete the rule, you will need to identify all rules which are the same.
A unique validation has been implemented. Rules cannot be saved if that validation fails.
> GDB-8750: Added Unique Validation for ACL Rules

- src/css/aclmanagement.css
- src/pages/aclmanagement.html
Increase the size of the rule reorder buttons.
To improve usability.
Increased the font-size of the button which affects the icon as well as removed the table cell padding in order to prevent buttons misalignment.
> GDB-8847 increase size of the acl rule reorder buttons

- src/pages/aclmanagement.html
Properly position the progress indicator in ACL management page.
The progress indicator was incorrectly added inside the ACL rules table where there was a condition to hide the table when there was no acl model. Also when the indicator was shown the table rows were not hidden which made it look broken.
Moved the progress indicator outside of the table to prevent issues and simplify the table template.
> GDB-8849 properly position the progress indicator in ACL management page

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/queryeditor/query-editor.directive.js
Perform spraql results download only via POST request.
In order to prevent request errors due to the GET request size limit being hit.
Removed the branching in the code which limited the expected behavior only for construct queries.
> GDB-8610 download sparql results via POST request

- src/js/angular/security/controllers.js
- src/js/angular/security/templates/user.html
In the user settings page the roles field should not be editable for regular users.
Only admins can change/assign roles to users different than admin or repo manager. For these two, custom roles cannot be assigned.
Added proper validation in the view and a method for checking the user type in the settings controller.
> GDB-8866 custom roles should not be editable by regular users

- src/js/angular/stats/app.js
There’s an error in the browser console saying ""$jwtAuth is not defined" when click on "Download" system information button.
Injection of $jwtAuth service has been removed by mistake when "GDB-8813 Refactor so token is fetched per request" was implemented.
Injection of $jwtAuth service has been added.
> GDB-8876 Report download button does not work

- src/js/angular/aclmanagement/controllers.js
The ACL list should not be reloaded when ACL update fails due to some error.
Currently when ACL save operation completes the ACL list in reloaded in the UI, but when an error occurs in the backend the list should not be reloaded in order to allow the user to correct his data and just lose it.
Moved the catch handler in the proper method where the update error should be caught thus effectively skipping the ACL reloading.
> GDB-8881 Don't reload the ACL when an error happens during ACL update

- src/js/angular/core/services/repositories.service.js
Repositories not loaded in "Repositories" view when two tabs are opened, the "Repositories" view is opened in first tab, the user is logged out from the second tab and logged in from the first tab. After the login in first tab a loader is displayed and never disappear, the repositories not loaded.
Two reason are reason for this behaviour:
- The "repositories" service has state. The function "getLocations" calls back end to fetch all locations. When the BE is called a promise of $http client is saved as service variable if another client of the service calls the function, the same instance of the promise will be returned. When request finish without matter successfully or not the variable is cleaned.
- The "unauthorized" interceptor checks all error from BE if the user is not authorized or …
> GDB-8908: Repositories view does not load after log in through another tab

- src/js/angular/explore/statements.service.js
There is an error when try to save some triples in resource edit view.
The error is caused by a string literal that ends with a double quote, leading to an exception in the backend.
Added escaping of double quotes of the literal.
> GDB-8336: WB edit of some context triples gives syntax toast errors

- src/js/angular/core/directives/queryeditor/query-editor.directive.js
- src/pages/sparql.html
Export results via form submit to allow progress monitoring in the browser.
Using the file saver plugin does the job of file downloading, but it's no more user friendly because it doesn't allow the user to see the download progress nor to terminate it.
Changed the form action to be POST instead of GET in order to prevent exceeding the browser's limit for GET requests. This is also the easier way to do simple crossbrowser download with progress and cancelation support.
> GDB-8610 do export results via form submit to allow progress monitoring in the browser

- src/js/angular/chatgpt/templates/chat.html
Disable the ask gpt button while previous question is in flight.
If the button is not disabled and another question is asked while the previous one is not already answered, then the answers in the pane are mismatched.
Disabled the button during the request is in progress using the `loading` flag.
> GDB-8891 disable the ask gpt button while previous question is in flight

- src/js/angular/core/interceptors/authentication.interceptor.js
- src/js/angular/core/services.js
- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/core/services/openid-auth.service.js
- test/security/openid-service.spec.js
Fix invalid client authentication scheme error when trying to log in with OpenID
When authenticating with OpenId, the calls that are made during the auth process were amended by the authentication interceptor, which caused failure of getting tokens. Also the OpenId access token, was not set in the AuthTokenService
- moved the OpenId configuration to AuthTokenService
- skipped headers change in authentication interceptor for OpenId requests
- set OpenId access token in AuthTokenService
> GDB-8914 Fix OpenId authentication process

- src/js/angular/core/interceptors/authentication.interceptor.js
- src/js/angular/core/services.js
- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/core/services/openid-auth.service.js
- test-cypress/integration/explore/similarity.spec.js
- test-cypress/integration/setup/my-settings.spec.js
- test-cypress/integration/sparql/sparql.menu.spec.js
- test-cypress/support/sparql-commands.js
- test/security/openid-service.spec.js
Fix invalid client authentication scheme error when trying to log in with OpenID
When authenticating with OpenId, the calls that are made during the auth process were amended by the authentication interceptor, which caused failure of getting tokens. Also the OpenId access token, was not set in the AuthTokenService
- moved the OpenId configuration to AuthTokenService
- skipped headers change in authentication interceptor for OpenId requests
- set OpenId access token in AuthTokenService
- there was a problem with logout/login flow with multiple tabs
- the localStorage listener was triggered by an unnecessary clearing of the token
> GDB-8914 Fix OpenId authentication process (#1066)

- src/js/angular/models/similarity/similarity-index-info.js
- src/js/angular/similarity/controllers/create-index.controller.js
When I create similarity indexes from existing one, the index type of result is not same as source index.
There was an initialization mistake in setting the "options" field of the SimilarityIndex object when tha view is loading. The field was being set on the SimilarityIndexInfo object instead of the SimilarityIndex.
Wrong setting of "options" field has been corrected.
> GDB-8687: The "isLiteral field" of the similarity index is not properly set

- package-lock.json
- package.json
- test-cypress/integration/sparql-editor/plugins/error-plugin.spec.js
- test-cypress/steps/yasgui/plugin/error-plugin-steps.js
- GDB-8438: "YASR: Update error plugin". When exception is thrown after executing of sparql query, the workbench shows the error. But if the error is too big the error area is too long. Most of the users do not need to see the entire message;
- GDB-8188: "Buttons labels of dialogs are not translated". Some labels are not translated in French;
- GDB-8185: "Тhe button for "Copy URL to clipboard" is not visible on Browser Firefox". When hovering over a URI in Yasr, the "Copy URL to clipboard" button is not visible in the Firefox browser.
- WB displays all error messages no matter of its length;
- Missed label translation;
- The CSS selector that displays the URI includes a ":has" selector, which is not supported by the Firefox browser.
Updates version of ontotext-yasgui-web-component.
> Updates version of ontotext-yasgui-web-component

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/controllers.js
- src/js/angular/clustermanagement/templates/modal/add-nodes-dialog.html
- src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
After typing invalid location from the Create cluster/Add node to cluster modal dialogs, it is stuck in the Remote locations list  and can be only removed from the repositories section
There is only button to add locations, not to remove or edit. If cluster is created the repository page does not show remote locations, and it is impossible to remove any from the workbench.
- added button to remove location from the add node/create cluster screens
> GDB-8576 Add ability to remove locations from cluster view dialogs

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/rest/sparql.rest.service.js
- src/js/angular/sparql-template/controllers.js
- src/pages/sparql-template-create.html
Disable the save sparql template button if the query is not changed.
It should be possible to perform sparql template saving only if there is a change in the existing query in the editor. Otherwise the backend throws error. It's not clear why this error happens but it is what it is for now.
Extended the ontotext-yasgui facade component to do dirty checking for the query value and emit a `queryChanged` event. The event is then handled in the sparql template edit controller where the `isDirty` flag is toggled. Also the save button is conditionally disabled or enabled according to the `isDirty` flag value.
> GDB-8686 Disable the save sparql template button if the query is not changed

- src/js/angular/chatgpt/templates/chat.html
Disable the ask gpt button while previous question is in flight.
If the button is not disabled and another question is asked while the previous one is not already answered, then the answers in the pane are mismatched.
Disabled the button during the request is in progress using the `loading` flag.
(cherry picked from commit 81ab5cf495a02fcd2215177d00a15c225b2c44ea)
> GDB-8891 disable the ask gpt button while previous question is in flight (#1070)

- src/app.js
- src/css/aclmanagement.css
- src/css/autocomplete-select.css
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/core/directives/autocomplete/autocomplete.directive.js
- src/js/angular/core/directives/autocomplete/templates/autocomplete.html
- src/js/angular/rest/mappers/autocomplete-mapper.js
- src/js/angular/rest/mappers/namespaces-mapper.js
- src/pages/aclmanagement.html
- test-cypress/integration/setup/aclmanagement/create-rule.spec.js
- test-cypress/integration/setup/aclmanagement/delete-rule.spec.js
- test-cypress/integration/setup/aclmanagement/edit-rule.spec.js
- test-cypress/integration/setup/aclmanagement/revert-rules.spec.js
- test-cypress/integration/setup/aclmanagement/update-rules.spec.js
- webpack.config.common.js
IRI autocomplete component is implemented and integrated it in the ACL management view.
This improves the user experience allowing easier completion of triples when editing acl rules.
Implemented the autocomplete component based on the rdf-resource-search component. Integrated the component in the ACL management view.
Integrated the autocomplete in the acl view
Make autocomplete to wrap uris in `<...>` because it's expected by the acl service that triples will be encoded as n-triples
Fix text and index column size which needs to fit properly the rule indexes at least to four digits
Cleanup the code
Removed hardcoded test uris
Fix uri wrapping for prefixes
Reset state of the ACL on repo change
Fix selection from suggested uris by mouse click.
Make the autosuggest menu visible when there …
> GDB-8810 introduces iri autocomplete select and integrates it in the acl view (#1055)

- src/js/angular/similarity/controllers/create-index.controller.js
- test-cypress/integration/explore/similariti-index-create.spec.js
An error without a message is displayed when:
- Open a similarity index for editing and click on the "Save" button;
- Open a similarity index view. Write an incorrect select query, click on the "Create" button and then click on the "Search query" tab.
The check that determines when an error message is displayed incorrectly verified the presence of errors. It checked all queries, regardless of the currently opened query tab.
The check has been fixed to verify only the query of the current opened tab.
> GDB-8691: When I edit similarity indexes workbench displays error line

- src/css/lib/ontotext-yasgui-web-component.css
The button was not precisely positioned in the editor. Also the text was a bit misplaced more on the bottom part.
Better UI perception.
Properly position the button and the text via css.
> GDB-8679 better display keyboard shortcuts button in yasgui

- src/css/lib/ontotext-yasgui-web-component.css
- src/js/angular/rest/graph-data.rest.service.js
- src/js/angular/sparql-editor/controllers.js
* When visual graph was opened with rdf* query the API request was made with wrong request payload which resulted in a NPE in the backend.
* Also fixed visualization of the open Visual Graph button in the sparql editor which was invisible due to missing color variable.
Prevent error when loading visual graph view. Also make the button visible again.
* Fixed request parameters building to return proper payload format.
* Fixed button color by applying the correct color variable.
* Changed the html tag used for the button from `div` to `button` which is semantically correct.
> GDB-8682 fix loading of visual graph using rdf*

- src/css/lib/ontotext-yasgui-web-component.css
Fix the color of the menu items in the download as dropdown.
The font color in the menu items in download as dropdown was incorrectly overridden by the style of the links in the yasr because the items in the dropdown are also links.
Change the specificity of the css selector and set the white color as expected.
> GDB-8677 fix download as menu items color

- src/css/sparql-editor.css
Properly position repository selector component in sparql view.
The repository selector component when visible used to overlap with the page title.
Fixed the margin of the component.
> GDB-8620 properly position repository selector component in sparql view

- src/css/repositories.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/monitoring/operations/active-operation-model.js
- src/js/angular/models/monitoring/operations/active-operations-model.js
- src/js/angular/repositories/controllers.js
- src/pages/repository.html
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/steps/repository-steps.js
- test/repositories/controllers.spec.js
If we are in a cluster, the edit button of the repository name should be disabled.
We decided to disable this operation while repository is in cluster for GraphDB 10.4.1.
- The edit button of repository name has been disabled when the repo is in cluster;
- A tool tip described that repo is in cluster and its name can't be edited has been added when mouse is hover the edit button.
> GDB-8988: Disable the edit button for renaming a repository while in cluster

- src/css/repositories.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/monitoring/operations/active-operation-model.js
- src/js/angular/models/monitoring/operations/active-operations-model.js
- src/js/angular/repositories/controllers.js
- src/pages/repository.html
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/steps/repository-steps.js
- test/repositories/controllers.spec.js
If we are in a cluster, the edit button of the repository name should be disabled.
We decided to disable this operation while repository is in cluster for GraphDB 10.4.1.
- The edit button of repository name has been disabled when the repo is in cluster;
- A tool tip described that repo is in cluster and its name can't be edited has been added when mouse is hover the edit button.
> Cherry-pick GDB-8988 from 2.4

- package-lock.json
- package.json
- src/css/lib/ontotext-yasgui-web-component.css
- src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/models/ontotext-yasgui/ontotext-yasgui-config.js
- src/js/angular/models/ontotext-yasgui/yasgui-config.js
- src/js/angular/models/ontotext-yasgui/yasgui-orientation.js
- src/js/angular/models/ontotext-yasgui/yasgui-query-http-method.js
- src/js/angular/models/ontotext-yasgui/yasqe-action-button-definition.js
- src/js/angular/models/ontotext-yasgui/yasqe-mode.js
- src/js/angular/models/ontotext-yasgui/yasr-before-update-query-result.js
- src/js/angular/models/ontotext-yasgui/yasr-query-response-status.js
- src/js/angular/models/ontotext-yasgui/yasr-toolbar-plugin.js
- src/js/angular/sparql-editor/controllers.js
- test-cypress/integration/sparql-editor/actions/inferred-sameas.spec.js
- test-cypress/stubs/repositories-stub.js
- GDB-8267: When repository is virtual. the inferred and sameAs buttons have to be active and should not be toggleable.
- GDB-8286: A new configuration property "language" has been introduced.
- GDB-8267: Missed requirement during development;
-  GDB-8286: There was no way to set the language when the component is created. The default language was English, so if the client wanted to open the component with French, for instance, they had to open it with English and then refresh it as set language on French. This flow caused component to be redrawn twice.
- GDB-8267,  GDB-8286:  The version of "ontotext-yasgui-web-component" has been updated.
- GDB-8267: Added styling when infer and sameAs are disabled.
- Added ontotext-yasgui-web-component configuration model.
> Gdb 8267_GDB-8286

- src/js/angular/graphexplore/directives/dependencies-chord.directive.js
- src/js/angular/graphexplore/directives/domain-range-graph.directive.js
- src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
- src/js/lib/common/svg-export.js
On pages class relationships, class hierarchy and domain range graph, the export svg button yields a broken file
The selector for the svg export is too broad "svg" and selects all svgs on the screen
- added a parameter to the export function to take a selector and passed appropriate selectors
> GDB-8986 Fix svg downloads

- src/css/bootstrap-graphdb-theme.css
- src/js/angular/core/templates/core-errors.html
- src/pages/import.html
In 10.4 we introduced underlining of links:
Dotted for button links in Workbench and internal links in the documentation
Solid for external links in both (was already there)
It looks like the default auto thickness and offset of the underline are a bit of a fringe value. Safari does wonderfully, Firefox has too thin lines on smaller font sizes, Chrome is a bit of an oddball here, especially with the dotted links – too thick and too close to the text. See attached screenshots.
We aim to reproduce a behaviour that is as close as possible to the default auto algorithm in Safari/Firefox on all browsers.
Specifying this seems to do the trick for the most part in a font-size neutral way:
```css
text-decoration-thickness: clamp(1px, 0.06em, 10px);
text-underline-offset: clamp(1px, 0.06em, 10px); …
```
> GDB-9013: Link underlining issues in Workbench and the documentation

- package-lock.json
- package.json
The version of ontotext-yasgui-web-component has been updated.
There are fixed issues with the new version.
- [GDB-8184](https://ontotext.atlassian.net/browse/GDB-8184)
- [GDB-8021](https://ontotext.atlassian.net/browse/GDB-8021)
The version of ontotext-yasgui-web-component has been updated.
> Update version of ontotext-yasgui-web-component

- src/js/angular/explore/statements.service.js
What
There is an error when try to save some triples in resource edit view.
Why
The error is caused by a string literal that ends with a double quote, leading to an exception in the backend.
How
Added escaping of double quotes of the literal.
> Cherry-pick GDB-8336: WB edit of some context triples gives syntax toast errors

- src/js/angular/explore/statements.service.js
What
Reverts the changes introduced to address the GDB-8336 issue.
Why
Added escaping to double quotes adds extra character in user data.
How
Removes the previously added double quote escaping.
> revert changes of GDB-8336

- src/css/bootstrap-graphdb-theme.css
Fixing rdf search field buttons font size.
The buttons font size css property was reset to something which doesn't have one which resulted in font size set to 0px.
Fixed the override and now font size is 16px as expected and scales down to 14px on lower resolutions.
> GDB-9042 (2.4) Fixing rdf search field buttons font size

- src/js/angular/core/directives/operations-statuses-monitor/operations-statuses-monitor.directive.js
- src/js/angular/core/directives/operations-statuses-monitor/templates/operations-statuses-monitor.html
- src/js/angular/models/monitoring/operations/active-operation-model.js
- src/js/angular/models/monitoring/operations/operation-status.js
- test-cypress/integration/monitor/global-operation-statuses-component.spec.js
- test-cypress/steps/operations-statuses-component-steps.js
When there are ongoing rebuild similarity index. The global operation component is displayed without icon and count of the ongoing operation.
The issue arose after a code refactoring that removed the summary object for all operations, done for optimization. To display ongoing operations, the UI relies on an array returned from the backend, which contains information about icons and the count of ongoing operations per operation group. The problem occurred because "queries" and "imports" are part of the same operation group, and they share the same icon and count (the sum of both operations). This resulted in double-displaying the "query" group icon and count, causing the update query to be skipped for visualization. Rebuilding the similarity index triggers only one update operation, which …
> GDB-9074: When only one Query and Update is running in the UI is not displayed

- src/js/angular/core/directives/operations-statuses-monitor/operations-statuses-monitor.directive.js
- src/js/angular/core/directives/operations-statuses-monitor/templates/operations-statuses-monitor.html
- src/js/angular/models/monitoring/operations/active-operation-model.js
- src/js/angular/models/monitoring/operations/operation-status.js
- test-cypress/integration/monitor/global-operation-statuses-component.spec.js
- test-cypress/steps/operations-statuses-component-steps.js
When there are ongoing rebuild similarity index. The global operation component is displayed without icon and count of the ongoing operation.
The issue arose after a code refactoring that removed the summary object for all operations, done for optimization. To display ongoing operations, the UI relies on an array returned from the backend, which contains information about icons and the count of ongoing operations per operation group. The problem occurred because "queries" and "imports" are part of the same operation group, and they share the same icon and count (the sum of both operations). This resulted in double-displaying the "query" group icon and count, causing the update query to be skipped for visualization. Rebuilding the similarity index triggers only one update operation, which …
> Chery-pick GDB-9074: When only one Query and Update is running in the UI is not displayed

- src/css/new-sparql.css
- src/js/angular/core/directives/queryeditor/query-editor.controller.js
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- test/core/directives/queryeditor/query-editor.controller.spec.js
Fix saved queries actions triggering which occasionally didn't happen.
The saved queries popup and actions inside it was badly implemented to mix the popover's behavior with the angular's show/hide which led to having the dom elements in inconsistent state at times so that the buttons in the popover had their click handlers not attached properly.
Removed redundant logic which used to rely on jquery.collapse and restyled the saved queries list items and buttons inside the popover to show/hide them by using just regular css instead of using javascript.
> GDB-9071 fix saved queries actions triggering

- src/css/new-sparql.css
- src/js/angular/core/directives/queryeditor/query-editor.controller.js
- src/js/angular/core/directives/queryeditor/templates/query-editor.html
- test/core/directives/queryeditor/query-editor.controller.spec.js
Fix saved queries actions triggering which occasionally didn't happen.
The saved queries popup and actions inside it was badly implemented to mix the popover's behavior with the angular's show/hide which led to having the dom elements in inconsistent state at times so that the buttons in the popover had their click handlers not attached properly.
Removed redundant logic which used to rely on jquery.collapse and restyled the saved queries list items and buttons inside the popover to show/hide them by using just regular css instead of using javascript.
Updated unit test to accommodate to change in the implementation
Reverted the css class applied to saved queries list items in the popup because it was used in the cypress tests. Also improved the styling of the saved queries dialog to …
> GDB-9071 fix saved queries actions triggering (#1119)

- src/js/angular/autocomplete/controllers.js
- src/js/angular/rdfrank/app.js
What
Toast messages not handling <>& symbols when stating the iri is invalid.
Why
These are special symbols in HTML that are not properly decoded by HTML
How
Using function decodeHTML() to decode HTML entities (e.g., &lt;, &gt;, &amp;) in a given HTML string back into their corresponding characters. It utilizes the HTML textarea element to perform this decoding.
> GDB-9092 Toast messages not handling <> and symbols when stating the iri is invalid.

- src/js/angular/autocomplete/controllers.js
- src/js/angular/rdfrank/app.js
What
In some cases toast error messages shows empty IRI to be invalid IRI. For example: "" is invalid IRI.
Why
When passing the IRI to the error message it is not taken the way the user input it but after transforming it.
How
Error message takes the initial input to use when creating the message and it is made consistent through both views Autocomplete and RDFRank.
> GDB-9092 Toast messages not handling <>& symbols when stating the iri is invalid

- src/js/angular/explore/statements.service.js
What
Corner case of parsing resource in single quotes.
Why
Turtle parser embraces literals in """ or '''.
How
Added check for a corner case when a literal start or/and ends with a single quote.
> GDB-8336 WB edit of some context triples gives syntax toast errors - Corner case

- package-lock.json
- package.json
- src/css/lib/ontotext-yasgui-web-component.css
Integrates the chart and pivot table yasr plugins.
These two plugins are not part of the opensource yasgui library from version 4 but are present in the workbench which currently uses an older yasgui version where they are still present. That's why both plugins needed to be reimplemented and introduced in the yasr as plugins again.
Implemented both plugins from scratch based on their versions from the old yasgui.
> GDB-7789 GDB-7790 integrates the chart and pivot table yasr plugins

- src/js/angular/explore/statements.service.js
What
Corner case of parsing resource in single quotes.
Why
Turtle parser embraces literals in """ or '''.
How
Added check for a corner case when a literal start or/and ends with a single quote.
> GDB-8336 WB edit of some context triples gives syntax toast errors

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/core/services/repositories.service.js
- src/js/angular/sparql-editor/controllers.js
- src/pages/sparql-editor.html
Fix download sparql results operation in the sparql view.
The `download as` operation seems to be broken for a while because we removed the form used for submitting the parameters needed for the export as well as there was another issue where the sparql endpoint was impossible to be resolved the way it was implemented because the `endpoint` configuration can be a string or a get function which is expected to be evaluated in the context of the YASGUI component and not in the workbench.
* Re-introduced the download as parameters form again.
* Refactored the obtaining of the sparql endpoint based on the query mode so that it can be used correctly in the context of the workbench.
> GDB-9077 fix download sparql results operation in the sparql view

- src/js/angular/core/services/repositories.service.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/rest/jdbc.rest.service.js
- test-cypress/integration/setup/jdbc.spec.js
Fix jdbc preview table results.
It was broken during some refactoring a while ago with the https://ontotext.atlassian.net/browse/GDB-8813 and https://ontotext.atlassian.net/browse/GDB-8644. The refactoring removed the http headers for repository and location for the jquery ajax api and then also moved the headers application into the authentication interceptor which were correct and good changes, but it wasn't accounted that for the case in jdbc view the preview request was made with jquery ajax because the response was passed directly to the yasr which expected it to in the format as jquery returned it. So migrating the code to use angular's http service for the request and then headers configuration broke it completely.
* Reverted setting the jquery.ajax header configuration with the …
> GDB-9117 fix jdbc preview table results

- src/js/angular/core/services/repositories.service.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/rest/jdbc.rest.service.js
- test-cypress/integration/setup/jdbc.spec.js
Fix jdbc preview table results.
It was broken during some refactoring a while ago with the https://ontotext.atlassian.net/browse/GDB-8813 and https://ontotext.atlassian.net/browse/GDB-8644. The refactoring removed the http headers for repository and location for the jquery ajax api and then also moved the headers application into the authentication interceptor which were correct and good changes, but it wasn't accounted that for the case in jdbc view the preview request was made with jquery ajax because the response was passed directly to the yasr which expected it to in the format as jquery returned it. So migrating the code to use angular's http service for the request and then headers configuration broke it completely.
* Reverted setting the jquery.ajax header configuration with the …
> GDB-9117 fix jdbc preview table results (#1130)

- package-lock.json
- package.json
- test-cypress/integration/resource/resource.spec.js
When `showResultTabs` flag for the yasgui component is set to `false` then all yasr plugins should be hidden.
There are some integration points like the explore (resource) view where only the yasr results table renderer should be displayed and no tabs should be visible. In the latest version of the yasgu component were introduced two new yasr plugins: charts and pivot table. These two plugins were not registered in the service which used to hide them when the flag is falsy.
* The component was updated and the new version is integrated in the workbench
* Also enabled tests.
> GDB-9118 hide all yasr plugin tabs if configured via showResultTabs

- package-lock.json
- package.json
Improve styling of yasr table results.
Cells holding literal values were not styled correctly to apply the ellipsis which resulted in value being cut off.
Integrated the latest version of the ontotext yasgui component which improves the styling of the paragraphs inside literal cells in order for the ellipsis to work and also applied a title attribute to them so that when the value gets truncated, the user to still be able to see the whole value.
> GDB-8247 improve styling of yasr table results

- src/css/lib/ontotext-yasgui-web-component.css
Fix download as menu styling for consistency with old yasgui.
The dropdown menu items padding and font size were left default as in the ontotext yasgui component which resulted in different menu and menu items size.
Overriding the menu items padding and font-size properties.
> GDB-9114 fix download as menu styling for consistency with old yasgui

- src/css/lib/ontotext-yasgui-web-component.css
Reposition yasqe action buttons to prevent overlapping with the vertical scrollbar when it's present in the yasqe.
Yasqe buttons were placed too close to the right-side border of the editor which led to overlapping between the vertical scrollbar and the run query button.
Increased the space between the buttons and the right-side editor border
> GDB-8994 reposition yasqe action buttons

- package-lock.json
- package.json
* yasr ellipsis checkbox is disabled by default
* styling improvements in yasgui
* Trying to improve consistency with the old yasgui.
* Ellipsis should be unchecked by default by requirement.
Integrated the latest released ontotext yasgui component version
> GDB-8994 and GDB-9006 integrate latest fixes in ontottext yasgui component

- src/js/angular/chatgpt/controllers.js
What
404 failing request to /rest/chat/retrieval when GraphDB started with external url.
Why
The services in the WB are unaware of the context path behind which the application might be deployed. For the talk to your graph view I think that the odd thing is the way the endpoint is given /rest/chat/retrieval?... starting with / which probably brakes the proper request routing.
How
Changed building request to rest/chat/retrieval to consider different path if provided.
> GDB-9132 "Talk to Your Graph" user interface fails to read graphdb.external-url

- package-lock.json
- package.json
- src/js/angular/clustermanagement/directives.js
- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/graphexplore/directives/dependencies-chord.directive.js
- src/js/angular/graphexplore/directives/domain-range-graph.directive.js
- src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
- src/js/lib/common/d3-utils.js
- src/js/lib/d3-tip/d3-tip-patch.js
- src/js/lib/d3.patch.js
Update the D3 library to latest version v7
There is a vulnerability in d3-color package in the used D3 v3 library. The vulnerability is fixed and released with D3 v7.8.5. Since there are major breaking changes in v4, a migration first to v4 and then to v7.
- refactored directives and controllers to update to D3 v7.8.5 (latest)
> GDB-9085 Upgrade D3.js library to v7

- docs/developers-guide.md
- src/js/angular/core/services/theme-service.js
- src/js/angular/resources/chart-models/chart-data.js
- src/js/angular/resources/chart-models/cluster-health/cluster-health-chart.js
- src/js/angular/resources/chart-models/performance/connections-chart.js
- src/js/angular/resources/chart-models/performance/epool-chart.js
- src/js/angular/resources/chart-models/performance/queries-chart.js
- src/js/angular/resources/chart-models/resource/cpu-load-chart.js
- src/js/angular/resources/chart-models/resource/disk-storage-chart.js
- src/js/angular/resources/chart-models/resource/file-descriptors-chart.js
- src/js/angular/resources/chart-models/resource/global-cache-chart.js
- src/js/angular/resources/chart-models/resource/heap-memory-chart.js
- src/js/angular/resources/chart-models/resource/non-heap-memory-chart.js
- src/js/angular/resources/controllers.js
- src/themes/default/plugin.js
- src/themes/onto-original/plugin.js
- test/resources/controllers.spec.js
* Use main font from css variable
* Use colors from theme (via css variables)
* Introduced new color in theme (gray-color-dark, essentially the computed value of rgba(0, 0, 0, 0.66) over a white background)
* Use semi-transparent colors for bulky bits (area, bars) + adjusted emphasis (on hover) for the storage graph
* Don't use ThemeService to access things
* All items in subtitle on one line + centered subtitle
* No tooltip on legend hover (shows the same string as the legend label)
* 24-hour clock for times
* HH:mm + bold format for round minutes in time series (this mimics more or less the default echarts behaviour without a formatter but the default one makes it too bold)
> GDB-9086: Usability improvements and cleanup

- src/css/lib/ontotext-yasgui-web-component.css
- test-cypress/integration/sparql-editor/yasr/toolbar/visual-graph-button.spec.js
- test-cypress/steps/yasgui/yasr-steps.js
Reorder yasr toolbar and make it responsive.
In order to comply with the existing visualization in the workbench
* Added media queries to improve responsiveness.
* Changed some styles to better match the existing workbench styling.
> GDB-8997 and GDB-8998 reorder yasr toolbar and make yasr more responsive

- src/js/angular/rest/rdf4j.repositories.rest.service.js
Unable to proceed requests to repositories/${repositoryId} when external url given.
Hard-coded path to rdf4j repositories/${repositoryId}.
Changed building request to rdf4j.repositories.rest.service.js to consider different path if provided.
> GDB-9210 Download As JSON and JSONLD User interface fails to read graphdb.external-url

- src/js/angular/similarity/controllers/create-index.controller.js
- test-cypress/integration/explore/similarity.spec.js
There is not "Index with this name already exists." error message when try to create similarity index with same name.
There is validation to check if index with same name exist, but the return statement inside the forEach loop doesn't actually terminate the outer function (validateSimilarityIndexNameExistence), so the Promise is not being returned correctly.
The validation function has been fixed.
> GDB-9179: Error when I create similarity index from existing one with the same name

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/pages/graph-config/saveGraphConfig.html
- src/pages/sparql-editor.html
- test-cypress/integration/sparql-editor/saved-query/abort-query.spec.js
- Different color on info icon in a SPARQL Query & Update;
- There is a randomly failing test 'Should prevent leaving with confirmation when expand query is changed';
- The test "should abort query when click on "Abort query" button." frequently fails.
- The theme changes has been added after implementation of sparql editor page and the theme color is not set to it;
- There is a NPE - "cons:error ✘ TypeError: Cannot read properties of undefined (reading 'getPropertyDescription')" when try to retrieve sample name of a query;
- When the "Abort query" button is clicked, the value of the button and the tooltip are changed. However, the time between clicking and disappearance is too short, leading to the test failure with "AssertionError: Timed out retrying after 15000ms: Expected to find …
> GDB-9167: Different color on info icon in a SPARQL Query & Update

- src/css/lib/ontotext-yasgui-web-component.css
Change yasqe font family.
For consistency with the current workbench.
Applied the existing font in the codemirror
> GDB-8992 change yasqe font family

- package.json
- src/css/lib/ontotext-yasgui-web-component.css
- test-cypress/integration/sparql-editor/plugins/error-plugin.spec.js
- The font of the explain plan query differs from the old yasr;
- The error plugin tests frequently failed.
- The "font-family" property was not set;
- We don't know exactly why. But the test fail on verification if full error message displayed.
- The "font-family" has been set to the same value as in the old yasr;
- The error text verification has been changed.
Updates the ontotext-yasgui-web-component version because there is a fix for the explain plan query. The result looks like plain text.
> Gdb 9168 wrong styling of explain plan

- src/css/lib/ontotext-yasgui-web-component.css
Fix the color of the rdf star triples in yasr results.
For consistency with the current workbench styles.
Overridden the style applied to triple link tag
> GDB-9008 fix the color of the rdf star triples in yasr results

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
- visual graph steps where user have click/doubleclick in user guides are broken;
- hierarchy steps where a node is zoomed or focused.
We updated the d3 library.
Changed behaviour to work with the new version of d3.
> GDB-9236: User Guides stop on Vis Graph segment and block the workbench

- package-lock.json
- package.json
- test-cypress/integration/resource/resource.spec.js
Update ontotext-yasgui component version to 1.1.8
The version includes following changes:
* GDB-8990 fix default query formatting in yasqe
* GDB-9002 improve styling of the hotkeys dialog
* GDB-8641 properly resolve tab by name and query before open a new one
* GDB-9231 prevent tab duplication when saved query is selected
* GDB-9230 remove chart config button when changing yasr tabs
* GDB-8642 switch labels on yasqe buttons when language is changed
Increased the version
> Update ontotext-yasgui component version to 1.1.8

- src/css/lib/ontotext-yasgui-web-component.css
Fix size of the yasgui orientation changing button.
Its size was decreased unexpectedly when the font-size was reset in the entire yasgui component.
Applied the correct font-size to the button
> GDB-9243 fix size of the yasgui orientation changing button

- package-lock.json
- package.json
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/models/ontotext-yasgui/keyboard-shortcut-name.js
The 'ontotext-yasgui-web-component' has been updated.
This update includes fixes for:
- GDB-8993 preserve cursor position when query is set in the editor;
- GDB-9145: Visual graph cannot open via Sparql view when used pivot table and google chart;
- GDB-8645: Keyboard shortcuts differences between old implementation;
- GDB-8189: When pressing the buttons [Ctrl|Cmd]-D Delete current/selected line(s) - several times in a row, I delete all rows until only the top row remains;
- GDB-9003: Keyboard shortcuts missing/unclear
- The 'ontotext-yasgui-web-component' has been updated to v1.1.10;
- In the new version, a configuration has been introduced to control which keyboard shortcuts are active. According to these changes, the configuration is updated in the yasgui-component directive to …
> Updates the version of 'ontotext-yasgui-web-component'

- src/css/lib/ontotext-yasgui-web-component.css
Change background color of the get snippet button in chart and pivot table yasr plugins.
For consistency with other buttons and with the current workbench
Changed the background color and also removed some redundant padding from the button which used to decrease the usual offset between the icon and its left border.
> GDB-9265 change background color of the get snippet button in chart and pivot table yasr plugins

- src/css/lib/ontotext-yasgui-web-component.css
Fix dialog font and color issues.
* Improve the selector used to reset the font-size in ontotext-yasgui so that it omits the heading tags to prevent breaking their native styling.
* Decrease margin between buttons in the dialog footer to be more consistent with the current workbench.
* Fix colors of the buttons in the dialog.
For consistency with other buttons and with the current workbench
Changed the css selectors and style properties of the buttons.
> GDB-9269 fix dialog font and color issues

- package-lock.json
- package.json
- src/css/lib/ontotext-yasgui-web-component.css
* Update ontotext-yasgui component version to 1.1.11 and also ensure needed changes in workbench styling are applied too.
The yasgui version includes following changes:
* GDB-9234: When scrolling through pages in the SPARQL editor and results, the page order is shortly lost
* GDB-8984: Add close other tabs keyboard shortcut description
* GDB-8984: Add close other tabs functionality when click on close tab button with 'Shift' key pressed
* GDB-9147 introduce an alert box component
* GDB-9147 handle google charts error
* GDB-9267 position the query button at the bottom of the editor
* GDB-9142 make datatable horizontally scrollable
Increased the version
> Update ontotext-yasgui component version to 1.1.11

- src/pages/cluster-management/clusterInfo.html
- test-cypress/integration/cluster/cluster-management.spec.js
Removed node replacement operation for GDB10.5 version.
Removed it due to instability of the cluster in the backend after introducing the feature.
Hide the button that opens the replace node dialog and skipped the tests.
> GDB-9108 removed node replacement operation for GDB10.5 version

- src/css/create-similarity-index.css
- src/css/graphs-config.css
- src/css/jdbc-create.css
- src/css/sparql-templates.css
- src/pages/sparql-template-create.html
In all views where yasgui is used the yasqe should have fixed height, so that it accomodates also some other elements below it, like buttons, etc.
There is a function in the yasgui component which dinamically calculates the yasqe height so that the editor to fit tightly in the available screen space. The function works ok for the sparql view, but in the rest of the views it screws the layout a bit, because there are some other elements below the editor and this forces a vertical scrollbar to appear in most places or just its height is not the same as in the current workbench.
Add fixed height to codemirror on each view so that to override the calculated base height.
> GDB-9269 change yasqe height in all views but sparql

- src/css/lib/ontotext-yasgui-web-component.css
Increase tab close confirmation dialog font size.
It differs from current workbench. The reason is that we use the custom confirmation-dialog web component from the ontotext-yasgui library where it is styled but the style is applied in the context of the yasgui-component and this dialog here is attached to the html body directly instead.
Added additional css selector for when the dialog is attached to the html body directly
> GDB-9317 increase tab close confirmation dialog font size

- src/css/lib/ontotext-yasgui-web-component.css
Add more space between buttons in delete tab dialog.
The delete tab dialog in yasgui is rendered directly in the body and that's why the styles for the dialogs in the yasgui context doesn't affect it. For consistency with the current workbench.
Added additional selector to match the delete tab dialog.
> GDB-9317 add more space between buttons in delete tab dialog

- src/js/angular/jdbc/controllers.js
Authorize JDBC preview requests which previously failed with status 401 when GDB security was on.
The changes related with the following tasks were causing loss of functionality where some of the required by the GDB http headers were not sent with the request for the JDBC preview. The following fix was applied later on https://github.com/Ontotext-AD/graphdb-workbench/pull/1131 but it seemingly missed the criteria for authenticating the preview requests.
Added the Authorization token if present as a header in the request config.
> GDB-9349 authorize jdbc preview requests

- Jenkinsfile
- package.json
- src/js/angular/jdbc/controllers.js
- src/js/angular/models/yasgui-component.js
- src/js/angular/similarity/controllers/create-index.controller.js
- When executing a query, the view mode is changed to "RenderMode.YASGUI" (both YASQE and YASR are visible);
- When executing a test query and switching to either the "Search query" or the "Analogical query," the YASGUI render view does not change to "YASQE" mode;
- When opening the JDBC Create view, unnecessary buttons are present in the YASQE view.
- We implemented this functionality with [GDB-8995](https://ontotext.atlassian.net/browse/GDB-8995), because this is the expected behavior;
- The YASGUI mode was previously only changed when the "Data query" tab was opened;
- It is omitted to hide.
- Updated the version of ontotext-yasgui-web-component. It includes changes that provide the opportunity to customize the render view after executing the query;
- Changed the `changeQueryTab` …
> Gdb 9310 long yasqe screen with useless buttons in sql table configuration

- package-lock.json
- package.json
- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/models/yasgui-component.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/sparql-template/controllers.js
- test-cypress/integration/setup/jdbc-create.spec.js
- test-cypress/integration/setup/sparql-template-create.js
- test-cypress/integration/sparql-editor/sparql-editor.spec.js
- test-cypress/steps/home-steps.js
- test-cypress/steps/setup/sparql-templates-steps.js
- test-cypress/steps/yasgui/yasr-steps.js
Handle repository change and reset results rendered in yasgui. This involves all views where the yasgui is used: sparql editor, jdbc, sparql templates, similarity index create, visual graph, resource view
For consistency with the current workbench.
Trigger the reset results method in yasgui component when repository gets changed. Also added a flag that prevents the reset on the initialization of the view when the repository change event is also fired.
> GDB-8643 Handle repository change and reset results rendered in yasgui

- src/css/bootstrap-graphdb-theme.css
- src/css/lib/ontotext-yasgui-web-component.css
Make yasr tabs consistent with current workbench. This involves changing color, borders, removing some duplicated and conflicting styles.
Minimize differences between new and old yasgui.
Remove duplicated styles and fixed the color of the yasr tab in the component stylesheet. Also changed the border styling to match closer with the workbench.
> GDB-8996 make yasr tabs consistent with current workbench

- src/js/angular/core/directives.js
- src/js/angular/sparql-editor/controllers.js
- src/pages/sparql-editor.html
Top align yasgui in sparql view.
It received some top offset when the core-errors directive was added. The way directive is implemented results in weird behavior where its content elements being always rendered in the DOM but invisible. That's why everything laying beneath being pushed down needlessly.
Refactored the directive a bit to check if there is actually a need to be rendered and show or hide its host element respectively.
> GDB-9398 top align yasgui in sparql view

- src/css/lib/ontotext-yasgui-web-component.css
GDB-8994 change yasqe buttons styling
Change yasqe buttons styling
* Change yasqe query button font-size and weight same as in current workbench.
* Change yasqe query button height and also make it responsive.
* Decrease yasqe icon buttons font-size to match current workbench
> GDB-8994 change yasqe buttons styling

- package-lock.json
- package.json
- src/css/lib/ontotext-yasgui-web-component.css
- Changed the color and weight of text in YASQE tabs;
- Changes color and sizing of tabs icon.
- The colors and weights were different from the old implementation;
- The colors and sizing were different from the old implementation.
- Changed the color to inherit from its parent and set the weight to 400;
- Changed the color to 'rgba(0, 0, 0, 0.66)' and set the size to 1.225em.
Increased the version of "ontotext-yasgui-web-component."
The new version includes:
- When opening "ontotext-editable-text-field" in edit mode, the buttons are positioned outside its container;
- When opening "ontotext-editable-text-field" in preview mode, the tab name and close button are not properly aligned;
- When hovering over the "Close tab" and "Add tab" icons, they do not resemble the appearance of the old …
> GDB-8984: Fixes YASQE tabs issues.

- src/css/lib/ontotext-yasgui-web-component.css
Change styles of download as button in yasgui.
* Add styles for height and font to make the button responsive.
* Remove media query which used to hide the button text on smaller resolutions. Also removed it for the visual graph button.
> GDB-8677 change styles of download as button in yasgui

- src/pages/explore.html
- test-cypress/integration/resource/resource.spec.js
The "Inference" dropdown in the resource view is not disabled when the selected role is context.
After the refactoring of the controller, the variable 'role' has been removed, but the view has not been updated accordingly.
Update the view of the resource view to align with the refactored model.
> GDB-9366: Drop-down list in Resource view should not be accessible from Context tab

- package-lock.json
- package.json
* GDB-9414 preserve the query loader indicator while query is running https://github.com/Ontotext-AD/ontotext-yasgui/pull/210
* GDB-9338: When opening a saved query, there should be a very brief highlighting of the tab name in red https://github.com/Ontotext-AD/ontotext-yasgui/pull/209
* GDB-9268 make yasgui layout modes consistent with current workbench https://github.com/Ontotext-AD/ontotext-yasgui/pull/208
* GDB-9004 reposition autocomplete hint to prevent overlapping with the current line in editor https://github.com/Ontotext-AD/ontotext-yasgui/pull/207
Get latest fixes and features from the component.
Increased the version
> Increase yasgui component version

- src/css/lib/ontotext-yasgui-web-component.css
Fix pivot table and charts tabs icon color.
Add `fill` color to override the svg styling of the icon coming from yasgui.
> GDB-8996 fix pivot table and charts tabs icon color

- src/css/graphs-config.css
- src/pages/graph-config/saveGraphConfig.html
Sample queries in visual graph should not be repeated in the user sample queries section.
There was a wrong check in the template which caused the repeat of the user samples section to be rendered for each of the configuration tabs.
* Fixed the expression the template to check the page for current active tab.
* Also added small css fix for the start node config type selector to make it equal width in all three instances.
> GDB-9361 sample queries in visual graph should not be repeated

- src/css/lib/ontotext-yasgui-web-component.css
Yasr table borders should be collapsed.
The datatable plugin used in yasr comes with the style for `table-collapse: separate` which makes the borders thicker which is not consistent with current workbench
Add style `border-collapse: collapse` to data table in yasr.
> GDB-8998 yasr table borders should be collapsed

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
The dialog displaying progress for creating/updating a connector does not close properly.
The dialog should be closed after a create/update connector operation succeeds or fails. To close the dialog, an event handler for the "queryExecuted" event is registered. This handler is specific to the SPARQL view, and it is passed as configuration to the "yasgui-component.directive." During the refactoring of the initial code and implementation of the directive, the handler was passed but not read in the directive, resulting in the handler not being registered for the event.
Added the missing registration of the handler.
> GDB-9413: Error handling when creating connectors

- src/css/jdbc-create.css
- src/css/lib/ontotext-yasgui-web-component.css
- src/css/sparql-templates.css
- src/pages/jdbc-create.html
- src/pages/sparql-template-create.html
Make yasqe height consistent with current workbench.
For consistency with current workbench.
* Changed the height of the codemirror inside yasqe.
* Also removed the fluid container class from the yasgui wrapper to prevent the excessive padding comming from it.
* Applied darker border color to codemirror to be consistent with the one in the workbench.
> GDB-9310 make yasqe height consistent with current workbench

- package-lock.json
- package.json
- src/css/sparql-editor.css
GDB-9360: Yasr - wrong extending the result table when sorting by one column
- When expanding some columns in the result table, the table overflows its parent container;
- GDB-9431: The width of the first column is not set properly when columns are not resizable and the number column is hidden;
- GDB-9449: When refreshing the SPARQL view ,the checkboxes for "Hide row numbers" and "Compact view" are reset to their default values, disregarding user changes;
- GDB-9242: When selecting/deselecting the checkbox "Hide row numbers", the yasr result table is updated too slowly;
- GDB-9443: change charts plugin label.
- The overflow properties were not set;
- GDB-9431: When the result table becomes unresizable, we set a fixed width for columns by CSS, excluding the first column for row numbers. …
> GDB-9360: Yasr - wrong extending the result table when sorting by column

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/core/directives/yasgui-component/yasgui-persistence-migration.service.js
- src/js/angular/models/sparql/constants.js
- src/js/angular/sparql-editor/controllers.js
- test-cypress/fixtures/locale-en.json
Migrate old yasgui persistence to new yasgui model.
Users which migrate from GDB workbench version with the old yasgui to a version with the new yasgui may want to have their current opened tabs to be preserved in the new version as well.
* Check if migration is needed and run the migration.
* Migration is done in the new yasgui persistence migration service. It copies the tabs data from the old persistence to the new one and preserves the old data after migration.
> GDB-9406 migrate old yasgui persistence to new yasgui model

- src/pages/graph-config/saveGraphConfig.html
Show copy of sample query in user query section in graphs config.
There was a wrong condition which prevented showing the query copy only on the first page.
Fixed the condition allowing to show the selected sample queries from previous configs to appear in the user queries section.
> GDB-9361 show copy of sample query in user query section in graphs config

- src/css/lib/ontotext-yasgui-web-component.css
Change buttons color on focus in yasgui dialogs.
There was missing selector for the case when buttons are on focus which basically should be the same as on hover.
Added missing selectors for on focus for confirm and cancel buttons
> GDB-9115 change buttons color on focus in yasgui dialogs

- src/pages/aclmanagement.html
Show ACL table rules when repository is selected
There are no rules when not connected to repository
Check added
> fix(GDB-9098): Show ACL table rules when repository is selected

- package-lock.json
- package.json
- GDB-9433: When attempting to delete a saved query with a long name, the name goes off the confirmation screen;
- GDB-9315: Warning Message in the Console After Clicking on Google Tab.
- GDB-9433: The issue occurs when the saved query name is too long and cannot be broken into a new line;
- Changes have been made to how the [Google Chart library](https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code) is loaded. Both plugins use different methods for loading, leading to the appearance of the warning message.
Increased the version of "ontotext-yasgui-web-component";
> Increase the version of "ontotext-yasgui-web-component"

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- src/pages/repository.html
- test-cypress/fixtures/locale-en.json
Fix repository edit view initialization to not break when the monitoring service throws some error.
There was a coupling in loading the monitoring service status and the repository info during the initialization of the view. Both requests were issued in parallel and had a single catch clause to handle the error which used to brake the template.
Decoupled the loading of repository info and monitoring status from each other and applied separate error handlers in order to prevent template braking.
> GDB-9451 fix repository edit view initialization

- src/css/lib/ontotext-yasgui-web-component.css
Unify the height of the yasgui and yasr tabs.
The height of those tabs should be consistent with the old yasgui and also be responsive.
Applied relative paddings to the tabs so that it scales properly.
> Unify yasgui and yasr tabs height

- src/css/aclmanagement.css
- src/css/autocomplete-select.css
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/core/directives/autocomplete/autocomplete.directive.js
- src/js/angular/core/directives/autocomplete/templates/autocomplete.html
- src/pages/aclmanagement.html
- test-cypress/integration/setup/aclmanagement/delete-rule.spec.js
Fixing functional issues in the ACL view.
For better perceiving and user experience.
- Adjusting the positioning of the autocomplete dropdown to prevent overflow outside the viewport.
- Fixing an off-by-one error in the delete confirmation dialog.
- Modifying the behavior of the Enter key to prevent unintended actions in the input fields.
- Correcting the outline display for required fields when empty.
- Preventing toast errors related to undefined repositories.
- Updating the 'required' field handling in the autocomplete directive.
- The adjustments in the autocomplete directive ensure that dropdowns are positioned correctly and that the Enter key behaves as expected across different input scenarios.
> fix(GDB-9484): Fix ACL functional issues

- src/css/aclmanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
Make save and cancel buttons sticky in ACL view.
In order to allow the user to have fast and easy access to those operations.
Styled the panel with the buttons to be sticky and have a background. Also added a message to warn the user that acl rules are not applied until the acl list is saved.
> GDB-9488 make save and cancel buttons sticky in ACL view

- package-lock.json
- package.json
- GDB-9476: this issue arises when there are no triples matching the query, leading to improper display empty row message;
- GDB-9483: fix query explain plan styling when displayed in multiple yasgui tabs;
- GDB-9475: There is an issue with the display of extended-table plugin controls. The problem can be reproduced with the following scenario:
- execute a select query;
- execute an update query.
- GDB-9475: The info message that describes the result of executed queries is differently positioned than in the old implementation of YASGUI.
- GDB-9476: the empty result message is displayed as row of datatable (jquery datatable behaviour). But the first column (row number) can be hidden and this causes the issues;
- GDB-9483: there was a wrong selector from the document for the explain plan …
> Fixes GDB-9475, GDB-9476 and GDB-9483

- package-lock.json
- package.json
Cherry-pick from master. Fixes GDB-9475, GDB-9476
- GDB-9476: this issue arises when there are no triples matching the query, leading to improper display empty row message;
- GDB-9483: fix query explain plan styling when displayed in multiple yasgui tabs;
- GDB-9475: There is an issue with the display of extended-table plugin controls. The problem can be reproduced with the following scenario:
- execute a select query;
- execute an update query.
- GDB-9475: The info message that describes the result of executed queries is differently positioned than in the old implementation of YASGUI.
- GDB-9476: the empty result message is displayed as row of datatable (jquery datatable behaviour). But the first column (row number) can be hidden and this causes the issues;
- GDB-9483: there was a wrong …
> Cherry-pick form master Fixes GDB-9475, GDB-9476

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
Enable inferred data and expand on same as property buttons in visual graph config view.
The user should be able to configure these two properties in the visual graph config.
Provided configuration for enabling these two buttons in the yasqe.
> GDB-9471 enable inferred data and expand on same as property buttons in visual graph config

- package-lock.json
- package.json
Update yasgui component version to 1.1.26
* GDB-8247 improve styling of yasr results containing long strings
> Update yasgui component version to 1.1.26

- package-lock.json
- package.json
Increase yasgui version to 1.2.1
* GDB-9500 fix explain plan styling
Increased version
> Increase yasgui version to 1.2.1

- package-lock.json
- package.json
Increase the version of "ontotext-yasgui-web-component"
WB has a new release 2.6, we increase the version of "ontotext-yasgui-web-component" for management purpose.
The "ontotext-yasgui-web-component" has been increased.
> Cherry-pick from 2.6: Increase the version of "ontotext-yasgui-web-component

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
The "Create rule" button is not translated to French.
The label was hardcoded, it missed to be translated.
Added translation to the button.
> GDB-9504: Create rule button not translated to french

- src/js/angular/jdbc/controllers.js
The information messages in the SQL table configuration will display bold text correctly.
The HTML tags were visible in the message.
I added a function to decode the HTML in the text.
> GDB-8670 - Decode HTML tag in toastr message

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
The "Create rule" button is not translated to French.
The label was hardcoded, it missed to be translated.
Added translation to the button.
> Cherry-pick from 2.6 GDB-9504: Create rule button not translated to french

- src/pages/similarity-indexes.html
The buttons in the Similarity index page are now all in the same color.
Previously, two of the buttons didn't match the rest.
I changed the element tag to `button`.
> GDB-9365 - Make Similarity index action buttons the same color

- src/js/angular/aclmanagement/controllers.js
Clear the rule highlighting on tab switch.
It's annoying bug where the selected rule index remains uncleared in the controller when tab is switched which causes a flickering of previously moved rule.
Cleared the selected rule index in the controller to prevent flickering on tab switch.
> GDB-9516 clear the rule highlighting on tab switch

- src/css/bootstrap-graphdb-theme-dark-auto.css
The dropdown menus will have styling to match the dark theme, whenever it's applied. 
The menus used to remain the same as in the light theme. This created a bad experience for users using the dark theme.
I added new styling for the `option` tags.
> GDB-9371 - Apply dark theme to dropdown menus

- src/css/aclmanagement.css
Autocomplete dropdown menu is cut off in acl table.
A combination of two reasons caused the dropdown menu to be cut off. First is that the autocomplete component is rendered inside the table cells and the second is the `responsive-table` style applied to the table wrapper which style used to apply `overflow-x:auto` property.
Overridden the overflow-x to prevent the overflowing behavior of the table wrapper. In this table we actually don't need this as the ACL table has predefined number of columns and doesn't need to overflow in the X axis.
> GDB-9516 autocomplete dropdown menu is cut off in acl table

- package-lock.json
- package.json
Increase version of ontotext-yasgui-web-component.
- GDB-9500 Explain plan should always be displayed in one column;
- GDB-9480 Rename a tab name should be selected to write on it rather than having to be manually deleted by the user;
- GDB-9462 Unable to close the tab when there are numerous saved results in local storage;
- GDB-9242 Refactoring compact view;
- GDB-9479 Different French label on button Abort query;
- GDB-9514 SPARQL Editor last tab can be closed which removes the entire view;
- GDB-9528 Copy link buttons of an RDF star link not properly displayed.
The version of ontotext-yasgui-web-component has been increased.
> increase version of ontotext-yasgui-web-component

- src/css/import.css
- src/pages/import.html
- test-cypress/integration/resource/resource.spec.js
The bottom text in the buttons in the Import page is positioned to always start under the first letter of the top text.
The bottom text would become misaligned in the first button when resizing the page.
I altered the template structure of the buttons and added new styling.
When resizing the page, the buttons look as follows:
* GDB-9237 - reposition import button text, so it doesn't "jump" on resize
* GDB-9237 - change grey text position
* GDB-9237 - remove extra div and apply styling to its parent
* GDB-9237 - add retry to test
(cherry picked from commit 15822ab61721c3e96a8adf7ac2afae0b9a372bf4)
> GDB-9237 - Reposition import button text (#1252)

- src/js/angular/core/services/repositories.service.js
Fix sparql query endpoint resolving.
When GDB WB is deployed behind a context path requests to all endpoints which the WB calls should start without `/` otherwise this might brake the request routing.
Removed the leading `/` from the sparql query endpoint used by the sparql editor and also by the download as feature.
(cherry picked from commit 793ff519574a90fee8de730d55ba095bcb08e285)
> GDB-9549 fix sparql query endpoint resolving

- src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
- src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
When open the step 36 or 58 from the "The Movies database guide" the guide dialog is appeared in top left corner of the browser instead under the query in YASQE.
When the SPARQL view is opened from a user guide, a new tab is opened. It is used by the guide because we don't want to change a user's query if we use the currently opened tab. The problem occurred in both steps because they have to display the dialog under the query in the YASQE editor. To find the editor they use selector that finds a "CodeMirror" element, after the element is visible the dialog is opened, but this process is quicker than this that opens the new tab. When tab is open the selected element is hidden this is why the dialog is moved to the upper lef corner of the view.
The problem occurred after replaced old …
> Cherry-pick from master GDB-9510: Interactive guides panels point to browser corner instead of inside the SPARQL Editor

- package-lock.json
- package.json
Increased the version of the "ontotext-yasgui-web-component".
- GDB-9242: Refactoring the compact view functionality;
- Fixes an issue related to [GDB-8247](https://ontotext.atlassian.net/browse/GDB-8247).
The version of "ontotext-yasgui-web-component" has been increased.
[GDB-8247]: https://ontotext.atlassian.net/browse/GDB-8247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase version of "ontotext-yasgui-web-component"

- src/pages/edit.html
The Resource view inputs will no longer suggest autocomplete options.
The autocomplete options were generated by the browser and irrelevant to the user.
I used the autocomplete property to achieve this.
> Cherry pick gdb 9371   - Turn off autocomplete in Resource edit view

- package-lock.json
- package.json
- src/css/create-similarity-index.css
- src/css/graphs-config.css
- src/css/jdbc-create.css
- src/css/sparql-templates.css
- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/js/angular/sparql-template/controllers.js
- Remove the non-functioning resize bar in the "Create similarity index";
- Remove the non-functioning resize bar in the "Create visual graph config";
- Remove the non-functioning resize bar in the "SQL table configuration";
- Remove the non-functioning resize bar in the "Create SPARQL Templates".
The height is set programmatically, and we don't want to change it.
The YASQE resizer has been hidden.
#Additional work
- GDB-9318: Turn off double click or YASQE resizer;
- GDB-9628 properly switch yasgui modes when tabs are switched or opened;
- GDB-9318: We don't want this behavior, when the component is used with other components in a view, this behavior can make the view look strange;
- GDB-9628:
- When switching to editor only mode, then changing to another tab or opening a new tab won't …
> Gdb 9387 remove yasqe resizer

- src/css/lib/ontotext-yasgui-web-component.css
GDB-8247: Cells in YASR are centered vertically.
This issue arises from the new YASGUI.
Top alignment has been added to all results in the YASR result table.
> GDB-8247: Cells in YASR are centered vertically

- src/css/lib/ontotext-yasgui-web-component.css
GDB-8247: Cells in YASR are centered vertically.
This issue arises from the new YASGUI.
Top alignment has been added to all results in the YASR result table.
> Chery-pick from 2.6.2 GDB-8247: Cells in YASR are centered vertically

- package-lock.json
- package.json
Update yasgui component version to 1.2.5
* GDB-9678: The 'Abort' button doesn't get translated when there are multiple running queries.
* GDB-9578 fix triple escaping when copying link
> Update yasgui component version to 1.2.5

- package-lock.json
- package.json
Update yasgui component version to 1.2.6
* GDB-9409: Change background color of yasr error plugin
> Update yasgui component version to 1.2.6

- src/css/create-similarity-index.css
- src/css/graphs-config.css
- src/css/jdbc-create.css
- src/css/sparql-templates.css
- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/js/angular/sparql-template/controllers.js
- Remove the non-functioning resize bar in the "Create similarity index";
- Remove the non-functioning resize bar in the "Create visual graph config";
- Remove the non-functioning resize bar in the "SQL table configuration";
- Remove the non-functioning resize bar in the "Create SPARQL Templates".
The height is set programmatically, and we don't want to change it.
The YASQE resizer has been hidden.
#Additional work
- GDB-9628: Properly switch yasgui modes when tabs are switched or opened;
- GDB-9318: Turn off double click of YASQE resizer.
- GDB-9628:
- When switching to editor only mode, then changing to another tab or opening a new tab won't preserve the selected mode;
- When switching to horizontal layout (2-columns), then yasqe spans the entire available page height, but when opening …
> Cherry pick from 2.6 gdb 9387 remove yasqe resizer

- package-lock.json
- package.json
Increase the version of "ontotext-yasgui-web-component".
There are fixes for:
- GDB-9409 Change background color of yasr error plugin
- GDB-9578 Invalid RDF-star triple on copy link in SPARQL editor.
The version has been increased.
> fixes for GDB-9409 and GDB-9578

- src/css/bootstrap-graphdb-theme-dark-auto.css
The dropdown menus will have styling to match the dark theme, whenever it's applied.
The menus used to remain the same as in the light theme. This created a bad experience for users using the dark theme.
I added new styling for the option tags.
> GDB-9371 - (cherry pick) set dark theme for dropdowns

- package-lock.json
- package.json
Update yasgui component version to 1.2.7
* GDB-9578: fix literal position in rdf star triple
> Update yasgui component version to 1.2.7

- package-lock.json
- package.json
Update yasgui component version to 1.3.3
* GDB-9578: fix literal position in rdf star triple
> Update yasgui component version to 1.3.3

- package-lock.json
- package.json
Update yasgui component version to 1.2.8
* GDB-9848: Yasr - Missing error in the result after abort query
> Update yasgui component version to 1.2.8

- package-lock.json
- package.json
Update yasgui component version to 1.3.4
* GDB-9719: Add loader when rendering result table after compact view toggled;
* GDB-9848: Missing error in the result after abort query.
> Update yasgui component version to 1.3.4

- src/js/angular/core/components/export-settings-modal/exportSettingsModal.html
- src/pages/explore.html
- src/pages/export.html
- test-cypress/integration/explore/graphs.overview.spec.js
- test-cypress/integration/import/import.server.files.spec.js
- test-cypress/integration/import/import.user.data.spec.js
- test-cypress/integration/resource/resource.spec.js
- test-cypress/integration/sparql-editor/yasr/download-as.spec.js
- test-cypress/steps/explore/graphs-overview-steps.js
- test-cypress/steps/import-steps.js
- test-cypress/steps/json-ld-modal-steps.js
- test-cypress/steps/resource/resource-steps.js
- test-cypress/steps/yasgui/yasr-steps.js
Add jsonld import/export tests.
To improve the code test coverage and prevent regressions.
> GDB-9211 add jsonld import/export tests

- src/css/operations-statuses-monitor.css
The icons were not properly separated from the text, they were too close to each other.
The labels had a CSS declaration that set padding to 5 px, but there was another declaration with higher specificity that set padding to 0 px.
The CSS selector has been modified to increase specificity scoring.
> GDB-9883: Misalignment on monitoring icons

- src/js/angular/rest/rdf4j.repositories.rest.service.js
There is an error when try to export results of query, that contains data.
The service which is responsible for downloading results makes a POST call to BE with "Content-Type" "application/x-www-form-urlencoded". The queries which causes the issue includes a data, for instance "FILTER (xsd:dateTime(?dateOfBirth) > "1999-03-22T14:17:31.290+02:00"^^xsd:dateTime)". The browser replace the character "+" with " " because of value of content type and this is the reason error appeared in BE. It can't parse data correctly.
Implemented query encoding before sending it to the backend. This encoding ensures correct parsing on the server side.
> GDB-9126: Cannot download json result from construct query

- src/js/angular/models/similarity/similarity-result-type.js
- src/js/angular/similarity/controllers/similarity-list.controller.js
- src/pages/similarity-indexes.html
- test-cypress/integration/explore/similarity.spec.js
- test-cypress/steps/explore/similarity-indexes-steps.js
When doing a similarity search and selecting a `result type`, the `search type` field will retain its value.
There was a bug the on `result type` selection, the `search type` would disappear and could not be selected again.
I added a method to set the `result type` whenever it's selected.
The working version allows the `result type` to be changed.
> GDB-9657 - Set the Similarity search result type correctly

- src/js/angular/clustermanagement/controllers/add-nodes.controller.js
- src/js/angular/clustermanagement/controllers/replace-nodes.controller.js
If a node goes offline, the add/replace node dialogs won't show it as an available remote location, until the node is removed first.
Previously, the node would appear as both added to the cluster and as an available location, which would cause some confusion.
The RPC address was checked previously and nodes without connection had no RPC address, meaning they didn't match the cluster node list and appeared as an available location.
I used an array to extract just the cluster node endpoints and used them to compare the locations against.
> GDB-9238 - hide remote locations already added to cluster node list

- package-lock.json
- package.json
Update ontotext-yasgui-web-component version to 1.3.6
- GDB-9430: Workbench footer overlaps with yasgui when it is in two column layout;
- GDB-9946: Workbench should allow to copy any long (truncated) value.
The version of ontotext-yasgui-web-component has been updated.
> Update ontotext-yasgui-web-component version to 1.3.6

- package-lock.json
- package.json
Update ontotext-yasgui-web-component version to 1.3.7
- GDB-9964: fixes YASGUI performance issue.
The version of ontotext-yasgui-web-component has been updated.
> Update ontotext-yasgui-web-component version to 1.3.7

- src/css/import.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers.js
- src/js/angular/import/file-prefix-registry.js
- src/js/angular/utils/file-utils.js
- src/pages/import.html
- test-cypress/fixtures/graphdb-import/sample-jsonld.json
- test-cypress/fixtures/locale-en.json
- test-cypress/integration-flaky/import/import.server.files.spec.js
- test-cypress/integration-flaky/setup/sparql-template-create.js
- test-cypress/integration/import/import-file-upload.spec.js
- test-cypress/integration/import/import-from-url.spec.js
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/integration/import/import-text-snippet.spec.js
- test-cypress/integration/import/import-user-data-tab.spec.js
- test-cypress/integration/import/import-view.spec.js
- test-cypress/integration/monitor/global-operation-statuses-component.spec.js
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/integration/setup/sparql-template-create.js
- test-cypress/steps/guides/guide-steps.js
- test-cypress/steps/import/import-steps.js
- test-cypress/support/commands.js
- test-cypress/support/import-commands.js
Change the upload files workflow in the user data tab on the import view.
The new upload workflow allows the user to decide if newly selected for upload files should override existing ones if filename collision occurs. If override is rejected, then all duplicated filenames are prefixed with a numerical index.
* Extended the import controller  and template so that when new files are selected to check for duplications and open a confirmation modal.
* Implemented additional utilities to calculate the file prefixes.
* Added new tests
> GDB-9972 change file upload workflow

- src/css/import-resource-tree.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
- src/pages/import.html
- test-cypress/fixtures/locale-en.json
- Added "Reset Status" and "Remove" buttons to the import-resource-tree directive;
- Added the "Import" button to the import-resource-tree directive;
- Added a dropdown menu for selecting files based on their status.
- This addition provides users with the ability to reset the status of imported resources and to remove files if they were uploaded by the user;
- This addition provides users with the ability to trigger the import of files with or without changing settings
- This addition provides users with the ability to select files based on their status.
> Gdb 9971 implements import resources buttons

- src/i18n/locale-fr.json
Wrong translation in French of 'Save' button in WB
The 'save'  button in french it's 'Enregistrer" (which is in the context of apps and saving progress , ..etc ) but in the WB app it's written "Sauver" (which is in the context of : Help , aid , "save a life" ).
Changed translation of "Save" button in French from Sauver to Enregistrer.
> GDB-10064 Wrong translation in French of 'Save' button in WB

- src/app.js
- src/js/angular/core/directives/prop-indeterminate/prop-indeterminate.directive.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
Implements an additional selection state for the "import-resource-tree" directive. This state is applied to directories indicates that not all children are selected.
To enhance user experience.
Implemented a new "propIndeterminate" directive that marks a checkbox as indeterminate. The "import-resource-tree" directive utilizes this directive to mark directories where some, but not all, children are selected.
> GDB-9971: Implement Three-State Checkbox

- src/css/import-resource-tree.css
- src/js/angular/import/directives/import-resource-message.directive.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-message.html
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-status.js
- Icons and colors have been added to resource messages;
- Implemented a reset status button for each resource in the tree.
- To enhance the user experience;
- This provides users with the opportunity to reset the status of individual files without having to click on checkboxes and use the global reset button.
- Different icons and colors have been applied to resource messages based on the import resource status. For example, errors are shown in red, successful operations in green, etc.
- The button has been added to each row in the import resource tree. When clicked, it calls the onReset function of the "import-resource-tree" directive client.
> Gdb 9971 add stylint to import resource messages

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
- src/js/angular/rest/mappers/import-mapper.js
- src/pages/import.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/steps/import/import-steps.js
- Implements the action to reset the import status of a single or multiple resources;
- Implements import single RDF resource;
- Implements interrupt single rdf resource import;
- Hides the "Delete" button when the server tab is active.
- This allows users to clear the status of either a single imported resource or all imported resources;
- This gives the user the opportunity to import a single RDF resource;
- This gives the user the opportunity to abort a rdf import if it is not finished yet;
- Server files can't be deleted from the workbench.
- Added a BE call to reset the status of either specified or all resources when the user clicks the "Reset status" button;
- Added a BE call to import a single RDF resource when the user clicks the "Import" button;
- Added BE call to abort a single …
> Gdb 9971 implement import resource file acitons

- src/js/angular/clustermanagement/directives.js
- src/js/angular/clustermanagement/services/cluster-drawing.service.js
The shortened recovery messages in the cluster view will appear full length on `mouseover`. They will become shortened on `mouseout`.
There was no way to see the full recovery message. 
I added event listeners in the service and used the original message size in the calculations.
On mouse over:
> GDB-10046 - show full recovery message on mouseover

- src/js/angular/import/directives/import-resource-status-info.directive.js
- src/js/angular/import/templates/import-resource-status-info.html
When the popover dialog displaying an imported resource appears at the bottom of the window, it causes the window to flicker.
The popover is initially positioned to the left of the icon, but if the content exceeds the available space and a vertical scrollbar appears, it causes the hovered icons to move. This movement triggers the popover to close and reopen under the cursor, leading to a flickering effect.
This fix removes the automatic closure of the popover when the mouse leaves the button. Now, the popover can only be closed by the user clicking on the close button, which appears in the top-left corner of the popover.
> GDB-9971: Fixes a popover issue

- src/res/swagger5/index.css
The links in the REST API view will appear the same color as the rest of the text.
The link styling came from the Swagger stylesheet and did not match the old UI.
I made sure to override the link style in the main `.css`.
> GDB-9664 - Match Swagger link color to the rest of the text on page

- src/js/angular/import/controllers.js
- src/js/angular/import/directives/import-resource-status-info.directive.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/file-status.js
- src/js/angular/models/import/import-resource-tree-element.js
- src/js/angular/models/import/import-resource.js
- src/js/angular/rest/mappers/import-mapper.js
- src/js/angular/rest/upload.rest.service.js
- src/pages/import.html
Clicking on the name link of an RDF text resource in the import-resource-tree.directive now opens a dialog containing the resource data, enabling users to update the imported RDF text data.
This functionality allows users to make modifications to the imported RDF data.
A listener for the "onEditResource" event from the import-resource-tree.directive has been added. When this event occurs, a dialog displaying the resource data is opened, allowing users to update the RDF data and import it into the GraphDB database.
- Fixes unsubscribing functionality of import-resource-status-info directive;
- Removes duplicated import resource status constants.
> Gdb 9970 add opportunity to user to change rdf text snipets

- src/js/angular/import/controllers.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/import-context.service.js
- src/js/angular/import/templates/filesTable.html
- src/pages/import.html
- test-cypress/integration/import/import-user-data-batch-operations.spec.js
Implemented a loader to display during the initialization of the import view.
After integration of the new resource list, the loader had to be changed to work again as expected.
Introduced a 'loader' flag to control the display of the loader. Upon page initialization, the loader is set to true, causing it to be displayed while hiding the import-resource-tree.directive. Once resources are loaded for the first time, the loader is set to false, triggering the display of resources and hiding the loader.
- The 'viewType' parameter was renamed to 'activeTabId' and moved to the import context service;
- The 'resources' parameter was moved to the import context service.
> Gdb 9971 fixses loader functionality

- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/import/templates/settingsModal.html
- src/pages/import.html
Moved jsonld context field in import setting dialog below replace graphs section where it should be in order to not precede it when it's visible.
The field was initially put on the wrong place in the settings form.
Just moved the field to be after the replace graph section.
* Additionally, moved the resource tree directive css to be loaded in the import template because it seems that webpack can't put it properly in the bundle otherwise.
> GDB-10135 move jsonld context field on the right place in import settings dialog

- src/js/angular/import/controllers/import-view.controller.js
- test-cypress/integration/import/import-user-data-file-upload.spec.js
- test-cypress/steps/import/import-settings-dialog-steps.js
Allow when a single file is selected for import to be allowed the graph replacement option.
This is the expected behavior which works in cases where the file is not selected but the import action is directly triggered for it, but doesn't work for cases where the file is selected via the checkbox and imported through the batch import option.
Implemented a check if a single file is selected and if that is the case, pass the file name to the import settings modal which in turn is used to enable the replace graph option.
> GDB-10136 allow replace graph option when importing single file

- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
Properly toggle batch operation buttons.
When an operation like reset for example is made, the resource status is changed, but the batch reset button remains active. This is due to the way the selected resources were kept in the scope as live references linked to the resources three.
Detached the selected resources from the resources tree and properly updated the selection status after each resources update cycle.
Additionally, disabled the local for any resource operation button when there are selected resources.
> GDB-9970 properly toggle batch operation buttons

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
- src/js/angular/import/controllers/file-override-confirmation.controller.js
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/templates/file-override-confirmation.html
- src/js/angular/import/templates/fileSizeLimitInfo.html
- src/js/angular/import/templates/textSnippet.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-user-data-file-upload.spec.js
- test-cypress/steps/import/file-overwrite-dialog-steps.js
* Add third button for cancel in the file override dialog.
* Disable import button in text import dialog when text size limit is violated.
* There should be a cancel operation which should really cancel the file upload.
* Text snippet import should be forbidden if the text size is above the allowed limit.
* Implemented new custom dialog for this, because the once we use for confirmation have only two buttons.
* Disable the import button when there is validation error.
> GDB-9970 add third button for cancel in the file override dialog

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Increase zoom-out level in visual graph.
This will greatly increase the usability of the graph visualization by the data engineers.
Changed the lower bound of the zoom level.
Current zoom out level
New zoom out level
> GDB-3698 increase zoom-out level in visual graph

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/app.js
- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- src/js/angular/clustermanagement/directives/cluster-configuration.directive.js
- src/js/angular/clustermanagement/events.js
- src/js/angular/clustermanagement/services/cluster-view-context.service.js
- src/js/angular/clustermanagement/templates/cluster-configuration.html
- src/pages/cluster-management/clusterInfo.html
- test-cypress/integration/cluster/cluster-management.spec.js
- test-cypress/integration/cluster/cluster-states.spec.js
- test-cypress/steps/cluster/cluster-configuration-steps.js
- test-cypress/steps/cluster/cluster-page-steps.js
Redesign cluster configuration panel.
Hide the delete cluster button inside and simplify the main cluster-management.controller.js by extracting the cluster configuration in separate component.
Extract cluster configuration in separate component and use it in the cluster view side panel. Introduced cluster-view-context.service.js for storing some context variables and allow inter-component communication.
> GDB-10161 Redesign cluster configuration panel

- src/css/import-resource-tree.css
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
- src/js/angular/rest/mappers/import-mapper.js
In the User Data tab, the Import RDF files option allows files with extremely long file names, up to 255 characters, to be imported. As a result, the overview elements overlap each other, and each checkbox cannot be clicked.
When the name is long and there is no space for it to break into a new line, the import-resource-tree component becomes larger than the workbench page, causing a horizontal scrollbar to appear. Moving the scrollbar to the right causes the checkboxes to move under the right panel menu. While they are visible, they are not clickable.
Added a property to the cell where the name is displayed that allows the browser to break the word anywhere.
> GDB-10170: Issue with long names in the import-resource-tree component

- src/js/angular/export/controllers.js
What?
When user selects more than one graph for export in Graphs View and afterwards deselect one or more this isn't reflected and all the deselected graphs are exported as well.
Why?
How?
I added filtering of selected graphs when exporting JSONLD & NDJSONLD.
> GDB-10191 Added missing filtering for selected graphs, while exporting JSONLD and NDJSONLD

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- src/js/angular/clustermanagement/directives/cluster-configuration.directive.js
- src/js/angular/clustermanagement/directives/cluster-graphical-view.directive.js
- src/js/angular/clustermanagement/events.js
- src/js/angular/clustermanagement/services/cluster-drawing.service.js
- src/js/angular/models/clustermanagement/states.js
- src/pages/cluster-management/clusterInfo.html
- test-cypress/fixtures/cluster/3-nodes-cluster-group-status-receiving-snapshot.json
- test-cypress/integration/cluster/cluster-states.spec.js
- test-cypress/steps/cluster/cluster-view-steps.js
Redesign cluster visualization.
Allow better perceiving and improved interraction with the cluster view from the users.
* Make cluster node hexagons having rounded corners.
* Make node links thiker.
* Changed color of the cluster zone circle and also thiker.
* Add arrowhead to links in receiving snapshot state.
* Removed artificial childContext shared between cluster-management.controller and cluster-graphical-view.directive which was needless and used to introduce tight coupling between them. Replaced interaction with events. Also moved some code from the controller to directive where it belongs. 
* Simplified some of the functions in the cluster-drawing.service by replacing conditional logic with static resolution from predefined mappings.
* Added test to verify the receiving snapshot …
> GDB-10160 redesign cluster visualization

- src/css/lib/ontotext-yasgui-web-component.css
There is an issue with the color styling of the "<<<" or ">>>" sequences in Microsoft Edge, Firefox, and Chrome.
JetBrains Mono has contextual ligatures for sequences of < and > (e.g. <<, <<<, >>, >>>). Affected browsers use the ligatures even when CSS says individual characters should have different formatting (in our case color).
Added zero-width characters via ::after
> GDB-9233: YASQE - Different color styling of query

- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- src/pages/cluster-management/clusterInfo.html
In Cluster management - the Cluster configuration menu pops-out  unexpectedly, when a zoom-out ( ctrl+mouse scroll ) action is performed in the browser.
It seems like the issue is related to the way the page slide panel (<pageslide>) is being sized using viewport units (vw). When the window is resizing by pressing control and scrolling, this might cause the page slide panel to momentarily appear or reposition due to the change in its size.
Added a fixed size for the panel width, which is calculated before the panel is opened.
> GDB-10211: Cluster configuration menu irregular behavior on zoom-out

- package-lock.json
- package.json
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/languageselector/language-selector.directive.js
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/sparql-editor/controllers.js
- test-cypress/fixtures/locale-en.json
- test-cypress/integration-flaky/import/import-user-data-batch-operations.spec.js
- test-cypress/integration-flaky/sparql-editor/actions/share-query.spec.js
- test-cypress/integration/sparql-editor/internationalization.spec.js
- test-cypress/steps/language-selector-steps.js
- test-cypress/steps/sparql-steps.js
- test-cypress/steps/yasgui/yasgui-steps.js
- test-cypress/support/sparql-commands.js
When the user changes the language while in the SPARQL view, the page will require permission to reload.
The configs are loaded with the language passed in during initialization, it cannot be changed afterwards. Hence, the page needs to reload in order to have the right labels in the config window.
I handle the dialog open and page reload in the `yasgui-component-directive`. If the user is on the SPARQL editor page, the dialog will appear.
**Dependency**: this MR depends on changes in the YASGUI component with MR https://github.com/Ontotext-AD/ontotext-yasgui/pull/265
> GDB-9304 - Translate labels in Google chart config and Pivot table

- package-lock.json
- package.json
Update YASGUI component version to 1.3.10.
A new YASGUI component version was released with the following improvement:
- Google chart width will take up the full window width
Package.json was updated.
> GDB-9502 - add newest yasgui version

- src/css/lib/ontotext-yasgui-web-component.css
It appears that some of the buttons rendered in the yasr toolbar have greater height than expected.
For consistency with the other large buttons in the WB.
Applied some explicit height for the buttons in the yasr toolbar.
> GDB-10156 fix buttons height in yasr toolbar

- src/js/angular/core/directives.js
- src/js/angular/import/controllers/import-view.controller.js
Some of the WB view depends on the selected repository. These views used the "core-error" directive inform users, that they must choose a repository before continue. However, when users refresh these views, the error directive is displayed briefly, regardless of whether a repository has already been chosen.
In the initial implementation of the core error directive, each view that used it called the 'setRestricted' function of the main controller.  This function calculated a value based on how the directive was configured and set the result to the global variable 'isRestricted.' Over time, the function grew more complex, and at one point, the result began to depend on the selected repository. As a result, the function was modified, and the flow was changed so that all function calls were …
> GDB-8254: Import tab quickly flashes a wrong message

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/similarity/controllers/create-index.controller.js
When GraphDB is behind a reverse proxy and there is a context path:
- the previewing the visual graph query fail to load.
- the test query of similarity index fail to load.
There were a slash in the beginning of relative urls
The slashes has been removed
> GDB-10242: Creating a visual graph config throws 404 when a preview is requested

- package-lock.json
- package.json
Increase ontotext-yasgui component version to 1.3.11.
Changes coming with the new version:
* GDB-3107 extend datatable to allow sorting individual columns based on the values type
Increased the dependency version.
> increase ontotext-yasgui component version to 1.3.11

- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- test-cypress/integration/cluster/cluster-management.spec.js
Optimize cluster view requests when no cluster is configured.
Currently there is a flaw in the request promise chain where when the first request for the cluster status fails with 404 and is caught in the catch clause there is no return from there which makes the next request in the promise to advance and to actually be executed although there is no need from that.
Added a return with rejection from the cluster status promise catch in order to allow the error to be propagated to the parent promise catch and next requests to be skipped.
> GDB-7884 optimize cluster view requests when no cluster is configured

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
If the user expands the query editor using the control bar at the bottom, and is writing a long query. While scrolled to the end and the beginning of the query is not visible, pasting new text will not cause the editor to scroll up to the cursor position. It will remain where the end of the query is visible.
In the above described case, when scrolled to the bottom of a long query, pasting text made the scroll reposition higher up. The user would lose sight of the end of the query.
I removed a function call in the `codeMirrorPasteHandler` for setting the query in the editor after it has been pasted. 
Example query tested with:
```
SELECT ?s ?p ?o
WHERE {
?s1 ?p1 ?o1 .
?s1 ?p2 ?o2 .
?s1 ?p3 ?o3 .
?s1 ?p4 ?o4 .
?s1 ?p5 ?o5 .
?s1 ?p6 ?o6 .
?s1 ?p7 ?o7 .
?s1 ?p8 ?o8 .
?s1 ?p9 ?o9 .
?s1 ?p10 …
```
> GDB-9968 - Stop the query editor from scrolling up on paste

- src/js/angular/rest/mappers/import-mapper.js
What
Enable the import button for folders in the server view.
Why
To match the behavior of the old implementation.
How
Change the condition to determine whether the import button is visible. Field paths of directories are needed for the reset button functionality.
> Enable the import button for folders.

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers/tab.controller.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-tree-element.js
- src/pages/import.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/integration/import/import-user-data.spec.js
- test-cypress/steps/import/import-steps.js
Introduces some changes in the import view that were suggested after some tests
It was decided that some changes are needed in order to further improve the UX in the import view.
* Changed help info messages in the import user data and server files tabs per request by the PO.
* Changed conditions for help info alert rendering. Now it renders always in the empty state. User can close it, but on the next page load it should pop up again.
* Moved resource properties values rendering in the top cells in the row. Previously those were rendered in the bottom cells.
* Updated tests to account changes in the help alert behavior
> GDB-10263 import view improvements

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/pages/import.html
Allow resource tree column labels to be customized.
Modified column has no meaning in user data where files are actually uploaded by the user and not modified.
Extended the resource tree with additional parameter holding the column label keys. And modified the template to use them.
> GDB-10263 Allow resource tree column labels to be customized

- src/js/angular/import/controllers/import-view.controller.js
Send folder for import if it's selected via the checkbox along with all the files within.
This will ensure consistent behavior with the scenario where the folder is imported using the import button next to it.
Removed the folders filtration before sending the import request.
> GDB-10263 Send folder for import if it's selected via the checkbox

- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource.js
- src/js/angular/rest/mappers/import-mapper.js
- src/js/angular/utils/hash-utils.js
Update file status after each file update.
There was an issue where when resources were rendered in the resource tree component, there was a `track by resource.name` expression in the template for optimization purposes which used to cause the issue where the template wasn't updated after resource was recreated even though it was passed via two-way binding.
Added a new hash property in the resource model which is generated each time based on the server response. Changed the resource-tree directive to track resources by this hash property instead of name.
> GDB-10263 Update file status after each file update

- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/services/import-context.service.js
- src/js/angular/import/templates/import-resource-tree.html
- src/pages/import.html
GDB-10263: Fixes Issue with Loader
What
Sometimes the loaders are not displayed when the import view is opened.
Why
The loader is included in the main import template, and its visibility is controlled by two controllers: one for user data and one for server files. The main controller uses three controllers with a shared variable that determines whether the loader should be displayed. There seems to be an issue with this variable, as both controllers extend the main import controller, leading to inconsistent behavior.
How
Moved the loader into the import-resource-tree directive. The variable that controls the visibility of the loader has been moved to the import context service, allowing it to be changed and used by all components. Additional Work
There is a possible issue when a REST …
> GDB-10263: Fixes Issue with Loader

- src/js/angular/security/controllers.js
The selected 'light' or 'dark' theme will be saved when the user clicks to save the changes in settings.
The theme would be saved and applied even if the user clicked 'Cancel'.
I moved the theme application logic to the submit function.
> GDB-10126 - Save the selected theme mode when the user clicks 'Save'

- src/css/import-resource-tree.css
- src/css/import.css
- src/js/angular/import/controllers/import-resource-message-dialog.controller.js
- src/js/angular/import/directives/import-resource-message.directive.js
- src/js/angular/import/services/import-resource-tree.service.js
- src/js/angular/import/templates/import-resource-message-dialog.html
- src/js/angular/import/templates/import-resource-message.html
- src/js/angular/models/import/import-resource-tree-element.js
- test-cypress/fixtures/graphdb-import/more-files-with-error/import-resource-with-long-error.rdf
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/integration/import/import-view.spec.js
- test-cypress/steps/import/import-resource-message-dialog.js
- test-cypress/steps/import/import-steps.js
What
When an import fails and the error message is lengthy, the view does not look good.
Why
In the WB, the server message returned for every import is displayed to the user as it is, without any modifications. When the message is too lengthy, it is displayed as simple text without formatting. This makes the error report unusable.
How
When the error message is too lengthy, we will show a small piece to the user as a button. When the user clicks it, a dialog with the full error message will open.
> GDB-10327: Implement error dialog on import failure

- src/js/angular/import/controllers/import-view.controller.js
- When the import view is opened, the init method of the main controller is called three times;
- Both the import and server data controllers are initialized regardless of the selected tab
On Bootstrap, all import controllers are initialized because they are defined in one module.
- When the main controller initializes all fields and functions, the init method is called. Inside the controller declaration, it calls its own init() function.
- When the server import controller is initialized, it extends the main controller. After initializing the fields and functions:
  - The main controller's init() function is called for the second time (triggered because the server import controller extends the main controller).
  - When the server controller is initialized, it calls its init method …
> Fixed three time calling init function in import view

- src/js/angular/models/import/import-resource-tree-element.js
- test-cypress/integration/import/import-server-files-batch-operations.spec.js
In the "Import server files" section, when a sub-file within a folder is selected (checked), the expected menu doesn’t show.
The directories are missed when fetching the names of selected files.
The retrieval function of selected files has been fixed.
> GDB-10343: Import server files options box doesn't show when a file is selected

- test-cypress/integration/import/import-server-files.spec.js
Skip server import test step due to missing fix in GDB.
GDB no longer returns the folder status when importing a directory, which is unexpected, but will be fixed soon.
Commented out two steps in the test spec for server import until the fix gets integrated.
(cherry picked from commit 451a98ac46dc6357f3f5a063d61a4c87b427bfa8)
> GDB-10295 skip server import test step due to missing fix in GDB

- Jenkinsfile
To ensure all node.js dependencies are properly installed before validation, the 'npm install' step has been added prior to the 'Validate translations' stage in the Jenkinsfile. This change aims to prevent errors related to missing node modules.
> Add npm install step before validation in Jenkins pipeline

- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/models/import/import-resource-tree-element.js
- src/js/angular/models/import/import-resource.js
Don't send for import children of folders that are completely selected. Meaning that all children are selected as well.
Sending the children of selected folders forces the backend to import them twice, once when the folder is imported and second for each individual resource sent for import.
Implemented separate method in the resource tree that allows collecting all selected resources but if the selected resource is a directory, then it's children is not collected for import.
> GDB-10366 don't send for import children of folders that are completely selected

- src/css/bootstrap-graphdb-theme.css
When resizing the window, the tabs in the Resource view will move down together, to make space for the button group on the right.
The previous behavior was odd, because each tab would move down separately.
I changed the styling of the tabs.
On resize after the suggested improvement to the styling:
> GDB-10354 - Move tabs in Resource view together when window resized

- src/css/bootstrap-graphdb-theme.css
When resizing the window, the tabs in the Resource view will move down together, to make space for the button group on the right.
The previous behavior was odd, because each tab would move down separately.
I changed the styling of the tabs.
On resize after the suggested improvement to the styling:
(cherry picked from commit 04d85758666d5d1f2fdb365ff49f3ae64b236e9e)
> Cherry pick GDB-10354 - move tabs in Resource view together when window resized

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/export/controllers.js
What
Current WB implementation of the Link header value in JSON-LD requests sent to GDB is missing the ; rel=http://www.w3.org/ns/json-ld#frame and ; rel=http://www.w3.org/ns/json-ld#context attributes. 
Why
These rel attributes are essential for indicating the relationship type of the linked resources as per the JSON-LD specifications.
How
Added rel attribute in Link header based on selected mode.
> GDB-10369 JSONLD and NDJSONLD export improvements

- src/css/bootstrap-graphdb-theme.css
- src/css/explore.css
The tabs in the Resource view will have different styling, which won't be applied to other tabs in the app.
With the fix in https://github.com/Ontotext-AD/graphdb-workbench/pull/1429, the styling of some other tabs was affected in an undesired way.
The styling was moved to the local stylesheet for the `explore` page.
> GDB-10354 - Move tab styling from global theme to local stylesheet

- src/css/bootstrap-graphdb-theme.css
- src/css/explore.css
The tabs in the Resource view will have different styling, which won't be applied to other tabs in the app.
With the fix in https://github.com/Ontotext-AD/graphdb-workbench/pull/1429, the styling of some other tabs was affected in an undesired way.
The styling was moved to the local stylesheet for the `explore` page.
(cherry picked from commit c00265cba7909ef6ef91bca88522089e8856c99e)
> Cherry pick GDB-10354 - move tab styling from global theme to local stylesheet

- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/models/import/import-resource-tree-element.js
Fix for the selection of files for import.
It appears that there are cases where files list maintained in the import view controller is not properly updated when a selection is made through the checkboxes in the resource tree which leads to wrong files sent for import.
Added subscription for the selectedFileNamesUpdated event and updated the selectedForImportFiles list in the import view controller.
> GDB-10397 fix for the selection of files for import

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/controllers/settings-modal.controller.js
- src/js/angular/import/templates/settingsModal.html
- test-cypress/fixtures/locale-en.json
When uploading a file, the dialog window will show "Only upload" and "Import" as the two button options. There will be no "Cancel" option in the "User data" tab. The "Server files"  tab will still have the "Cancel" button.
The "Cancel" button was confusing, because the file would get uploaded either way.
I changed the label in the modal by giving it information about the current tab.
User Data tab:
> GDB-10416 - change label on import modal cancel button

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/controllers/settings-modal.controller.js
- src/js/angular/import/templates/settingsModal.html
- test-cypress/fixtures/locale-en.json
When uploading a file, the dialog window will show "Only upload" and "Import" as the two button options. There will be no "Cancel" option in the "User data" tab. The "Server files" tab will still have the "Cancel" button.
The "Cancel" button was confusing, because the file would get uploaded either way.
I changed the label in the modal by giving it information about the current tab.
User Data tab:
> (2.7 branch) GDB-10416 - Change label on import modal cancel button

- package-lock.json
- package.json
- src/js/angular/models/ontotext-yasgui/ontotext-yasgui-config.js
- src/js/angular/sparql-editor/controllers.js
- src/js/angular/utils/local-storage-adapter.js
- test-cypress/integration/sparql-editor/actions/expand-results-over-sameas.spec.js
What
The YASR results and YASQE buttons are not cleared when the repository is changed from the repository view.
Why
The YASGUI is a third-party library and does not know about repository changes. Managing repository changes is a function of the GraphDB Workbench.
How
Added functionality to persist the repository used by the YASGUI instance. When the YASGUI is initialized, a clearState flag is passed to the configuration. The value of the flag is based on whether the current repository is different from the last one used by YASGUI. If the repositories differ, the flag is set to true, which triggers the clearing of the YASR results and the YASQE buttons.
> GDB-10382: Default message info not displayed when the reinitialized function is called

- src/js/angular/controllers.js
- src/template.html
The "Import" and "SPARQL" main menu labels will render faster on window resize.
The two labels would load slower than the rest during resize.
I changed the ng-if to ng-show and added a debounce function to the function called.
(cherry picked from commit 309bf22789698a40c0bb1ba2625d62e9f635925e)
> (Cherry pick) GDB 10391 - Render menu labels faster

- src/js/angular/import/controllers/import-view.controller.js
Prevent requests without repository id in import view.
When the import view is loaded, a request for uploaded/imported files is made, but in case where a repository is not selected the request fails to be registered by the authentication interceptor and in result the server responds with 401 which causes the browser to open the native login form. That's why we need to ensure that each request will have the mandatory repository id parameter.
Implemented a check if there is a repository selected before issuing the GET request for the imported files.
> GDB-10422 prevent requests without repository id in import view

- src/js/angular/import/controllers/import-view.controller.js
This also fixes the regress caused by the previous fix for the https://ontotext.atlassian.net/browse/GDB-10397 issue.
It appears that there are cases where files list maintained in the import view controller is not properly updated when a selection is made through the checkboxes in the resource tree which leads to wrong files sent for import.
Added subscription for the selectedFileNamesUpdated event and updated the selectedForImportFiles list in the import view controller. The subscription is implemented in the server import tab controller because it affects the import files selection and should not affect the user data tab.
* Removed the redundant selectedForImportFiles variable and replaced with direct references to selections from the context or the uploaded files depending on the …
> GDB-10471 multi file upload fix (#1462)

- src/js/angular/import/controllers/import-view.controller.js
Prevent requests without repository id in import view.
When the import view is loaded, a request for uploaded/imported files is made, but in case where a repository is not selected the request fails to be registered by the authentication interceptor and in result the server responds with 401 which causes the browser to open the native login form. That's why we need to ensure that each request will have the mandatory repository id parameter.
Implemented a check if there is a repository selected before issuing the GET request for the imported files.
(cherry picked from commit edb66c66188efa6598dfaeeb3b07fc7ce8b426ef)
> GDB-10422 prevent requests without repository id in import view (#1464)

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
Revert the fix for the editor collapsing after paste because it was fixed with another more generic approach with GDB-10399
The fix which was applied and which is now removed causes a regression in the editor where after query get's pasted, the needed prefixes are not automatically inserted.
Reverted the fix applied with the related task so that the query to be re-applied in the editor after paste in order to trigger the prefixes insertion behavior.
> GDB-9968 revert the fix for the editor collapsing after paste

- package-lock.json
- package.json
- webpack.config.common.js
Extended the webpack build process with functionality that replaces specific strings inside JS and HTML files with the actual version of the workbench.
There was such functionality before, which prevented browsers from using cached resources if the workbench version changed.
The old plugin that performed this task is not supported in Webpack version 5. It was replaced with the "string-replace-loader" that performs the same function.
> GDB-10563: Fix workbench version replacements

- src/css/sparql-templates.css
- src/js/angular/clustermanagement/templates/cluster-configuration.html
- src/pages/sparql-template-create.html
- test-cypress/integration/explore/graphs.overview.spec.js
- test-cypress/integration/setup/namespaces.spec.js
- test-cypress/steps/explore/graphs-overview-steps.js
When in French, the buttons in the Cluster configuration panel will have space between them and the popover in the SPARQL Templates create view will not cover part of the button.
Skipped flaky tests, which will be addressed in another MR.
The issues with these elements created an inconsistent style when switching languages.
I edited the styling.
The popover covering part of the button when in French (before and after fix):
> GDB-10527 - Fix some usability issues and button positioning

- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/rest/import.rest.service.js
Fix api url used for abort operation of server files.
As most operations on the import view, there two distinct API's for aborting the import on the server files and user data tabs. The issue was that the API for aborting user data import was used on the server file import which resulted in anability to stop the import.
Exposed a REST service for aborting server file import and updated the import controller to switch between REST services depending on the currently selected tab in the view.
> GDB-10582 fix api url used for abort operation of server files

- src/js/angular/core/directives/paginations.js
- test-cypress/integration/explore/graphs.overview.spec.js
- test-cypress/steps/explore/graphs-overview-steps.js
The pagination directive tests will not fail due to errors in the directive's code.
The tests were thought to be flaky due to a change in the directive. However, upon further examination of the Jenkins logs it could be seen that the root cause of the failure was the injector being incorrectly written to handle minification.
I used the inline array annotation for the directive. I also refactored some of the steps used in the tests for better readability.
> Cherry pick GDB-10527 Fix flaky pagination tests

- src/css/sparql-templates.css
- src/js/angular/clustermanagement/templates/cluster-configuration.html
- src/pages/sparql-template-create.html
- test-cypress/integration/setup/namespaces.spec.js
When in French, the buttons in the Cluster configuration panel will have space between them and the popover in the SPARQL Templates create view will not cover part of the button.
The issues with these elements created an inconsistent style when switching languages.
I edited the styling.
The popover covering part of the button when in French (before and after fix):
> Cherry pick GDB-10527 Fix usability issues (buttons and styling)

- src/js/angular/import/controllers/import-view.controller.js
Large upload files doesn't appear in the import list.
Files in the list are fetched from the backend and displayed in the UI without modification. If a file is not appearing in the list, it indicates there was an error during the upload process. We discovered that error handling was not functioning correctly; specifically, an empty error handling function was added alongside a function to calculate the upload percentage. We expected that the error handling function would be executed, but it was not.
Moved the error handling logic from the catch function to a dedicated error handling function.
Added resetting of progressPercentage and uploadProgressMessage in the finally to ensure that the loader is hidden regardless of whether the upload fails or succeeds.
Files Are Imported Regardless of …
> GDB-10610: Large Upload File Does not Appear in the Import List

- package-lock.json
- package.json
- test-cypress/integration/sparql-editor/sparql-editor.spec.js
- test-cypress/support/commands.js
- test-cypress/support/sparql-commands.js
Increase the version of the ontotext-yasgui-web-component and add a test for the paste functionality.
**New in this version:**
- GDB-9968 - Prevent CodeMirror auto-scroll on paste
The new version of the component includes a bug fix. The paste functionality should add prefixes, if the query has any. There was no test for this.
Version increased and test introduced.
> Increase yasgui version and add prefix test (related GDB-9968)

- package-lock.json
- package.json
- test-cypress/integration/sparql-editor/sparql-editor.spec.js
- test-cypress/support/sparql-commands.js
Increase the version of the ontotext-yasgui-web-component and add a test for the paste functionality.
New in this version:
- GDB-9968 - Prevent CodeMirror auto-scroll on paste
The new version of the component includes a bug fix. The paste functionality should add prefixes, if the query has any. There was no test for this.
Version increased and test introduced.
* Increase yasgui version and add prefix test
* Refactor test and command. Now using waitUntil
* Refactor test for better readability
(cherry picked from commit bbb27ebff27694a4dfb97d1fb27f476b827994a7)
> Cherry pick - Increase yasgui version and add prefix test (related GDB-9968) (#1488)

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/repositories.service.js
- src/pages/guides.html
- src/pages/repositories.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-view.spec.js
- When hovering on a button in the repositories table, the popovers will remain visible until the mouse is moved away from the button or some of the data in the repository Map is changed.
- Added a missing French label in the Guides view.
The popovers in the repositories table would hide each time the list was refreshed from a call to the API (every 5 seconds).
I add hashes to the repositories, before they are stored in the Locations Map. The template now will track the changes by each hash.
> GDB-10573 - Add hash to repositories list for "track by" in view

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/repositories.service.js
- src/pages/guides.html
- src/pages/repositories.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-view.spec.js
- When hovering on a button in the repositories table, the popovers will remain visible until the mouse is moved away from the button or some of the data in the repository Map is changed.
- Added a missing French label in the Guides view.
The popovers in the repositories table would hide each time the list was refreshed from a call to the API (every 5 seconds).
I add hashes to the repositories, before they are stored in the Locations Map. The template now will track the changes by each hash.
* GDB-10573 - add hash to repositories to ensure popovers don't hide on polling. Add missing French label.
* Add wait to flaky test to reduce failed runs
(cherry picked from commit 03437ba90351c296454e1da15c9f8d0dbfe619e3)
> Cherry-pick GDB-10573 - Add hash to repositories list for "track by" in view (#1489)

- src/css/clustermanagement.css
- src/js/angular/clustermanagement/directives/cluster-legend.directive.js
- test-cypress/steps/cluster/cluster-page-steps.js
Improve cluster legend positioning in firefox and safari.
In firefox and safari the legend is not properly positioned because of an issue with the width and height of the topmost svg when it had been hidden with `display: none`.
Replaced the legend toggle using `display: none` with `visibility: hidden` to prevent misplacement of the legend items.
> GDB-10626 improve cluster legend positioning in firefox and safari

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/controllers/settings-modal.controller.js
- src/js/angular/import/services/import-context.service.js
- src/js/angular/import/templates/settingsModal.html
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/integration/import/import-user-data-file-upload.spec.js
- test-cypress/steps/import/import-resource-message-dialog.js
- test-cypress/steps/import/import-settings-dialog-steps.js
- test-cypress/steps/modal-dialog-steps.js
Properly manage import settings dialog buttons visibility.
The import settings dialog is used in user data and server files tabs for all (upload) and import operations. Technically it contains information only for the import, but as far as we now have a composite operation upload+import, it is now opened also after the user selects some files for upload. Due to above reasons, this dialog renders multiple action buttons: import, cancel import, only upload and cancel upload, plus the close dialog [x] button. It appeared that some buttons appear in scenarios where they shouldn't.
* Passed additional options to the settings dialog so that it is able to decide properly which buttons should be rendered.
* Added a button `cancel` upload which was missing for some reason, but is allows the dialog …
> GDB-10682 properly manage import settings dialog buttons visibility

- src/js/angular/queries/controllers.js
Fixed the download query functionality in the 'SPARQL Query & Update' view.
When GDB WB is deployed behind a context path requests to all endpoints which the WB calls should start without `/` otherwise this might brake the request routing.
Removed the leading `/` from the download query endpoint used by the 'SPARQL Query & Update' view download functionality.
> GDB-10572: Fix download query in 'SPARQL Query & Update' view

- src/js/angular/queries/controllers.js
Fixed the download query functionality in the 'SPARQL Query & Update' view.
When GDB WB is deployed behind a context path requests to all endpoints which the WB calls should start without `/` otherwise this might brake the request routing.
Removed the leading `/` from the download query endpoint used by the 'SPARQL Query & Update' view download functionality.
(cherry picked from commit 7dc11f144e4a9bde5a2d11ecb92a21d76a609364)
> GDB-10572: Fix download query in 'SPARQL Query & Update' view (#1504)

- src/js/angular/core/interceptors/authentication.interceptor.js
Kerberos authentication is not working as expected. When GraphDB is configured to use Kerberos authentication, and a user with the correct browser configuration tries to access any page in the Workbench (WB), the WB redirects the user to the login page.
After the login/logout functionality was refactored, an "Authorization" header was added to requests regardless of its value or the configured authentication method. When Kerberos is configured, the "Authorization" header is set with a null value because no token is present. This null header breaks the Kerberos authentication process.
When Kerberos is configured the authentication token is null, that's why the code was changed to add Authentication header only if there is token.
> GDB-9177: Workbench fails to authenticate when Authorization header is provided externally

- src/js/angular/core/interceptors/authentication.interceptor.js
Kerberos authentication is not working as expected. When GraphDB is configured to use Kerberos authentication, and a user with the correct browser configuration tries to access any page in the Workbench (WB), the WB redirects the user to the login page.
After the login/logout functionality was refactored, an "Authorization" header was added to requests regardless of its value or the configured authentication method. When Kerberos is configured, the "Authorization" header is set with a null value because no token is present. This null header breaks the Kerberos authentication process.
When Kerberos is configured the authentication token is null, that's why the code was changed to add Authentication header only if there is token.
> Cherry-pick GDB-9177: Workbench fails to authenticate when Authorization header is provided externally 

- src/css/import-resource-tree.css
- src/css/import.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/event-emitter-service.js
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/import/controllers/tab.controller.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/services/import-context.service.js
- src/js/angular/import/services/import-resource-tree.service.js
- src/js/angular/import/templates/import-resource-message.html
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/models/import/import-resource-status.js
- src/js/angular/rest/mappers/import-mapper.js
- test-cypress/fixtures/locale-en.json
- test-cypress/steps/import/import-steps.js
- Introduced `emitSynch` function to handle events in parallel, invoking each subscriber and their callbacks independently.
- Added `subscribeSynch` function to register subscribers for parallel event handling with an option to unsubscribe.
- Update javadoc for old functions.
- To support scenarios where event subscribers need to be executed in parallel.
- To provide a mechanism for parallel event subscription and easy removal of subscribers when they are no longer needed.
- Implemented `emitSynch` to call all registered subscribers for an event in parallel and handle their individual callbacks.
- Created `subscribeSynch` to add subscribers for parallel event handling and return an unsubscribe function to manage subscription lifecycle.
- Revised Javadoc documentation to accurately …
> Gdb 10610 file upload and progress improvements (#1509)

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
The change improves a sentence in the Server and User upload help boxes.
The change makes it easier for the user to understand that the repository is the object in question.
Edited locale files.
Last bullet point changed. Previously was **"Interrupt is supported only when the location is local."**
> GDB-10611 - Reword a sentence in import help

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
The change improves a sentence in the Server and User upload help boxes.
The change makes it easier for the user to understand that the repository is the object in question.
Edited locale files.
Last bullet point changed. Previously was "Interrupt is supported only when the location is local."
(cherry picked from commit 94f4f92e84431c8cc4ac9aa2de6f2d1296639c29)
> (cherry pick) GDB-10611 - reword a sentence in import help (#1512)

- src/app.js
- src/js/angular/import/directives/import-resource-tree.directive.js
- src/js/angular/import/templates/import-resource-tree.html
- src/js/angular/utils/size-util.js
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/steps/import/import-steps.js
The sorting by size in the import view was not functioning.
The size field of imported resources was returned in a human-readable format, while the sorting algorithm expected the size in bytes.
The backend has been updated to return sizes in bytes. However, existing files' data, which is persisted as human-readable strings, needed to be handled. The sorting algorithm was kept the same, sorting by bytes. Before sorting, the value is now converted to bytes, regardless of whether it is in a human-readable format or not.
(cherry picked from commit 0a3c7ed3adf8e3226e2b5e280c526c2804f03390)
> GDB-10717: Fix sorting by size (#1515)

- src/css/aclmanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/security/controllers.js
- src/js/angular/security/templates/user.html
- src/js/angular/utils/role-name-prefix-utils.js
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/setup/aclmanagement/create-rule.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/steps/setup/acl-management-steps.js
- test-cypress/steps/setup/user-and-access-steps.js
The user will be warned when using "CUSTOM_" as a prefix for ACL rules and when adding roles to a User in Setup.
The back-end adds the prefix and the user is not notified, which can lead to errors when adding roles.
I created new templates for the error messages and added a check during the rest of the rule validation steps.
Tests added.
The message in ACL view:
The message in User setup:
* GDB-10450 - add warnings when user uses CUSTOM_ prefix on ACL rule creation and during user custom role addition. Tests added
* GDB-10450 - add new labels to cypress locale file
* GDB-10450 - remove prefix warning dialogs and replace with inline text. Alter tests and remove unused templates and controllers.
* GDB-10450 - resize columns in ACL table
* GDB-10450 - refactor and create util class
(cherry …
> (cherry pick) GDB-10450 - Add warnings when user uses CUSTOM_ prefix (#1511)

- src/js/angular/repositories/controllers.js
- test-cypress/fixtures/repositories/builtin_Rules.pie
- test-cypress/fixtures/repositories/invalid_builtin_Rules.pie
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/steps/repository-steps.js
When creating a repository and adding a custom ruleset, an invalid ruleset file followed by a valid one, will not stop the repository from being created. The valid ruleset file will be set.
Uploading an invalid ruleset file caused an error and even though a valid file was later selected, the error persisted. This was due to the API response having status 200 on successful and failed uploads. Hence, the correct error handler was not triggered and the flag for invalid file remained set.
I set the flag to the correct value when the file is uploaded successfully. This allowed the repository to be created and then deleted without errors.
Test added.
> GDB-937 - Fix ruleset upload logic on invalid file selection

- src/css/aclmanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/aclmanagement/directives/custom-role-prefix.directive.js
- src/js/angular/aclmanagement/model.js
- src/js/angular/security/controllers.js
- src/js/angular/security/templates/user.html
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/setup/aclmanagement/create-rule.spec.js
- test-cypress/integration/setup/aclmanagement/scopes.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/steps/setup/acl-management-steps.js
The functionality of the ACL role warnings will remain mostly unchanged. Only the input field border will be highlighted when CUSTOM_ prefix detected.
The code needed to be reworked to reflect the review notes in MR https://github.com/Ontotext-AD/graphdb-workbench/pull/1511.
After discussing with team members, the changes proposed are in the existing custom-role-prefix.directive, which I extended to act as a validator in the cases when the user types "CUSTOM_". When the field is no longer present, I use the model to signal if a warning icon should be visible or not.
I made minor changes to function names and tests.
JSdoc for the directive updated.
> GDB-10785 - Rework and refactor existing solution for ACL role warnings on CUSTOM_ prefix use

- src/css/aclmanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/aclmanagement/controllers.js
- src/js/angular/aclmanagement/directives/custom-role-prefix.directive.js
- src/js/angular/aclmanagement/model.js
- src/js/angular/security/controllers.js
- src/js/angular/security/templates/user.html
- src/pages/aclmanagement.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/setup/aclmanagement/create-rule.spec.js
- test-cypress/integration/setup/aclmanagement/scopes.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/steps/setup/acl-management-steps.js
The functionality of the ACL role warnings will remain unchanged.
The code needed to be reworked to reflect the review notes in MR https://github.com/Ontotext-AD/graphdb-workbench/pull/1511.
After discussing with team members, the changes proposed are in the existing custom-role-prefix.directive, which add a property to ngModel when the user types "CUSTOM_". When the field is no longer present, I use the model to signal if a warning icon should be visible or not.
I made minor changes to function names and tests.
JSdoc for the directive updated.
* GDB-10785 - rework and refactor existing solution for ACL role warnings on CUSTOM_ prefix use. Changes according to review notes.
* GDB-10785 - reused directive logic to show error message in user create/edit view. Add negation prefix check in …
> (Cherry pick) GDB-10785 - Rework and refactor existing solution for ACL role warnings

- src/css/ttyg/agent-list.css
- src/css/ttyg/chat-list.css
- src/css/ttyg/no-agents-view.css
- src/css/ttyg/ttyg.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/agents.js
- src/js/angular/rest/ttyg.rest.service.fake.backend.js
- src/js/angular/rest/ttyg.rest.service.js
- src/js/angular/ttyg/app.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/agent-list.directive.js
- src/js/angular/ttyg/directives/no-agents-view.directive.js
- src/js/angular/ttyg/services/constants.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- src/js/angular/ttyg/templates/no-agents-view.html
- src/js/angular/ttyg/templates/ttyg.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/chats/get-chat-1.json
- test-cypress/integration/ttyg/agent-list.spec.js
- test-cypress/integration/ttyg/chat-list.spec.js
- test-cypress/integration/ttyg/ttyg-view.spec.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
- test-cypress/stubs/ttyg/ttyg-stubs.js
Introduce a no agents view with create agent button and help message.
Agent list is filtered by the current repository by default.
This no agent view is rendered when there are no agents created yet and displays help messages to the user and provides a create agent button.
Implemented a new component for the view and integrated with the page.
Changed the way how the chats and agents are initially loaded because when there are no agents, then the no agents view must be rendered and chats request may not be executed.
Implemented tests.
Add more tests.
Improved styling by adding more padding to list items and made the agent list scrollable only so that the filter menu is always visible.
> GDB-10709 introduce a no agents view with create agent button and help message

- src/css/dependencies.css
- src/pages/dependencies.html
When scrolling in `Class relationships` view, the even row background colors won't flicker.
The background color for the even rows would flicker when the user scrolled the list. This was most likely due to the dynamic fetching of the list items. Angular would re-calculate the styling and re-render. However, this re-render made it difficult to track the list while scrolling, as it was distracting.
I changed the way the styling is set and added a background color to the odd rows as well.
> GDB-10801 - Fix background flicker on even rows while scrolling

- src/css/import.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
The "Import RDF data from URL" dialog format button will have an aligned drop-down menu and the label will not appear as a JSON key.
The label was missing and the drop-down was misaligned.
I removed the `margin` for the dialog buttons and added the missing key.
Before
After
> GDB-10888 - Add missing label key and remove button margin

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/chat-item.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/chat-panel.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/import/import-user-data.spec.js
- test-cypress/integration/ttyg/chat-panel.spec.js
- test-cypress/steps/import/import-steps.js
- test-cypress/steps/ttyg/chat-panel-steps.js
- test-cypress/steps/window-steps.js
Added functionality for copying and regenerating chat content:
- The copy action allows users to copy chat answer to the clipboard;
- The regenerate action re-generates the answer of a question.
To fulfill the requirements for user interactions with chat content.
The copy and regenerate actions are implemented in the main TTYG controller. Actions are triggered from the chat panel. Communication between the chat panel component and the controller is managed through the TTYG Context Service.
> Implement copy and regenerate action of chat panel.

- src/css/import.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
The "Import RDF data from URL" dialog format button will have an aligned drop-down menu and the label will not appear as a JSON key.
The label was missing and the drop-down was misaligned.
I removed the margin for the dialog buttons and added the missing key.
Before
After
(cherry picked from commit ef6c3ffd740092b7374ab681dd089114259172e8)
> (cherry-pick) GDB-10888 - add missing label key and remove button right margin (#1543)

- src/css/dependencies.css
- src/pages/dependencies.html
When scrolling in Class relationships view, the even row background colors won't flicker.
The background color for the even rows would flicker when the user scrolled the list. This was most likely due to the dynamic fetching of the list items. Angular would re-calculate the styling and re-render. However, this re-render made it difficult to track the list while scrolling, as it was distracting.
I changed the way the styling is set and added a background color to the odd rows as well.
(cherry picked from commit 70e7758447ba01a53abc0724ddfe23da0005b5d0)
> (cherry-pick) GDB-10801 - set styling for dynamically fetched odd and even rows

- src/js/angular/ttyg/services/ttyg-storage.service.js
What
A NullPointerException (NPE) occurs in the console when attempting to save the agent ID in the browser's local storage for the first time.
Why
The issue arises because, if the saved object in the local storage does not have an agent field, the code tries to save the ID to an undefined field.
How
A check was added to verify if the agent and chat fields of the TTYG persisted object exist. If they don't, they are initialized before saving the data.
> Fixed NPE when trying to save agent ID for the first time

- src/js/angular/explore/controllers.js
- src/pages/edit.html
When editing a resource as an Admin and switching to a read only user, the page will show a message, instead of allowing the user to continue editing.
Editing a resource as a non-admin user was allowed when the URL was accessed manually. The behavior should be that only admin users are allowed to edit resources.
I show an error message if the user does not have an admin role.
> GDB-10772 - Show error message on resource edit when user not admin

- src/js/angular/explore/controllers.js
- src/pages/edit.html
When editing a resource as an Admin and switching to a read only user, the page will show a message, instead of allowing the user to continue editing.
Editing a resource as a non-admin user was allowed when the URL was accessed manually. The behavior should be that only admin users are allowed to edit resources.
I show an error message if the user does not have an admin role.
(cherry picked from commit ba4cc4900ec7be8f585cafcd5cdf3dd1a26ef04a)
> (cherry-pick) GDB-10772 - Show error message on resource edit when user not admin

- src/js/angular/graphexplore/controllers/dependencies-chord.controller.js
- src/pages/dependencies.html
- test-cypress/integration/explore/class.relationships.spec.js
The Class list in Class relationships page will perform better when scrolled faster.
When using a mouse with infinite scroll and scrolling very fast, the list would partially or entirely disappear. This is due to the capabilities of the library and the lazy loading of the list.
I added some additional properties to the directive in the HTML. This improves the usability without causing noticeably slower page loading.
**Know issue: Using infinite scroll and scrolling very fast will still cause the initial bug to appear. The directive used for handling this list removes items when they go out of view and adds items as they come close to being visible. The purpose is to improve loading performance. Scrolling fast breaks the internal logic, possibly due to the fast changes in the row indexes …
> GDB-10801 - Improve fast scrolling behavior in class relationships list

- src/css/cluster-list.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/templates/cluster-list.html
- src/js/angular/models/clustermanagement/cluster.js
- test-cypress/fixtures/locale-en.json
- Implemented logic to identify the local node within the cluster.
- Enhanced the canDeleteNode function to restrict deletion if more than half of the healthy nodes are selected.
- Updated the UI to display a custom tooltip explaining why the delete button is disabled when applicable.
- Added translation keys and modified the cluster-list.html template to dynamically change tooltips.
- Updated CSS to style the tooltip when deletion is restricted.
Ensuring that the system restricts users from deleting more than half of the healthy nodes to maintain quorum-based replication and prevent split-brain scenarios.
- Modified the cluster model to set the local node's endpoint during initialization.
- Updated the canDeleteNode logic to enforce restrictions based on the total number of nodes in the …
> feat(GDB-10852) Add local node handling and tooltip for delete restrctions

- src/js/angular/graphexplore/controllers/dependencies-chord.controller.js
- src/pages/dependencies.html
- test-cypress/integration/explore/class.relationships.spec.js
The Class list in Class relationships page will perform better when scrolled faster.
When using a mouse with infinite scroll and scrolling very fast, the list would partially or entirely disappear. This is due to the capabilities of the library and the lazy loading of the list.
I added some additional properties to the directive in the HTML. This improves the usability without causing noticeably slower page loading.
**Know issue: Using infinite scroll and scrolling very fast will still cause the initial bug to appear. The directive used for handling this list removes items when they go out of view and adds items as they come close to being visible. The purpose is to improve loading performance. Scrolling fast breaks the internal logic, possibly due to the fast changes in the row indexes …
> (cherry-pick) GDB-10801 - Improve fast scrolling behavior in class relationships list

- package-lock.json
- package.json
Increase the version of the ontotext-yasgui-web-component.
New in this version:
- GDB-10876 - Add escape HTML entity "&"
The new version of the component includes a functionality fix to reduce XSS attacks.
Version increased.
> Upgrade ontotext-yasgui-web-component version to 1.3.18

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/repositories.service.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/ttyg/chat-list.spec.js
- test-cypress/integration/ttyg/ttyg-view.spec.js
Added confirmation dialog for repository change when the user clicks on a link redirecting to the create similarity page or create ChatGPT retrieval connector.
The both pages depends on the selected repository. To allow the user to create an index or connector in the repository chosen in the create agent dialog, the repository must be changed before navigating to the create similarity or create ChatGPT page if the repository selected in the workbench differs from the one in the dialog.
Added a check to control when the confirmation dialog is displayed and when the user is redirected without prompting.
> Gdb 10937 fixes links to create similarity and chatgpt pages

- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
When the Workbench is opened in a way, which doesn't have a secure context, or if `navigator.clipboard` is not supported, the text copying functionality will still work.
Some copy buttons in the WB did not work  when the document was not in a secure context.
I added a fallback option using `document.execCommand('copy');`, as used in other views (e.g. repository URL copy button).
> GDB-10897 - Import page "copy" button fallback added for non-secure contexts

- package-lock.json
- package.json
Increase the version of the ontotext-yasgui-web-component.
New in this version:
- GDB-10876 - Add escape HTML entity "&"
The new version of the component includes a functionality fix to reduce XSS attacks.
Version increased.
(cherry picked from commit 7687740ec3df526539103421d4a1ccd208d3355c)
> (cherry-pick) Upgrade ontotext-yasgui-web-component version to 1.3.18

- src/css/cluster-list.css
- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- src/js/angular/clustermanagement/directives/cluster-list.directive.js
- src/js/angular/clustermanagement/services/remote-locations.service.js
Remove unused locations after cluster update. Locations with errors during creation are also removed.
To sanitize unused locations as they are unnecessary and slow down cluster configuration processes.
- Modified the `cluster-list.directive.js` and `cluster-management.controller.js` to delete locations after an error during the cluster update process and after cluster update.
- Removed the unused methods.
- Refactored `cluster-list.css` by removing nested rules left
> fix(GDB-10854) Remove unused locations

- src/js/angular/utils/yasgui-utils.js
When downloading SPARQL results, the downloaded files won't include a "+" in the beginning.
The extra character made the json files invalid.
I removed the extra characters before the encoded content.
> GDB-10931 - Remove "+" in href for file download

- src/css/ttyg/agent-settings-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/interceptors/authentication.interceptor.js
- src/js/angular/core/services/connectors.service.js
- src/js/angular/core/services/similarity.service.js
- src/js/angular/models/ttyg/agent-form.js
- src/js/angular/rest/connectors.rest.service.js
- src/js/angular/rest/similarity.rest.service.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/fixtures/connectors/get-ttyg-chatgpt-connectors.json
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/similarity/get-ttyg-similarity-connectors.json
- test-cypress/integration/ttyg/chat-panel.spec.js
- test-cypress/integration/ttyg/create-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
- test-cypress/stubs/connector-stubs.js
- test-cypress/stubs/similarity-index-stubs.js
- test-cypress/stubs/ttyg/ttyg-stubs.js
- When the repository in the create/edit agent form is changed, the options in "Full-text search" and "Similarity search" are incorrect.
- The options are generated when the dialog is opened and are based on the selected repository in the workbench.
- Implemented logic in the create/edit agent to refresh the options and selected values for "Full-text search," "Similarity search," and "ChatGPT retrieval connector" when the repository is changed;
- Changed the functionality for expanding and collapsing query methods;
- Modified the behavior of the authentication interceptor that reads the saved repository ID and location from local storage. Implemented a check to determine if the request headers contain repository headers. If not, the interceptor retrieves them from local storage; …
> GDB-10937: Reloads similarity indexes and ChatGPT connectors when the repository is changed

- src/css/cluster-nodes-configuration.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/app.js
- src/js/angular/clustermanagement/controllers/cluster-management.controller.js
- src/js/angular/clustermanagement/controllers/edit-cluster-nodes-modal.controller.js
- src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
- src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
- src/js/angular/clustermanagement/templates/modal/edit-cluster-nodes-modal.html
- src/js/angular/core/directives/validate-duplicate-url.directive.js
- src/js/angular/models/clustermanagement/cluster.js
- src/pages/cluster-management/clusterInfo.html
- test-cypress/fixtures/cluster/2-nodes-cluster-group-status-deleted.json
- test-cypress/fixtures/cluster/2-nodes-cluster-group-status.json
- test-cypress/fixtures/cluster/3-nodes-cluster-group-status-after-replace.json
- test-cypress/fixtures/cluster/4-nodes-cluster-group-status.json
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/cluster/edit-cluster-nodes-modal.spec.js
- test-cypress/steps/cluster/cluster-page-steps.js
- test-cypress/steps/cluster/custer-nodes-configuration-steps.js
- test-cypress/stubs/cluster/cluster-stubs.js
- test-cypress/stubs/cluster/remote-location-stubs.js
- Renamed multiple components, templates, CSS classes, and Cypress tests from `cluster-list` to `cluster-nodes-configuration`
- Added a new directive `validate-duplicate-url` for checking duplicate URLs in the cluster configuration
- Updated Cypress tests and fixtures to reflect the changes
- Improved the logic in the `saveNode` method by refactoring duplicated code into helper functions
- This change was necessary to improve the naming consistency
- Adding the `validate-duplicate-url` directive is necessary for validation of added urls
- The refactored code in `saveNode` reduces duplication
- Renamed all instances of `cluster-list` to `cluster-nodes-configuration` across JS files, templates, CSS, and Cypress tests.
- Introduced a new AngularJS directive `validate-duplicate-url`, which …
> ref(GDB-10848) Refactor cluster management components for naming consistency

- src/js/angular/import/templates/import-resource-status-info.html
When a file import fails, an incorrect timestamp will not be displayed in the status info dialog. In this case, the timestamp will be hidden.
The back-end returns "0" for `importedOn` in the case of a failed import. This incorrectly gets filtered into a date.
I added a condition to show the date only if it's defined.
> GDB-10913 - On failed import, hide the invalid timestamp in the status info

- src/js/angular/models/ttyg/agent-form.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/ttyg.html
- test-cypress/integration/ttyg/ttyg-view.spec.js
* Reset the ttyg context on destroy.
* Change the sparqlConstruct parameter for the sparql search method to sparqlQuery.
* Hide the edit agent settings action when there is no selected agent.
* The context needs to be cleared because it is implemented as a service and the services in angular are singletons and the properties in it remains when the page controller is destroyed which is unexpected.
* The edit agent settings button needs to be hid because when there is no selected agent, it doesn't behave properly.
* The sparqlQuery property was changed again due to changes in the backend.
Applied the needed changes.
> GDB-10937 - reset context and fix sparql method config

- src/js/angular/models/ttyg/chats.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/chat-list.directive.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/chat-panel.html
- The "Explain Example" button is non-functional;
- A new chat field is not created when attempting to start a chat for the first time. ## Why
- The onAskHowDeliveredAnswer function binding is not passed to the chatItemDetail component;
- There was an issue where an action reset the question during the chat creation flow.
- Added the missing binding for onAskHowDeliveredAnswer;
- Updated the chat creation flow. When the "Start a New Chat" button is clicked, or the "Ask" button is clicked when no chats exist, the ttygController now creates a dummy chat model instance and updates the context with it. Once the chat is created by the backend, the dummy chat is replaced with the newly created instance.
> GDB-11001: The Explain Example button does not work

- src/js/angular/core/services/repositories.service.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- test-cypress/fixtures/repositories/get-ttyg-repositories.json
- test-cypress/integration/ttyg/agent-list.spec.js
- test-cypress/integration/ttyg/create-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
Added filtering of repositories for:
- The dropdown in the "Create Agent" dialog;
- The repository filter in the agent list panel.
TTYG functionality is designed to work only with GraphDB repositories.
Implemented filtering by repository type when loading repositories for dropdowns.
> GDB-11001: Filtering Repositories in TTYG Functionality

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/agents.js
- src/js/angular/ttyg/directives/chat-item-detail.directive.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- src/js/angular/ttyg/templates/chat-panel.html
- test-cypress/fixtures/locale-en.json
* Show the agent name when the agent icon in the chat panel is hovered.
* Prevent typing in the question input field if there isn't a selected agent.
For better usability the agent name needs to be visible in each agent answer because we allow the agent to be changed in the same chat. There are cases where when the currently selected is missing the question input field is not disabled and the user can type a question and send it by clicking on the [enter] key which is unwanted.
Extended the agent list model with a mapping of agent id to agent name map which is then used in the chat details component to show the agent tooltip. Extended the condition for disabling the question input with a check if there is a selected agent.
> GDB-10937 - show agent name and other improvements

- src/app.js
- src/js/angular/controllers.js
- src/js/angular/core/services/cookie.service.js
- src/js/angular/core/services/installation-cookie.service.js
- src/js/angular/core/services/license.service.js
- src/template.html
- test-cypress/integration/home/workbench.home.spec.js
- test-cypress/stubs/environment-stubs.js
- test-cypress/stubs/license-stubs.js
- webpack.config.dev.js
- webpack.config.prod.js
- Introduced a new CookieService for managing cookies
- Modified the license check logic to include setting or deleting cookies based on tracking permissions.
- Updated the run block in app.js to inject the new CookieService.
- Added handling of devMode to distinguish between development and production environments.
- To ensure tracking by using cookies
- The devMode flag was introduced to prevent tracking and cookie management in development environments, ensuring that tracking is only enabled in production.
- Created a CookieService that provides functions to get, set, and delete cookies.
- The cookie structure includes the version, installationId, and timestamp.
- Integrated the CookieService with the license checking logic, allowing cookies to be set or deleted based on whether …
> feat(GDB-11024) Add CookieService to manage installation ID tracking

- test-cypress/package-lock.json
- test-cypress/package.json
Update of cypress test application dependencies
Get latest reliability, performance and vulunerability fixes.
* Updated cypress to latest
* updated cypress-wait-until to latest
* updated cypress-localstorage-commands to latest
* updated del to latest
and reverted back to 6.1.1 due to incompatibilities that broke the build
*
> GDB-11032 update test libs

- package.json
- src/css/ttyg/chat-item-details.css
- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- src/js/angular/core/directives/markdown-content/markdown-content.js
- src/js/angular/core/directives/open-in-sparql-editor/open-in-sparql-editor.directive.js
- src/js/angular/core/services/markdown/markdown.service.js
- src/js/angular/core/services/markdown/plugins/markdown-code-copy-plugin.js
- src/js/angular/core/services/markdown/plugins/markdown-open-in-sparql-editor-plugin.js
- src/js/angular/rest/ttyg.rest.service.fake.backend.js
- src/js/angular/ttyg/directives/chat-item-detail.directive.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- test-cypress/fixtures/ttyg/chats/get-chat.json
- test-cypress/steps/ttyg/chat-panel-steps.js
- A custom plugin has been added to enable code copying from markdown content;
- A custom plugin allows SPARQL code embedded in Markdown content to be opened directly in the SPARQL editor;
- A markdown content component has been implemented.
- To provide clients with the ability to easily copy code from markdown blocks;
- To enhance usability by allowing clients to open and execute SPARQL queries written in Markdown directly in the SPARQL editor, streamlining their workflow;
- To enable visualization of markdown content within the application.
- The markdown-it-code-copy plugin was removed because it used a different tooltip style than the workbench and had a hardcoded, non-customizable label. A custom plugin was implemented to address these issues;
- A custom plugin was developed and …
> GDB-10937: Explain Response Improvements

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/controllers.js
- src/js/angular/core/directives/open-in-sparql-editor/open-in-sparql-editor.directive.js
- src/js/angular/core/services.js
- src/js/angular/core/templates/modal/modal-warning.html
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- test-cypress/fixtures/locale-en.json
10937: Modal Dialog Improvements
- The Edit Agent dialog has been configured to prevent it from closing when a user clicks outside the dialog;
- Updated the confirmation button label when opening a SPARQL query in a different repository.
- To avoid accidental closures of the dialog when users mistakenly click outside, which could result in unsaved changes or interrupted actions;
- To make the label semantically more aligned with the confirmation action.
- The modal configuration was modified to disable closing the dialog on outside clicks by setting the backdrop option to 'static';
- The ModalService was extended to be more configurable. Added the ability to change the confirmation button label. Additionally, the modal dialog can now be configured to remain open when clicking outside of …
> 10937 disable closing of dialog when click outside it

- src/js/angular/explore/controllers.js
- src/pages/edit.html
Reverting GDB-10772.
The fix introduced a new bug, which limits usability and access for all regular users.
Fix reverted.
Reverts Ontotext-AD/graphdb-workbench#1556
> Revert "(cherry-pick) GDB-10772 - Show error message on resource edit when user not admin"

- src/js/angular/explore/controllers.js
- src/pages/edit.html
Reverting GDB-10772.
The fix introduced a new bug, which limits usability and access for all regular users.
Fix reverted.
Reverts Ontotext-AD/graphdb-workbench#1554
> Revert "GDB-10772 - Show error message on resource edit when user not admin"

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/agent-list.directive.js
- src/js/angular/ttyg/directives/no-agents-view.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/chat-item-detail.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- src/js/angular/ttyg/templates/no-agents-view.html
- src/js/angular/ttyg/templates/ttyg.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/ttyg/agent-list.spec.js
- test-cypress/integration/ttyg/agent-select-menu.spec.js
- test-cypress/integration/ttyg/clone-agent.spec.js
- test-cypress/integration/ttyg/delete-agent.spec.js
- test-cypress/integration/ttyg/edit-agent.spec.js
- test-cypress/integration/ttyg/ttyg-permission.spec.js
- test-cypress/integration/ttyg/ttyg-view.spec.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
- test-cypress/support/commands.js
- test-cypress/support/security-command.js
- test-cypress/support/user-commands.js
Users cannot create or edit agents.
Only admin users are allowed to perform these actions.
The create/edit buttons are disabled if the user is not an admin or have ROLE_REPO_MANAGER.
> 10937: Disable the Create/Edit Agent Buttons

- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/templates/ttyg.html
- Sometimes the selected agent appears to be empty;
- No agent component is briefly displayed when the page is reloaded.
- The functionality that selects the last used agent depends on the list of agents being loaded. When the page is opened, the system attempts to set the last used agent before the list of agents is fully loaded. As a result, the agent cannot be found in the list;
- Previously, the condition to show the component was based on whether the agents field was undefined or empty. The agents field is undefined when the page is first loaded, and while the agent list is being fetched, the component was displayed briefly.
- The loading of the last used agent has been moved to occur after the agent list is fully loaded;
- The condition was modified to ensure the component is not …
> 10937 Selected Agent Sometimes Empty

- scripts/validate-translations.js
- src/js/angular/core/services/repositories.service.js
- src/js/angular/core/services/ttyg.service.js
- src/js/angular/models/ttyg/chats.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/services/agents.mapper.js
- src/js/angular/ttyg/services/constants.js
- test-cypress/integration/ttyg/agent-list.spec.js
- test-cypress/integration/ttyg/create-agent.spec.js
* Stop reloading of chat list after chat is deleted or exported.
* In the agent list filter menu and in agent create dialog are visible repositories from other locations.
* New chats or chats that were recently used should stay on top of the chat list.
* Reloading chat list is not necesarry after these operations.
* Repositories and locations from other instances should not be allowed when agent is being created and in the agent list filter.
* The recent chats should be on top of the list because this is the expected order and also the backend actually returns them in this way, but as we don't reload the chat list after each answer, the list remains in the initial order which is inconvenient.
* Removed emitting of load chats event from the delete and export chat handers. Replaced the …
> GDB-10937 ttyg view improvements

- src/css/ttyg/agent-settings-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/agent/get-agent-defaults.json
- test-cypress/integration/ttyg/create-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
* Show warning when the user sets temperature higher than 1.
* Show warning and an alert to the user when he tries to override the base instructions.
* Because it would help the user to receive more meaningful results from the agent.
* Because this would prevent unexpected results if the user provides incorrect instructions.
* Implemented icon with tooltip next to the temperature field label, and a handler for the property change to toggle the warning.
* Implemented icon with tooltip and an alert that is displayed when the field value becomes different from empty string.
> GDB-10937 show warnings in agent settings modal

- src/js/angular/controllers.js
- src/template.html
When the side main menu is collapsed, the main content will always remain at expanded width, even on page refresh.
On page refresh/load, the main content wouldn't apply its expanded class and there would be a gap between the collapsed menu and the main content.
I reworked the logic and added a menu check on page load, while keeping the checks on menu toggle.
The gap remains like this when the page loads and the menu is collapsed.
> GDB-11070 - improve logic for menu toggle and main content resize

- src/pages/login.html
The browser won't show its own form field tooltips on the login page.
This change is required because the browser's tooltips are in English. So if the user is using the Workbench in French, the tooltips will not be in French.
I added the `novalidate` attribute to the HTML `form`.
> GDB-11055 - Disable browser form validation for login page

- src/css/ttyg/agent-list.css
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
There is a double loading of the selected chat when the TTYG page is loaded.
When the page loads, we retrieve the persisted chat ID and load it from the server. After the chat is loaded, we call the TTYGContextService.selectChat function with the loaded chat, which triggers a second loading of the selected chat.
The setup of the selected chat has been moved to occur after the chat list (chats without messages) is loaded. Then, the chat is fetched from the list using the persisted chat ID, followed by calling TTYGContextService.selectChat. In short, the initial loading of the persisted chat has been removed.
> GDB-10937: Fixes double loading of selected chat when loading the TTYG page

- src/css/ttyg/agent-settings-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/agent-form.js
- src/js/angular/models/ttyg/agents.js
- src/js/angular/ttyg/services/agents.mapper.js
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/agent/create-agent.json
- test-cypress/fixtures/ttyg/agent/get-agent-defaults.json
- test-cypress/fixtures/ttyg/agent/get-agent-list-new-agent.json
- test-cypress/fixtures/ttyg/agent/get-agent.json
- test-cypress/integration/ttyg/create-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
Added additional option to sparql method for automatic insertion of the needed namespaces in generated sparql query.
This prevents errors when the agent generated a query without namespaces.
* Extended the agent models and mappers with the new option.
* Added the checkbox field in the sparql method section.
> GDB-10937 add missing namespaces option to sparql method

- src/js/angular/ttyg/directives/chat-list.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/chat-list.html
* Prevent renaming new chats.
* New chat should not be possible to be renamed because it has no id and would cause error.
* Added additional check to the editable field for the chat name to prevent it to enter in edit mode for new chats.
> GDB-10937 prevent renaming new chats and other fixes

- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- test-cypress/fixtures/ttyg/chats/create/create-chat-response.json
- test-cypress/fixtures/ttyg/chats/create/get-chats-after-create.json
- test-cypress/fixtures/ttyg/chats/create/get-chats-before-create.json
- test-cypress/fixtures/ttyg/chats/get-chat.json
- test-cypress/integration/ttyg/create-chat.spec.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
- test-cypress/stubs/ttyg/ttyg-stubs.js
The ID of a newly created chat was not being persisted in the local store.
This was missed during the implementation.
After a new chat is created and its ID is retrieved, the ID is now persisted in the local store.
> GDB-10937: Save newly created chat in local store

- webpack.config.common.js
Added transform: replaceVersion to the CopyPlugin configuration in webpack.config.common.js specifically for the js/angular/core/templates folder.
This omission caused version placeholders to remain unreplaced.
- Updated the CopyPlugin configuration for the js/angular/core/templates directory to include transform: replaceVersion
> fix(GDB-11129) Add Missing Version Replacement in Webpack Config

- webpack.config.common.js
Added transform: replaceVersion to the CopyPlugin configuration in webpack.config.common.js specifically for the js/angular/core/templates folder.
This omission caused version placeholders to remain unreplaced.
- Updated the CopyPlugin configuration for the js/angular/core/templates directory to include transform: replaceVersion
cherry pick from https://github.com/Ontotext-AD/graphdb-workbench/pull/1648
> fix(GDB-11129) Add Missing Version Replacement in Webpack Config 2.8

- src/css/ttyg/chat-item-details.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/chat-answer.js
- src/js/angular/models/ttyg/chat-item.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- Added support for the now function (a hidden always-enabled additional query method)
- The model needs to be aware of the current time in order to answer time-relative questions
- Added translation keys for "now"
- Added support for explaining tools without queries (such as "now")
- Send browser time zone offset so the model sees the same time zone as the browser/user (note that lastMessageId is removed from ContinueChatRun because it's no longer used)
Other changes: fix alignment of images in HTML produced from model markdown
> TTYG support for the now function

- src/css/ttyg/chat-item-details.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/chat-answer.js
- src/js/angular/models/ttyg/chat-item.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- Added support for the now function (a hidden always-enabled additional query method)
- The model needs to be aware of the current time in order to answer time-relative questions
- Added translation keys for "now"
- Added support for explaining tools without queries (such as "now")
- Send browser time zone offset so the model sees the same time zone as the browser/user (note that lastMessageId is removed from ContinueChatRun because it's no longer used)
Other changes: fix alignment of images in HTML produced from model markdown
Co-authored-by: Pavel Mihaylov <pavel@ontotext.com>
Co-authored-by: boyan-tonchev <108174872+boyan-tonchev@users.noreply.github.com>
(cherry picked from commit 780810e4d63d5d231fabc3f73de8164767018cc6)
> TTYG support for the now function (#1647)

- src/js/angular/clustermanagement/directives/cluster-configuration/multi-region.directive.js
Updated the controller property in secondaryModalConfig to use array syntax for dependency injection, ensuring $scope, $uibModalInstance, and config are correctly injected into secondaryModeModalController.
This change prevents minification errors that occurred due to missing dependency injection, causing the controller function to fail in production.
Wrapped the secondaryModeModalController in an array syntax to ensure AngularJS correctly injects dependencies even after minification.
cherry-pick from https://github.com/Ontotext-AD/graphdb-workbench/pull/1654
> fix(GDB-11096) Fix injection issue in secondary modal controller for multi-region cluster configuration

- src/css/ttyg/chat-item-details.css
- src/js/angular/rest/ttyg.rest.service.fake.backend.js
Addresses an issue where the chat panel sometimes displays a horizontal scroll.
Typically, the backend returns formatted assistant queries, which the markdown library displays correctly with line breaks and tabs. Occasionally, however, the backend returns a single, continuous string without line breaks or tabs, causing excessively long lines that expand the container width and introduce horizontal scrolling.
Set a maximum width on the container displaying explanation messages, which forces the browser to wrap long query strings correctly.
> GDB-11131: Fixes max width for explanation messages

- package-lock.json
- package.json
- src/css/bootstrap-graphdb-theme.css
- src/css/common.css
- src/css/ttyg/chat-item-details.css
- src/css/ttyg/ttyg.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/templates/cluster-configuration/multi-region.html
- src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- src/js/angular/core/directives/open-in-sparql-editor/open-in-sparql-editor.directive.js
- src/js/angular/templates/titlePopoverTemplate.html
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/agent-select-menu.html
- src/js/angular/ttyg/templates/chat-item-detail.html
- src/js/angular/ttyg/templates/chat-list.html
- src/js/angular/ttyg/templates/chat-panel.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- src/js/angular/ttyg/templates/no-agents-view.html
- src/js/angular/ttyg/templates/ttyg.html
- src/pages/cluster-management/clusterInfo.html
- src/pages/export.html
- src/pages/ux-test2.html
- src/vendor.js
- test-cypress/fixtures/locale-en.json
- webpack.config.common.js
- FontAwesome icons are scaled globally (also added a preview in ux-test2)
- FontAwesome icons use only the fa class (and not fa-regular or alternatives like fa-thin) and the font weight is determined by the --fa-style variable.
- Removed various hacks for individual icons
- Removed FontAwesome 4 from package list
- There was one icon in export view using it
- Note that this npm module brought the classes pull-right and pull-left, which now need to be defined explicitly now
- Copy button directive and Open in SPARQL directive are now styled like all similar icon buttons inside the directive
- Open in SPARQL directive uses a composite FontAwesome icon to recreate the {...} icon from our font and match the rest of the FontAwesome icons around it
Other fixes:
- Added max-width to …
> Fixed various issues with FontAwesome vs our icons

- src/css/ttyg/chat-item-details.css
- src/js/angular/rest/ttyg.rest.service.fake.backend.js
Addresses an issue where the chat panel sometimes displays a horizontal scroll.
Typically, the backend returns formatted assistant queries, which the markdown library displays correctly with line breaks and tabs. Occasionally, however, the backend returns a single, continuous string without line breaks or tabs, causing excessively long lines that expand the container width and introduce horizontal scrolling.
Set a maximum width on the container displaying explanation messages, which forces the browser to wrap long query strings correctly.
(cherry picked from commit 1e13ca46c291dfefc850cd07dba69dadf311bde7)
> GDB-11131: Fixes max width for explanation messages (#1653)

- package-lock.json
- package.json
- src/css/bootstrap-graphdb-theme.css
- src/css/common.css
- src/css/ttyg/chat-item-details.css
- src/css/ttyg/ttyg.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/templates/cluster-configuration/multi-region.html
- src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- src/js/angular/core/directives/open-in-sparql-editor/open-in-sparql-editor.directive.js
- src/js/angular/templates/titlePopoverTemplate.html
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/agent-select-menu.html
- src/js/angular/ttyg/templates/chat-item-detail.html
- src/js/angular/ttyg/templates/chat-list.html
- src/js/angular/ttyg/templates/chat-panel.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- src/js/angular/ttyg/templates/no-agents-view.html
- src/js/angular/ttyg/templates/ttyg.html
- src/pages/cluster-management/clusterInfo.html
- src/pages/export.html
- src/pages/ux-test2.html
- src/vendor.js
- test-cypress/fixtures/locale-en.json
- webpack.config.common.js
- FontAwesome icons are scaled globally (also added a preview in ux-test2)
- FontAwesome icons use only the fa class (and not fa-regular or alternatives like fa-thin) and the font weight is determined by the --fa-style variable.
- Removed various hacks for individual icons
- Removed FontAwesome 4 from package list
- There was one icon in export view using it
- Note that this npm module brought the classes pull-right and pull-left, which now need to be defined explicitly now
- Copy button directive and Open in SPARQL directive are now styled like all similar icon buttons inside the directive
- Open in SPARQL directive uses a composite FontAwesome icon to recreate the {...} icon from our font and match the rest of the FontAwesome icons around it
Other fixes:
- Added max-width to …
> Fixed various issues with FontAwesome vs our icons (#1656)

- src/js/angular/models/ttyg/agent-form.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/integration/ttyg/create-agent.spec.js
The validation for the create/edit agent dialog is refreshed when the dialog’s tab becomes active.
When users open the create/edit agent dialog and select the "FTS," "Similarity," or "ChatGPT" execution method, a help message appears if the required settings are not yet configured in GraphDB. This message provides a link to the appropriate view in the workbench. After users navigate to that view and complete the necessary setup, they can return to the dialog tab, where the validation will update automatically to reflect these changes, eliminating the need for additional manual refresh actions.
An event listener was added to detect when the user reactivates the tab containing the open create/edit agent dialog. When this event occurs, the dialog’s validation is automatically refreshed to …
> GDB-10937: Automatically Update Validation in Create/Edit Agent Dialog

- src/js/angular/core/services/license.service.js
- src/pages/licenseInfo.html
- test-cypress/integration/license/license.spec.js
- test-cypress/steps/license-steps.js
- test-cypress/stubs/license-stubs.js
What
The buttons "Revert to Free License" and "Set New License" are visible, and the informational message, "License cannot be changed from the Workbench as it was set ..." does not appear, regardless than GraphDB has a license set via the configuration graphdb.license.file.
Why
This occurs due to an incorrect check following the server response.
How
The license configuration check has been corrected to address this issue.
> GDB-11114: License appears editable regardless than GraphDB configured through a file

- src/js/angular/aclmanagement/controllers.js
- src/js/angular/core/services/autocomplete-status.service.js
- src/js/angular/similarity/controllers/similarity-list.controller.js
An unnecessary periodic check for "autocomplete enabled" is triggered in the repository view. Steps to reproduce:
- Open the autocomplete view.
- Switch to the repository view.
Opening the autocomplete view initializes $autocompleteStatus service, that registers a listener for repositoryIsSet event, which triggers a check for autocomplete enabled. The service remains active after the autocomplete page is visited, until the tab is closed or refreshed. The repository view fires the repositoryIsSet event every 5 seconds, causing repeated, unnecessary checks.
Added check if 'repositoryIsSet' is fired because repository is changed if yes the check is executed.
Fixes autocomplete in aclmanagement view
> GDB-10925: Remove Unnecessary Autocomplete Check in Repository View

- package-lock.json
- package.json
Fix automatic prefix insertion in queries. It used to happen in certain scenarios, but in others it required some unwanted preconditions.
Our sesame-prefixes autocomplete plugin for codemirror appeared to be broken/incomplete in handling scenarios where the prefixes had to be inserted in the query. Such scenarios were the cases where the short uri prefix was immediately preceded by some punctuation character like a brace, caret, slash, etc.
Extended the condition that checks whether the prefix should be inserted in the query or not.
> GDB-10834 updated yasgui component version containing a fix for prefix auto insert in queries

- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/security/controllers.js
- Modified `toggleSecurity` in `jwt-auth.service.js` to always return a promise
- Removed the `$timeout` timer and `$scope.$on('$destroy', ...)` logic in `controllers.js` that previously managed the timing of `$window.location.reload()`.
- Previously, a `$timeout` was used to delay `$window.location.reload()` in `controllers.js` because the state change initiated by `$jwtAuth.toggleSecurity(...)` is asynchronous. This timer was a workaround to ensure the security toggle had time to take effect
- This workaround was unreliable, as the timer might not perfectly align with the completion of the asynchronous operation, leading to inconsistencies such the user remains logged in
- By ensuring that `toggleSecurity` always returns a promise, we can now use `.then(...)` in `controllers.js` to wait …
> Ensure `toggleSecurity` consistently returns a promise and remove redundant timer in `controllers.js`

- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/security/controllers.js
- Modified `toggleSecurity` in `jwt-auth.service.js` to always return a promise
- Removed the `$timeout` timer and `$scope.$on('$destroy', ...)` logic in `controllers.js` that previously managed the timing of `$window.location.reload()`.
- Previously, a `$timeout` was used to delay `$window.location.reload()` in `controllers.js` because the state change initiated by `$jwtAuth.toggleSecurity(...)` is asynchronous. This timer was a workaround to ensure the security toggle had time to take effect
- This workaround was unreliable, as the timer might not perfectly align with the completion of the asynchronous operation, leading to inconsistencies such the user remains logged in
- By ensuring that `toggleSecurity` always returns a promise, we can now use `.then(...)` in `controllers.js` to wait …
> Ensure `toggleSecurity` consistently returns a promise and remove reаundant timer in `controllers.js`

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/resources/chart-models/resource/non-heap-memory-chart.js
- test-cypress/fixtures/locale-en.json
The subtitle for the **Off-heap memory usage chart** will be **Maximum off-heap size**.
The label used to be the same as the  **Heap memory usage chart**, which incorrect. It was instantiated and applied to both charts when the **Heap memory usage chart** was created.
I added a translation method for the `NonHeapMemoryChart` class. I also added a new label in the locale files.
N/A for labels.
> GDB-11166 - Add correct subtitle to Off-heap monitoring chart

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/resources/chart-models/resource/non-heap-memory-chart.js
- test-cypress/fixtures/locale-en.json
The subtitle for the **Off-heap memory usage chart** will be **Maximum off-heap size**.
The label used to be the same as the **Heap memory usage chart**, which incorrect. It was instantiated and applied to both charts when the **Heap memory usage chart** was created.
I added a translation method for the `NonHeapMemoryChart` class. I also added a new label in the locale files.
N/A for labels.
> (cherry-pick) GDB-11166 - Add correct subtitle to Off-heap monitoring chart

- .eslintrc
- package-lock.json
- package.json
- src/js/angular/jdbc/controllers.js
- test-cypress/integration/setup/jdbc/jdbc-create.spec.js
- test-cypress/integration/setup/jdbc/jdbc.spec.js
- test-cypress/stubs/jdbc/jdbc-stubs.js
Fix error handling in JDBC view.
The promise from the update request for the JDBC config was not returned by the method used in the controller which made the handler to misbehave.
Changed the update method to return the promise so that the handler to be able to react on the success and errors.
* Moved specs for the JDBC view in separate folder.
* Installed cypress plugin for ESLint to help with the analysis and get rid of the warnings in the test specs for undefined cypress stuff.
* Refactored and fixed jdbc tests and added tests to cover the scenarios with server errors during save and update.
> GDB-11134 fix error handling in JDBC view

- src/i18n/locale-en.json
- src/js/angular/ttyg/directives/chat-item-detail.directive.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- test-cypress/fixtures/locale-en.json
When the "Regenerate" or "How did you derive this answer?" buttons are clicked, the tooltip showing the time for questions and answers is incorrect.
Upon asking a question, the chat messages list in the UI is updated so the question becomes visible immediately after the user clicks the "Ask" button. Therefore, the question time needs to be set on the chatItem passed to the askQuestion function. This behavior already works for regular questions, but in the "Regenerate" and "How did you derive this answer?" scenarios, the time was not set before askQuestion was called.
The question time is now set before calling the askQuestion function when the "Regenerate" or "How did you derive this answer?" buttons are clicked.
> GDB-11179 issue with times in tooltip

- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- test-cypress/integration/ttyg/create-chat.spec.js
The agent id should not be persisted in the local storage anymore.
This leads to some unwanted behavior when the recently selected agent was deleted or the repository is changed where the view in certain scenarios is trying to load the agent using the saved agent id but it can't. This functionality is now replaced by the feature where the agent is derived by the most recent chat.
Removed the steps for persisting and loading of agent by saved id on page load.
Existing tests were updated.
> GDB-11177 agent id should not be persisted in local storage anymore

- src/css/create-similarity-index.css
- src/js/angular/similarity/controllers/create-index.controller.js
- src/pages/create-index.html
- test-cypress/integration/explore/similarity-index/similarity-index-create.spec.js
- test-cypress/integration/explore/similarity-index/similarity-index.spec.js
- test-cypress/integration/explore/similarity-index/similarity.spec.js
- test-cypress/steps/yasgui/yasqe-steps.js
Fix error handling in similarity indexes view.
Error handling in the similarity indexes view is broken and leads to unpleasant experience in the user. For example, when user tries to create or edit a namespace, but the server returns some error, the UI doesn't show a notification for the error, but just navigates to other view which leads to confusion.
* Refactored the save and edit action handlers and added a flag that indicates whether the operation is in progress which is also reflected in the UI with a progress indicator in the respective action button.
> GDB-11134 fix error handling in similarity indexes view

- src/js/angular/core/services/security.service.js
- src/js/angular/models/security/security.js
- src/js/angular/rest/security.rest.service.js
- src/js/angular/security/app.js
- src/js/angular/security/controllers.js
- src/js/angular/security/controllers/user-settings.controller.js
- src/js/angular/security/plugin.js
- src/js/angular/security/services/authorities-util.js
- src/js/angular/security/services/constants.js
Fix the error handling in my settings view so that the UI state to be properly saved or retained when server error occurs during save or update operation.
This broken error handling harms the user experience in the view.
* Moved switching the theme in the success handler after user's data have been updated to prevent the inconsistency in the UI state when a server error occurs and the user update operation fails.
* Extracted the ChangeUserPasswordSettingsCtrl as UserSettingsController in separate controller file. Extracted constants and utilities in separate files.
* Also reorganized and cleaned the code in the new UserSettingsController a bit for better readability and maintainability.
> GDB-11134 fix error handling in my settings view

- .eslintrc
- src/js/angular/namespaces/controllers.js
- test-cypress/integration/setup/namespaces.spec.js
- test-cypress/steps/setup/namespace-steps.js
- test-cypress/stubs/namespace-stubs.js
Fixing the error handling in the namespaces view.
Error handling in the namespace view is practically missing which makes the UI to behave in unexpected ways. For example, when user tries to edit a namespace, but the server returns some error, the UI updated, although it mustn't.
* Implemented error handling for create and edit namespace operation.
* Did some minor refactoring and removed some duplications.
Updated jsdoc
(cherry picked from commit 15bc755564ea651e5036c515134f17e5a8322b0b)
> Cherry-pick GDB-11134 fix error handling in namespace view (#1661)

- src/css/ttyg/chat-list.css
- src/js/angular/core/directives/inline-editable-text/templates/inline-editable-text.template.html
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/show-tooltip-on-overflow.directive.js
- src/js/angular/ttyg/templates/chat-list.html
Long chat names will be truncated with an ellipsis. The user can see the longer name on hover.
The names were not truncated, due to an incorrect selector.
I added the correct selector and a directive, which works on hover to add the long name as a tooltip.
(cherry picked from commit cca49af52da291948c25ab2566d756090e50e283)
> Cherry-pick GDB-11171 - show ellipsis on long chat names and show full name on hover, with the help of a new directive.

- src/js/angular/core/services/jwt-auth.service.js
- src/js/angular/security/controllers.js
* GDB-11134 fix issues in users and settings view when in cluster mode
* Activating free access mode in a cluster in secondary mode results in incorrect state of the checkbox in the ui.
* When trying to activate free access in a node from secondary cluster group, there is 412 error response from the backend which is not properly handled in the UI which results in incorrect state of the checkbox.
* Fixed two thing here. First: properly handle the error state to prevent an error in result of incorrect extraction of the error message from the backend response. Second: moved the initialization of the `freeAccess` property in the jwt-auth.service.js to happen after the success response and not before.
* ## What
* Trying to disable the security while in cluster secondary mode (which is not …
> Cherry-pick GDB-11134 fix issues in users and settings view when in cluster mode

- src/js/angular/core/services/security.service.js
- src/js/angular/models/security/security.js
- src/js/angular/rest/security.rest.service.js
- src/js/angular/security/app.js
- src/js/angular/security/controllers.js
- src/js/angular/security/controllers/user-settings.controller.js
- src/js/angular/security/plugin.js
- src/js/angular/security/services/authorities-util.js
- src/js/angular/security/services/constants.js
* Extracted the ChangeUserPasswordSettingsCtrl as UserSettingsController in separate controller file. Extracted constants and utilities in separate files.
* Move switching the theme in the success handler after user's data have been updated to prevent the inconsistency in the UI state when a server error occurs and the user update operation fails. Also reorganized and cleaned the code a bit for better readability and maintainability.
* Fixed collisions after rebase and some more cleanup
* Fixed jsdoc for the showCookiePolicyLink flag. Refactored get principal function.
(cherry picked from commit 46544a82bd2fb449de573907f27b78b4f3fc0fe5)
> Cherry-pick GDB-11134 fix error handling in my settings view

- src/css/clustermanagement.css
- src/css/repositories.css
The text button labels are not visible in dark mode because they appear black on a black background.
The color styles for text buttons are not explicitly set and depend on the user's browser's default settings. In some cases, this results in the text color being set to black, making it invisible against the black background.
Set an explicit color for text buttons to ensure visibility across all themes, including dark mode.
> GDB-11148: Cluster creation popup, advanced options label is black onblack in dark mode

- src/css/clustermanagement.css
- src/css/repositories.css
The text button labels are not visible in dark mode because they appear black on a black background.
The color styles for text buttons are not explicitly set and depend on the user's browser's default settings. In some cases, this results in the text color being set to black, making it invisible against the black background.
Set an explicit color for text buttons to ensure visibility across all themes, including dark mode.
(cherry picked from commit e2d4ed3205d61afec7d12558579f72f227b628ab)
> Cherry-pick GDB-11148: Cluster creation popup, advanced options label is black on black in dark mode

- src/css/bootstrap-graphdb-theme.css
- src/js/angular/models/clustermanagement/cluster-management-constants.js
- src/vendor.js
Icons are missing from the cluster legend in the "Cluster Management" view.
We recently started using a new pro version of Font Awesome, which introduces a new font-family name: "Font Awesome 6 Pro". Initially, both the new and old versions of Font Awesome were included, so the icons were displayed correctly. However, a recent commit removed the old Font Awesome version, breaking the icon visualization. The difference between the two versions lies in the font-family name, likely for backward compatibility. The old font-family name was "FontAwesome", while the new one is "Font Awesome 6 Pro".
- Updated the font-family name to the new version.
- Fixed solid icons by including the solid CSS file in the vendor bundle.
> GDB-11227: Missing Icons for Cluster Legend

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- src/pages/repositories.html
- src/pages/repository.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/repositories/get-remote-and-local-repositories.json
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/steps/repository-steps.js
When the node is in a cluster, restarting the Local repositories from the Repositories view and the Edit Repository view will not be allowed.
The action is forbidden in the back-end and performing a restart on a Local repo, while in a cluster, causes problems for the GraphDB. 
I added checks to see if the node is in a cluster and if the edited repo is a remote location or not.
Tests added.
N/A
> GDB-10693 - Disable local repo restart in cluster

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- src/pages/repositories.html
- src/pages/repository.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/repositories/get-remote-and-local-repositories.json
- test-cypress/integration/repository/repositories.spec.js
- test-cypress/steps/repository-steps.js
When the node is in a cluster, restarting the Local repositories from the Repositories view and the Edit Repository view will not be allowed.
The action is forbidden in the back-end and performing a restart on a Local repo, while in a cluster, causes problems for the GraphDB.
I added checks to see if the node is in a cluster and if the edited repo is a remote location or not.
Tests added.
N/A
> (cherry-pick) GDB-10693 - Disable local repo restart in cluster

- packages/root-config/src/index.ejs
- packages/shared-components/stencil.config.ts
The browser console displays the following warning messages:
- ```The resource http://localhost:9000/single-spa.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.```
- ```single-spa minified message``` See https://single-spa.js.org/error/?code=41
- An unnecessary <link> tag preloads single-spa.min.js in the index.html, but the resource does not exist on the server after building.
- The shared-components module includes a single-spa dependency, which is loaded when the shared components are initialized in the browser. However, single-spa is already provided by the host application, leading to redundancy.
- Removed the unnecessary <link> tag for …
> Fixes warning messages in browser console

- src/css/sparql-editor.css
- src/pages/sparql-editor.html
In the SPARQL editor page, the user will be able to see the entire `info popover` after hovering the icon next to the title and will be able to click the link to the documentation.
The positioning of the elements in the DOM meant that the `active tab` was visible above the popover and triggered the `mouseleave` event, even though the user could see the mouse was over the popover. The result was that the popover disappeared before the user had a chance to click the link to the documentation. 
I created the correct `stacking context` by moving the `z-index`.
No tests for CSS changes
**The long text in the Editor does not render on top of the popover, allowing the link to be reached.**
> GDB-11204 - Position Info Popover, so user can hover and click the link inside

- src/js/angular/clustermanagement/templates/cluster-configuration/multi-region.html
Add `ng-if="isAdmin"` condition to the delete tag button in the multi-region cluster configuration template to restrict its visibility to admin users.
The delete button was visible to basic users, who are not allowed to delete tags. Clicking the button resulted in a "forbidden" toast and banner, which blocked the cluster view until a page refresh.
Added a `ng-if="isAdmin"` directive to the delete tag button in the HTML template. This ensures the button is only rendered for admin users, preventing basic users from interacting with it.
Admin user
Regular user
> fix(GDB-11271) Restrict delete tag button visibility to admin users in cluster configuration

- src/css/sparql-editor.css
- src/pages/sparql-editor.html
In the SPARQL editor page, the user will be able to see the entire `info popover` after hovering the icon next to the title and will be able to click the link to the documentation.
The positioning of the elements in the DOM meant that the `active tab` was visible above the popover and triggered the mouseleave event, even though the user could see the mouse was over the popover. The result was that the popover disappeared before the user had a chance to click the link to the documentation.
I created the correct `stacking context` by moving the `z-index`.
No tests for CSS changes
**The long text in the Editor does not render on top of the popover, allowing the link to be reached.**
(cherry picked from commit 4f50d83ba10784093308bedd02679180e86f366c)
> (cherry-pick) GDB-11204 - Position Info Popover, so user can hover and click the link inside

- src/js/angular/import/templates/fileSizeLimitInfo.html
When the user clicks on the link **GraphDB REST API** in the Imports page, the `REST API` page will open correctly even in an external context.
The link resolved wrong.
I corrected the link.
N/A
N/A
> GDB-11291 - Fix href in Imports page in external contexts

- src/js/angular/import/templates/fileSizeLimitInfo.html
When the user clicks on the link **GraphDB REST API** in the Imports page, the `REST API` page will open correctly even in an external context.
The link resolved wrong.
I corrected the link.
N/A
N/A
(cherry picked from commit 7db2349d92dda50741cdba1e232f9b27e7dedc58)
> (cherry-pick) GDB-11291 - Fix href in Imports page in external contexts

- src/js/angular/clustermanagement/templates/cluster-configuration/multi-region.html
Add `ng-if="isAdmin"` condition to the delete tag button in the multi-region cluster configuration template to restrict its visibility to admin users.
The delete button was visible to basic users, who are not allowed to delete tags. Clicking the button resulted in a "forbidden" toast and banner, which blocked the cluster view until a page refresh.
Added a `ng-if="isAdmin"` directive to the delete tag button in the HTML template. This ensures the button is only rendered for admin users, preventing basic users from interacting with it.
(cherry picked from commit 181c4e1f2b9418686af275c95cef3073ac24cd3b)
> cherry-pick(GDB-11271) Restrict delete tag button visibility to admin users in cluster configuration

- src/js/angular/ttyg/templates/no-agents-view.html
When clicking the link in the bottom panel of the TTYG page, the user will be taken to the correct page in the documentation.
The link did not work before.
I added the missing parameter from the directive for the interpolation to work.
N/A
Link visible in screenshot:
> GDB-11295 - Add missing TTYG documentation link

- src/js/angular/ttyg/services/agents.mapper.js
When the user edits an `Agent`  that has `Fetch ontology from a named graph` selected, selecting `Provide a SPARQL CONSTRUCT query that fetches the ontology` will display the default SPARQL query in the text field.
Previously, switching from `Fetch ontology from a named graph` to `Provide a SPARQL CONSTRUCT query that fetches the ontology` loaded an empty text field, because for the named graph option there was no `sparqlQuery` for that extraction method when the `Agent` is loaded initially.
I edited the `extraction methods form mapper` to use the `default Agent` values for the `sparqlQuery` and `ontologyGraph` fields when the current model data has an `undefined` property.
N/A
N/A
> GDB-11294 - Load the default SPARQL query during Agent Edit

- src/js/angular/ttyg/services/agents.mapper.js
When the user edits an Agent that has `Fetch ontology from a named graph` selected, selecting `Provide a SPARQL CONSTRUCT query that fetches the ontology` will display the default SPARQL query in the text field.
Previously, switching from `Fetch ontology from a named graph` to `Provide a SPARQL CONSTRUCT query that fetches the ontology` loaded an empty text field, because for the named graph option there was no `sparqlQuery` for that extraction method when the `Agent` is loaded initially.
I edited the `extraction methods form mapper` to use the `default Agent` values for the `sparqlQuery` and `ontologyGraph` fields when the current model data has an `undefined` property.
N/A
N/A
(cherry picked from commit 1a345c3a8b33329cbc72ea48aff605e55b763730)
> (cherry-pick) GDB-11294 - Load the default SPARQL query during Agent Edit

- src/js/angular/ttyg/templates/no-agents-view.html
When clicking the link in the bottom panel of the TTYG page, the user will be taken to the correct page in the documentation.
The link did not work before.
I added the missing parameter from the directive for the interpolation to work.
N/A
Link visible in screenshot:
> (cherry-pick) GDB-11295 - Add missing TTYG documentation link

- src/js/angular/controllers.js
- src/template.html
The user will be able to copy the information in the repository popover, because it will not disappear on `mouseleave`. Instead it will disappear on click outside.
The functionality is an improvement suggested by users. There was no way to copy this information before.
I moved the popover to another element, in order to allow it to close on click outside.
N/A
N/A
> GDB-11251 - Close repo info popover on click outside, so content can be copied

- src/js/angular/utils/workbench-settings-storage-service.js
Whenever the user changes the theme mode (Light or Dark) in the Settings page, the mode will not be applied if the changes are not saved.
There were several cases when toggling the mode changed the theme even when the setting were not saved. Exiting the page or clicking cancel after changing the mode option would apply the selected option if the `local store` did not have a saved value.
The reason for this bug is that whenever the `local store` does not have the settings saved, it returns the default settings. That object is mutated every time the user changes the theme mode.
I clone the default settings before they are returned. This way only the clone is changed before saving to the `local store`.
N/A
N/A
> GDB-11286 - Ensure theme mode changes in My Settings are only applied on Save

- src/js/angular/security/controllers/user-settings.controller.js
Pass the password property with the expected name to the UpdateUserPayload model.
A logged-in user can't edit his own password.
Fixed the password property name passed to the user model so that it can be mapped correctly.
> GDB-11387 Pass the password property with the expected name to the UpdateUserPayload model

- src/js/angular/utils/workbench-settings-storage-service.js
Whenever the user changes the theme mode (Light or Dark) in the Settings page, the mode will not be applied if the changes are not saved.
There were several cases when toggling the mode changed the theme even when the setting were not saved. Exiting the page or clicking cancel after changing the mode option would apply the selected option if the `local store` did not have a saved value.
The reason for this bug is that whenever the `local store` does not have the settings saved, it returns the default settings. That object is mutated every time the user changes the theme mode.
I clone the default settings before they are returned. This way only the clone is changed before saving to the `local store`.
N/A
N/A
(cherry picked from commit 4650315f86618f97c00d69002949fa1ecb4aa56d)
> (cherry-pick) GDB-11286 - Ensure theme mode changes in My Settings are only applied on Save

- src/template.html
The popovers in the dropdown list for repository selection will not appear cut off by the top of the browser.
The top repositories would have a partially visible popover, because they appeared too high up and would get cut off at the end of the page.
I changed the popover position to better fit the amount of rows in the popover template. This should make it less likely that it is cut off.
N/A
Before (as reported in the Jira bug):
After:
> GDB-11397 - Re-position the dropdown repo list popovers

- src/template.html
The popovers in the dropdown list for repository selection will not appear cut off by the top of the browser.
The top repositories would have a partially visible popover, because they appeared too high up and would get cut off at the end of the page.
I changed the popover position to better fit the amount of rows in the popover template. This should make it less likely that it is cut off.
N/A
Before (as reported in the Jira bug):
After:
> (cherry-pick) GDB-11397 - Re-position the dropdown repo list popovers

- packages/shared-components/docker-compose.yaml
- packages/shared-components/tsconfig.json
- Added baseUrl to the tsconfig.json file in the shared-components package.
- Mounted the api directory to the shared_components service in docker-compose.yaml.
baseUrl in tsconfig.json:
- Required for proper resolution of module paths defined in the paths configuration, particularly for the @ontotext/workbench-api alias
Mounting the api directory:
- Enables the shared_components service to access the api directory on the host machine
- Updated tsconfig.json: Added "baseUrl": "./" under compilerOptions to support path alias resolution.
- Updated docker-compose.yaml: Added ../api:/api as a volume for the shared_components service to expose the api directory inside the container
> fix(GDB-10638) Add baseUrl and mount api directory

- src/js/angular/security/controllers/user-settings.controller.js
When the user switches between the `Default theme` and `Ontotext original theme` in the settings, the selected theme will be applied as before, however if the changes aren't saved or can't be saved, the theme will be restored. 
Previously, once toggled, the theme would be applied and would remain even if the settings weren't saved.
I restore the theme `on destroy`, using the `Local store` values.
N/A
N/A
> GDB-11404 - Ensure Local Store theme name (or default) is applied when settings aren't saved

- .editorconfig
- packages/api/src/models/common/index.ts
- packages/api/src/models/product-info/index.ts
- packages/api/src/models/product-info/product-info.ts
- packages/api/src/ontotext-workbench-api.ts
- packages/api/src/services/license/license-context.service.ts
- packages/api/src/services/license/license-rest.service.ts
- packages/api/src/services/license/test/license-context.service.spec.ts
- packages/api/src/services/product-info/index.ts
- packages/api/src/services/product-info/mappers/product-info.mapper.spec.ts
- packages/api/src/services/product-info/mappers/product-info.mapper.ts
- packages/api/src/services/product-info/product-info-context.service.ts
- packages/api/src/services/product-info/product-info-rest.service.ts
- packages/api/src/services/product-info/product-info.service.ts
- packages/api/src/services/product-info/test/product-info-context.service.spec.ts
- packages/api/src/services/product-info/test/product-info.service.spec.ts
- packages/root-config/src/ontotext-root-config.js
- packages/shared-components/cypress/e2e/footer/footer.cy.js
- packages/shared-components/cypress/steps/footer/footer-steps.js
- packages/shared-components/src/assets/i18n/en.json
- packages/shared-components/src/assets/i18n/fr.json
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-footer/onto-footer.tsx
- packages/shared-components/src/components/onto-footer/readme.md
- packages/shared-components/src/components/onto-header/onto-header.tsx
- packages/shared-components/src/components/onto-test-context/onto-test-context.tsx
- packages/shared-components/src/components/onto-test-context/readme.md
- packages/shared-components/src/pages/footer/index.html
- packages/shared-components/src/pages/js/main.js
Implemented dynamic data loading for footer component
To populate the versions, mentioned in the footer dynamically.
Added a request to `/rest/info/version?local=1` upon `single-spa:first-mount`. If the request is successful, we update the license context with the product info. The `onto-footer` component now gets the data from the context and visualises it, once it is available.
Jest unit tests and cypress component tests
> GDB-10571 Implement workbench footer component

- packages/api/src/models/storage/index.ts
- packages/api/src/models/storage/storage-data.ts
- packages/api/src/models/storage/storage-key.ts
- packages/api/src/ontotext-workbench-api.ts
- packages/api/src/services/storage/index.ts
- packages/api/src/services/storage/local-storage.service.ts
- packages/api/src/services/storage/persistence.ts
- packages/api/src/services/storage/test/local-storage.service.spec.ts
Introduce a local storage service that will be used to persist data in the browser.
Some features in the workbench require data to be persisted locally in the browser.
* Implemented a Persistence interface that must be implemented by every storage service. The Persistence name was chosen to avoid confusion with the native Storage interface.
* Implemented a LocalStorageService backed by the localStorage API.
* Implemented a StorageData wrapper model which provides convenient methods for access and convert the stored value.
Implemented tests for the service and storage data wrapper.
NA
> GDB-11282 introduce local storage service

- package-lock.json
- package.json
- scripts/validate-translations.js
- src/app.js
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/graphql-playground/graphql-playground.directive.js
- src/js/angular/core/directives/graphql-playground/templates/graphql-playground.html
- src/js/angular/graphql/app.js
- src/js/angular/graphql/controllers/graphql-playground-view.controller.js
- src/js/angular/graphql/plugin.js
- src/pages/graphql/graphql-playground.html
- test-cypress/integration/graphql/graphql-playground.spec.js
- test-cypress/package.json
- test-cypress/steps/graphql/graphql-playground-steps.js
- webpack.config.common.js
Added a new GraphQL Playground integration with the following:
- `graphql-playground.directive.js`: Custom directive for embedding the GraphQL Playground component
- `graphql-playground-view.controller.js`: Controller for managing GraphQL Playground view.
- `graphql-playground.html`: Templates for both the directive and route views.
- `plugin.js`: Registered routes and main menu entries for GraphQL Playground.
- Added translations in locale-en.json and locale-fr.json.
- Included ontotext-graphql-playground-component in package.json.
- Updated webpack.config.common.js to bundle required assets.
- Modified app.js to load the GraphQL component’s custom elements.
- To provide an initial integration of GraphQL Playground component
- Created a new Angular module graphdb.framework.graphql for …
> feat(GDB-10459) Initial GraphQL Playground integration

- packages/legacy-workbench/src/template.html
- packages/root-config/src/styles/onto-stylesheet.css
- packages/shared-components/cypress/e2e/permission-banner/permission-banner.cy.js
- packages/shared-components/cypress/steps/permission-banner/permission-banner-steps.js
- packages/shared-components/src/assets/i18n/en.json
- packages/shared-components/src/assets/i18n/fr.json
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-layout/onto-layout.scss
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/components/onto-layout/readme.md
- packages/shared-components/src/components/onto-permission-banner/onto-permission-banner.scss
- packages/shared-components/src/components/onto-permission-banner/onto-permission-banner.tsx
- packages/shared-components/src/components/onto-permission-banner/readme.md
- packages/shared-components/src/components/translate-label/readme.md
- packages/shared-components/src/index.html
- packages/shared-components/src/pages/permission-banner/index.html
- packages/shared-components/src/pages/permission-banner/main.js
The "permission denied" banner has been created in the new WB. Functionality to be added with another MR.
This was one of the elements due to be migrated.
I created a new shared component with the banner and styled it like the one in the legacy WB.
Test added.
> GDB-11319 - Create denied permission alert banner

- Jenkinsfile
- packages/shared-components/docker-compose.yaml
- packages/shared-components/package-lock.json
- packages/shared-components/package.json
- packages/shared-components/sonar-project.js
- packages/workbench/package-lock.json
- packages/workbench/package.json
- packages/workbench/sonar-project.js
Fixes running sonar at CI
To monitor results from the sonar static analisys and keep the code clean from issues.
Fixed configurations.
NA
NA
> fix(GDB-10638) Fix sonar stage

- packages/api/src/models/storage/storage-data.ts
- packages/api/src/services/repository/index.ts
- packages/api/src/services/repository/repository-context.service.ts
- packages/api/src/services/repository/repository-storage.service.ts
- packages/api/src/services/repository/test/repository-context.service.spec.ts
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/core/interceptors/authentication.interceptor.js
- packages/legacy-workbench/src/js/angular/core/services/jwt-auth.service.js
- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
- packages/legacy-workbench/src/js/angular/graphexplore/controllers/graphs-config.controller.js
- packages/legacy-workbench/src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- packages/legacy-workbench/src/js/angular/similarity/controllers/similarity-list.controller.js
- packages/legacy-workbench/src/pages/repositories.html
- packages/root-config/src/ontotext-root-config.js
- packages/shared-components/cypress/e2e/repository-selector/repository-selector.cy.js
- packages/shared-components/cypress/steps/header/repository-selector-steps.js
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
- packages/shared-components/src/components/onto-test-context/onto-test-context.tsx
- packages/shared-components/src/components/onto-test-context/readme.md
- packages/shared-components/src/pages/js/main.js
- packages/shared-components/src/pages/repository-selector/index.html
- packages/workbench/src/app/graphql/graphql.component.ts
Refactored the repository selector component and extended repository context service to allow loading repositories from the context and synchronizing the selected repository through the local storage. Additionaly, updated the legacy-workbench to use the new context and storage services from the api module.
It is expected that repositories are loaded during application bootstrap and also the selected repository to be persisted in local storage so that application opened in multiple tabs to be synchronized automatically.
* Extended repository context service and implemented repository storage service in the api module.
* Updated root-config to fetch repositories from backend and store the in the repository context service.
* Refactored repository selector shared component to fetch …
> GDB-11282 save selected repository in local storage

- packages/shared-components/src/components/onto-dropdown/onto-dropdown.scss
- packages/shared-components/src/components/onto-header/onto-header.scss
- packages/shared-components/src/components/onto-language-selector/onto-language-selector.scss
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.scss
The changes address some of the differences in the repository popover and icon styles in the repo selector. 
There were some styling differences when comparing with the legacy Workbench.
I edited the tooltip theme and button icon size.
N/A
Legacy WB:
Current update:
> GDB-11398 - Style popover and repo icon like in the legacy WB

- package-lock.json
- package.json
- src/js/angular/graphql/controllers/graphql-playground-view.controller.js
- src/js/angular/graphql/templates/graphql-playground.html
- src/js/angular/models/graphql/graphql-playground-config.js
Allow the graphiql playground to work when GDB security is enabled.
Users should be able to use the feature when security is ON.
* The graphiql component was extended to support `headers` property provided through the external configuration. 
* Extended the playground view to provide the Authorization header with the configuration so that the graphiql component to be able to configure its internal http fetcher to pass it through with each query request.
The graphiql component has tests for supporting the new `headers` configuration.
> GDB-11463-support-security-mode-in-graphql-playground

- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
- packages/shared-components/stencil.config.ts
- webpack.config.common.js
Fix the navbar logo
It wasn't being displayed
- Added copy instructions in webpack, to copy the `assets` folder into `dist`, since stenciljs doesn't take care of that
- Removed the use of `getAssetPath` from `@stencil/core` as it is unreliable and returns wrong paths. Currently, we control the destination of the copied resources, hence we can statically reference them.
None. There is no new testable code
Expanded:
Not expanded:
> GDB-11480 Fix logo not showing

- src/js/angular/graphql/templates/graphql-playground.html
Move graphql endpoint selector in the page heading row.
To save some vertical space on the page.
Moved the select component in the heading.
NA
> GDB-11459 move graphql endpoint selector in the page heading row

- packages/api/src/models/events/event-name.ts
- packages/api/src/models/events/event-observer.ts
- packages/api/src/models/events/index.ts
- packages/api/src/models/events/navigation/navigation-end-payload.ts
- packages/api/src/models/events/navigation/navigation-end.ts
- packages/api/src/models/security/index.ts
- packages/api/src/models/security/restricted-pages.ts
- packages/api/src/models/security/test/restricted-pages.spec.ts
- packages/api/src/ontotext-workbench-api.ts
- packages/api/src/services/event-service/event.service.ts
- packages/api/src/services/event-service/index.ts
- packages/api/src/services/event-service/test/event.service.spec.ts
- packages/api/src/services/security/index.ts
- packages/api/src/services/security/security-context.service.ts
- packages/api/src/services/security/test/security-context.service.spec.ts
- packages/api/src/services/user-permission/user-permission-storage.service.ts
- packages/legacy-workbench/src/js/angular/core/interceptors/unauthorized.interceptor.js
- packages/legacy-workbench/src/template.html
- packages/root-config/src/ontotext-root-config.js
- packages/shared-components/cypress/e2e/permission-banner/restricted-pages.cy.js
- packages/shared-components/cypress/steps/restricted-pages/restricted-pages-steps.js
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/components/onto-navbar/onto-navbar.scss
- packages/shared-components/src/components/onto-test-context/onto-test-context.tsx
- packages/shared-components/src/components/onto-test-context/readme.md
- packages/shared-components/src/index.html
- packages/shared-components/src/pages/js/main.js
- packages/shared-components/src/pages/restricted-pages/index.html
- packages/shared-components/src/pages/restricted-pages/main.js
- The user denied permission banner will appear when the page is unauthorized;
- The onto-navbar remains aligned to the top of the page regardless of the margin-top set on the onto-layout. For instance, if onto-layout has margin-top: 100px, the navbar will still stay fixed at the top of the page.
- The banner was added as a component, but the functionality was not;
- This behavior occurs because there is a top: 0 declaration on the onto-navbar container.
- I added a context service, which communicates between the new and old WB. The onto-layout also listens for route changes, in order to know that the flag for the banner should be re-calculated. The UserPermissionStorageService remains from a previous implementation of the solution, but is not used here otherwise;
- Remove the top: 0 CSS …
> GDB-11319 - Add functionality to permission banner

- .npmrc
- docs/developers-guide.md
- package-lock.json
- package.json
- Removed the integration of Fontawesome PRO iconset via `npm`.
- Updated `.npmrc` to eliminate authentication token for Fontawesome.
- Deleted Fontawesome-specific dependencies from `package.json` and `package-lock.json`.
- Revised the developer's guide to reflect manual updates of Fontawesome files.
- Storing sensitive authentication tokens in `.npmrc` poses a security risk.
- Switching to manual file updates reduces dependency
- Authentication token and references to Fontawesome PRO were removed from `.npmrc`.
- Dependencies on `@awesome.me/kit-94ffd2fc4a` and related packages were deleted from the package files.
- Developer's Guide now includes detailed steps for manually downloading and replacing Fontawesome PRO files from our Fontawesome account.
> fix(GDB-11550) Remove npm-based Fontawesome PRO integration

- .babelrc
- .eslintrc
- package-lock.json
- package.json
- webpack.config.common.js
Changes compilation target of the javascript to ecmascript 2022.
Compiling to ECMAScript 2022 (ES2022) instead of ES2015 offers several benefits like:
* New language features: Top-level await, Class fields and private methods, Logical assignment operators (&&=, ||=, ??=), WeakRefs and FinalizationRegistry, Array.prototype.at(), Object.hasOwn()
* Improved performance
* Better syntax
* Updated and configured babel toolting
* Configured eslint
* Updated webpack config to transpile the code using the new babel
NA
NA
> Changes compilation target of the javascript to ecmascript 2022

- src/js/angular/core/directives/dynamic-form/dynamic-form.directive.js
- src/js/angular/core/directives/dynamic-form/templates/dynamic-form.html
- webpack.config.common.js
- Added a new directive "dynamicConfigurationForm" to render dynamic configuration forms.
- Created an HTML template for the directive to support multiple configuration types (string, text, boolean, JSON, single select, multi-select).
- Updated the webpack configuration to copy the new directive's template into the build output.
- To enable dynamic rendering of configuration forms based on configuration objects.
- To support select and multi-select options modeled by SelectMenuOptionsModel.
- To improve modularity and maintainability by encapsulating the configuration form logic in its own directive.
- Implemented the directive
- Created the corresponding HTML template
- Modified `webpack.config.common.js` to include the new template directory in the build process
NB. Depends on …
> feat(GDB-11566) Introduce dynamic configuration form

- src/js/angular/similarity/controllers/similarity-list.controller.js
Fix the way object property is treated when the search query is built to prevent errors. 
Seems like there was a regression which caused the object property to be always treated as a literal for predicate search.
Fixed the condition which was causing the property to not be wrapped in angle brackets for predicate searches
NA
NA
> GDB-11670 fix object property when predicate search query is built

- src/js/angular/similarity/controllers/similarity-list.controller.js
Fix the way object property is treated when the search query is built to prevent errors.
Seems like there was a regression which caused the object property to be always treated as a literal for predicate search.
Fixed the condition which was causing the property to not be wrapped in angle brackets for predicate searches
NA
NA
> GDB-11670 fix object property when semantic search query is built

- src/css/graphql/graphql-endpoint-configuration-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/dynamic-form/dynamic-form.directive.js
- src/js/angular/core/directives/dynamic-form/templates/dynamic-form.html
- src/js/angular/core/services/graphql.service.js
- src/js/angular/graphql/app.js
- src/js/angular/graphql/controllers/graphql-endpoint-configuration-modal.controller.js
- src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
- src/js/angular/graphql/services/graphql-context.service.js
- src/js/angular/graphql/templates/graphql-endpoint-management.html
- src/js/angular/graphql/templates/modal/endpoint-configuration-modal.html
- src/js/angular/models/dynamic-form/dynamic-form-field.js
- src/js/angular/models/graphql/graphql-endpoint-configuration-setting.js
- src/js/angular/models/graphql/graphql-endpoint-configuration.js
- src/js/angular/rest/graphql.rest.service.js
- src/js/angular/rest/mappers/dynamic-form-fied-mapper.js
- src/js/angular/rest/mock-backend/graphql-rest-service-mock.js
- test-cypress/fixtures/graphql/endpoints/graphql-endpoint-configuration-types.json
- test-cypress/fixtures/graphql/endpoints/graphql-endpoint-configuration.json
- test-cypress/integration/graphql/edit-graphql-enpoint.spec.js
- test-cypress/steps/graphql/edit-graphql-endpoint-steps.js
- test-cypress/steps/graphql/graphql-endpoint-management-steps.js
- test-cypress/steps/modal-dialog-steps.js
- test-cypress/stubs/graphql/graphql-stubs.js
- Added a new modal dialog for configuring GraphQL endpoints via a dynamic form.
- Updated the dynamic form directive to expose its form controller (formCtrl) for parent-level state checks.
- Introduced new REST service methods (getGraphqlEndpointConfiguration and saveEndpointConfiguration) to fetch and save endpoint configurations.
- Added a dedicated controller (GraphqlEndpointConfigurationModalController) and its template to manage the modal’s behavior, including cancel and save actions
- Updated i18n files to include modal titles and messages in both English and French.
- Extended Cypress stubs and tests
- To enable re-configuration of each GraphQL endpoint from the endpoints management view
- To integrate the new configuration flow into the existing GraphQL endpoint management …
> feat(GDB-11565) Implement GraphQL Endpoint Configuration Modal

- src/js/angular/namespaces/controllers.js
- test-cypress/integration/setup/namespaces.spec.js
- test-cypress/steps/setup/namespace-steps.js
The pagination in the "Namespaces" view is not working.
With the changes made for [MR for GDB-11134](https://github.com/Ontotext-AD/graphdb-workbench/pull/1661), the changePagination function was accidentally removed from $scope. This caused the issue because the paginator relies on this function to navigate to the next page.
Reintroduced the changePagination function as a $scope function.
> GDB-11676: Changing Pages Does Not Work on the Namespaces View

- src/js/angular/namespaces/controllers.js
- test-cypress/integration/setup/namespaces.spec.js
- test-cypress/steps/setup/namespace-steps.js
The pagination in the "Namespaces" view is not working.
With the changes made for [MR for GDB-11134](https://github.com/Ontotext-AD/graphdb-workbench/pull/1661), the changePagination function was accidentally removed from $scope. This caused the issue because the paginator relies on this function to navigate to the next page.
Reintroduced the changePagination function as a $scope function.
(cherry picked from commit 4150a6192f6f1cc1fad633a98bd655325542c10a)
> Cherry-pick GDB-11676: Changing Pages Does Not Work on the Namespaces View

- src/js/angular/core/controllers.js
- src/js/angular/core/templates/modal/modal-warning.html
- src/pages/cluster-management/clusterInfo.html
The dialog content overflow is broken.
Steps to reproduce:
- Add many files for import (20–30);
- Select all of them;
- Click on the "Remove" button.
The confirmation dialog in the import view uses the "modal-warning.html" template for confirmation. It is passed to the $uibModal service to open the dialog. This creates a <div> container with the class "modal-content", which has a display: flex declaration. Its children include three elements with the classes "modal-header", "modal-body", and "modal-footer". The dialog has a max-height of 90vh, and the "modal-body" has CSS rules that make it fit all available height within the dialog. If the content exceeds this height, a scrollbar should appear. Event handling is properly set up and should not cause this issue. However, [in this merge …
> GDB-11717: UI not responsive when trying to delete a lot of uploaded files from the imports screen

- src/js/angular/core/controllers.js
- src/js/angular/core/templates/modal/modal-warning.html
- src/pages/cluster-management/clusterInfo.html
The dialog content overflow is broken.
Steps to reproduce:
- Add many files for import (20–30);
- Select all of them;
- Click on the "Remove" button.
The confirmation dialog in the import view uses the "modal-warning.html" template for confirmation. It is passed to the $uibModal service to open the dialog. This creates a <div> container with the class "modal-content", which has a display: flex declaration. Its children include three elements with the classes "modal-header", "modal-body", and "modal-footer". The dialog has a max-height of 90vh, and the "modal-body" has CSS rules that make it fit all available height within the dialog. If the content exceeds this height, a scrollbar should appear. Event handling is properly set up and should not cause this issue. However, [in this merge …
> Cherry-pick GDB-11717: UI not responsive when trying to delete a lot of uploaded files from the imports screen

- packages/root-config/src/ontotext-root-config.js
- packages/shared-components/global.d.ts
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/models/plugin/plugin-registry.ts
Fix menu items, which weren't being shown sometimes in prod mode
Because menu items should be shown in those circumstances
Previously the `ontotext-root-config` waited for the navbar to be available and added the menu items to it. The `onto-layout` component listens for changes to the security context and authenticated user. Every time a change is made, the menu items' visibility is recalculated. In prod mode, the requests sometimes finish, before root-config sets the menu items of the navbar, leaving nothing to be filtered so no elements are displayed. 
Now the initial population of the menu items is moved into `onto-layout`, immediately after the navbar reference is resolved. Then we recalculate the visibility of the items. This way it doesn't matter in what order the operations …
> GDB-11536 Fix menu items not shown in prod mode

- package-lock.json
- package.json
- src/css/graphql/graphql-playground.css
- src/js/angular/core/directives/graphql-playground/graphql-playground-directive.util.js
- src/js/angular/core/directives/graphql-playground/graphql-playground.directive.js
- src/js/angular/graphql/controllers/graphql-playground-view.controller.js
- src/js/angular/graphql/templates/graphql-playground.html
- src/js/angular/models/graphql/graphql-playground-component.js
- src/js/angular/models/graphql/graphql-playground-config.js
- test-cypress/integration/graphql/graphql-playground.spec.js
- test-cypress/steps/graphql/graphiql-editor-tools-steps.js
- test-cypress/steps/graphql/graphiql-playground-steps.js
Internationalized the ontotext-graphql-playground component.
The ontotext-graphql-playground component must support multiple languages.
- Added a language change event listener;
- Updated the GraphQL Playground component to reflect the selected language.
> GDB-11239: Internationalize the ontotext-graphql-playground Component

- packages/legacy-workbench/src/js/angular/core/services/jwt-auth.service.js
Fix cookie consent error, upon toggle, with disabled security
There is an error currently, as there is no authenticated user set in the context.
Updated authenticated user upon refresh, whenever we have disabled security. Currently in this scenario, the context wasn't being updated, which caused the error.
none, as the context is populated in the legacy workbench
> GDB-11320 Fix cookie consent toggle without security

- src/css/graphql/graphql-endpoint-management.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/graphql.service.js
- src/js/angular/graphql/controllers/create-graphql-endpoint-view.controller.js
- src/js/angular/graphql/controllers/graphql-endpoint-configuration-modal.controller.js
- src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
- src/js/angular/graphql/controllers/graphql-playground-view.controller.js
- src/js/angular/graphql/models/endpoints.js
- src/js/angular/graphql/services/endpoint-generation-report.mapper.js
- src/js/angular/graphql/services/endpoint-info-list.mapper.js
- src/js/angular/graphql/services/endpoint-utils.js
- src/js/angular/graphql/services/endpoints.mapper.js
- src/js/angular/graphql/templates/graphql-endpoint-management.html
- src/js/angular/models/graphql/graphql-endpoints-info.js
- src/js/angular/models/graphql/update-endpoint-request.js
- src/js/angular/rest/graphql.rest.service.js
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/graphql/edit-graphql-enpoint.spec.js
- test-cypress/integration/graphql/graphql-set-default-endpoint.spec.js
- test-cypress/steps/graphql/graphql-endpoint-management-steps.js
Allow changing which is the default graphql endpoint. There can be only one default endpoint.
This allows the user to switch which is the default endpoint from the UI.
Implemented operation handler in the controller and a UI control for the user to interact with.
Implemented tests.
> GDB-11563 set endpoint default state

- src/css/ttyg/agent-settings-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/agent-form.js
- src/js/angular/models/ttyg/agents.js
- src/js/angular/ttyg/app.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/services/agents.mapper.js
- src/js/angular/ttyg/templates/autocomplete-iri-discovery-search.html
- src/js/angular/ttyg/templates/iri-discovery-search.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/agent/get-agent-list-autocomplete-query.json
- test-cypress/fixtures/ttyg/autocomplete-response.json
- test-cypress/integration/ttyg/edit-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
- test-cypress/stubs/ttyg/ttyg-stubs.js
Introducing a new Additional query method to the TTYG form.
The method gives the user another option for IRI discovery, based on GDB's autocomplete index.
I updated the form, models, mapper, styles etc.
Test added
> GDB-11689 - Autocomplete index integration

- test-cypress/integration/sparql-editor/saved-query/readonly-query.spec.js
Skipped a test that relies on security toggling in the afterEach hook, which can cause cascading failures.
If the test fails and the afterEach hook does not properly reset security, all subsequent tests will also fail due to security remaining enabled.
- Skipped the test to prevent instability.
- Added a reminder to refactor it using stubs or a better implementation in the future.
N/A
N/A
- [-] Tests
> Skip unstable security-related test

- src/js/angular/guides/steps/complex/main-menu/plugin.js
- test-cypress/integration/sparql-editor/saved-query/readonly-query.spec.js
Extend the `click-main-menu` block to support navigating to TTYG view
This will allow the guides to be configured to go to the TTYG page
- add another condition in the `click-main-menu` guide block for `ttyg` route
A test for the complete TTYG guide will be implemented at the end
> GDB-11571 Extend Main Menu guide step to support TTYG

- package-lock.json
- package.json
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/graphql-playground/graphql-playground.directive.js
- src/js/angular/core/directives/graphql-playground/templates/graphql-playground.html
- src/js/angular/graphql/controllers/graphql-playground-view.controller.js
- src/js/angular/models/graphql/graphql-playground-config.js
- Added a new header, "X-GraphDB-Track-Alias", to each GraphQL query request. This header contains a unique value to differentiate internal SPARQL queries from other queries.
- Extended the graphql-playground.directive wrapper to listen for the "abortQuery" event triggered by the abort button in the updated ontotext-graphql-playground-component.
- Upon receiving the "abortQuery" event, a DELETE request is sent to cancel the corresponding SPARQL query using the unique value from the "X-GraphDB-Track-Alias" header.
To cancel an internal SPARQL query that is part of a GraphQL query.
- Introduced a unique "X-GraphDB-Track-Alias" header to help identify and differentiate internal SPARQL queries.
- Modified graphql-playground.directive to listen for the "abortQuery" event and trigger a DELETE …
> GDB-11741: Extend the Graphiql component with ability to terminate long running graphql queries in GDB

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/guides/steps/complex/create-repository/plugin.js
- src/pages/repository.html
- test-cypress/fixtures/locale-en.json
Extend  guide steps when creating repository to be able to enable FTS
This will allow enabling of FTS to be included in the guides
- added a step configuration option `fts` which would add the step to enable fts to the guide
Testing will be done on whole guide
> GDB-11583 Extend guide steps for repository

- src/js/angular/guides/steps/complex/ttyg/create-ttyg-agent/plugin.js
- src/js/angular/guides/steps/core/plugin.js
- src/js/angular/guides/tour-lib-services/shepherd.service.js
- Extends the 'guide-end' options with the ability to configure its content and title.
- Changes the setup of steps to allow 'guide-end' to be placed in the middle of a guide.
The newly implemented guide has a branch in the middle. There is a configuration step that the user can complete before starting the GraphDB server. If this configuration is not set, the guide must be completed in the middle of the process.
- Enhanced the configuration of the 'guide-end' step by adding a new field, "lastStep", and the ability to read content from the configuration;
- Modified the service behavior for adding step buttons to support cases where an end step can be positioned in the middle of a guide.
The step configuration now supports content option:
```
{
"guideBlockName": "guide-end",
"options": { …
```
> GDB-11781: TTYG guide: Extend End Guide Step with Option to Change Content

- src/js/angular/guides/tour-lib-services/shepherd.service.js
Extend guides with an option to hide the "Previous" button.
Currently, our guides always display a "Previous" button, which may not be necessary in certain cases. To improve flexibility, we have added a configuration option that allows users to hide the "Previous" button when needed.
A new option, "disablePreviousFlow", has been introduced. When set to true, the "Previous" button will not be displayed.
You can use the following configuration to test this feature:
```
{
"guideName": {
"en": "Talk To Your Graph guide",
"fr": "Le guide Star Wars"
},
"guideDescription": {
"en": "This is the TTYG guide",
"fr": "Le guide Star Wars est un guide pour débutant montrant la création d'un dépôt, l'importation de données RDF à partir d'un fichier, le début de l'exploration des données du graphe visuel …
```
> GDB-11790: TTYG Guide – Extend Guides with an Option to Hide the "Previous" Button

- src/js/angular/core/services/security.service.js
- src/js/angular/graphql/plugin.js
- src/js/angular/security/templates/modal/default-authorities.html
- test-cypress/integration-flaky/setup/users-and-access/security-and-free-access.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/integration/sparql-editor/saved-query/readonly-query.spec.js
- test-cypress/integration/ttyg/ttyg-permission.spec.js
- test-cypress/steps/login-steps.js
- test-cypress/steps/setup/user-and-access-steps.js
- Updated the default authorities modal template to include GraphQL authority settings.
- Enhanced the free access API endpoints in the security service with mapping functions to correctly handle authority data.
- Administrators need the ability to assign GraphQL-only authorities in the free access configuration.
- Updated the security service methods (getFreeAccess and setFreeAccess) to transform the data properly for authority mapping.
- Enhanced the modal template for default authorities to include a new GraphQL checkbox and adjusted the grid layout for consistent display.
- Modified the Angular plugin configuration to change the required role to 'IS_AUTHENTICATED_FULLY' in the GraphQL plugin.
Depends on https://github.com/Ontotext-AD/graphdb-workbench/pull/1809
> feat(GDB-11772) Enable GraphQL-Only Authority Setting for Free Access

- src/css/graphql/create-graphql-endpoint.css
- src/css/graphql/graphql-endpoint-management.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/services/graphql.service.js
- src/js/angular/graphql/controllers/create-graphql-endpoint-view.controller.js
- src/js/angular/graphql/controllers/endpoint-generation-failure-result-modal.controller.js
- src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
- src/js/angular/graphql/controllers/import-endpoint-definition-modal.controller.js
- src/js/angular/graphql/services/endpoint-generation-report.mapper.js
- src/js/angular/graphql/services/graphql-context.service.js
- src/js/angular/graphql/templates/create-graphql-endpoint.html
- src/js/angular/graphql/templates/graphql-endpoint-management.html
- src/js/angular/graphql/templates/modal/endpoint-generation-failure-result-modal.html
- src/js/angular/graphql/templates/step-generate-endpoint.html
- src/js/angular/graphql/templates/step-select-schema-sources.html
- src/js/angular/models/graphql/graphql-endpoint-configuration.js
- src/js/angular/rest/graphql.rest.service.js
- test-cypress/integration/graphql/graphql-endpoint-management-view.spec.js
- test-cypress/integration/graphql/import-graphql-endpoint-definitions.spec.js
- test-cypress/steps/graphql/graphql-endpoint-management-steps.js
* Implemented a delete endpoint report operation.
* Did multiple improvements in the create endpoint workflow.
* This allows users to clear the current generation state for particular endpoint if they are not interested in it.
* Improves the UX.
* Extended the graphql managment to support the delete operation.
* Did further improvments in the UI layout.
* Disabled the wizard buttons: back, cancel, generate, as well as the source repository selector during generation.
* Did some improvements in the layout and presentation of data in the endpoints generation overview page.
* Added pattern validator to the endpoint id field to prevent invalid data to be entered by the user which can lead to errors during the generation.
Updated tests
> GDB-11802 allow deleting generated endpoint report

- src/js/angular/graphql/plugin.js
- src/js/angular/security/templates/user.html
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/steps/setup/user-and-access-steps.js
- Changed GraphQL Endpoint Management menu role from IS_AUTHENTICATED_FULLY to ROLE_REPO_MANAGER.
- Ensures only repository managers or higher can manage GraphQL endpoints, improving security alignment.
- Updated plugin.js to specify ROLE_REPO_MANAGER for Endpoint Management.
- Added test coverage to confirm correct behavior with the new authority requirement.
- Modified user-and-access-steps.js and user.html to accommodate realClick() for checkboxes.
> fix(GDB-11838) Require ROLE_REPO_MANAGER for GraphQL Endpoint Management

- src/css/graphql/import-endpoint-definition-modal.css
- src/js/angular/graphql/controllers/import-endpoint-definition-modal.controller.js
- src/js/angular/graphql/templates/modal/import-endpoint-definition-modal.html
- test-cypress/integration/graphql/import-graphql-endpoint-definitions.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
* Allow files to be added or removed from the selected file list in the import dialog after the upload has finished. 
* Made the drop area in the import dialog bigger so that drag and drop to easier.
This ensures better user experience with the import dialog.
Reorganized the drop area in the dialog so that it's bigger and to allow files to be easily dropped regardles if in the area might have other files already.
Also removed the condition from the remove file button in order to allow files to be removed in every state except during import.
Removed the logic for resetting the selected file list on the next selection after import has been completed.
Extended tests.
NA
> GDB-11808 improve the import definition dialog layout and behavior

- src/js/angular/models/graphql/graphql-endpoint-configuration.js
When creating from OWL and `use all graphs` option is selected then we should not send all found graphs with the request but empty array.
The backend has logic that can handle this scenario and releave the client from the need to build and send potentially big requests if there tousands or even million graphs in the repository.
Added a check when the request payload is prepared to handle the case when the `use all graphs` option is selected and pass an empty array instead of listing all graphs.
NA
NA
> GDB-11575 don't send all graph when creating from OWL

- src/css/repositories.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- src/pages/repository.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/repository/repositories.spec.js
Allow repository ID to be changed, whenever it is in a cluster
Previously the backend didn't allow it. Now it is possible
- Removed the tooltip and styling, which didn't allow the user to click edit.
- Removed labels, associated with the disabling functionality.
- Removed cypress tests, which checked the functionality
removed existing, since they are not needed
> GDB-11745 Enable repositori rename in cluster

- src/js/angular/graphql/plugin.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/steps/setup/user-and-access-steps.js
- test-cypress/support/repository-commands.js
- test-cypress/support/security-command.js
- test-cypress/support/user-commands.js
- Introduce new Cypress commands (loginAsAdmin, switchOffSecurity, switchOffFreeAccess) that capture and reuse the Authorization header.
- Update user, repository, and security commands to pass the admin token in requests.
- Adjust tests to use the new commands and reduce repetitive cleanup logic.
- We need a standardized way to authenticate and manage security features in our Cypress tests.
- Added loginAsAdmin to capture the Authorization token from the response and store it in Cypress.env.
- Reworked existing commands (switchOffSecurity, switchOffFreeAccess, etc.) to use the stored token.
> fix(GDB-11838) Add Cypress admin login & free access toggle commands

- src/css/bootstrap-graphdb-theme.css
- src/css/graphql/create-graphql-endpoint.css
- src/css/graphql/graphql-endpoint-management.css
- src/css/graphql/graphql-playground.css
- src/css/wizard.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/graphql/controllers/create-graphql-endpoint-view.controller.js
- src/js/angular/graphql/directives/generate-endpoint.directive.js
- src/js/angular/graphql/models/endpoints.js
- src/js/angular/graphql/services/graphql-context.service.js
- src/js/angular/graphql/templates/create-graphql-endpoint.html
- src/js/angular/graphql/templates/graphql-endpoint-management.html
- src/js/angular/graphql/templates/step-generate-endpoint.html
- src/js/angular/models/graphql/wizard.js
* Align endpoint links list with the heading above it
* Allow going back in the workflow by clicking on the wizard's step handlers.
* Remove the forward slash from the endpoint urls used for navigation between views to prevent issues when WB works behind context path.
* When generation is complete, hide the Create button and show the Finish button which opens the management view.
* Removed the info message that used to appear after the endpoint generation and changed the info text appearing before the generation in the overview panel.
* Graphiql playground was restyled to better fit the workbench look and feel.
To boost the UX
--
NA
> GDB-11854 graphql view ux improvements

- src/js/angular/controllers.js
- src/js/angular/core/directives/cookie-policy/cookie-consent.directive.js
- src/js/angular/core/directives/cookie-policy/cookie-policy-modal-controller.js
- src/js/angular/core/services/tracking/tracking.service.js
- src/js/angular/security/controllers.js
- src/js/angular/security/controllers/user-settings.controller.js
- src/js/angular/settings/controllers.js
- src/js/angular/utils/local-storage-adapter.js
- Ensures that local storage is used properly for free-access users.
- Updates the TrackingService to read from local storage or backend consistently, depending on the access mode
- Cookie handling was not working in freaa access mode.
- Removes the internal getCookieConsent() call in the CookiePolicyModalController and injects the same instance from the directive
- Ensures that isTrackingAllowed() and getCookieConsent() are used consistently in TrackingService, and re-initializes tracking when user consent updates.
- Adds LSKeys.COOKIE_CONSENT as a known local storage key and leverages LocalStorageAdapter appropriately.
> fix(GDB-11795) Fix cookie saving in free access mode

- src/pages/repository.html
- test-cypress/integration/repository/repositories.spec.js
Disable entity index size in edit repository mode
It should be allowed only, when creating a repository
Added `ng-disable` to the form field, whenever the form is in edit mode
cypress
create repo: 
edit repo:
> GDB-11245 Disable entity index size in edit mode

- src/js/angular/import/directives/validate-uri.directive.js
- src/js/angular/import/templates/settingsModal.html
- src/js/angular/import/templates/urlImport.html
- test-cypress/integration/import/import-server-files.spec.js
- test-cypress/integration/import/import-user-data-url.spec.js
- test-cypress/steps/import/import-settings-dialog-steps.js
- test-cypress/steps/import/import-steps.js
- test-cypress/steps/import/import-user-data-steps.js
Cannot import file(s) if the "JSON-LD context" field is marked as dirty and empty.
The input is validated using the validate-uri directive, but an empty string is not a valid URI. As a result, the directive marks the input as invalid.
Added a check to the validate-uri directive to skip validation if the field is empty. Validating whether the field is empty is the responsibility of other functionality that checks for required fields
> GDB-11416: JSON-LD Context field should allow empty

- test-cypress/integration/graphql/activate-deactivate-graphql-endpoint.spec.js
- test-cypress/integration/graphql/edit-graphql-enpoint.spec.js
- test-cypress/support/import-commands.js
Fix graphql cypress tests data provisioning.
Most of the tests required provisioning of some test data whiich was done through the `/soml` API that is now removed.
Updated cypress commands used for importing endpoint definitions to use the new import API.
> Fix graphql cypress tests data provisioning

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/lib/d3-tip/d3-tip.css
- test-cypress/fixtures/locale-en.json
Visual Graph View node types overflow the tooltip container when hovering over a node.
A maximum height of 30px was set on the tooltip container.
The max-height constraint has been removed.
- The old implementation separated node types using a middle dot (·), but when the tooltip was opened, all types appeared one after another, making them hard to read. This has been refactored so that each type now appears on a separate line within the tooltip.
- Added a translation for the "No types" label, which was previously hardcoded.
N/A
before:
after:
> GDB-11292: Visual Graph View types for nodes are overflowing when hovering a node

- src/js/angular/backup-and-restore/plugin.js
- src/js/angular/guides/plugin.js
- test-cypress/integration/setup/user-and-access.spec.js
- Removed the Backup & Restore and User Guides menu items from basic users by restricting them to users with the ROLE_REPO_MANAGER role.
The Backup & Restore view always returns a restricted message for basic users, regardless of the active repository
- Updated src/js/angular/backup-and-restore/plugin.js and src/js/angular/guides/plugin.js
> fix(GDB-11028) Remove Backup & Restore and User Guides views for basic users

- src/app.js
- src/css/graphs-vizualizations.css
- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
- src/js/angular/utils/html-util.js
- src/pages/graphs-visualizations.html
- test-cypress/integration/explore/visual-graph/visual-graph-node-labels.spec.js
- test-cypress/steps/visual-graph-steps.js
- test-cypress/utils/html-util.js
The node label did not break into a new line, even when containing '\n' or '&lt;br&gt;'.
The node label was originally implemented to display text, which is why '\n' and '&lt;br&gt;' did not work as expected.
Enhanced the visual graph functionality to allow node labels to span multiple lines. We use the D3.js library for graph visualization. Previously, the node label was implemented using the "text" function. This has been changed to "html", allowing the label to be displayed across multiple lines. During label processing, all HTML tags are removed, and the \n character is replaced with &lt;br&gt;.
Summary: Node labels now support multiline visualization using the \n character.
Removed the function that processed the ellipsis for long node labels and replaced it with CSS declarations, …
> GDB-10914: allow line break in VizGraph "Node Basics"

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
Fix relative path to graphql endpoint management view so that they can open correctly when GDB is working behind context path different from the base `/`
When a relative path in the web application starts with a `/`, then it can't be properly forwarded by the reverse proxy, hence the 404 we are seeing in such cases.
Removed the forward slash from the link that opens the endpoint managament view.
NA
NA
> GDB-11858 fix relative path to graphql endpoint management view

- src/css/graphql/graphql-playground.css
* Move the create tab button on the left when there aren't any tabs yet.
* Removed the all around padding from the bottom toolbar to reduce the taken space and make it more consistent with the rest elements in the playground.
* Made the toggle button of the variables and headers widgets in the bottom to look the primary color on hover as the rest of the buttons.
.
.
.
> GDB-11854 improve styling of buttons in playground

- src/css/graphql/graphql-playground.css
Certain background elements in the GraphQL Playground remain dark even when the workbench is set to light mode, provided the OS is in dark mode.
This issue comes from the GraphQL playground component, which automatically switches to dark mode when the OS theme is set to dark.
Add a CSS rule to ensure the background color aligns with the workbench settings.
N/A
before
after
> GDB-11920: GraphQL playground looks bad when OS theme is set to dark.

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/filters/bytes-filter.js
- src/js/angular/import/controllers/import-view.controller.js
- src/js/angular/utils/file-utils.js
- src/pages/import.html
Fix broken file upload, when maxUploadSize is less than 1MB
File upload wasn't working
Previously the maxUploadSize bytes were converted into integer MB. That value was also added as `ngf-max-size` to the import. Values, which were less than 1MB resulted in 0 as max value, hence nothing was allowed. Now the exact `maxUploadSize` value is used to set `ngf-max-size` and the value is converted into a readable label only for display purposes
existing
exceeded size
within boundaries
> GDB-11722 Fix broken file upload when maxUploadSize is less than 1MB

- packages/api/src/models/monitoring/operation-group-summary.ts
- packages/api/src/models/monitoring/operation.ts
- packages/api/src/services/monitoring/mapper/test/operation-group-summary-list.mapper.spec.ts
- packages/api/src/services/monitoring/mapper/test/operation-list.mapper.spec.ts
- packages/api/src/services/monitoring/mapper/test/operation-summary-mapper.spec.ts
- packages/api/src/services/monitoring/monitoring.service.ts
Fix blinking dropdown menu of operations notification
It shouldn't be blinking
Changed the ids(keys) of the operations and operation groups to be a summary of their contents. This way when, we have identical results, stencil won't re-render elements. It will reuse them instead
none
none
> GDB-11318 Fix blinking dropdown menu of operations notification

- packages/root-config/src/styles/partials/_core.scss
- packages/root-config/src/styles/partials/responsive/_responsive.scss
- packages/shared-components/cypress/e2e/header/header.cy.js
- packages/shared-components/cypress/e2e/user-menu/user-menu.cy.js
- packages/shared-components/cypress/steps/header/header-steps.js
- packages/shared-components/cypress/steps/user-menu/user-menu-steps.js
- packages/shared-components/global.d.ts
- packages/shared-components/src/assets/i18n/en.json
- packages/shared-components/src/assets/i18n/fr.json
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-header/onto-header.tsx
- packages/shared-components/src/components/onto-header/readme.md
- packages/shared-components/src/components/onto-layout/readme.md
- packages/shared-components/src/components/onto-user-menu/onto-user-menu.scss
- packages/shared-components/src/components/onto-user-menu/onto-user-menu.tsx
- packages/shared-components/src/components/onto-user-menu/readme.md
- packages/shared-components/src/components/translate-label/readme.md
- packages/shared-components/src/index.html
- packages/shared-components/src/models/single-spa/single-spa.ts
- packages/shared-components/src/pages/header/index.html
- packages/shared-components/src/pages/user-menu/index.html
- packages/shared-components/src/pages/user-menu/main.js
- packages/shared-components/src/utils/routing-utils.ts
Implement user menu component inside the header
To have visibility of logged-in user, as well as settings and logout
Created `onto-user-menu` component, which displays a button with the currently logged-in user. The component will be displayed, when security is on, and there is an authenticated user When clicked, it shows a dropdown with `My-settings` and `Logout` options. The logout is currently not implemented When an external user is logged, there is no logout option The header is subscribed to changes for user and security configuration, and determines, weather to display the new component
cypress
> GDB-11317 Implement user menu

- packages/shared-components/src/components/onto-dropdown/onto-dropdown.scss
- packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
- packages/shared-components/src/components/onto-language-selector/onto-language-selector.scss
- packages/shared-components/src/components/onto-operations-notification/onto-operations-notification.scss
Fix the scaling of buttons inside the header, whenever the screen width is less than 1439px.
This doesn't include making the header entirely responsive. There are still issues with that
It wasn't working correct for all buttons
Removed @media queries from the language selector and repository selectors. They will use the global one. Added smooth transition for the scaling to all buttons Changed `span` to `i` tag in `onto-dropdown` as it was styling the button icon slightly differently
nont, as it is only styling
> GDB-10490 Fix header buttons scaling

- packages/shared-components/cypress/e2e/tooltip/tooltip.cy.js
- packages/shared-components/cypress/steps/tooltip-steps.js
- packages/shared-components/src/components/onto-tooltip/onto-tooltip.tsx
- packages/shared-components/src/pages/tooltip/index.html
- packages/shared-components/src/pages/tooltip/main.js
Add functionality to remove existing tooltip, when its target element has been removed from the dom
Because currently, when an element, which has a tooltip is removed, the tooltip stays visible
Added a mutation observer, which listens to changes in the body and monitors removed nodes. When a node is removed, it is checked to see, if it has a tooltip. If a tooltip is present, it is destroyed.
cypress
before: 
after:
> GDB-11267 destroy tooltip on node removal

- webpack.config.common.js
When creating a Cluster or editing its nodes, the styles in the dialog will load correctly.
Some styles in the Cluster create/edit dialog were not loaded correctly. This was due to one of the stylesheets not resolving its version correctly.
I updated the webpack config.
N/A
N/A
> GDB-12002 - add replaceVersion for cluster management templates

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- test-cypress/fixtures/locale-en.json
When renaming a repo, the user won't see the cluster renaming part of the warning.
Necessary changes were made in the BE for repo renaming in cluster to happen without user interaction.
I removed the label from the language files and the controller.
N/A
Old:
New:
> GDB-12032 - Remove old repo rename warning

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/repositories/controllers.js
- test-cypress/fixtures/locale-en.json
When renaming a repo, the user won't see the cluster renaming part of the warning.
Necessary changes were made in the BE for repo renaming in cluster to happen without user interaction.
I removed the label from the language files and the controller.
N/A
Old
New:
> (cherry-pick) GDB-12032 - Remove old repo rename warning

- Jenkinsfile
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/templates/autocomplete-iri-discovery-search.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/ttyg/edit-agent.spec.js
The `Autocomplete IRI method` in TTYG will be hidden. A missing label has been added. The `Search predicates` field was removed.
The method is not finalized for release.
I commented out the template from `ExtractionMethodTemplates`.
One test for the method skipped.
> GDB-12015 - Hide autocomplete IRI discovery method in TTYG

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
Fixes a typo in the property key readShaclPropertiesLabels → readShaclPropertyLabels in English and French i18n files and test fixtures.
The incorrect property name readShaclPropertiesLabels was being used in the i18n files. However, the correct property used in the public REST API and the SomlOntology is readShaclPropertyLabels.
Renamed all occurrences of readShaclPropertiesLabels to readShaclPropertyLabels
> fix(GDB-12088) Correct SHACL property label key to match API contract

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
Fixes a typo in the property key readShaclPropertiesLabels → readShaclPropertyLabels in English and French i18n files and test fixtures.
The incorrect property name readShaclPropertiesLabels was being used in the i18n files. However, the correct property used in the public REST API and the SomlOntology is readShaclPropertyLabels.
Renamed all occurrences of readShaclPropertiesLabels to readShaclPropertyLabels
cherry-pick from 124f49e8d6f12ffd4d7b6a04576f2bba6966ea16
> fix(GDB-12088) Correct SHACL property label key to match API contract 3.0

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/explore/visual-graph/visual.graph.spec.js
Improve the grammar of the overview sentences displayed before creating a GraphQL endpoint.
N/A
> GDB-12029: Fix grammar of sentence on GraphQL endpoint creation screen

- src/js/angular/models/monitoring/query-and-update/monitoring-track-record-state.js
- src/js/angular/models/monitoring/query-and-update/monitoring-track-record-type.js
- src/js/angular/models/monitoring/query-and-update/monitoring-track-record.js
- src/js/angular/queries/controllers.js
- src/pages/monitor/queries.html
Enhanced the GraphDB Workbench to support appropriate file extensions when downloading running queries from the Queries Monitoring tab.
With the introduction of GraphQL functionality, the list of possible query types has expanded to include "GRAPHQL". When the download button is clicked for such queries, the downloaded file should have a .json extension. Currently, all files are downloaded with a .rq extension, which is incorrect for GraphQL queries.
Updated the logic to dynamically determine the file extension based on the type of the executed query.
N/A
N/A
> GDB-11944: Support Different File Types for Downloading Running GraphQL Queries

- src/css/graphql/graphql-playground.css
- Removes the inner scroll from the GraphiQL Explorer plugin, since the parent container with the class "graphiql-plugin" already provides scrolling;
- Styled the buttons and dropdowns to align with the Workbench design.
- Added a separate horizontal scroll for all containers that hold queries/mutations.
- The parent container already has vertical scroll enabled, which made the inner scroll unnecessary and created visual issues (e.g., a scroll area with no visible scrollbar);
- The buttons and dropdowns looked inconsistent with those used in the Workbench.
- Set overflow: hidden on the container to remove the unnecessary scroll.
- Applied styling consistent with the Workbench. Some CSS declarations use !important due to inline styles applied by GraphiQL Playground.
N/A
<p>
<div>Remove …
> GDB-12006: GraphiQL pop-up menu's text is much too large

- src/js/angular/resources/chart-models/performance/connections-chart.js
- src/js/angular/resources/chart-models/performance/epool-chart.js
- src/js/angular/resources/chart-models/performance/queries-chart.js
When filtering the Monitoring charts, the axis will show the correct ranges, without cutting off a part of the data.
The y-axis names will not overlap long tick labels.
No value was passed in for the multiplier and the wrong function parameter was used to calculate the y-axis max value. Hence, the y-axis max value would reset to 1 when the chart data was toggled.
I made sure the function receives the multiplier value where it is expected.
I added a bigger gap between the axis name and the tick label.
N/A
> (cherry-pick) GDB-11287 - Fix chart axis resetting when using chart filters

- docs/developers-guide.md
- packages/api/src/interceptor/auth/auth-request-interceptor.ts
- packages/api/src/interceptor/auth/test/auth-request-interceptor.spec.ts
- packages/api/src/interceptor/interceptors.ts
- packages/api/src/models/common/model-list.ts
- packages/api/src/models/http/http-request.ts
- packages/api/src/models/interceptor/http-interceptor.ts
- packages/api/src/services/http/http.service.ts
- packages/api/src/services/http/test/http.service.spec.ts
- packages/api/src/services/interceptor/interceptor.service.ts
- packages/api/src/services/interceptor/test/interceptor.service.spec.ts
Define a structure for HTTP interceptors
To have the ability to pre- and post-process HTTP requests
Created an abstract class, which holds the contract methods of an HTTP interceptor. An interceptor can pre- and post-process a request. To do that, it needs to implement the `preProcess` and/or `postProcess` methods. For those methods to be considered, the interceptor must implement `shouldPreProcess` and `shouldPostProcess`, which will determine, what must be intercepted
Added `interceptor.service`, which chains all `preProcess` and `postProcess`
Interceptors have a priority (number). If an interceptor needs to be executed in a specific order, this can be done, by modifying that property. Interceptors with higher priority are executed first
Modified `http-service` to call the `preProcess` …
> GDB-12117 Define HTTP interceptor structure

- src/css/dynamic-form.css
Added spacing between labels and input values in the second step of the Endpoint Creation wizard.
There was no space between labels and input fields in dynamic form-inline containers, which made the layout hard to read.
The labels and values are rendered using the dynamic-form component, placed inside a container with CSS Grid. A column-gap was added to create proper spacing between the labels and their corresponding input fields.
N/A
<p>
<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
</p>
> GDB-11996: Endpoint Management wizard to have better spacing of elements

- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/explore/visual-graph/visual.graph.spec.js
Improve the grammar of the overview sentences displayed before creating a GraphQL endpoint.
(cherry picked from commit b447a863ae6fe1d7d2d9c177e8e5869588fe791d)
N/A
> Cherry-pick GDB-12029: Fix grammar of sentence on GraphQL endpoint creation screen

- packages/shared-components/src/components/dialogs/onto-cookie-policy-dialog/onto-cookie-policy-dialog.tsx
- packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
Fix flaky tests in dropdown and cookie-consent components
They are flaky
Added catch clauses to promises in those components. When the tests fail, the error which is reported from cypress, points to a non-handled rejected promise. Catch clauses are added to the promises in those components, which should stop the flakiness
cypress
none
> Gdb 11320 fix flaky tests in dropdown and cookie

- src/js/angular/models/monitoring/query-and-update/monitoring-track-record-state.js
- src/js/angular/models/monitoring/query-and-update/monitoring-track-record-type.js
- src/js/angular/models/monitoring/query-and-update/monitoring-track-record.js
- src/js/angular/queries/controllers.js
- src/pages/monitor/queries.html
Enhanced the GraphDB Workbench to support appropriate file extensions when downloading running queries from the Queries Monitoring tab.
With the introduction of GraphQL functionality, the list of possible query types has expanded to include "GRAPHQL". When the download button is clicked for such queries, the downloaded file should have a .json extension. Currently, all files are downloaded with a .rq extension, which is incorrect for GraphQL queries.
Updated the logic to dynamically determine the file extension based on the type of the executed query.
(cherry picked from commit 1e74974507e0964cf29659e91fe7f4fcf5a4a0df)
N/A
N/A
> Cherry-pick GDB-11944: Support Different File Types for Downloading Running GraphQL Queries

- src/css/graphql/graphql-playground.css
- Removes the inner scroll from the GraphiQL Explorer plugin, since the parent container with the class "graphiql-plugin" already provides scrolling;
- Styled the buttons and dropdowns to align with the Workbench design.
- Added a separate horizontal scroll for all containers that hold queries/mutations.
- The parent container already has vertical scroll enabled, which made the inner scroll unnecessary and created visual issues (e.g., a scroll area with no visible scrollbar);
- The buttons and dropdowns looked inconsistent with those used in the Workbench.
- Set overflow: hidden on the container to remove the unnecessary scroll.
- Applied styling consistent with the Workbench. Some CSS declarations use !important due to inline styles applied by GraphiQL Playground.
(cherry picked from …
> Cherry-pick GDB-12006: GraphiQL pop-up menu's text is much too large

- src/css/dynamic-form.css
Added spacing between labels and input values in the second step of the Endpoint Creation wizard.
There was no space between labels and input fields in dynamic form-inline containers, which made the layout hard to read.
The labels and values are rendered using the dynamic-form component, placed inside a container with CSS Grid. A column-gap was added to create proper spacing between the labels and their corresponding input fields.
(cherry picked from commit 0e836992b6e8276782c1437414023ebfd19d03cf)
N/A
<p>
<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
</p>
> Cherry-pick GDB-11996: Endpoint Management wizard to have better spacing of elements

- src/js/angular/models/import/file-formats.js
macOS users will be able to select `.nq.gz` archives from the Import page.
macOS users couldn't select the `.nq.gz` archives from the Import page.
I added the `mime types` and `.gz` extension explicitly. 
Tested on Sequoia 15.3.2. Bug observed before fix. Bug not present after fix.
N/A
> GDB-11916 - Fix nq.gz file not visible on macOS

- packages/root-config/src/index.ejs
- webpack.config.common.js
The "Pivot table" and "Google Chart" plugins in the "SPARQL Query & Update" view are not working.
Both plugins fail to load because they require external resources that were blocked by the current Content Security Policy (CSP).
Updated the Content-Security-Policy directive to include the required external resources for both plugins.
N/A
<p>
</p>
<p>
</p>
> GDB-10684: WB Migration: resolve issues with the ontotext-yasgui custom component

- src/js/angular/import/controllers/import-view.controller.js
When editing and updating an imported `text snipped`, the changes will not be lost.
The update call and the import call sometimes happened before the list updates. This meant that the old file was used and any new changes the user made to the snippet would be lost.
This was a little hard to reproduce, because the update and import actions had to be done very quickly. The solution was to add a list update call after the successful update.
N/A
N/A
> GDB-12078 - Update text snippet correctly after Edit

- src/js/angular/import/controllers/import-view.controller.js
When editing and updating an imported `text snipped`, the changes will not be lost.
The update call and the import call sometimes happened before the list updates. This meant that the old file was used and any new changes the user made to the snippet would be lost.
This was a little hard to reproduce, because the update and import actions had to be done very quickly. The solution was to add a list update call after the successful update.
N/A
N/A
> (cherry pick) GDB-12078 - Update text snippet correctly after Edit

- src/js/angular/models/import/file-formats.js
macOS users will be able to select `.nq.gz` archives from the Import page.
macOS users couldn't select the `.nq.gz` archives from the Import page.
I added the `mime types` and `.gz` extension explicitly.
Tested on Sequoia 15.3.2. Bug observed before fix. Bug not present after fix.
> (cherry-pick) GDB-11916 - Fix nq.gz file not visible on macOS

- src/js/angular/controllers.js
Start the guide if the security is off or if the security is on, start the guide if the user is at least a Repository Manager as guides need to create repositories. The guide will autostart once the user has logged in.
The guides autostart wes not implemented to take into account if security is turned on.
- moved the autostart logic in the on `securityInit` callback. It is called after login or ono load if security is off
- added check if user is Repository manager
- added check to not double start the guide if callback is applied multiple times
> GDB-12107 Fix guide autostart when security is on

- packages/legacy-workbench/src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
The saved queries are loaded successfully but are not displayed in the Yasgui dialog.
The saved queries are passed to Yasgui through the bound property savedQueryConfig. After the queries are loaded, the object is updated, but Yasgui not triggered to re-render.
The queries were previously loaded using Promise.all. This has been changed to use AngularJS $q service, which triggers Angular's digest cycle.
N/A
<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span>
> GDB-10684: Saved queries are not displayed in Yasgui

- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
What
The saved queries are loaded successfully but appear with a noticeable delay in the Yasgui dialog.
Why
The saved queries are passed to Yasgui through the bound property savedQueryConfig. Although the object is updated after loading, Yasgui's re-render is delayed because the AngularJS digest cycle is not triggered immediately. Instead, it's triggered later by a different component, causing the queries to appear slowly.
How
The loading logic was initially implemented using Promise.all, which does not trigger AngularJS’s digest cycle. It has been updated to use Angular's $q service, ensuring the digest cycle runs at the right time and the Yasgui dialog updates promptly.
N/A
N/A
> Saved queries are not displayed in Yasgui immediately

- e2e-tests/e2e-legacy/sparql-editor/actions/execute-query.spec.js
- e2e-tests/e2e-legacy/sparql-editor/actions/expand-results-over-sameas.spec.js
- e2e-tests/e2e-legacy/sparql-editor/actions/include-inferred-statements.spec.js
- e2e-tests/e2e-legacy/sparql-editor/actions/inferred-sameas.spec.js
- e2e-tests/e2e-legacy/sparql-editor/actions/save-query.spec.js
- e2e-tests/e2e-legacy/sparql-editor/actions/show-saved-queries.spec.js
- e2e-tests/e2e-legacy/sparql-editor/saved-query/delete-query.spec.js
- e2e-tests/e2e-legacy/sparql-editor/saved-query/edit-query.spec.js
- e2e-tests/e2e-legacy/sparql-editor/sparql-editor.spec.js
- e2e-tests/e2e-legacy/sparql-editor/yasgui-tabs.spec.js
- e2e-tests/e2e-legacy/sparql-editor/yasr/download-as.spec.js
- e2e-tests/e2e-legacy/sparql-editor/yasr/pagination.spec.js
- e2e-tests/e2e-legacy/sparql-editor/yasr/table-plugin.spec.js
- e2e-tests/e2e-legacy/sparql-editor/yasr/toolbar/visual-graph-button.spec.js
- packages/api/src/models/events/event-name.ts
- packages/api/src/models/events/index.ts
- packages/api/src/models/events/navigation/navigation-start-payload.ts
- packages/api/src/models/events/navigation/navigation-start.ts
- packages/legacy-workbench/src/js/angular/sparql-editor/controllers.js
- packages/root-config/src/ontotext-root-config.js
The old workbench has functionality to ask the user for confirmation when attempting to leave the "SPARQL Query & Update" view while at least one query or update is still running. This functionality works when navigating to the view via the main menu, but it stops working if the page is refreshed while on the view.
When leaving the view, the Yasgui component instance is used to check for ongoing queries or updates. Yasgui is a web component built using the Stencil framework and uses the disconnectedCallback lifecycle hook to clean up when destroyed. In the failing scenario, there's a difference in the order of event listeners — the disconnectedCallback is triggered before AngularJS's $locationChangeStart, which means Yasgui is already destroyed before the check for ongoing queries/updates …
> GDB-10684: Fixes issue with the confirmation dialog

- packages/api/src/models/context/before-change-validation-promise.ts
- packages/api/src/models/context/test/value-context.spec.ts
- packages/api/src/models/context/value-context.ts
- packages/api/src/services/context/context.service.ts
- packages/api/src/services/context/test/context.servce.spec.ts
- packages/api/src/services/language/language-context.service.ts
- packages/api/src/services/language/test/language-context.service.spec.ts
- packages/legacy-workbench/.editorconfig
- packages/legacy-workbench/src/js/angular/sparql-editor/controllers.js
- packages/legacy-workbench/src/js/angular/sparql-template/controllers.js
Display confirmation dialog when changing the language on the SPARQL view
Since the page must be reloaded in order to change the language, the user might lose data about running queries in the SPARQL editor
- defined a new `BeforeChangeValidationPromise` function which takes a value and returns a Promise which resolves to a boolean
- added an array of `BeforeChangeValidationPromise` in `ValueContext` to hold validation functions
- refactored `subscribe` method of `ValueContext` to accept validation functions and also to remove them in the unsubscribe function
- added a new async method `canUpdate` in `ValueContext` which calls the validation functions and returns true if they all resolve to true or false if some resolves to false or if the promise is rejected
- added a new method …
> GDB-12152 Display confirmation dialog when changing the language on in SPARQL view

- src/js/angular/controllers.js
When a `GQL Read only` user opens the homepage, there will be no `toast` message with a Namespace error. 
The error would appear, because the user does not have rights to call the API. This is expected. The message causes confusion.
I added a `GQL RO` check before the API is called.
N/A
N/A
> GDB-12146 - Prevent namespace API call when GQL RO rights

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
When creating a Visual Graph, typed extra spaces will be removed.
Saving two graphs with names "foo bar" (one space) and "foo  bar" (two spaces), created two graphs called "foo bar", when the second one should have been invalid and rejected.
I clean up the name input from extra spaces when the form is submitted.
N/A
N/A
> GDB-7797 - Remove extra whitespaces from new visual graph names

- src/js/angular/controllers.js
When a GQL Read only user opens the homepage, there will be no toast message with a Namespace error.
The error would appear, because the user does not have rights to call the API. This is expected. The message causes confusion.
I added a GQL RO check before the API is called.
N/A
N/A
> (cherry-pick) GDB-12146 - Prevent namespace API call when GQL RO rights

- src/css/clustermanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
- src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- test-cypress/fixtures/locale-en.json
Several improvements added to cluster create dialog:
- field for new node gets auto-focused;
- current node replace is not allowed;
- added new locations can be removed during cluster creation (exception is the Current node);
- copy functionality added for locations.
The changes improve the user experience.
I extended the existing copy-to-clipboard directive with a custom tooltip for the copy action notification. I added the necessary logic for input focus of the dynamic fields.
N/A
Cluster creation
https://github.com/user-attachments/assets/c438e6c7-acbf-4ff2-9646-6bac92521733
> GDB-11955 - Introduce cluster Create dialog improvements

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
When creating a Visual Graph, typed extra spaces will be removed.
Saving two graphs with names "foo bar" (one space) and "foo bar" (two spaces), created two graphs called "foo bar", when the second one should have been invalid and rejected.
I clean up the name input from extra spaces when the form is submitted.
N/A
N/A
> (cherry-pick) GDB-7797 - Remove extra whitespaces from new visual graph names

- src/css/clustermanagement.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
- src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
- src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- test-cypress/fixtures/locale-en.json
Several improvements added to cluster create dialog:
- field for new node gets auto-focused;
- current node replace is not allowed;
- added new locations can be removed during cluster creation (exception is the Current node);
- copy functionality added for locations.
The changes improve the user experience.
I extended the existing copy-to-clipboard directive with a custom tooltip for the copy action notification. I added the necessary logic for input focus of the dynamic fields.
N/A
Video in MR for Master branch - https://github.com/Ontotext-AD/graphdb-workbench/pull/1926
> (cherry-pick) GDB-11955 - Introduce cluster Create dialog improvements

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Pressing the arrow keys, while in the Save Graph modal, will not cause the graph in the background to rotate.
The event was propagated and while the cursor moved in the Name input field, the graph in the background also rotated.
I check if the modal is open and stop the event propagation. I added a modal counter to handle the case when the existing instance is restarted and the close flag is reset too early.
N/A
N/A
> GDB-7796 - Stop key press propagation from modal to graph

- .github/pull_request_template.md
- Jenkinsfile
- docker-rootfs/etc/nginx/conf.d/default.conf
- package.json
- release.Jenkinsfile
- scripts/copyfiles.js
- scripts/license-report.js
- test-cypress/cypress.config.js
- test-cypress/integration/home/cookie-policy.spec.js
- test-cypress/integration/setup/user-and-access.spec.js
- test-cypress/plugins/index.js
- Migrated the main Jenkinsfile to run on the new Jenkins
- Migrated the main Jenkinsfile to use the shared ontotext-platform@v0.1.49 library
- Introduced a new release.Jenkinsfile for handling npm package publishing
- Moved pull_request_template.md to .github/ for proper GitHub PR template support
- Replaced external license-checker CLI usage with custom scripts/license-report.js and scripts/copyfiles.js
- Added validate-translations as an npm script
To unify and standardize CI/CD pipelines across Ontotext projects
- Rewrote the Jenkinsfile to use new structure: shared ontotext-platform library, declarative stages, dockerCompose helpers, Sonar error handling, secrets via KSM
- Introduced a new release.Jenkinsfile that builds, tags, and publishes npm packages, with optional Slack …
> feat(GDB-11897) Migrate pipelines to new Jenkins 2.8

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Pressing the arrow keys, while in the Save Graph modal, will not cause the graph in the background to rotate.
The event was propagated and while the cursor moved in the Name input field, the graph in the background also rotated.
I check if the modal is open and stop the event propagation. I added a modal counter to handle the case when the existing instance is restarted and the close flag is reset too early.
> (cherry-pick) GDB-7796 - Stop key press propagation from modal to graph

- src/css/ttyg/agent-list.css
- src/css/ttyg/agent-select-menu.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/agents.js
- src/js/angular/ttyg/directives/agent-select-menu.directive.js
- src/js/angular/ttyg/services/agents.mapper.js
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/agent-select-menu.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/agent/get-agent-list-with-incompatible-agents.json
- test-cypress/integration/ttyg/agent-list.spec.js
- test-cypress/integration/ttyg/agent-select-menu.spec.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
- test-cypress/stubs/ttyg/ttyg-stubs.js
Added restrictions on interactions with agents:
- Restricted actions for incompatible agents: If an agent is not compatible with the currently running version of GraphDB, it can only be deleted;
- Restricted agent selection: Incompatible agents cannot be selected or used.
Agent implementations can vary between GraphDB versions, which may lead to issues due to differences in features or protocol changes. The agent model returned from the backend is now extended with a new field, compatibility, which determines whether a given agent is compatible with the currently running instance of GraphDB.
- Restricted the available actions in the agent action menu. For incompatible agents, only the Delete button is displayed;
- Disabled the ability to select incompatible agents as active. Such agents …
> GDB-12302: List and disable agents incompatible with TTYG version

- src/css/clustermanagement.css
The error text in the Cluster create/edit dialog will be slightly larger.
QA reported error message was too small.
Font size changed and duplicate declaration was removed.
N/A
Before:
Now:
> GDB-11955 - Increase error text size in create/edit cluster info

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Added name normalization to another screen for creating a Visual Graph.
Putting extra spaces in the name would create graphs with the same name, because the spaces get removed after creation and the duplication is not captured.
I clean up the name input from extra spaces when the form is submitted. This is done in the "Create" and "Save as new..." dialog.
N/A
The view in question:
> GDB-7797 - Add string normalization to visual graph save dialog

- src/css/editable-content.css
- src/css/markdown-content.css
- src/css/ttyg/chat-panel.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/core/directives/editable-content/editable-content.js
- src/js/angular/core/directives/markdown-content/markdown-content.js
- src/js/angular/core/templates/editable-content/editable-content.html
- src/js/angular/core/templates/markdown-content/markdown-content.html
- src/js/angular/guides/steps/complex/ttyg/ask-ttyg-agent/plugin.js
- src/js/angular/ttyg/directives/chat-panel.directive.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- src/js/angular/ttyg/templates/chat-panel.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/ttyg/chat-panel.spec.js
- test-cypress/integration/ttyg/create-chat.spec.js
- test-cypress/steps/ttyg/chat-panel-steps.js
Extend the question input to support inserting a new line when pressing Shift+Enter.
Users want to be able to insert a new line character in the prompt using Shift+Enter, without triggering the LLM.
- Implement a new editable-content directive that provides this functionality using the contenteditable attribute;
- Update the new question input to use the editable-content directive.
> GDB-11393: Shift+Enter to go to a new line without prompting the LLM should be supported

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Added name normalization to another screen for creating a Visual Graph.
Putting extra spaces in the name would create graphs with the same name, because the spaces get removed after creation and the duplication is not captured.
I clean up the name input from extra spaces when the form is submitted. This is done in the "Create" and "Save as new..." dialog.
N/A
The view in question:
> (cherry-pick) GDB-7797 - Add string normalization to visual graph save dialog

- src/js/angular/repositories/controllers.js
- src/js/angular/repositories/ontop-repo.directive.js
- src/js/angular/rest/repositories.rest.service.js
When creating a repository on a remote location, the parameter for location will be sent, whenever an attached file is edited.
File fields in question:
The `location` parameter was not sent and the back-end couldn't perform the necessary validations.
I pass in the location to the `Edit controller`, so that it can use it when calling the `Rest service`. When the location is "Local", an empty string is sent, which is handled in the BE.
N/A
Location is remote:
Location is local (empty string):
> (cherry-pick) GDB-12201 - Send missing location param to "/file" endpoint

- src/css/ttyg/chat-item-details.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/models/ttyg/chat-answer.js
- src/js/angular/models/ttyg/chat-message.js
- src/js/angular/models/ttyg/token-usage-info.js
- src/js/angular/ttyg/directives/chat-item-detail.directive.js
- src/js/angular/ttyg/services/chat-message.mapper.js
- src/js/angular/ttyg/templates/chat-item-detail.html
- test-cypress/fixtures/locale-en.json
- test-cypress/fixtures/ttyg/chats/ask-question.json
- test-cypress/fixtures/ttyg/chats/get-chat.json
- test-cypress/integration/ttyg/chat-panel.spec.js
- test-cypress/steps/ttyg/ttyg-view-steps.js
Added a visualisation showing the number of response tokens used by the LLM.
Users need to know how many response tokens were consumed to better understand the cost of the response.
A new button was added between the "Copy answer" and "Explain response" buttons. When the user hovers over this button, a popup appears displaying information about the tokens used in the response.
##
> GDB-11469: UI visualization of LLM response tokens used

- src/js/angular/resources/chart-models/performance/epool-chart.js
The "Reads" label in the Entity pool chart will be closer to the axis.
It was cut off slightly by the navigation menu.
I edited the gap in the configuration.
N/A
Before:
After:
> GDB-11287 - Reposition Entity pool chart axis label to make it more visible

- src/js/angular/resources/chart-models/performance/epool-chart.js
The "Reads" label in the Entity pool chart will be closer to the axis.
It was cut off slightly by the navigation menu.
I edited the gap in the configuration.
N/A
Before:
After:
> (cherry-pick) GDB-11287 - Reposition Entity pool chart axis label to make it more visible

- package.json
- packages/api/src/services/context/context.service.ts
- packages/api/src/services/context/test/context.servce.spec.ts
- packages/api/src/services/language/language-context.service.ts
- packages/api/src/services/language/test/language-context.service.spec.ts
- packages/api/src/services/repository/repository-context.service.ts
- packages/legacy-workbench/src/i18n/locale-en.json
- packages/legacy-workbench/src/i18n/locale-fr.json
- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
- packages/legacy-workbench/src/js/angular/jdbc/controllers.js
- packages/legacy-workbench/src/js/angular/similarity/controllers/create-index.controller.js
- packages/legacy-workbench/src/js/angular/sparql-template/controllers.js
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
- scripts/clean-locks.sh
- scripts/clean.sh
- scripts/install-local.sh
Fixed showing confirmation dialog when changing repositories with unsaved data in edit views, replacing the legacy event system with the new RepositoryContextService.
Users need to be warned before losing unsaved changes when switching repositories. This migration restores critical functionality from the old Workbench to prevent accidental data loss in edit modes for SPARQL Templates, SQL Table Configuration, and Similarity Index views.
- Replaced `EventEmitterService`'s `repositoryWillChangeEvent` with `RepositoryContextService`'s `onSelectedRepositoryIdChanged`
- Added validation callbacks to repository change handlers that return a confirmation modal which resolves to true if ok and false if not ok to change repository
- updated context service to separate validation from update …
> GDB-12151 Fix confirmation dialog for repository changes with unsaved data

- packages/shared-components/src/components/onto-language-selector/onto-language-selector.tsx
- packages/shared-components/src/components/translate-label/translate-label.tsx
Fixes an issue where the language selector does not reflect the selected language after navigating to a new route.
Previously, the language selector’s internal state was initialized only in the constructor, which is not re-invoked on route changes. As a result, when the language was changed post-routing, the selector did not update
- Moved initialization logic from the constructor to connectedCallback() in both TranslateLabel and OntoLanguageSelector components to ensure proper setup on each mount.
- Replaced redundant service retrieval with readonly properties directly initialized from ServiceProvider.
- Ensured fallback to default language when no language is selected.
> fix(GDB-12315): Fix language selector not updating after route change

- package-lock.json
- package.json
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/rest/mappers/saved-query-mapper.js
- src/js/angular/rest/sparql.rest.service.js
- test-cypress/integration/sparql-editor/saved-query/edit-query.spec.js
- test-cypress/support/sparql-commands.js
When a user edits a saved query, they will be able to edit the name without getting an error.
Previously, only editing the body of the query was possible, because the BE searches for them by name.
I added the original query name in the payload, so the BE can process it.  
**Merge should be synced with BE**
> GDB-12134 - Create a new payload for saved query updates

- src/js/angular/controllers.js
If there's no active repository selected, the namespaces won't be fetched.
On login, the `onSelectedRepositoryIdUpdated` call is triggered twice. Once is when the old (before logout) repo is set. The second time happens a second or two after, and the repo is correctly set to what it is, or as not selected. The first call triggers an error toastr to appear in the following scenario:
1. Admin selects a repo to which a GQL read-only user doesn't have rights.
2. Admin logs out.
3. GQL read-only user logs in.
4. Sees toastr error, because the repo selected by the Admin is updated, before the active repo is correctly set on the second call.
Due to the many flows and complexity of these services, I opted for checking if there is an `active repository object`, before the API call for the …
> GDB-12146 - Prevent Namespace error appearing, if there's no active repo

- package-lock.json
- package.json
- src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
- src/js/angular/rest/mappers/saved-query-mapper.js
- src/js/angular/rest/sparql.rest.service.js
- test-cypress/integration/sparql-editor/saved-query/edit-query.spec.js
- test-cypress/support/sparql-commands.js
When a user edits a saved query, they will be able to edit the name without getting an error.
Previously, only editing the body of the query was possible, because the BE searches for them by name.
I added the original query name in the payload, so the BE can process it.
Added, but skipped until BE release a server version with the changes. 
N/A
> (cherry-pick) GDB-12134 - Create a new payload for saved query updates

- packages/api/src/services/utils/routing-utils.ts
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
Fix navigation links not updating upon certain navigations
They are not updated, when a non-reloading navigation is triggered inside the app
- Added a subscription to `navigation-end` inside `onto-navbar`. Whenever a navigation ends, the current route is taken from the URL. It is then used to match the corresponding menu item and select it. If the navigation is towards the home page, then all navbar links are closed and cleared.
- Added `getCurrentRoute` to get the current pathname with removed leading `/`. This is used to match the menu items via href
existing
> GDB-12247 Fix navigation link not updating

- src/js/angular/controllers.js
If there's no active repository selected, the namespaces won't be fetched.
On login, the `onSelectedRepositoryIdUpdated` call is triggered twice. Once is when the old (before logout) repo is set. The second time happens a second or two after, and the repo is correctly set to what it is, or as not selected. The first call triggers an error toastr to appear in the following scenario:
1. Admin selects a repo to which a GQL read-only user doesn't have rights.
2. Admin logs out.
3. GQL read-only user logs in.
4. Sees toastr error, because the repo selected by the Admin is updated, before the active repo is correctly set on the second call.
Due to the many flows and complexity of these services, I opted for checking if there is an `active repository object`, before the API call for the …
> (Cherry-pick) GDB-12146 - Prevent Namespace error appearing, if there's no active repo

- packages/shared-components/src/components/onto-dropdown/onto-dropdown.scss
- packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
- packages/shared-components/src/components/onto-header/onto-header.scss
- packages/shared-components/src/components/onto-language-selector/onto-language-selector.scss
Arrows were missing from the dropdown menus in the page header.
They were not implemented initially because the necessary icons were not available when the components were first introduced.
Arrows have been added to the dropdown menus.
N/A
> GDB-12249: Arrows are missing from dropdown menus in the page header

- src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
Added name normalization to another screen for creating a Visual Graph.
Putting extra spaces in the name would create graphs with the same name, because the spaces get removed after creation and the duplication is not captured.
I clean up the name input from extra spaces when the form is submitted. This is done in the "Create" and "Save as new..." dialog.
The view in question:
> (cherry-pick) GDB-7797 - Add string normalization to visual graph save dialog 

- packages/legacy-workbench/src/js/angular/plugin.js
A temporary navigation link to a test page implemented in the new Angular module is currently present in the navigation bar.
This test link was added for development purposes and is no longer needed in production. It should be removed to clean up the UI and prevent user confusion.
Remove the menu item from the navigation model.
N/A
> GDB-12348: Remove test navigation link to the new Angular page from the navigation bar

- src/css/rdf-class-hierarchy.css
- src/js/angular/graphexplore/controllers/rdf-class-hierarchy.controller.js
- src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
- src/pages/rdfClassHierarchyInfo.html
The active state of the "All graphs" dropdown will be styled like the other dropdowns.
The side panel will not be toggled when a class is selected and the "hide prefixes" toggle clicked.
There was a mismatch in the button styling.
The "hide prefixes" toggle would open and close the info panel, when a class was focused.
I edited the styling and added a flag to track when the panel shouldn't be opened.
N/A
Dropdown style, when open, matches the other dropdowns in the app.
Dropdown closed:
> GDB-12319 - Class hierarchy visual inconsistency and side panel bug

- e2e-tests/e2e-legacy/sparql-editor/actions/inferred-sameas.spec.js
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/root-config/src/bootstrap/autocomplete/autocomplete.js
Fix incorrect value of the autocomplete `enabled` status on application startup
It wasn't set correctly. It's always false on startup, regardless if the selected repository has autocomplete enabled
Made `updateAutocompleteStatus` to be called regardless, if the newly selected repository is the same as the `WorkbenchContextService` repository. The problem is that now, the `onRepositoriesChanged` method is called within a subscription to repositoryIdChange (the migrated context). The new repository context service emits twice on startup (first with undefined and a second time with the actual value).
The first problem is that the first call to `onRepositoriesChanged` has different values for new and old repositories, which sets the context to the new value. When new and old value are the …
> GDB-12338 Fix incorrect legacy autocomplete status on startup

- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
Refactored the onto-repository-selector component to prevent a stack overflow caused by recursive property updates
Previously, the @Watch('items') handler reassigned this.items after modifying it, which retriggered the watcher recursively
- Introduced a private field dropdownItems to hold tooltip items.
- Updated the @Watch('items') handler to assign to dropdownItems instead of items.
> fix(GDB-12246) Fix stack overflow by separating decorated and internal dropdown items

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/js/angular/sparql-template/controllers.js
The RO user will be able to copy the code in `CodeMirror` in the following views:
- SPARQL Template
- Similarity index copy, which leads to Create view
- JDBC SQL table configuration
- Create visual graph config (tabs with editor).
Copying was not allowed in these views, when the user has RO rights.
I changed the `yasqeMode` in the configuration to allow copying.
N/A
N/A
> GDB-12327 - Allow RO user to copy text from Yasqe in different views

- src/js/angular/graphexplore/controllers/graphs-config.controller.js
- src/js/angular/jdbc/controllers.js
- src/js/angular/similarity/controllers/create-index.controller.js
- src/js/angular/sparql-template/controllers.js
The RO user will be able to copy the code in `CodeMirror` in the following views:
- SPARQL Template
- Similarity index copy, which leads to Create view
- JDBC SQL table configuration
- Create visual graph config (tabs with editor).
Copying was not allowed in these views, when the user has RO rights.
I changed the `yasqeMode` in the configuration to allow copying.
N/A
N/A
> (cherry-pick) GDB-12327 - Allow RO user to copy text from Yasqe in different views

- e2e-tests/e2e-legacy/sparql-editor/sparql-page-with-selected-repository.spec.js
- e2e-tests/e2e-legacy/sparql-editor/sparql-page-without-selected-repository.spec.js
- e2e-tests/steps/error-steps.js
- e2e-tests/steps/main-menu-steps.js
Add initial state tests for SPARQL view
To ensure the view starts up correctly with and without selected repository
Added spec files with and without selected repository, which assert the initial state in those cases
cypress
n/a
> GDB-12173 Add initial state tests for SPARQL view

- src/css/rdf-class-hierarchy.css
- src/js/angular/graphexplore/controllers/rdf-class-hierarchy.controller.js
- src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
- src/pages/rdfClassHierarchyInfo.html
The active state of the "All graphs" dropdown will be styled like the other dropdowns.
The side panel will not be toggled when a class is selected and the "hide prefixes" toggle clicked.
There was a mismatch in the button styling.
The "hide prefixes" toggle would open and close the info panel, when a class was focused.
I edited the styling and added a flag to track when the panel shouldn't be opened.
N/A
Dropdown style, when open, matches the other dropdowns in the app.
Dropdown closed:
> (cherry-pick) GDB-12319 - Class hierarchy visual inconsistency and side panel bug

- src/css/ttyg/chat-item-details.css
- src/css/ttyg/chat-panel.css
- src/js/angular/ttyg/templates/chat-item-detail.html
Updated the tokens usage icon in the TTYG conversation UI.
During the sprint demo, feedback was given that the existing icon looked more like a help icon. Based on this feedback, we decided to change it for better clarity.
Replaced the previous icon with the "fa-coin-blank" icon.
Changed the user question to be displayed using the markdown component.
N/A
> GDB-12369: Change the tokens usage icon in TTYG conversation

- src/js/angular/utils/error-utils.js
When an invalid `.pie` file is uploaded, the response will be 422 and the error message will be correctly displayed.
After the BE change, the invalid file would trigger a `toastr` with a "Generic error". The actual error message in the response would be lost.
I extended the `error util` to check for `errorMessage` in the received data object.
N/A
Before:
After:
> (cherry-pick) GDB-12203 - Extend error util

- src/js/angular/ttyg/controllers/ttyg-view.controller.js
When opening links in the `Create Agent` modal, the links will resolve correctly behind a context path.
Links in question:
- Similarity index
- Connectors
- Autocomplete index
Previously, the links would resolve incorrectly and show 404.
I removed the leading `/` in the links.
N/A
> GDB-12372 - Fix 404 links in agent modal

- packages/shared-components/src/components/onto-navbar/onto-navbar.scss
Menu items in the `navbar` will be colored the same.
Menu items in the `navbar` were inheriting the wrong text color.
Added `scss` rules for the link states to override the inherited `bootstrap` rule.
N/A
Before:
After:
> GDB-12385 - Make navbar menu items same color

- packages/root-config/package.json
- packages/root-config/scripts/validate-translations.js
- packages/root-config/test/validate-translations.test.js
- packages/root-config/test/validate-utils.test.js
- packages/shared-components/src/assets/i18n/en.json
Translate french language option in language selector..
For consistency with the legacy workbench.
Updated French language labels in i18n file. Changed the French language label and tooltip text to use French terms ("Français").
> GDB-12399 translate french language option in language selector

- packages/legacy-workbench/src/css/repositories.css
- packages/root-config/src/styles/partials/anchor/_anchor.scss
Remove underline from button links
To be consistent with the legacy workbench
Added a CSS psudo class to not apply anchor styling on `.btn` anchor elements
n/a
> GDB-12395 Remove underline from button links

- packages/legacy-workbench/src/js/angular/graphql/directives/configure-endpoint.directive.js
- packages/legacy-workbench/src/js/angular/graphql/directives/select-schema-sources.directive.js
Fix infinite loading in create graphql endpoint view.
Usage of Promise.all should be avoided in angularjs because the framework knows and uses the $q library to handle promises and although it has similar API as the Promises, it doesn't react properly to this particular expression.
Replaced the `Promise.all` with `$q.all` which is properly handled by angularjs.
> GDB-12421 fix infinite loading in create graphql endpoint view

- e2e-tests/e2e-legacy/home/home-page-without-repositories.spec.js
- packages/shared-components/src/assets/i18n/en.json
- packages/shared-components/src/assets/i18n/fr.json
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
Fixed the repository dropdown text, which didn't change, depending on the availability/absence of repositories
The text should be different, depending on whether there are available repositories or not
Added another `@State` label for `No accessible repositories` and added a condition to switch labels based on the presence/absence of repositories
cypress
> GDB-12388 Fix repository dropdown text not changing

- packages/shared-components/src/components/onto-header/onto-header.scss
Align welcome message with bottom of logo
To be consistent with the legacy workbench
Added padding to the bottom of the header
n/a
> GDB-12394 Align welcome message to bottom of logo

- packages/legacy-workbench/src/js/angular/rest/security.rest.service.js
Added noCancelOnRouteChange: true to the $http.get() call for the getAuthenticatedUser() request in security.rest.service.js.
When a user is not authenticated, the getAuthenticatedUser() endpoint should return a 401, which is handled by jwt-auth.service.js to trigger a redirect to the login page. However, during route changes, AngularJS may cancel pending $http requests, causing this check to be aborted. As a result, the 401 never reaches the catch, and the user is left on a broken page instead of being redirected.
Set noCancelOnRouteChange: true in the $http.get() options to prevent Angular from cancelling the request when navigating between routes. This ensures the 401 response is properly received and handled.
> fix(GDB-12423) Ensure auth check is not cancelled on route change to trigger login redirect

- packages/api/src/models/context/test/value-context.spec.ts
- packages/api/src/models/context/value-context.ts
- packages/api/src/providers/service/lifecycle-hooks.ts
- packages/api/src/providers/service/service.provider.ts
- packages/api/src/providers/service/test/service.provider.spec.ts
- packages/api/src/services/autocomplete/autocomplete-context.service.ts
- packages/api/src/services/context/context-subscription-manager.ts
- packages/api/src/services/context/context.service.ts
- packages/api/src/services/context/index.ts
- packages/api/src/services/context/test/context-subscription-manager.spec.ts
- packages/api/src/services/context/test/context.service.spec.ts
- packages/api/src/services/language/language-context.service.ts
- packages/api/src/services/license/license-context.service.ts
- packages/api/src/services/namespace/namespaces-context.service.ts
- packages/api/src/services/product-info/product-info-context.service.ts
- packages/api/src/services/repository-location/repository-location-context.service.ts
- packages/api/src/services/repository/repository-context.service.ts
- packages/api/src/services/security/security-context.service.ts
- packages/legacy-workbench/src/single-spa-angularjs.js
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-test-context/onto-test-context.tsx
- packages/shared-components/src/components/onto-test-context/readme.md
- Introduced LifecycleHooks interface with onCreated() method.
- Centralized context service registration via ContextServiceRegistry.
- Enabled global context subscriptions using subscribeToAllRegisteredContexts.
- Ensured afterChangeCallback is invoked after main callback.
- Hooked AngularJS $rootScope.$apply() to context changes during mount.
- Unsubscribed automatically on unmount to prevent memory leaks.
- Eliminate tight coupling and manual registration of context services.
- Support reactive cross-cutting logic through lifecycle hooks.
- Trigger AngularJS digest cycles on external context changes.
- Added LifecycleHooks and integrated into ServiceProvider.get.
- Context services self-register via onCreated() into the registry.
- Replaced legacy static subscription utility with …
> feat(GDB-12347): integrate context updates and AngularJS change detection

- packages/root-config/src/bootstrap/autocomplete/autocomplete.js
- packages/root-config/src/bootstrap/bootstrap.js
- packages/root-config/src/bootstrap/repository/repository-bootstrap.js
- packages/root-config/src/ontotext-root-config.js
Fix missing saved repository on startup
Upon bootstrap, a request for autocomplete is made, if there is a saved repository in the local store. That repository might have been deleted at the time of startup. The local store shows a saved repository, which prompts the autocomplete-bootstrap to make a request to `/enabled`. Since the repository doesn't exist, the backend throws an error.
Moved the repository bootstrap functions ahead of all other bootstrap functions. Whenever they are resolved, the rest of the bootstrap functions will be triggered. This way we first get the list of existing repositories and then check to see if the last saved repository still exists.
n/a
n/a
> GDB-12361 Fix missing saved repository on startup

- e2e-tests/package.json
- Added "test": "npm run cy:run-legacy" in e2e-tests/package.json.
- The graphdb-test-functional-cypress module invokes npm test to run the Cypress suite during the GraphDB build process. Without a "test" script defined, the build fails because npm test has no target in e2e-tests.
- Inserted "test": "npm run cy:run-legacy"
> fix(GDB-12483)WBM: add missing test script to prevent GraphDB build failure

- packages/shared-components/src/components/onto-tooltip/onto-tooltip.tsx
Fix RDF search tooltip not closing
During the usage of the workbench, single-spa mounts and unmounts microfrontends at various points. The disconnectedCallback then disconnects the observer, listening for DOM changes, which is responsible for removing tooltips of non-existent elements. Upon reconnect `componentWillLoad` is not called and therefore a new observer is not set up
Changed the node removal handling to be done inside `connectedCallback` instead of `componentWillLoad`.
n/a
> Gdb 12343 fix rdf tooltip not closing when search is opened

- src/js/angular/rest/guides.rest.service.js
Fix autostart of guides when security is on and the connection is slow
The slow connection causes a racing conditions with the login redirect in the workbench, which cancels the guides request.
- added `noCancelOnRouteChange: true` for the guide fetch request so it is not canceled on navigation
N/A
N/A
> GDB-12468: Fix guide autostart with security and slow connection

- packages/legacy-workbench/src/css/import.css
- packages/legacy-workbench/src/pages/import.html
- packages/root-config/src/styles/partials/anchor/_anchor.scss
Remove the anchor styling from active buttons, which contain anchors in them.
Because they were incorrectly styled as links with underline
Added a condition to `_anchor.scss` not to style active links with `.btn` class. Also changed the import RDF button to be `div` instead of `<a>`, since it was styled incorrectly
n/a
> GDB-12450 Remove text underline on active link buttons

- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.scss
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
Fixes layout and logic issues in the repository status tooltip for the repository selector component.
During the migration, visual and logical inconsistencies were introduced in the tooltip showing repository size details. Specifically:
- The tooltip layout lacked spacing between labels and values.
- The logic for showing the expansion ratio was duplicated and could result in confusing output when the explicit value was 0.
- Updated the SCSS to add left margin between the label and value fields within the tooltip rows.
- Refactored the conditional logic that renders the expansion ratio
- Fixed 4 sonarqube issues
> fix(GDB-12403) WB migration: Fix repository status tooltip issues

- packages/legacy-workbench/src/pages/import.html
- packages/root-config/src/styles/partials/anchor/_anchor.scss
The Import page "Server files" and "User data" tabs will be styled like in the legacy WB. All `.nav-link` and `.menu-element-root` will not be styled from the `_anchor.scss`. This includes `.nav-link` tabs in:
- ACL management
- Cluster configuration
- Create similarity index
- Graph explore
- Graph config
- Graph visualizations
- Import
- System info
- JDBC create
- Resources
- RDF rank
The `.menu-element-root`  exception will not underline navbar root items (Import and SPARQL).
The tabs picked up the wrong styling (they were underlined on hover and click).
Added rule exceptions.
N/A
> GDB-12452 - Remove underline on Import tabs

- packages/legacy-workbench/src/js/angular/guides/tour-lib-services/shepherd.service.js
The Workbench crashes when attempting to start a guide.
A SPARQL editor step includes functionality that allows a query to be set in the SPARQL editor by clicking a button displayed in the guide dialog. This button is implemented using AngularJS functionality.
In shepherd.service.js, guide steps are compiled as they are AngularJS templates. After compilation, the scope is expected to be bound to the element. However, after the migration, this functionality broke — the scope of the element is now always undefined.
A temporary check was added to prevent the Workbench from crashing when the scope is undefined. This avoids a hard failure, but the affected copy-to-editor functionality no longer works.
To restore this functionality, it needs to be reimplemented in a way that does not depend on …
> GDB-12484: Clicking on User Guides blocks the entire workbench until refresh

- e2e-tests/cypress.config.js
Updated the specPattern in e2e-tests/cypress.config.js from 'e2e/**/*.{js,jsx,ts,tsx}' to './**/*.{js,jsx,ts,tsx}'.
The previous pattern only matched files under the e2e/ directory, but our Cypress test files now reside in a different folder structure (e.g. e2e-legacy/, integration/, etc.). As a result, Cypress was not detecting any spec files, causing tests to be skipped and CI builds to fail.
Replaced the hardcoded e2e/**/*.{js,jsx,ts,tsx} glob with ./**/*.{js,jsx,ts,tsx}, allowing Cypress to recursively search from the project root for any matching JavaScript/TypeScript test files.
> fix(GDB-12496) WBM: Fix cypress config spec pattern path

- packages/api/src/ontotext-workbench-api.ts
- packages/api/src/services/navigation/index.ts
- packages/api/src/services/navigation/navigation-context.service.ts
- packages/api/src/services/utils/routing-utils.ts
- packages/legacy-workbench/src/js/angular/security/controllers/user-settings.controller.js
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
- packages/shared-components/src/components/onto-navbar/readme.md
Fix sidebar glitching from My Settings menu
It has random glitches, when you select a menu, redirects you to a different menu and page. Also when you visit the My settings mage from the Imports menu and press `Cancel`, it does not redirect you back to `Import`
- Replaced `window.history.back()` with the single-spa native `navigateTo` in `user-settings.controller.js`. Removed the timeout, in which the navigation happened.
- Added `navigation-context.service`, which holds the last url in the application. It is used to navigate to the previously visited page, when `cancel` is pressed. It strips ending `#` symbols from the URL, because single-spa doesn't redirect, when they are present for some reason
- Removed `currentRoute` from `onto-layout`. Whenever single-spa unmounts/mounts …
> GDB-12408 Fix sidebar glitching from My Settings

- packages/api/src/models/license/license.ts
- packages/api/src/services/license/license.service.ts
- packages/api/src/services/license/test/license.service.spec.ts
- packages/legacy-workbench/src/js/angular/core/services/license.service.js
- packages/shared-components/src/components/onto-footer/onto-footer.tsx
- packages/shared-components/src/pages/footer/main.js
- packages/shared-components/src/pages/layout/main.js
Fix missing cookie banner modal
It wasn't showing up, when a license is deleted
- Synchronized the logic, which shows/hides the banner with master. Recent changes, were not propagated to the migration branch and the logic differed.
- Added a subscription to license change in `onto-footer` to recalculate visibility, whenever a license has changed
- Moved `updateGraphdbLicense` from `then` into `finally`, because the license object will be different if the request to the backend returns an error
cypress
> GDB-12432 Fix missing cookie banner modal

- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-repository/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/main-menu/plugin.js
- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
- The "Main Menu" guide step was not working in the migration branch;
- Removed unnecessary calls to the guide.next() function.
- The old navigation bar was replaced with a new one from the shared-components package. The new menu items were missing the guide-selector attribute required by the guide service.
- There was a bug causing elements not to respond to clicks in some steps. After fixing that bug, programmatically calling guide.next() led to the second dialog opening unintentionally.
- Each plugin that describes a navigation bar item provides a guideSelector property, which is added as the guide-selector attribute.
- Removed the redundant call to advance to the next guide step.
N/A
N/A
> GDB-12484: Fixes "main menu" and "create repository" steps

- packages/api/src/models/security/security-config.ts
- packages/api/src/services/security/mappers/test/security-config.mapper.spec.ts
- packages/legacy-workbench/src/js/angular/core/services/jwt-auth.service.js
- packages/shared-components/src/components.d.ts
- packages/shared-components/src/components/onto-header/onto-header.tsx
- packages/shared-components/src/components/onto-user-menu/onto-user-menu.tsx
- packages/shared-components/src/components/onto-user-menu/readme.md
- packages/shared-components/src/pages/user-menu/main.js
Fixed an issue where the logout button was not shown for users authenticated via OpenLDAP, despite the expectation that it should appear
The existing logic to determine whether to display the logout button was incorrectly based solely on the user.external property. However, for externally authenticated users (e.g., via OpenLDAP), a separate config property in jwt-auth.service.js (hasExternalAuthUser) is the reliable source of truth indicating such authentication. Without this fix, users under OpenLDAP couldn't properly log out from the UI.
- Introduced a new hasExternalAuthUser property to SecurityConfig and populated it in jwt-auth.service.js.
- Updated OntoUserMenu to receive securityConfig as a prop.
- Adjusted the logout button condition to check securityConfig.hasExternalAuthUser …
> fix(GDB-12503) WBM: Display logout button for external users based on externalAuthUser flag

- e2e-tests/e2e-legacy/guides/movies-interactive-guide.spec.js
- e2e-tests/e2e-legacy/guides/star-wars-interactive-guide.js
- e2e-tests/steps/main-menu-steps.js
- packages/legacy-workbench/src/js/angular/autocomplete/plugin.js
- packages/legacy-workbench/src/js/angular/graphexplore/controllers/rdf-class-hierarchy.controller.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/select-repository/plugin.js
- packages/legacy-workbench/src/pages/rdfClassHierarchyInfo.html
- Extended the dropdown component with the ability to configure whether it should automatically close when the user clicks outside of it.
- Fixed the "View all <count> instances in SPARQL" link in the right-hand Class Hierarchy info sidebar, which wasn't working.
- Updated all guide steps to function correctly in the migration branch.
- When the guide is on a step that requires selecting a repository, the dropdown must remain open even when the user clicks elsewhere. Otherwise, the dropdown closes and breaks the guide flow.
- The link used a href attribute for navigation, which did not work correctly with the Single-SPA setup.
- When the "Select repository" guide step is active, the dropdown auto-close behavior is disabled. Once the step is completed, auto-close is re-enabled.
- …
> GDB-12484: Interactive guides don't work on the migration branch

- packages/root-config/src/microfrontend-layout.html
- packages/shared-components/src/components/onto-footer/onto-footer.scss
Set `page-content` class on the main slot of the layout
Something caused an overflow and a scroll bar to be visible. Added a `page-content` class as it is in the legacy workbench.
- added `page-content` class to main slot in the layout
- set footer height to 30px as it is in the legacy
n/A
> GDB-12477: Fix ACL management view overflow

- packages/legacy-workbench/src/css/search-resource-input.css
- packages/legacy-workbench/src/js/angular/core/templates/search-resource-input.html
Set correct styling for the search resource input hint font-size
The search resource input used a css which was loaded by another directive which wrapped the SRI. Since this other directive is replaced by an Onto component, it no longer loads the styles.
- extracted the SRI style into its own file and loaded it
n/a
> GDB-12406: Fix search resource input hint font-size

- src/js/angular/controllers.js
When the page loads, if the user has accepted cookies, the banner will not show on the screen at all.
The check for allowed tracking would return before the license was set, causing the cookie banner would appear. Then after the tracking consent returned the correct state based on the license, the banner would disappear.
I delay the tracking consent, if no license is set.
N/A
N/A
> (cherry-pick) GDB-12159 - Fix cookie banner flicker on refresh

- packages/legacy-workbench/src/js/angular/graphexplore/plugin.js
- packages/legacy-workbench/src/js/angular/jdbc/plugin.js
- packages/legacy-workbench/src/js/angular/repositories/plugin.js
- packages/legacy-workbench/src/js/angular/security/plugin.js
- packages/legacy-workbench/src/js/angular/sparql-template/plugin.js
- packages/shared-components/src/components/onto-navbar/navbar-model.ts
- packages/shared-components/src/components/onto-navbar/navbar-service.ts
- packages/shared-components/src/components/onto-navbar/test/navbar-model.spec.tsx
- packages/shared-components/src/components/onto-navbar/test/navbar-service.spec.tsx
Fixed menu to highlight items when their children are selected. Also added logic to match against wildcard hrefs with changing parameters
Menu was left unselected when navigating to any child route
- added parent model to the `NavbarItemModel`
- added methods for adding children and removed the setter to properly add them
- added/changed methods in `NavbarModel` to do stuff recursively
- added logic to match against a wildcard href containing `*`
- changed method in the `NavbarService` to include `ExternalMenuItemModel` children and to set the parent model
- changed some plugin definitions to include correct children
- amended tests to use new methods -
fixed
> GDB-12417: Fix navigation menu to highlight item

- packages/shared-components/src/components/onto-navbar/navbar-model.ts
- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
The menu items with submenus do not respond the first time after opening the Import view.
Steps to reproduce:
1. Open the Import view
2. Click on a menu item with submenus
When clicking on a menu item that has submenus, we expect the submenu to be displayed instead of navigating to another page. However, in the onto-navbar component, we always navigate to the href of the selected item, regardless of whether it's a parent or not. All parent menu items have "#" as their href, and this somehow (possibly due to single-spa) breaks the expected functionality.
Updated the logic to skip navigation if the clicked item is a menu with submenus.
N/A
N/A
> GDB-12543: Sidebar dropdowns briefly not responding after clicking import

- packages/root-config/src/styles/partials/anchor/_anchor.scss
Links in the Nodes tab of the Cluster Management view are underlined even when not hovered.
A CSS declaration sets text-decoration, which overrides the styles defined in the legacy Workbench.
The CSS rule was updated to exclude links in the Nodes tab, preserving the expected appearance.
N/A
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/7f846645-5a3b-4fcf-98fb-3eb08bb61d55) | ![After](https://github.com/user-attachments/assets/ebf514bc-a40a-42ad-829b-29fb287c9716) |
> GDB-12546: Nodes in Cluster Configuration are underlined without mouse hover

- packages/root-config/src/styles/partials/anchor/_anchor.scss
Fixes an incorrect anchor selector.
The [MR](https://github.com/Ontotext-AD/graphdb-workbench/pull/2106) that addresses GDB-12546 introduced an incorrect CSS selector.
Corrects the CSS rule.
N/A
N/A
> GDB-12546: fixing anchor selector

- packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
Fix repository selector popover blocking repository selection
The repo info popover is closed when the dropdown is clicked, so that it does not block the repository selection. There are some cases where this does not happen because of retriggering the tooltip.
- added a timeout with a minimal delay of 50ms so that the state of the repository selector is updated correctly before retriggering the popover
n/a
> GDB-12533: Fix repository selector popover blocking UI

- packages/api/src/models/repositories/repository.ts
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
Fix unnecessary autocomplete `/enabled` check, when the selected repository is deleted
The backend throws an error, since the repository does not exist anymore
Made `updateSelectedRepository` to return the resolved promise of `validatePropertyChange`. Previously, when a repository was deleted, `updateSelectedRepository` was called, but the validations from `validatePropertyChange` happen in a promise, in a separate thread tick. Then `repositoryIsSet` was broadcasted with wrong store data. This caused the application to make a request for autocomplete enabled
n/a
> GDB-12505 Fix enabled request on repository deletion

- packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
- packages/shared-components/src/utils/tooltip-util.ts
Refactored the `onto-dropdown` component to handle tooltip content updates for the dropdown button in a reactive way
The previous implementation directly manipulated the DOM from within an event handler (`onMouseEnter`) to update the tooltip content
The logic for updating the tooltip has been moved from the event handler to the `componentDidUpdate` lifecycle hook.
1.  A reference to the dropdown button element is now captured using `ref` and stored in a class property.
2.  The `onMouseEnter` handler's sole responsibility is now to calculate the new tooltip content and update the component's state via `@State() buttonTooltipContent`.
3.  When the state changes, Stencil re-renders the component. Immediately after the render, `componentDidUpdate` is called.
4.  Inside `componentDidUpdate`, …
> feat(GDB-12506): Refactor tooltip update to use component lifecycle

- e2e-tests/e2e-legacy/import/import-user-data-file-upload.spec.js
- e2e-tests/steps/import/import-steps.js
Fixed and re-enabled the flaky `import-user-data-file-upload.spec.js` end-to-end test suite.
The test suite was disabled due to migration caused issues
- in `import-user-data-file-upload.spec.js`, the `createFile()` call was decoupled from the `selectFile()` call. The file object is now created once and stored in a `const` variable. This constant is then passed to the `selectFile` step.
- re-enabled all tests
- removed commented and obsolete code
> fix(GDB-11410): WBM Fix import-user-data-file-upload tests

- packages/api/src/models/security/index.ts
- packages/api/src/models/security/rights.ts
- packages/api/src/services/repository/repository.service.ts
- packages/api/src/services/security/authentication.service.ts
- packages/api/src/services/security/test/authentication.service.spec.ts
- packages/shared-components/src/components/onto-header/onto-header.tsx
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
Add filtering to the repository dropdown, based on user rights
It currently shows repositories, to which the user has no access to
Implemented a `canReadRepo` method in `authentication.service`, which contains the existing logic from `jwt-auth.service`. Added a filter by that function in `onto-header`
jest
What repositories, the user sees
What repositories does the user have access to
Available repositories at the moment
> GDB-12553 add repository filtering by rights

- packages/api/src/ontotext-workbench-api.ts
- packages/api/src/services/http/http.service.ts
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/single-spa-angularjs.js
Trigger digest cycle in legacy workbench after each request done by the rest services in the API package
This will ensure that the legacy workbench is updated
- added an event emitter in the `HttpService` in the `API` package, which will emit a new event after each request completed,
- added a listener for this event in the `mount` function for the legacy workbench
N/A
n/a
> GDB-12574: Trigger digest cycle after API service rest calls

- e2e-tests/e2e-legacy/monitor/backup-and-restore/backup-and-restore-with-repository.spec.js
- e2e-tests/e2e-legacy/monitor/backup-and-restore/backup-and-restore-without-repository.spec.js
- e2e-tests/e2e-legacy/monitor/backup-and-restore/backup-and-restore.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/monitoring/backup-and-restore-steps.js
- packages/legacy-workbench/src/js/angular/backup-and-restore/plugin.js
- packages/legacy-workbench/src/pages/monitor/backup-and-restore.html
Added tests to verify the initial state of the Backup And Restore view.
N/A
> GDB-12173 Add initial state tests for the Backup And Restore view

- e2e-tests/e2e-legacy/monitor/system/monitor.resources.spec.js
- e2e-tests/e2e-legacy/monitor/system/system-monitoring-with-repository.spec.js
- e2e-tests/e2e-legacy/monitor/system/system-monitoring-without-repository.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/monitoring/system-monitoring-steps.js
- packages/legacy-workbench/src/js/angular/resources/plugin.js
- packages/legacy-workbench/src/pages/monitor/resources.html
Added tests to verify the initial state of the System monitoring view.
N/A
> GDB-12173 Add initial state tests for the System monitoring view

- src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
- test-cypress/integration/cluster/edit-cluster-nodes-modal.spec.js
Canceling a the replace action for a node will not replace the node with the next one added.
When the user clicked "Replace node" and then "Cancel", and added a new node to the cluster, the newly added node would still replace the first node (even thought the replace action was canceled). The node would be removed from the cluster.
I reset the edit state on cancel node action.
Added test
N/A
> GDB-12556 - Reset node edit state on cancel node action

- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
Fix restricted pages showing, when a user has rights to view the page
Restricted pages were being shown on users, which they shouldn't be
Reset the restricted pages upon user logout. When a user gets a 403 response, the page, which he is in on gets added to a list. That list is not reset for new logins, so every next logged in user would continue with the same restricted pages. If they are visited again, they will not be shown, even though the user may have rights to view them
n/a
n/a
> GDB-12567 Fix restricted page showing on admin user

- e2e-tests/e2e-legacy/setup/aclmanagement/acl-management-with-selected repository.spec.js
- e2e-tests/e2e-legacy/setup/aclmanagement/acl-management-without-repositories.spec.js
- e2e-tests/steps/main-menu-steps.js
- packages/legacy-workbench/src/js/angular/aclmanagement/plugin.js
Added tests which assert the initial state of the acl management view.
To ensure the page loads correctly
Added tests, which verify the state of the view by navigating via URL and by visiting it through the navigation menu. Added tests with a selected repo and without any repositories
cypress
> GDB-12173 Add initial state specs for ACL management

- e2e-tests/e2e-legacy/setup/jdbc/jdbc-create.spec.js
- e2e-tests/e2e-legacy/setup/jdbc/jdbc-with-repository.spec.js
- e2e-tests/e2e-legacy/setup/jdbc/jdbc-without-repository.spec.js
- e2e-tests/e2e-legacy/setup/jdbc/jdbc.spec.js
- e2e-tests/e2e-legacy/setup/rdf-rank/rdf-rank-with-repository.spec.js
- e2e-tests/e2e-legacy/setup/rdf-rank/rdf-rank-without-repository.spec.js
- e2e-tests/e2e-legacy/setup/rdf-rank/rdf-rank.spec.js
- e2e-tests/e2e-legacy/setup/sparql-template/sparql-template-create.js
- e2e-tests/e2e-legacy/setup/sparql-template/sparql-template-with-repository.spec.js
- e2e-tests/e2e-legacy/setup/sparql-template/sparql-template-without-repository.spec.js
- e2e-tests/e2e-legacy/setup/sparql-template/sparql-templates.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/setup/jdbc-steps.js
- e2e-tests/steps/setup/rdf-rank-steps.js
- e2e-tests/steps/setup/sparql-templates-steps.js
- packages/legacy-workbench/src/js/angular/jdbc/plugin.js
- packages/legacy-workbench/src/js/angular/rdfrank/plugin.js
- packages/legacy-workbench/src/js/angular/sparql-template/plugin.js
- packages/legacy-workbench/src/pages/jdbc.html
- packages/legacy-workbench/src/pages/rdfrank.html
- packages/legacy-workbench/src/pages/sparql-templates.html
- packages/shared-components/src/pages/js/main.js
- Added tests to verify the initial state of the Sparql templates view;
- Added tests to verify the initial state of the JDBC view;
- Added tests to verify the initial state of the RDF Rank view.
N/A
> GDB-12173 Add initial state tests

- e2e-tests/e2e-legacy/setup/connectors/connectors-initial-state-with-selected-repository.spec.js
- e2e-tests/e2e-legacy/setup/connectors/connectors-initial-state-without-repositories.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/setup/connectors-steps.js
- packages/legacy-workbench/src/js/angular/externalsync/plugin.js
- packages/legacy-workbench/src/pages/connectorsInfo.html
Added tests which assert the initial state of connectors view.
To ensure the page loads correctly
Added tests, which verify the state of the view by navigating via URL and by visiting it through the navigation menu. Added tests with a selected repo and without any repositories
cypress
> GDB-12173 Add initial state specs for connectors

- packages/api/src/services/autocomplete/autocomplete-rest.service.ts
- packages/api/src/services/autocomplete/test/autocomplete.service.spec.ts
- packages/api/src/services/cookie/test/cookie.service.spec.ts
- packages/api/src/services/language/language-rest.service.ts
- packages/api/src/services/language/test/language.service.spec.ts
- packages/api/src/services/license/license-rest.service.ts
- packages/api/src/services/license/test/license.service.spec.ts
- packages/api/src/services/namespace/namespaces-rest.service.ts
- packages/api/src/services/namespace/test/namespaces.service.spec.ts
- packages/api/src/services/product-info/product-info-rest.service.ts
- packages/api/src/services/product-info/test/product-info.service.spec.ts
- packages/api/src/services/repository-location/repository-location-rest.service.ts
- packages/api/src/services/repository-location/test/repository-location.service.spec.ts
- packages/api/src/services/repository/repository-rest.service.ts
- packages/api/src/services/repository/test/repository.service.spec.ts
- packages/api/src/services/security/security-rest.service.ts
- packages/api/src/services/security/test/security.service.spec.ts
- packages/legacy-workbench/src/app.js
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/root-config/src/index.ejs
- packages/shared-components/cypress/e2e/license-alert/license-alert.cy.js
- packages/shared-components/src/components/onto-license-alert/onto-license-alert.tsx
- packages/shared-components/src/components/onto-navbar/onto-navbar.tsx
- packages/shared-components/src/pages/fake-server.js
- webpack.config.prod.js
The workbench now loads and works correct behind a context path
The GDB and WB can be run in different environments and so they must build correctly
- changed absolute paths to relative for rest calls
- changed absolute paths to relative for scripts and the single spa packages
- changed webpack publicPath to be relative for production build
N/A
N/A
> GDB-12586: Fix WB build running through external context

- e2e-tests/e2e-legacy/setup/autocomplete/autocomplete-with-repository.spec.js
- e2e-tests/e2e-legacy/setup/autocomplete/autocomplete-without-repository.spec.js
- e2e-tests/e2e-legacy/setup/autocomplete/autocomplete.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/setup/autocomplete-steps.js
- packages/legacy-workbench/src/pages/autocomplete.html
Added tests to verify the initial state of the Autocomplete view.
N/A
> GDB-12173 Add initial state tests for the Autocomplete view

- e2e-tests/e2e-legacy/setup/plugins/plugins-with-repository.spec.js
- e2e-tests/e2e-legacy/setup/plugins/plugins-without-repository.spec.js
- e2e-tests/e2e-legacy/setup/plugins/plugins.spec.js
- e2e-tests/steps/main-menu-steps.js
- e2e-tests/steps/setup/plugins-steps.js
- packages/legacy-workbench/src/js/angular/plugins/plugin.js
- packages/legacy-workbench/src/pages/plugins.html
Added tests to verify the initial state of the Plugins view.
N/A
> GDB-12173 Add initial state tests for the Plugins view

- packages/legacy-workbench/src/pages/cluster-management/clusterInfo.html
The node tooltip link in the tooltip in the cluster view now opens in a new tab
Same as other anchor tags which opened in a new tab without target="_blank" on the legacy, now open in tha current tab
- added `target="_blank" rel="noopener"`
N/a
N/A
> GDB-12584: Fix cluster node link not opening in new tab

- Jenkinsfile
- package-lock.json
- src/pages/create-index.html
- src/pages/rdfrank.html
- test-cypress/package-lock.json
The nodejs version in the Jenkinsfile was upgraded to v16.20.2. The same version was used to build new package-lock files for the app and Cypress.
Backend pipeline is failing. We suspect the nodejs version is to blame. 
Updated Jenkinsfile.
Added closing tag to a few HTML elements, which were not rendering.
N/A
N/A
> GDB-12532 - Update nodejs version in jenkinsfile and update package-locks

- packages/api/src/services/utils/routing-utils.ts
An unnecessary authenticated-user request was being made immediately after login when the Workbench is started under a context path.
There is a subscription to security context changes, which triggers the fetching of the authenticated user details. This request is normally skipped on the login page, as the user is not yet authenticated.
However, the check only verified whether the current route was exactly "login". The route was determined using a utility function that returns the pathname without accounting for the context (base href), which caused the check to fail—leading to the additional request being sent.
The GraphDB server correctly updates the <base href> tag in the index.html to reflect the current context, but this value was not being used in the migrated Workbench code.
Fixes …
> GDB-12611: Unnecessary authenticated-user request upon login

- packages/shared-components/cypress/e2e/rdf-search/rdf-search.cy.js
- packages/shared-components/cypress/e2e/user-menu/user-menu.cy.js
- packages/shared-components/src/components/onto-search-resource-input/onto-search-resource-input.tsx
- packages/shared-components/src/components/onto-user-menu/onto-user-menu.tsx
Fix broken navigations, when GraphDb is behind a proxy
Thy are not working
- Changed `navigateTo` parameters to be relative, instead of absolute. This fixes the navigation from the user menu to the settings page and the autocomplete toast message redirect
Fixes: GDB-12616 and GDB-12613 as well
n/a
> GDB-12612 Fix broken navigations, when behind context

- test-cypress/integration/setup/sparql-templates.spec.js
The second test in sparql-templates.spec.js is skipped.
The test fails in CI builds, but scenario passes in prod build and if test is run on its own. Skipping to allow BE to build and test.
Test skipped.
Skipped one test in sparql-templates.spec.js.
N/A
> GDB-12532 - Skip failing CI test

- packages/api/src/services/repository/repository.service.ts
- packages/api/src/services/security/authentication.service.ts
- packages/shared-components/src/components/onto-header/onto-header.tsx
Fix repository dropdown filtering with GQL
Currently GQL access is not taken into account
Migrated the `hasGraphQlAuthority` functionality from the legacy workbench and added the filter in the repository dropdown items
n/a
> GDB-12626 Fix GQL repository dropdown filtering

- packages/api/src/models/rdf-search/autocomplete-search-result.ts
- packages/shared-components/src/components/onto-search-resource-input/onto-search-resource-input.tsx
When a user types a value into the RDF Resource Search component, suggestions are correctly displayed based on the entered value. The input value is persisted, and suggestions should be displayed every time the component is opened—even after a page refresh.
However, after refreshing the page, while the persisted input value is restored, the suggestions are not consistently displayed
The RDF Resource Search component subscribes to an "autocomplete enabled" event. There's a race condition in how this subscription is registered. When the page loads, results are fetched from GraphDB. If the subscription is registered after the results are loaded, the component might not be properly initialized.
In some cases, when the subscription is registered, the autocomplete state may not yet be …
> GDB-12652: Suggestions not displayed after page refresh

- packages/shared-components/src/utils/tooltip-util.spec.ts
- packages/shared-components/src/utils/tooltip-util.ts
Fix tooltip in the YASGUI components getting destroyed
The `onto-tooltip` component uses the same library as the YASGUI - `tippy.js`. The problem is that the `onto-tooltip` does not differentiate from tooltip created by it and other and listens globally on document mouseout to destroy them, which destroys all instances created by `tippy.js`
How
- added a class to the host element, when the tooltip is created
- added a condition to only destroy tooltips with the specified class
Added tests for `TooltipUtil`
> GDB-12631 Fix tooltip in the YASGUI components getting destroyed

- src/js/angular/core/services/tracking/installation-cookie.service.js
- Introduce a new constant SAME_SITE_POLICY = 'Lax'.
- Update the CookieService.set call in installation-cookie.service.js to include sameSite: SAME_SITE_POLICY.
Explicitly declaring SameSite='Lax' ensures that installation cookies are sent on same-site requests and top-level navigations while blocking most third-party contexts, reducing CSRF risk.
- Defined const SAME_SITE_POLICY = 'Lax'
- Passed sameSite: SAME_SITE_POLICY into the options object of CookieService.set(...)
> fix(GDB-12649) Add SameSite=‘Lax’ policy to installation cookie

- e2e-tests/e2e-legacy/home/rdf-resource-search.spec.js
- e2e-tests/stubs/browser-stubs.js
- packages/api/src/services/monitoring/test/monigoring.service.spec.ts
- packages/api/src/services/toastr/test/onto-toastr.service.spec.ts
- packages/api/src/services/utils/generator-utils.ts
- packages/api/src/services/utils/test/generator-utils.spec.ts
- packages/shared-components/cypress/e2e/operations-notification/operations-notification.cy.js
- packages/shared-components/cypress/e2e/rdf-search/rdf-search.cy.js
- packages/shared-components/cypress/e2e/toastr/toastr.cy.js
Fix missing toast messages, when using GDB without ssl
They are not being displayed due to an error
Replaced `window.crypto.randomUUID` with a custom generator for ids. When GDB is deployed without SSL and not on a local machine, there is no `window.crypto`, which results in an error, when opening migration toasts
jest
> GDB-12654 Fix broken toasts without ssl

- packages/api/src/interceptor/auth/auth-request-interceptor.ts
- packages/legacy-workbench/src/js/angular/core/interceptors/authentication.interceptor.js
Add guards in both the new (shouldProcess) and legacy (authentication.interceptor.js) interceptors so that OpenID URL checks run only when both openIdKeysUri and openIdTokenUrl are present.
When both URIs were undefined, the some(...indexOf(...)) check produced a false‐positive match, causing the XHR detection header (X-Requested-With) to be omitted. That omission triggered the browser’s native authentication popup (the reported bug).
- Extract openIdKeysUri and openIdTokenUrl into separate constants.
- Wrap the URL‐matching logic in an if (openIdKeysUri && openIdTokenUrl) { … } block so it only executes when both values exist.
- Default to injecting headers normally (returning true or falling through) whenever either URI is missing.
> fix(GDB-12626) Only skip header injection when OpenID URIs are defined and match

- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
Fix visible user menu without rights
It was being shown to plain users with no rights
Moved the restricted page reset inside `onRepositorySet`. Before there was a race condition between repositories and users requests. Depending on, which is which, the restricted pages banner was shown or not shown. This happened because inside `seRepository` we do not broadcast `repositoryIsSet` anymore, but we use the new context services. Broadcasts happen as many times as they are called, while context services do not broadcast the same value twice. For this reason `setRepository` might not trigger `updateSelectedRepository`. In this case, this is what is supposed to trigger another call to get users and display the banner.
n/a
> GDB-12627 Fix visible user menu without rights

- packages/legacy-workbench/src/js/angular/graphql/templates/create-graphql-endpoint.html
Added the write attribute to the core-errors-container directive in create-graphql-endpoint.html.
This change triggers the write-permission check for the selected repository. If the user lacks write rights, the component will now display the appropriate banner with a description of the problem.
Updated the template line
> fix(GDB-12625) Enable write checks in GraphQL endpoint creation template

- packages/legacy-workbench/src/app.js
Reintroduced a conditional block in the Workbench template to display a restricted access warning when the user lacks authority but has permission and an active repository.
During the migration from the legacy Workbench to single-spa, the conditional UI check handling restricted repository access was accidentally omitted. As a result, users without proper authority were being redirected to the login page instead of seeing an informative warning.
Added back the missing `ng-if="hasPermission() && !hasAuthority() && getActiveRepository()"` container with the appropriate warning banner, preserving the intended UX from the legacy implementation.
> fix(GDB-12677) Show restricted access banner instead of redirecting to login page

- packages/shared-components/src/components/onto-header/onto-header.tsx
Updated the shouldShowRdfSearch() method in onto-header.tsx to add an extra permission check.
Users who have only GQL rights on a repository should not see the RDF Search icon, since they lack the necessary read permissions to use it.
Added this.authService.canReadRepo(this.currentRepository) to the existing conditions in shouldShowRdfSearch(), so the icon is only shown when the user can actually read the repository.
> fix(GDB-12680): hide RDF Search icon for users with only GQL rights

- src/css/ttyg/agent-list.css
- src/css/ttyg/agent-select-menu.css
- src/css/ttyg/agent-settings-modal.css
- src/i18n/locale-en.json
- src/i18n/locale-fr.json
- src/js/angular/rest/ttyg.rest.service.js
- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- src/js/angular/ttyg/controllers/ttyg-view.controller.js
- src/js/angular/ttyg/directives/agent-list.directive.js
- src/js/angular/ttyg/directives/help-info-popover.directive.js
- src/js/angular/ttyg/services/ttyg-context.service.js
- src/js/angular/ttyg/templates/agent-list.html
- src/js/angular/ttyg/templates/agent-select-menu.html
- src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- src/js/angular/ttyg/templates/modal/helpInfoExternalLink.html
- src/js/angular/ttyg/templates/modal/helpInfoPopoverTemplate.html
- test-cypress/fixtures/locale-en.json
- test-cypress/integration/ttyg/create-agent.spec.js
- test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
The user will be able to see which Model for each agent in several places in the TTYG view. The Agent Create/Edit modal also has an updated modal for the Model.
This is part of a new requirement, and will allow the user to see more about the TTYG configuration.
I added the information to the agent select dropdown, to the agent management panel and to the agent create/edit dialog.
Due to the rearrangement of the Agent modal, one test had to be edited to scroll for an element.
Info icon in Create/Edit agent modal:
> (cherry-pick) GDB-12592 - Add Model info to TTYG view

- packages/root-config/src/styles/partials/anchor/_anchor.scss
- packages/shared-components/src/components/onto-search-resource-input/onto-search-resource-input.tsx
The autocomplete warning toastr will not have an underline on hover.
Incorrect styling not matching the pre-migration state.
I added a class exception to the _anchor.scss and a class to the anchor element.
N/A
> GDB-12689 - Remove underlines from anchors in autocomplete toastr

- e2e-tests/e2e-legacy/ttyg/ttyg-initial-state-with-selected-repository.spec.js
Both tests in ttyg-initial-state-with-selected-repository.spec.js skipped. API key in test was updated.
The BE has updated the API key name and the Workbench still expects the old one. This fails the BE builds. Hence, the test is skipped until the BE releases successfully.
I skipped the test and updated the property.
N/A
N/A
> GDB-12738 - Skip test with new API key property name for BE builds

- packages/shared-components/cypress/e2e/header/header.cy.js
- packages/shared-components/src/components/onto-user-login/onto-user-login.tsx
When Free Access is enabled and the user clicks the login button, the login page does not open when GraphDB is running under a context path. Additionally, errors appear in the console.
The login link started with a leading /, which breaks navigation when the application is served under a context path.
The leading / was removed from the login URL to support relative navigation under any context path.
N/A
> GDB-12731: Free Access login button not functioning

- packages/shared-components/src/components/onto-operations-notification/onto-operations-notification.tsx
The cluster status dropdown won't have underlines for the statuses on hover.
Incorrect styling not matching the pre-migration state.
I added a class exception to the _anchor.scss.
N/A
> GDB-12690 - Remove underlines from anchors in cluster operations dropdown

- e2e-tests/e2e-legacy/ttyg/agent-list.spec.js
- e2e-tests/e2e-legacy/ttyg/edit-agent.spec.js
- e2e-tests/fixtures/locale-en.json
- e2e-tests/steps/ttyg/ttyg-agent-settings-modal.steps.js
- e2e-tests/steps/ttyg/ttyg-view-steps.js
- e2e-tests/stubs/ttyg/ttyg-stubs.js
- packages/legacy-workbench/src/css/ttyg/agent-settings-modal.css
- packages/legacy-workbench/src/css/ttyg/external-integration-configuration-modal.css
- packages/legacy-workbench/src/i18n/locale-en.json
- packages/legacy-workbench/src/i18n/locale-fr.json
- packages/legacy-workbench/src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
- packages/legacy-workbench/src/js/angular/rest/locations.rest.service.js
- packages/legacy-workbench/src/js/angular/rest/ttyg.rest.service.js
- packages/legacy-workbench/src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- packages/legacy-workbench/src/js/angular/ttyg/controllers/external-integration-configuration-modal.controller.js
- packages/legacy-workbench/src/js/angular/ttyg/directives/agent-list.directive.js
- packages/legacy-workbench/src/js/angular/ttyg/services/externalIntegrationModal.service.js
- packages/legacy-workbench/src/js/angular/ttyg/templates/agent-list.html
- packages/legacy-workbench/src/js/angular/ttyg/templates/modal/agent-settings-modal.html
- packages/legacy-workbench/src/js/angular/ttyg/templates/modal/external-integration-configuration-modal.html
The user will be able to copy the configuration and enabled tools for any agent, using either the Edit agent modal or the action buttons in the agent side-panel list.
This links will be used to retrieve the configuration and enabled tools for that agent, enabling integration with external systems like Dify via the "Expose GraphDB LLM Tools via OpenAPI for Agent Integration" functionality.
I edited the copyToClipboard to allow custom toastr messages. I created a modal for the agent data to be copied.
Tests added.
Custom toastr:
> GDB-12692 - Introduce copy Agent functionality and tests

- packages/legacy-workbench/src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
- packages/legacy-workbench/src/js/angular/guides/tour-lib-services/shepherd.service.js
The "Copy to Editor" button does not function as expected during the guide step that introduces the SPARQL editor.
The original implementation of the "Copy to Editor" functionality relied on Angular's scope. However, this approach does not work reliably in a single-spa environment.
The "Copy to Editor" functionality was updated to use explicit event listeners instead of relying on Angular scope:
- On step show: A click event listener is registered on the "Copy to Editor" button.
- On step hide: The listener is properly removed to prevent memory leaks or unexpected behavior.
When the button is clicked, the listener explicitly fills the query editor with the query content defined in the guide step.
N/A
> GDB-12739: "Copy to Editor" Button Not Working in SPARQL Editor Step

- e2e-tests/e2e-security/setup/users-and-access/user-and-access.spec.js
- packages/shared-components/src/components/onto-header/onto-header.tsx
The repositories displayed in the repository selector component are not consistent with the current security state (e.g., whether security is enabled or disabled, free access is on or off, or whether a user is logged in).
The repository selector is only updated when it is initialized or when a repository is created or deleted. Since the visible repositories are filtered based on the security state and user access rights, this becomes an issue. When the authenticated user changes (e.g., on login/logout), the selector is not regenerated, resulting in outdated or incorrect repository visibility.
A listener for authenticated user change events was added. The selector now re-renders the repository list based on the current user's access rights or free access status.
> GDB-12760: Repository selector does not update after login

- e2e-tests/e2e-security/setup/users-and-access/turn-on-security-and-password-change.spec.js
- packages/legacy-workbench/src/js/angular/controllers.js
Fix the error in the console when logging out, and show the toaster, which caused the error
The redirect to the login (which happens 2 times) breaks the toaster, and it shows an error in the console and does not show in the view
How
- moved the toaster trigger in the `redirectToLogin` promise chain
added in the security suite
> GDB-12787 Fix error in console when logging out

- packages/api/src/models/monitoring/operation-type.ts
- packages/api/src/models/monitoring/operation.ts
- packages/api/src/services/monitoring/mapper/operation-list.mapper.ts
- packages/shared-components/cypress/e2e/operations-notification/operations-notification.cy.js
Fix wrong redirect to `import` when user clicks on running imports while importing in cluster
The redirect was wrong to `imports`, rather than `import` when user clicks on running imports
How
- fixed typo
Fixed
> GDB-12791 Fix wrong redirect from operations notification component

- e2e-tests/e2e-security/setup/home/cookie-policy.spec.js
- e2e-tests/steps/login-steps.js
- e2e-tests/steps/setup/user-and-access-steps.js
- packages/legacy-workbench/src/js/angular/core/services/tracking/tracking.service.js
- packages/legacy-workbench/src/js/angular/models/cookie-policy/cookie-consent.js
A console error occurs when the login page is rendered and free access is turned off.
When the login page is displayed, the TrackingService attempts to apply tracking consent. This process tries to extract the cookie consent, but in this particular state, there is no principal available, resulting in a NullPointerException.
Updated the functionality to check for a principal before applying tracking consent.
> GDB-12776: There is console log when login page is displayed.

- packages/legacy-workbench/src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
- packages/legacy-workbench/src/js/angular/ttyg/templates/autocomplete-iri-discovery-search.html
**This also should be fixing** https://graphwise.atlassian.net/browse/GDB-12800
User might not be able to save a TTYG agent due to agent settings form validation error which is not shown.
When user switches browser tabs while the agent settings modal is opened and returns back to the same tab, a request for autocomplete status check is made then the autocompleteDisabled validation is set in the form's ng model. This request and the validation in the model needs to be done only if the respective autocomplete_iri_discovery_search method is enabled. Otherwise it makes it unclear for the user why the form remains invalid and agent settings can't be saved.
Made sure that the autocomplete status check is not performed and the autocompleteDisabled validation status is not set if the …
> GDB-12802 improve ttyg agent settings form validation

- packages/legacy-workbench/src/js/angular/clustermanagement/services/cluster-drawing.service.js
Fix console error for cluster node recovery label on initialization
If there is no recovery status the `objectWidth` prop is not set and so a division with a NaN is triggered
How
- added failback for the message if there is no `recoveryStatus`
> GDB-12826 Fix cluster node recovery label console error

- packages/root-config/src/index.ejs
The favicon was not visible when the Workbench was accessed under a context path.
Because of an incorrect relative path to the icon.
The path to the favicon has been corrected.
Before
After
> GDB-12542: favicon is missing

- packages/legacy-workbench/src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
The "Temperature" and "Top P" sliders will show correct values, consistent with the model.
The sliders would always load at value 1 when the Create/Edit Agent modal was opened. This was due to the model and sliders not being available at the same time when the controller is initialized.
I added a delay to re-render the sliders with the correct values.
N/A
N/A
> GDB-12815 - Fix inconsistent values on field sliders

- packages/api/src/services/security/authentication.service.ts
- packages/api/src/services/security/test/authentication.service.spec.ts
- packages/legacy-workbench/src/js/angular/core/services/jwt-auth.service.js
- packages/root-config/src/bootstrap/bootstrap.js
- packages/root-config/src/bootstrap/product-info/product-info-bootstrap.js
- packages/root-config/src/bootstrap/repository/repository-bootstrap.js
- packages/shared-components/cypress/e2e/layout/layout.cy.js
- packages/shared-components/src/components/onto-header/onto-header.tsx
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
- packages/shared-components/src/pages/header/index.html
- packages/shared-components/src/pages/header/main.js
- packages/shared-components/src/pages/layout/main.js
- packages/shared-components/src/pages/operations-notification/main.js
Fix menu and header visualization for free access users
- Header wasn't being shown to free access user
- Free access user wasn't seeing repositories, which he has access to
- Footer wasn't being shown on the login screen
- Changed bootstrap to load repositories and product info initially. This solves missing repositories in the selector and missing info in the footer
- Added checks for free access authorities
- Replaced legacy `freeAccessActive` with the config `freeAccess.enabled`. This is needed for correct resolving of conditions in the layout
- Made the footer visible always and corrected the condition for the header
n/a
> GDB-12799 show menu and header correctly for free access user

- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-repository/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-similarity-index/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/ask-ttyg-agent/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/configure-agent/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/fts-search-method/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/similarity-search-method/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/sparql-search-method/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/create-ttyg-agent/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/edit-ttyg-agent/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/select-ttyg-agent/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js
The user guide crashes when clicking the "Previous" button on certain steps.
The previous flow is too complex because showing a previous step requires restoring the application's state before the step is displayed. This is not a trivial task, as the required state may depend not only on the immediately previous step, but also on earlier steps in the flow. If the "Previous" button is clicked and the necessary state can't be restored, the guide crashes, the element where the dialog should appear may no longer exist.
There is a flag that controls whether the "Previous" button is shown. The default behavior was to always show the button, this has now been changed to hide it by default.
The functionality is still available and can be enabled where it's safe and useful, for example, in form …
> GDB-12728: The user guide crashes when clicking the Previous button

- packages/api/src/models/security/restricted-pages.ts
- packages/legacy-workbench/src/app.js
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/core/services/jwt-auth.service.js
- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
- packages/legacy-workbench/src/js/angular/plugin.js
- packages/legacy-workbench/src/js/angular/settings/app.js
- packages/shared-components/src/components/onto-layout/onto-layout.tsx
Centralize page permissions and base them off of menu declarations
Page permissions were set based on 403 responses which were not always available on pages where the user does not have permission to view.
How
- added a function to set permissions based on menu item role for each defined route
- removed unauthorized interceptor, because it is no longer needed
- removed `$rootScope.deniedPermissions` and used `SecurityContextService` as single point of truth about permissions
- changed conditions in legacy template to allow the application to show `coreError` directive
- based showing the permission banner in layout on the `SecurityContextService` permissions
* Admin user with no restrictions
* Repo manager with some restrictions
* User with more restrictions
* Free access user
> GDB-11874 Fix page permissions

- packages/legacy-workbench/src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
Movie guide step 31 won't break on double click.
Double click would make the next step not appear properly (the sidepanel would remain closed).
I added an event listener for `dblclick` to make sure the sidepanel is opened on double click.
N/A
N/A
> GDB-12487 - Fix movie guide step 31 when side-panel won't open

- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/core/services/repositories.service.js
- packages/legacy-workbench/src/js/angular/core/templates/core-errors.html
- packages/legacy-workbench/src/js/angular/security/templates/user.html
- packages/legacy-workbench/src/template.html
All repositories are displayed by default even when "Show remote locations" is not clicked
After the introduction of GraphQL functionality, the template responsible for displaying repositories in the core error directive was changed. As a result, it started showing all repositories without filtering by location (local or remote).
The directive was updated to use a method that filters the displayed repositories based on whether "Show remote locations" is selected.
Before
After
> GDB-12378: All repositories are displayed by default

- packages/legacy-workbench/src/css/rdfrank.css
- packages/legacy-workbench/src/i18n/locale-en.json
- packages/legacy-workbench/src/i18n/locale-fr.json
- packages/legacy-workbench/src/js/angular/guides/steps/complex/main-menu/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/rdf-rank/plugin.js
- packages/legacy-workbench/src/pages/rdfrank.html
Added a new step: rdf-rank-compute-fill.
This enhances the guides with the opportunity to teach users how to trigger the computation of the RDF Rank values.
- Implemented a new step that selects the "Compute Full" button.
- Extended the "click-main-menu" step to support the RDF Rank submenu.
> GDB-12874: Add a guide step for RDF Rank

- src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
The "Temperature" and "Top P" sliders will show correct values, consistent with the model.
The sliders would always load at value 1 when the Create/Edit Agent modal was opened. This was due to the model and sliders not being available at the same time when the controller is initialized.
I added a delay to re-render the sliders with the correct values.
> (cherry-pick) GDB-12815 - Fix inconsistent values on field sliders

- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-repository/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/complex/main-menu/plugin.js
- The `create-repository` core steps have been extracted.
- Missed `-guide-dialog` suffix removed.
- Extracting the steps allows developers to reuse them.
- For some reason IDE didn't show the suffix instance when searching all files for previous MR changes.
N/A
N/A
> GDB-12885 -  Extract create-repository core steps

- packages/api/src/interceptor/auth/unauthorized-interceptor.ts
- packages/api/src/interceptor/interceptors.ts
When the backend is restarted, existing JWT tokens become invalid. This caused issues where a logged-in user would see a broken workbench.
When the page is reloaded, the backend returns 401 because an invalid JWT token is used. In the new REST services, there is no interceptor that removes the token from storage, so the workbench keeps using it. As a result, the backend always returns 401 and the user cannot use the system until the JWT token is manually deleted from local storage.
The fix ensures that on a 401 response:
- The JWT token is removed from local storage;
- The user is redirected to the login page;
- The page is reloaded to guarantee proper bootstrap after re-authentication.
> Cherry-pick GDB-12924: Clear auth token on 401

- packages/shared-components/stencil.config.ts
- webpack.config.prod.js
Remove the .stencil folder after build. This contains ts.d files that are not needed in a production build, but we can't find a way to disable stencil to output them. Effectively this removes the folder which brakes windows distribution because of the quite long file paths.
Also disabled source map files generation for the web components due to the same reason -> too long names
> 3.1 clean up tsd files generated by stenciljs

- packages/legacy-workbench/src/i18n/locale-en.json
- packages/legacy-workbench/src/i18n/locale-fr.json
change `skip` to `skip section` in the guide dialog
To be more discriptive
Renamed the labels for french and english
n/a
> GDB-12907 change skip to skip section

- e2e-tests/e2e-legacy/ttyg/agent-select-menu.spec.js
- e2e-tests/e2e-legacy/ttyg/edit-agent.spec.js
- packages/legacy-workbench/src/js/angular/ttyg/directives/agent-select-menu.directive.js
The first agent in the TTYG agent select dropdown will be selected on page load. If the user selects another agent, it will be remembered the next time the page is loaded.
The improvement reduces steps needed to be taken in order to ask a question.
I save the user selected agent to the local store, otherwise if local store is empty, I load the first option from the dropdown. When a chat is loaded, the last agent used in the chat will be selected, as per the original functionality, regardless what is in local store.
Test expectations edited to fit the default first option selected.
N/A
> GDB-12500 - Save selected agent to local store and select first in dropdown

- packages/shared-components/stencil.config.ts
- webpack.config.prod.js
Remove the .stencil folder after build. This contains ts.d files that are not needed in a production build, but we can't find a way to disable stencil to output them. This effectively removes the folder which brakes windows distribution because of the quite long file paths.
Also disabled source map files generation for the web components due to the same reason -> too long names
> Remove the .stencil folder after build

- packages/legacy-workbench/src/pages/connectorsInfo.html
Fixed the issue where the connector form required two clicks to open due to Bootstrap collapse and AngularJS interaction.
The first click triggered a "page flash" caused by Bootstrap’s `href="#collapse-...{{$index}}"` navigation updating the URL fragment and Angular’s digest cycle re-rendering.
- Replaced `href`-based collapse toggle with `data-target` to prevent fragment navigation.
> GDB-12979: Required to click any connector twice for the form to open

- packages/legacy-workbench/src/js/angular/guides/model/guides.js
- packages/legacy-workbench/src/js/angular/guides/tour-lib-services/shepherd.service.js
Changed the default scrollTo configuration to use a smoother and less disruptive alignment.
The previous strategy scrolled elements to the top of the viewport, which often caused the screen to flash or jump abruptly. This degraded the user experience during guides.
- Updated `scrollTo.behavior` to smooth for natural animated scrolling;
- Updated block and inline to nearest, ensuring minimal movement while keeping the element visible.
> GDB-12980: Change default scrollTo strategy to prevent screen flashing

- packages/legacy-workbench/src/css/shepherd-custom.css
Long text won't overflow guide step containers.
One of the steps included a long IRI, which went outside the container.
I handle the overflow in the css file.
N/A
After the fix:
> GDB-12685 - Handle overflowing content in guide steps

- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/sparql-search-method/plugin.js
The checkbox under the SPARQL query method in the TTYG guide can be checked or unchecked regardless of the option selected. The option can be passed into the guide config.
Both the Ontology graph and SPARQL CONSTRUCT query methods allow checking the checkbox, so it's an option for both.
I check for this option in both the Ontology graph and SPARQL CONSTRUCT step flows.
> (cherry-pick) GDB-12852 - User guides. TTYG. Allow specifying if "Add Missing Namespaces" should be checked

- e2e-tests/cypress-flaky.config.js
- e2e-tests/cypress-legacy.config.js
- e2e-tests/cypress.config.js
- e2e-tests/eslint.config.js
- e2e-tests/package.json
- e2e-tests/plugins/index.js
- e2e-tests/steps/home-steps.js
- e2e-tests/support/e2e.js
- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/repositories/controllers.js
- Make repo create flow return to the actual originating route via previous query param.
Users were sent to generic paths after creating/canceling, instead of going back to where they started—hurting UX.
- goToAddRepo - capture the current $location.url() and pass it as previous when navigating to repository/create
- goBackToPreviousLocation - read previous, remove it, navigate to it, else default to /repository
- Add trailing commas in arrays/objects/imports, ensure semicolons, normalize function() spacing, replace let with const where applicable and remove stray blank lines across touched files.
> feat(GDB-12742) Respect return URL on repo create

- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/create-ttyg-agent/plugin.js
Fix wrong position of create agent step
It was positioning the dialog in the top left corner
Added `wait-for-element-to-hide` step, before the create agent step. We wait for the container of the spinner to hide, since it is the element, which has a `display none` applied to it. This way the button is visible, when it is time to position the step on top of it
n/a
> Cherry-pick GDB-12988 Fix wrong position on create agent step

- packages/legacy-workbench/src/pages/home.html
Updated the logic for displaying saved SPARQL queries to ensure that shared queries are correctly hidden based on user settings.
To prevent incorrect visibility of shared queries
Modified the `ng-hide` condition in the `home.html` file to include an additional check for the `shared` property of the query.
n/a
> Cherry-pick GDB-12664 fix missing saved SPARQL queries

- packages/legacy-workbench/src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
- packages/legacy-workbench/src/js/angular/clustermanagement/templates/cluster-nodes-configuration.html
When creating/editing cluster nodes, the user will be able to confirm valid node addresses with "Enter" and cancel adding the current line with "Esc".
This is a usability improvement.
I added a helper method to trigger on key-press. It checks if the form is valid before saving.
Dialog in question
> (cherry-pick) GDB-12873 - Save cluster node on Enter or cancel adding/editing on Esc

- packages/api/src/services/security/authentication.service.ts
- packages/api/src/services/security/test/authentication.service.spec.ts
- packages/shared-components/src/components/onto-header/onto-header.tsx
Fix operations requests handling for users with free access, ensuring proper operation polling.
Because they are not supposed to be requested, when a user is not authenticated
Updated the `isAuthenticated` method to `isLoggedIn` in `authentication.service.ts` and adjusted the operation polling logic in `onto-header.tsx` to account for free access scenarios.
jest
> Cherry-pick GDB-13029 fix operations requests for free access users

- packages/shared-components/src/components/onto-layout/onto-layout.tsx
Fix the visibility logic for the footer on the login page by ensuring it is always displayed.
The footer was previously conditionally rendered based on authentication status, which caused it to be missing in the login screen.
Updated the state variable from `showFooter` to `showHeader` and adjusted the visibility logic accordingly. Changed the authentication check from `isAuthenticated` to `isLoggedIn` to use the legacy workbench as the source of truth.
n/a
> Cherry-pick GDB-13032 Fix missing footer on login page

- .gitignore
- assets/configuration.default.json
- scripts/copy-plugins.sh
- webpack.config.common.js
Fix failing tests for external plugins in GDB
There is an issue in GDB, where `workbench/plugins` is read instead of `/plugins`
Renamed `plugins` to `wb-plugins` as a quick fix to ensure GDB doesn't look in the wrong folder
n/a
> GDB-13037 fix GDB external plugin tests

- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-similarity-index/plugin.js
The step that instructs users to wait until a similarity index is created is skipped when the "create-similarity-index" step is used.
During the extraction of similarity steps from the complex, the skipped step was mistakenly left without a guideBlockName. This caused the guide to skip it
Added the missing guideBlockName to the step.
> GDB-13076: Guide skips waiting for Similarity Index build

- packages/legacy-workbench/src/js/angular/guides/steps/complex/create-similarity-index/plugin.js
The step that instructs users to wait until a similarity index is created is skipped when the "create-similarity-index" step is used.
During the extraction of similarity steps from the complex, the skipped step was mistakenly left without a guideBlockName. This caused the guide to skip it
Added the missing guideBlockName to the step.
(cherry picked from commit 9568cf4c12497581e44b8054eb873b8243cd4e4d)
> Cherry-pick GDB-13076: Guide skips waiting for Similarity Index build

- packages/api/src/models/security/authentication/auth-strategy-type.ts
- packages/api/src/models/security/authentication/auth-strategy.ts
Created an interface for authentication strategies and an enum for supported authentication types.
This implementation promotes flexibility and extensibility in the security module by allowing pluggable authentication strategies without entangled logic.
- Added `AuthStrategyType` enum with various authentication strategy types.
- Defined `AuthStrategy` interface with methods for initialization, login, logout, and authentication checks.
> GDB-12700: Define authentication strategy interface

- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/ask-ttyg-agent/plugin.js
Fix the placement of the guide step for the ttyg agent in the chat panel
On smaller screens, the dialog covers the chat panel
Removed the `placement: 'left'` line from the configuration object in `plugin.js`. This now positions the dialog either above or below the chat panel. Since it resizes, this is much more flexible
n/a
[Screencast from 2025-09-24 09-04-30.webm](https://github.com/user-attachments/assets/8a0e30dd-854c-45fb-863e-0b33c389c1a2)
> GDB-13086 fix ttyg guide step covering chat panel on smaller screen

- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/sparql-search-method/plugin.js
Fix the guide step for continuing without selecting the `Auto-add missing namespaces` checkbox
To ensure that users will proceed in the guide only after checking the checkbox
Added the element to the  `clickableElementSelector` property to ensure the checkbox is clicked. Previously the guide continued when the clicked element is the surrounding parent
n/a
(cherry picked from commit bff34adf98679d3332e50ba553909b30086325df)
> GDB-13099 fix guide continuing without namespace checkbox

- packages/legacy-workbench/src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
- packages/legacy-workbench/src/js/angular/guides/tour-lib-services/shepherd.service.js
Add a Previous button to the import-upload-rdf-file step.
In this step, the user must upload a file that was downloaded in the previous step. If they skip that step, they currently have to stop the guide and restart it. With the Previous button, the user can go back to the previous step to download the file without restarting the guide.
Update the import-upload-rdf-file step to display a Previous button.
Added a check to ensure that a step has a defined url before navigating to it in the previous flow, since missing URLs caused the guide to crash.
> GDB-13146: Can't return to dataset download step if skipped, requiring restart

- package-lock.json
- package.json
- webpack.config.common.js
Update the graphdb-workbench-plugins version.
A new version is available with all guide plugins updated.
Bump the graphdb-workbench-plugins dependency to the latest version.
> GDB-12871: update version of graphdb-workbench-plugins

- packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/sparql-search-method/plugin.js
- packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js
Disallow the guide from continuing if toggleable elements are not clicked.
There are scenarios, where you have a previous button, and you can go back and uncheck a checkbox/toggle button. This click advances the guide, but the checkbox/toggle button need to be checked
- Added new `toggle-element` step, which functions similarly to `clickable-element`. It also contains click event listener and doesn't allow the guide to proceed, if the input element is not checked. This effectively blocks deselecting of the element
- Replaced `ttyg-sparql-method-enable` and `ttyg-sparql-click-add-namespaces` steps to be toggleable elements
n/a
(cherry picked from commit bcbee92fce1a4a22780aa286a6808c781a2962d8)
> Cherry pick GDB-13142 Disallow the guide from continuing if toggleable elements are not clicked

- packages/legacy-workbench/src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
- packages/root-config/src/vendor/common.css
Fix the interaction behavior of the sidebar in the hierarchy view during guide
To ensure a user can't click any sidebar links and break the guide, while on the class-hierarchy guide
- added `pointer-events-none` global class
- Added toggling of the class for the sidebar, during `class-hierarchy-open-rdf-instances-side-panel` and `class-hierarchy-explain-class`
n/a
(cherry picked from commit 26b0c5f71f9b78a5ae2e7e8fe9d622a42552a043)
> Cherry pick GDB-12373 fix hierarchy view sidebar interactability

- packages/legacy-workbench/src/js/angular/controllers.js
- packages/legacy-workbench/src/js/angular/core/templates/core-errors.html
Fix the autocomplete status resolution for anonymous.
It wasn't being calculated correctly. When an anonymous user tried to use the `view resource` search, the workbench incorrectly showed a `Autocomplete is off` message
Modified the condition to check against `getActiveRepositoryObject()` instead of `getActiveRepository()` in `controllers.js`. The `jwtService#canReadRepo` expects a repository object. Currently, `getActiveRepository` is passed, which returns the repositoryId (string). This breaks the authorities calculation.
n/a
> GDB-13199 fix autocomplete is off for anonymous users
