Ontotext-AD/graphdb-workbench

.gitignore
.travis.yml
karma.conf.js
package-lock.json
package.json

The cycle includes triggering Jasmine tests under PhantomJS (headless) and coverage publishing to Coveralls.

Configured Travis CI build cycle

---

src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js

Merge in separated project the changes from https://gitlab.ontotext.com/graphdb-team/graphdb/merge_requests/1202/diffs

Merge GDB-3642 changes from gdb master branch to separated workbench

---

.travis.yml
README.md
sonar-project.properties

Configure sonarcloud

---

src/js/angular/repositories/services.js

Reverts Ontotext-AD/graphdb-workbench#17 as this breaks cypress tests

Revert "Merge branch 'GDB-3336-Broken-Cluster-Visualization' from graphdb master"

---

src/js/angular/core/templates/core-errors.html
src/js/angular/core/templates/search-resource-input.html
src/pages/home.html
test-cypress/fixtures/snippet-import-template.json
test-cypress/integration/home/workbench.home.spec.js
test-cypress/steps/home-steps.js
test-cypress/support/commands.js
test-cypress/support/index.js
test-cypress/support/repository-commands.js

- Rewrite home page with class selectors
- Do not execute queries, only check navigation
- When returning to autocomplete page and executing autocomplete, wait for autocomplete/enabled request 
- Create autocomplete index and import data programatically

Gdb 3764 stabilize home page

---

src/js/angular/graphexplore/templates/listItemsSearchFilterTemplate.html
src/pages/dependencies.html
test-cypress/integration/explore/class.relationships.spec.js

Implemented Test initial state scenario

Implement class relationships tests

---

test-cypress/integration/monitor/monitor.resources.spec.js

Implement Initial state scenario tests

Introduced monitor resources tests

---

src/pages/monitor/queries.html
test-cypress/integration/monitor/monitor.queries.spec.js

Implement Initial state scenario tests

Introduced monitor queries tests

---

src/js/angular/security/templates/users.html
test-cypress/integration/monitor/monitor.queries.spec.js
test-cypress/integration/setup/user-and-access.spec.js

Implemented initial state scenario

Introduce user and access tests

---

src/index.html
src/pages/repositories.html
src/pages/repository.html
test-cypress/integration/repository/repositories.spec.js
test-cypress/integration/repository/repository-commands.spec.js
test-cypress/support/repository-commands.js

Added several classes for easier test interaction.

Added Cypress tests for repositories CRUD UI operations

---

src/js/angular/security/templates/user.html
test-cypress/integration/setup/my-settings.spec.js
test-cypress/integration/setup/user-and-access.spec.js

Implemented initial state spec

Introduce my settings view tests

---

src/pages/info.html
test-cypress/integration/help/system-information.spec.js

Implemented initial state spec

Introduce system information view tests

---

src/pages/namespaces.html
test-cypress/integration/setup/namespaces.spec.js

Added several classes in the DOM for easier selection in the specs.

Added Cypress tests for Setup/Namespaces page

---

src/pages/autocomplete.html
test-cypress/integration/home/workbench.home.spec.js
test-cypress/integration/setup/autocomplete.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js
test-cypress/steps/home-steps.js

Tested enabling it, suggesting resources in the SPARQL editor and added
tests that verify no auto suggests when autocomplete is not enabled.
Added several selectors in the autocomplete page for easier selections.

Added Cypress autocomplete tests

---

src/pages/rdfrank.html
test-cypress/integration/setup/rdf-rank.spec.js

Tested the building of the ranks with and without filtering.
Added several selectors in the rdf rank page for easier selections.

Added Cypress tests for RDF rank setup page

---

test-cypress/integration/import/onto-refine.spec.js

Tested that the iframe is properly rendered with its available tabs and panels

Added Cypress tests for OntoRefine import page

---

src/js/angular/externalsync/controllers.js
src/pages/connectorsInfo.html

GDB-3816: Wrong exporting of 'elasticsearchClusterSniff' setting from… Connectors view
GDB-3819: Viewing existing connectors doesn't show the values of options that were set by default value and not explicitly

GDB-3816 and GDB-3819: Issues with connector manager

---

test-cypress/integration/explore/class.hierarchy.spec.js
test-cypress/integration/explore/class.relationships.spec.js
test-cypress/integration/explore/visual.graph.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js
test-cypress/support/import-commands.js

Implemented cypress command and updated tests.

Change importing of wine rdf to be through server import rest call

---

.travis.yml
src/js/angular/repositories/controllers.js
test/repositories/controllers.spec.js

It appeared that fantomjs which is used when tests are run in CI doesn't support latest javascript features. Fixed by not using `let` but `var` in controller.

Enabled unit tests and fixed issue

---

README.md

Added examples with GraphDB distribution and with Docker

Updated the read me on how to deploy and run the workbench

---

test-cypress/integration/help/system-information.spec.js

Do not expect exactly but at least 5 number of lines in the tables as… these are variable

Fix system info checks

---

src/js/angular/externalsync/controllers.js
src/js/angular/externalsync/templates/deleteConnector.html
test-cypress/integration/setup/connectors-lucene.spec.js
webpack.config.common.js

GDB-3906: Added force delete support to connector manager

---

test-cypress/integration/setup/connectors-lucene.spec.js

fix due to two elements with class creating-connector-dialog

GDB-3936 Flaky connector test 

---

src/js/angular/similarity/controllers/create-index.controller.js
test-cypress/integration/explore/similarity.spec.js

Call setQuery on window.editor to force proper initialization
Remove toast checks as they are flaky and not so important

GDB-3942 Similarity edit search query SPARQL editor not loaded properly

---

package-lock.json
package.json
src/pages/repository.html
test-cypress/package-lock.json
test-cypress/package.json

Add checkboxes for SHACL validation in repository create page. Depends on GraphDB 9.1.0-TR9.

Gdb 4034 create shacl repo in workbench

---

src/pages/repository.html

GDB-4034 Removed ng-disabled of ShaclRepo settings on repository edit

---

src/js/angular/graphexplore/app.js
src/pages/graph-config/saveGraphConfig.html
src/pages/graphs-visualizations.html
test-cypress/integration/explore/visual.graph.spec.js

Add query editor components in visual graph controller. Add basic cypress test for create visual graph config.

GDB-4100 fix cannot create custom graph

---

src/pages/repository.html

Also:
Offset SHACL options to visually group them with the "Enable SHACL" options and added tooltips that describe each option.

GDB-4090: Removed deprecated SHACL options ignoreNoShapesLoadedException

---

package-lock.json
package.json
test-cypress/package-lock.json
test-cypress/package.json

A version to test travis npm publish

Version 1.2.3-TR1

---

src/js/angular/export/controllers.js
src/js/angular/import/controllers.js
src/js/angular/import/templates/urlImport.html
src/js/angular/utils/file-types.js

Add rdf types for import/export

GDB-4287 Import/export rdf* types (turtlestar and trigstar)

---

src/css/yasr.custom.css
src/js/angular/core/directives/queryeditor/query-editor.directive.js
src/js/lib/yasr.bundled.js

Render application/x-sparqlstar-results+json results that contain JSON with triple entities in YASR table view.
- Use YASR editor from https://github.com/Ontotext-AD/YASR-Ontotext/pull/2
- Change YASR accept header to acceptHeaderSelect: "application/x-sparqlstar-results+json.."
- Style the new triple elements

Gdb 4248 render rdfstar tuple query result in sparql editor

---

package-lock.json
package.json
src/js/angular/core/directives/queryeditor/query-editor.directive.js
src/js/lib/yasr.bundled.js
test-cypress/package-lock.json
test-cypress/package.json

-  Consume application/x-graphdb-table-results+json for Graph queries with priority
- Use latest YASR

GDB-4249 Consume application/x-graphdb-table-results+json for Graph queries

---

src/js/lib/yasr.bundled.js

When literals inside a triple expand xsd prefix and add " for literals with no datatype to provide valid triple links

GDB-4381 Fix invalid triple links 

---

src/js/angular/core/services.js
src/js/angular/explore/controllers.js
src/pages/explore.html
test/resource/controllers.spec.js

Provides the ability to handle with Triples
Separate logic for processing single URIs and triples.

GDB-4331 Explore triples like resources

---

src/js/angular/core/directives.js

Link to the resource view with triple parameter for autocomplete results of type triple

GDB-4289 Autocomplete triple with label predicates

---

package-lock.json
package.json

Update babel version, update minimist with force resolution because karma and eslint don't have new version released with new minimist dependency.

GDB-4386 Update minimist with force dependency version

---

package-lock.json
package.json

Script execution in package.json breaks package installation, remove it and commit version in package-lock

GDB-4386 Remove force resolution from package.json

---

src/js/angular/similarity/controllers/similarity-list.controller.js

Fix search query for triples when autocomplete triples in similarity document to document search

GDB-4395 Fix autocomplete triples in similarity search

---

package-lock.json
package.json
test-cypress/package-lock.json
test-cypress/package.json

Prepare final workbench release 1.3.0

---

test-cypress/fixtures/queries/prefix-query.sparql
test-cypress/integration/sparql/sparql.menu.spec.js

Fixed failing cypress tests for sparql menu spec.

Fixed failing sparql menu tests

---

src/js/angular/controllers.js
src/js/angular/core/directives/queryeditor/templates/query-editor.html
src/js/angular/queries/plugin.js
src/js/angular/resources/plugin.js

Updated plugins to reflect added monitoring rights for regular clients, but no rights for viewing resources.

GDB 4705 User query monitoring

---

src/pages/repository.html

GDB-4950: Add checkboxes in the repo creation page for SHACL features

---

package-lock.json
package.json

Executed `npm audit fix` to update libs

Updated libraries

---

package-lock.json
package.json

Made with npm audit fix
reverted jquery update

GDB-4497 Fix latest vulnerabilities

---

src/js/angular/repositories/controllers.js
src/pages/repository.html

GDB-5018 Add option for virtual repo and create virtual repo
Upload virtual repo files and send as parameters
Mark required virtual repo files as such and add validation
Edit virtual repo

GDB-5018 Create virtual repo

---

package-lock.json
package.json
src/js/angular/repositories/controllers.js
test-cypress/package-lock.json
test-cypress/package.json

GDB-5025 Download ontop repos as zip and bump workbench version to 1.5.0-TR1

GDB-5025 Download ontop repos as zip and bump workbench version to 1.5.0-TR1

---

src/js/angular/jdbc/controllers.js
src/js/angular/rest/jdbc.rest.service.js
src/pages/jdbc-create.html

Added preview option rendering results of execution of SQL query. There is a limit option, which is currently unused, and default value is set to 100 in backend. Preview btn is hidden or shown, while switching between tabs.

GDB-5038 Preview functionality

---

src/js/angular/jdbc/controllers.js

Show suggestion warning when existing suggestions will be overwritten.

GDB-5035 JDBC UI Columns suggestions warning fix

---

src/js/angular/repositories/controllers.js
src/pages/repository.html

Upload new ontop files on edit ontop repo. Make inputs readonly. Use the same icon styling as the on in the repo id.

GDB-5088 Change ontop files on edit repo

---

src/js/angular/controllers.js
src/js/angular/core/directives.js
src/js/angular/core/templates/core-errors.html
src/js/angular/jdbc/controllers.js
src/js/angular/queries/controllers.js
src/pages/autocomplete.html
src/pages/connectorsInfo.html
src/pages/import.html
src/pages/jdbc.html
src/pages/monitor/queries.html
src/pages/rdfrank.html

Introduced new core-errors attrs "ontop". If such is found and such repo, proper message about the restrictions related with repository of type Ontop will be shown to the user. Also added and JDBC page to the those with warning about Virtual Repository, because latter doesn't have data directory.

GDB-5092 Stopped InstanceNotFoundException in Query Monitoring when connected to a virtual repository.

---

src/js/angular/jdbc/controllers.js
src/pages/jdbc-create.html

Also fixes:
GDB-5171 JDBC Incorrect Preview in SQL table configuration page

GDB-5170 JDBC Save and Cancel should close SQL table configuration page

---

src/pages/jdbc-create.html
test-cypress/fixtures/graphdb-import/200-row-allianz.ttl
test-cypress/integration/setup/jdbc.spec.js

Gdb 5100 create jdbc cypress tests

---

.travis.yml

* run acceptance tests in build script
* do not run tests when deploy

Refactor travis stages

---

src/js/angular/repositories/controllers.js
src/js/angular/rest/repositories.rest.service.js

When updating ontop repo files use a copy of the file instead of saving directly the original file

GDB-5214 Revert edit ontop repo files on cancel

---

src/pages/ontorefine.html

GDB-5091 Refine makes no sense being used with ontop repositories. Disable it.

GDB-5091 disable refine for ontop repos

---

src/js/angular/controllers.js
src/js/angular/repositories/controllers.js

Also fixed minor console error in isOntopRepoFileUploaded function.

GDB-5279 Added check for Ontop repository, when is called getQueries.

---

src/js/angular/templates/repositorySize.html

+ Added an additional condition for repository access in repository popover
+ If repository is not writable the access will be set to "Read-only"

GDB-5260 Add additional check for read/write access in popove

---

src/js/angular/explore/controllers.js
src/js/angular/export/controllers.js
src/js/lib/yasr.bundled.js
src/pages/explore.html
src/pages/export.html

Replaced YASR bundle to support shacl context/ Added methods to explore/export controller.

GDB-5242 Added shacl shape graph to graph overview

---

karma.conf.js
package-lock.json
package.json
src/js/angular/core/services/openid-auth.service.js
test/security/openid-service.spec.js

- Extra space in OpenID scope
- Extra & in URL parameters
- Sending some unencoded parameters
- Success callback not called correctly on login with the implicit callback
- Possible errors in corner cases
- Replaced window with $window for better testability
- Unit tests that should cover almost everything

GDB-5344: Various OpenID fixes

---

src/js/angular/core/directives.js

Parameter was not encoded which caused inconsistent resource search

GDB-5363 Fix url param encoding with rdf search box

---

src/css/repository.create.css
src/js/angular/repositories/controllers.js
src/js/angular/repositories/plugin.js
src/pages/choose-repository-type.html
src/pages/repository.html
test-cypress/integration/repository/repositories.spec.js
test/repositories/controllers.spec.js

- Implemented controller/view to choose repository type
- Fixed tests to use new view

GDB-5354 Separate repository type selection from create view

---

package-lock.json
src/js/angular/controllers.js
src/js/angular/core/directives.js
src/js/angular/core/directives/rdfresourcesearch/rdf-resource-search.directive.js
src/js/angular/core/directives/rdfresourcesearch/templates/rdfResourceSearchTemplate.html
src/pages/home.html
test-cypress/integration/home/workbench.home.spec.js
test-cypress/steps/home-steps.js

Removed popup search on home page
Added close icon to home page rdf search
Added {esc} key press listener to home page rfd search to clean input

GDB-5414 Do not show two search boxes on home page

---

test-cypress/integration/setup/my-settings.spec.js

Added cypress tests for changing the default inference, sameAs and count total results in My Settings.

Gdb 5495 extend my settings cypress tests

---

src/css/bootstrap-graphdb-theme.css
src/js/angular/jdbc/controllers.js
src/js/angular/utils/error-utils.js
src/pages/jdbc-create.html
src/pages/jdbc.html

GDB-5558: Usability issues in the JDBC table UI

---

package-lock.json
test-cypress/package.json

Changed package-lock.json file as well

Moved "cypress-wait-until" dependency from devDependencies to dependencies

---

test-cypress/integration/explore/visual.graph.spec.js
test-cypress/integration/setup/my-settings.spec.js

Also changed verification for checked input type button in my-settings.spec.js.

GDB-5728 Added scrollIntoView in visual.graph.spec.js. 

---

src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/pages/graphs-visualizations.html
test-cypress/integration/explore/similarity.spec.js

Small fix in similarity.spec.js.

GDB-5595 Visualized language tags in properties panel. 

---

test-cypress/integration/setup/user-and-access.spec.js

Added tests for creating different user roles, logging in/out, checking for permissions, user deletion.

Gdb 5812 extend users and access cypress tests

---

src/js/angular/controllers.js
src/js/angular/core/directives/rdfresourcesearch/rdf-resource-search.directive.js

Show dashes when trying to get a FedX repository size.
Also disable checking for autocomplete(in rdf-resource-search.directive.js) when FedX repo is active as an error in the logs was ocurring.

Gdb 5962 Get FedX Repo Size

---

src/js/angular/controllers.js
src/js/angular/core/directives/queryeditor/query-editor.controller.js
src/js/angular/core/services/repositories.service.js

Disable all results count in SPARQL editor when the repo is FedX

GDB-6008 Disable count for FedX repos

---

src/js/angular/controllers.js
src/js/angular/core/directives/rdfresourcesearch/rdf-resource-search.directive.js
src/js/angular/repositories/fedx-repo.directive.js

The relevant changes are in the $scope.ok() function. 
Added a toastr error if the repo that the user is trying to add already exists as a member.

GDB-6007 Handle Adding of identical repos as members

---

src/js/angular/core/directives.js
src/pages/dependencies.html
test-cypress/integration/explore/class.hierarchy.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js
test-cypress/support/sparql-commands.js

Manually cherry-picked the changes for GDB-6080 and GDB-6079 that are planned for 9.9.1 release. Also added fixes for cypress tests.

Manually cherry-picked

---

src/js/angular/core/directives.js
test-cypress/integration/home/workbench.home.spec.js

changed openInNewWindowTab to keep the sub path

GDB-5866 Fixed Search RDF results to work behind context path

---

src/js/angular/autocomplete/controllers.js
src/js/angular/core/directives.js
src/js/angular/core/templates/inactive-plugin-warning-page.html
src/js/angular/rdfrank/app.js
src/js/angular/rest/rdf4j.repositories.rest.service.js
src/js/angular/similarity/controllers/similarity-list.controller.js
src/js/angular/sparql-template/controllers.js
src/pages/autocomplete.html
src/pages/rdfrank.html
src/pages/similarity-indexes.html
src/pages/sparql-templates.html
test-cypress/integration/explore/similarity.spec.js

Moved check for active plugin into new inactive plugin directive and added this directive into all plugin views like Similarity, Autocomplete and RDF rank for consistency

GDB-6323 Added check if SPARQL Template plugin is active. 

---

src/js/angular/security/controllers.js
test-cypress/integration/setup/my-settings.spec.js

A modal window is shown when the user clicks Save at "My settings" if he had checked Unset password checkbox. The modal warns the user about the consequences of unsetting the password.

GDB-6448 Warn users when they unset the password

---

src/js/angular/core/directives/queryeditor/query-editor.directive.js
src/js/lib/yasr.bundled.js

Apply syntax highlighting to the explain plan shown in GDB Workbench by using the same colour as the original SPARQL query

GDB-6423 Make explain plan syntax highlighted

---

src/js/angular/security/controllers.js
test-cypress/integration/setup/my-settings.spec.js
test-cypress/integration/setup/user-and-access.spec.js

Added warning  when creating admin user and when editing admin user through Users and Access
Added cypress tests for both cases

GDB-6448 Fix Warn users when they unset the password

---

Jenkinsfile
README.md

cherry picked from master to 1.11

Gdb 6532 delete gdb after build 1.11

---

src/js/angular/security/controllers.js
test-cypress/integration/setup/my-settings.spec.js
test-cypress/integration/setup/user-and-access.spec.js

Last and working version of the fixed cypress test for warning when creating user. Also, after all toggles security to OFF

Gdb 6448 fix warn users when they unset their password master

---

src/js/angular/security/controllers.js
test-cypress/integration/setup/my-settings.spec.js
test-cypress/integration/setup/user-and-access.spec.js

Added warning  when creating admin user and when editing admin user through Users and Access
Added cypress tests for both cases

GDB-6448 Fix Warn users when they unset the password Master

---

test-cypress/integration/setup/user-and-access.spec.js

Cherry-picked changes from fixing cypress tests on warning users when they unset their password

Gdb 6448 fix warn users when they unset their password master 1.11

---

src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/pages/graphs-visualizations.html
test-cypress/integration/explore/visual.graph.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js

If such is detected proper error message is shown to the user. Added cypress test in visual.graph.spec verifying the change.

GDB-6280 Added verification for invalid links value on change. 

---

src/js/angular/settings/controllers.js

Changing the outdated warning.

Fixing Confusing warning when reverting to Free

---

src/css/yasr.custom.css
src/js/angular/core/directives/queryeditor/query-editor.directive.js

Change explain plan highlighting strategy
Change explain plan font to be the same monospaced font as in the editor

GDB-6423 Change explain plan font and detection

---

src/js/angular/queries/controllers.js
src/js/angular/resources/controllers.js
src/pages/monitor/queries.html
src/pages/monitor/resources.html
test/queries/controllers.spec.js

Replace Jolokia error messages

GDB-6407 Remove Jolokia and replace its uses with a REST API

---

src/css/plugins.css
src/js/angular/autocomplete/controllers.js
src/js/angular/controllers.js
src/js/angular/plugins/app.js
src/js/angular/plugins/controllers.js
src/js/angular/plugins/plugin.js
src/js/angular/rest/plugins.rest.service.js
src/pages/plugins.html
test-cypress/integration/setup/plugins.spec.js
test-cypress/integration/sparql/main.menu.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js

Add plugin management from the workbench.
All plugins can be activated/deactivated, except plugin control, because it cannot be deactivated.
Added cypress test.

Gdb 6337 as a user i need to be able to start/stop/list plugins from the workbench master

---

src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/templates/modal/cluster-delete-dialog.html
src/js/angular/rest/cluster.rest.service.js
src/pages/cluster-management/clusterInfo.html

- implemented button and Delete cluster dialog in cluster management

GDB-6753 Implement Delete cluster action

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/templates/modal/cluster-delete-dialog.html
src/pages/cluster-management/cluster-configuration.html
src/pages/cluster-management/clusterInfo.html

- redesigned cluster create page to hide advanced options
- added validation to rpc address
- added validations to advanced option numeric fields
- fixed problem with force delete checkbox not working correctly
- added French translations for cluster

GDB-6813 Fix issues with cluster management

---

src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/pages/cluster-management/cluster-configuration.html

- remove validation for rpc address

GDB-6813 Fix issue with rpc address validation

---

src/css/clustermanagement.css
src/js/angular/clustermanagement/cluster-drawing.service.js
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/directives.js
src/js/angular/clustermanagement/plugin.js
src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
src/pages/cluster-management/clusterInfo.html

- removed old visualization code
- separated component creating to a service ClusterDrawingService
- showing create cluster view in a modal dialog when clicked on cluster zone
- added basic label for when there is cluster

GDB-6401 Create raft cluster visualization

---

src/css/clustermanagement.css
src/js/angular/clustermanagement/cluster-drawing.service.js
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/directives.js
src/pages/cluster-management/clusterInfo.html

- added visualization of cluster nodes
- styled nodes as per node status
- added links between nodes
- styled links as per link status

GDB-6401 Display cluster nodes

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/js/angular/clustermanagement/app.js
src/js/angular/clustermanagement/controllers.js
src/pages/cluster-management/clusterInfo.html

- added a button to show a panel with cluster settings

GDB-6401 Add cluster settings panel

---

src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/directives.js
src/pages/cluster-management/clusterInfo.html
webpack.config.prod.js

- added a tooltip which is visible when clicked on node to display node status

GDB-6401 Add tooltip to cluster nodes

---

src/css/repositories.css
src/js/angular/core/templates/core-errors.html
src/js/angular/repositories/templates/fedx-repo.html

- fixed some sonar issues
- improved the fedex repository create page

GDB-6856 Fix sonar issues

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
src/pages/cluster-management/clusterInfo.html
test-cypress/fixtures/locale-en.json

- aligned delete and settings buttons
- fixed node icons center position on FF
- fixed different cursor in FF. set cursor to pointer for all browsers as the nodes are clickable
- added clarification on cluster create dialog
- set Signature option as default when adding remote locations
- added break-word to endpoints in node tooltip as they might be big
- fixed problem with remote locations not visible if create window is reopened or adding a location errors out

GDB-6868 Cluster UI improvements

---

src/js/angular/clustermanagement/controllers.js
src/pages/cluster-management/clusterInfo.html

- fixed endpoint link not opening new location
- set Signature authentication type as default when adding remote location in cluster view
- fixed problem with cluster configuration side panel not opening once closed

GDB-6870 Fix cluster UI bugs

---

src/js/angular/clustermanagement/controllers.js
test/clustermanagement/controllers.spec.js

- added karma tests for cluster view
- replaced success/error promise methods with then/catch

GDB-6873 Add tests for cluster view

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
test/clustermanagement/controllers.spec.js

- changed error handling logic when adding locations to refetch the new location since an error message might be present there
- fixed overflow style of remote locations list
- fixed typo in label
- set new default values

GDB-6857 Fix issues wit cluster remote locations

---

src/js/angular/rest/security.rest.service.js

Added a function for encoding URI.
The previous implementation had problems encoding some characters in the string component.
I added new function which replaces the problematic characters from the URI string component.

GDB-6853 - add function to remove illegal characters from URI component

---

src/js/angular/repositories/controllers.js
src/pages/repository.html

- the locations failed to load sometimes as they are lazy loaded and the fetch method returns an array or a promise
- added logic to subscribe to the promise if returned
- changed the select to use ng-repeat on option tags

GDB-6861 Fix locations not loading when creating repository

---

src/pages/repository.html

Remove some text that was left

GDB-6861 Remove leftover text in view

---

src/i18n/locale-en.json
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/templates/modal/cluster-edit-dialog.html
src/pages/cluster-management/clusterInfo.html

- implemented dialog and controller to facilitate cluster settings update
- added button in cluster configuration side panel to open edit cluster dialog

GDB-6782 Implement cluster configuration edit action

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/js/angular/clustermanagement/cluster-drawing.service.js
src/js/angular/clustermanagement/controllers.js
src/js/angular/clustermanagement/directives.js
src/pages/cluster-management/clusterInfo.html

- added a legend with all node and link states
- added button to toggle legend visibility

GDB-6865 Add legend to cluster management view

---

src/pages/cluster-management/clusterInfo.html

- added ng-if directive on the button to display it only on the leader

GDB-6923 Hide edit cluster button on non-leaders

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/cluster-drawing.service.js
src/js/angular/clustermanagement/directives.js
src/pages/cluster-management/clusterInfo.html
test-cypress/fixtures/locale-en.json

- cleaned code, styles and i18n labels from old cluster
- added i18n to cluster drawing
- added tooltips for legend labels that exceed boundaries

GDB-6873 Clean old cluster code and add i18n

---

src/app.js
src/res/sparql/keyboard-shortcuts.html
webpack.config.common.js

- added ?v=[AIV]{version}[/AIV] suffix similar to templates
- added some missing translation

GDB-6764 Add version to locale files to avoid caching

---

src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
src/js/angular/clustermanagement/templates/modal/cluster-edit-dialog.html

GDB-6906 Change cluster create and edit ok buttons

---

src/js/angular/clustermanagement/cluster-drawing.service.js

- changed to new "readonly" icon

GDB-6895 Change cluster readonly icon

---

src/css/repositories.css
src/js/angular/repositories/templates/fedx-repo.html

- when creating fedex repository, the button to add remote fedex repository was broken
- reverted old implementation and added some stilyng

GDB-6991 Fix not being able to add remote fedex repo

---

src/js/angular/controllers.js
src/js/angular/core/directives/queryeditor/query-editor.controller.js
src/js/angular/core/services/jwt-auth.service.js
src/js/angular/explore/controllers.js
src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/js/angular/security/controllers.js
src/pages/home.html
src/template.html
test/core/directives/queryeditor/query-editor.controller.spec.js
test/mainCtrl.spec.js
test/security/controllers.spec.js

- the view expects the security principal from jwtAuth Service, which is an async request
- sometimes the request is delayed and a NPE is thrown
- refactored, so if the request is in progress, the controller will wait before using it
- refactored QueryEditorController and some tests to wait for the new promise

GDB-6781 Fix problem with explore view and async requests

---

src/js/angular/import/controllers.js

Add $translate into two importCtrl.controller because $translate was undefined.

GDB-7004 Fix Import View not showing any error when larger than 200mb file is imported

---

src/css/bootstrap-graphdb-theme.css
src/js/angular/autocomplete/templates/modal/add-label.html
src/js/angular/clustermanagement/directives.js
src/js/angular/clustermanagement/templates/modal/add-nodes-dialog.html
src/js/angular/clustermanagement/templates/modal/cluster-create-dialog.html
src/js/angular/clustermanagement/templates/modal/cluster-delete-dialog.html
src/js/angular/clustermanagement/templates/modal/cluster-edit-dialog.html
src/js/angular/clustermanagement/templates/modal/remove-nodes-dialog.html
src/js/angular/core/directives/queryeditor/templates/query-sample.html
src/js/angular/core/templates/modal/copy-to-clipboard-modal.html
src/js/angular/externalsync/templates/deleteConnector.html
src/js/angular/graphexplore/templates/modal/save-graph.html
src/js/angular/import/templates/settingsModal.html
src/js/angular/settings/modal/location-settings.html
src/js/angular/templates/modal/add-fedx-remote-repo.html
src/js/angular/templates/modal/add-location.html
src/js/angular/templates/modal/edit-location.html
src/pages/createConnector.html

- refactored modal dialog views to have the `modal-body` with overflow auto and set modal-content to have max-height 90vh
- set dropdown menus to toggle visibility with display: none/block rather than visibility: visible/hidden

GDB-7014 Fix where scrollbars appear in dialogs

---

src/js/angular/core/services.js

WHEN:
Add a new sub menu in Help menu. The sub menu is missing.
WHY:
All registered extension points are processed one by one. When an extension point is registered we add it as child (submenu) if it has set parent property. The problem is when we try to register an extension point for a parent which is not already registered. We skip such extension point.
HOW:
Added a collection where to save such extension points and when we register a new parent we will try to register all extension points with missed parents.

GDB-7245: Missing sub menu item

---

src/js/angular/guides/steps/complex/enable-autocomplete/plugin.js
src/js/angular/guides/steps/complex/main-menu/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js

WHAT:
Changes implementation of ShepherdService
WHY:
There was an wrong calling onPreviousClick function on previous step instead current one.
HOW:
The correct step function is called.
Additional changes:
Changes implementations of all "guide.step" plugins according service changes.

GDB-7271: Implement guide service

---

src/app.js
src/css/guides.css
src/i18n/locale-en.json
src/js/angular/controllers.js
src/js/angular/guides/app.js
src/js/angular/guides/controllers.js
src/js/angular/guides/guide-utils.js
src/js/angular/guides/guides.service.js
src/js/angular/guides/plugin.js
src/js/angular/guides/steps/complex/main-menu/plugin.js
src/js/angular/guides/steps/core/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js
src/js/angular/repositories/controllers.js
src/pages/guides.html
src/template.html
test-cypress/integration/sparql/main.menu.spec.js
test/repositories/controllers.spec.js
webpack.config.common.js

Added guides page to Workbench.
Added validation before given guide step is executed.
Added new step plugins: "guide-ended" and "info-message".
Fixes labels in "main-menu" plugin.

Added guides page to Workbench.

---

src/i18n/locale-en.json
src/js/angular/core/directives/queryeditor/templates/query-editor.html
src/js/angular/guides/guide-utils.js
src/js/angular/guides/guides.service.js
src/js/angular/guides/steps/complex/create-repository/plugin.js
src/js/angular/guides/steps/complex/download-guide-resource/plugin.js
src/js/angular/guides/steps/complex/enable-autocomplete/plugin.js
src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
src/js/angular/guides/steps/complex/main-menu/plugin.js
src/js/angular/guides/steps/complex/select-repository/plugin.js
src/js/angular/guides/steps/complex/visual-graph/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js

Added "execute-sparql-query" block
- extended function getSteps of the plugins. Added second argument "services" which is object with all needed services for the steps.

GDB-7313: Execute SPARQL query or update

---

src/i18n/locale-en.json
src/js/angular/controllers.js
src/js/angular/guides/guide-utils.js
src/js/angular/guides/guides.service.js
src/js/angular/guides/steps/complex/create-repository/plugin.js
src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
src/js/angular/guides/steps/complex/main-menu/plugin.js
src/js/angular/guides/steps/complex/select-repository/plugin.js
src/js/angular/guides/steps/complex/visual-graph/plugin.js
src/js/angular/guides/steps/core/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js

Added confirmation when user canceled the guide.
Added functionality to stop guide and show error notification if something went wrong.

GDB-7386: Add confirmation on guide user cancel

---

src/js/angular/controllers.js
src/js/angular/guides/steps/complex/select-repository/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js

Added logic to prevent closing select repository menu when click somewhere on the page when a guide is active.

GDB-7450: User Guide crashes on repo select step

---

src/js/angular/guides/steps/complex/import-rdf-file/plugin.js

Problem occurred because of dialog animation. Added a little delay 300ms before step popover dialog to appear.

GDB-7460: User Guide popup dialog panel positioning

---

src/js/angular/guides/guide-utils.js

Fixed bug in GuideUtils functions which creates SPARQL editor selector.

Wrong guide selector when try to show all instance

---

src/i18n/locale-en.json
src/pages/repository.html

Originally included changes for GDB-7467 but they were already merged via another branch.

GDB-5548: Allow shapes to be stored in a user specified named graph - exposed in the UI

---

src/js/angular/core/directives/queryeditor/query-editor.directive.js

Fixed customError message when disabled plugin is called.

GDB-7302-Incomplete error message when you try to query disabled plugin

---

src/js/angular/guides/tour-lib-services/shepherd.service.js

Removed pause button of user guides.

GDB-7505: 'Pause' functionality stability and improvement

---

src/js/angular/guides/guide-utils.js
src/js/angular/guides/guides.service.js
src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
src/js/angular/guides/steps/complex/create-repository/plugin.js
src/js/angular/guides/steps/complex/download-guide-resource/plugin.js
src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
src/js/angular/guides/steps/complex/main-menu/plugin.js
src/js/angular/guides/steps/complex/select-repository/plugin.js
src/js/angular/guides/steps/complex/table-graph/plugin.js
src/js/angular/guides/steps/complex/visual-graph/plugin.js
src/js/angular/guides/steps/core/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js

Added a new function "initPreviousStep" to the all steps. It will be called when "Previous" button is clicked. This function will initialize the state of previous step which will be visualized. If the state of the step depends on its previous step then previous step "initPreviousStep" function will be called and so on until reach a step which not depends on previous one.
Fixed: GDB-7454, GDB-7469, GDB-7476 and GDB-7477

Previous flow issues

---

src/js/angular/security/templates/users.html

* Changed logic not to show create and delete users buttons to logged users with external authority.

GDB-6417 WB: "Create new user" button & screen should not be availabe when using LDAP

---

src/css/plugins.css
src/js/angular/plugins/controllers.js
src/pages/plugins.html

What?
Background color of plugin items is incorrect in plugins view.
Why?
Incorrect set background color on different window sizes. The background color depends on column and rows counts, are they odd or even.
How?
Implemented function applies white or grey style on plugin depends on it position into the table. This function is called when window is resized or plugin list is updated.
There was blinking in the screen every 5 seconds when plugins list is refreshed. Refactoring the controller to refresh the displayed plugins only if they are changed.

GDB-6793: The plugin configuration table is visually changed

---

src/js/angular/similarity/controllers/create-index.controller.js
src/js/angular/similarity/controllers/similarity-list.controller.js

* Inserted check for use of a missing prefix in View mode /View Index Query/.
* Replacing custom prefix in the template for http://www.ontotext.com/graphdb/similarity/instance/ in View mode /View SPARQL Query/.

GDB-7591 The Similarity indexes "Show SPARQL query" gives a broken SPARQL

---

src/pages/namespaces.html
test-cypress/integration/setup/namespaces.spec.js

* Modified Cypress test for namespaces.html as some functionalities were hardcoded for number of prefixes displayed on one page.

GDB-6624 Predefine function prefixes

---

package-lock.json
package.json
src/js/angular/sparql-editor/controllers.js

What?
Added visualization buttons:
* Editor only
* Editor and results
* Results only
* Vertical or Horizontal view
Why?
Our clients needs functionality to switch between different yagui views.
How?
Updates version of "ontotext-yasgui-web-component". Updates component configuration.

GDB-7771: Implement yasgui visualization buttons

---

src/js/angular/namespaces/controllers.js
src/pages/namespaces.html
test-cypress/integration/explore/visual.graph.spec.js
test-cypress/integration/setup/connectors-lucene.spec.js
test-cypress/integration/setup/namespaces.spec.js
test-cypress/steps/visual-graph-steps.js
test-cypress/support/commands.js

* Added guards for stabilizing tests like hiding toasts, invoking for buttons to be visible and reusing custom command cy.pasteQuery.

GDB-7803 Fix flaky Cypress tests before WB release.

---

package-lock.json
package.json
src/js/angular/rest/mappers/saved-query-mapper.js
src/js/angular/rest/sparql.rest.service.js
src/js/angular/sparql-editor/controllers.js
src/pages/sparql-editor.html
test-cypress/integration/sparql-editor/actions/delete-query.spec.js
test-cypress/steps/yasgui/yasgui-steps.js

Integrate the delete saved query action.
Delete saved query action exists in current implementation in the GDB WB. It allows the user to delete an existing saved query.
* Introduced additional event handler for the delete action.

GDB-7784 integrate delete saved query action

---

package-lock.json
package.json
test-cypress/integration/sparql-editor/actions/expand-results-over-sameas.spec.js
test-cypress/integration/sparql-editor/actions/include-inferred-statements.spec.js
test-cypress/steps/yasgui/yasqe-steps.js

Allow the client to include inferred statements and expand results over owl:sameAs.
The WB has these features.
* Introduced include inferred statements action in the editor which controls the value of the `infer` request parameter.
* Introduced expand results over owl:sameAs action in the editor which controls the value of the `sameAs` request parameter.

GDB-7786 Introduce actions to include inferred statements and expand results over owl:sameAs

---

src/js/angular/sparql-editor/controllers.js

When security is enabled an Authorization header holding auth token must be sent with the request.
In order to be able to execute queries when GDB security is enabled.
* When there is a token found add it in the request headers map.

GDB-7890 support authentication when security is enabled

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/pages/repository.html
test-cypress/fixtures/locale-en.json

* Added warning in Create FedX Repo page for being an experimental feature.

GDB-7727 GraphDB becomes unresponsive when FedX repositories are used

---

src/i18n/locale-en.json
src/js/angular/resources/chart-models/performance/connections-chart.js
src/js/angular/resources/chart-models/performance/epool-chart.js
src/js/angular/resources/controllers.js
src/pages/monitor/resources.html
test-cypress/integration/monitor/monitor.resources.spec.js
test/resources/controllers.spec.js

Refactor the error handling so that an error of one request will not hide whole page
This will allow the user to see available data, even when some requests fail.
- refactored the error handling and made it more generic
- if an error is encountered, the request is retried several times, set in MAX_RETRIES constant

GDB-7889 Refactor error handling in monitor view

---

package-lock.json
package.json
src/app.js
src/js/angular/sparql-editor/controllers.js
src/pages/sparql-editor.html
test-cypress/integration/sparql-editor/internationalization.spec.js
test-cypress/integration/sparql-editor/yasr/table-plugin.spec.js
test-cypress/steps/yasgui/table-plugin-steps.js
test-cypress/steps/yasgui/yasr-steps.js

What?
Integrate the extended table yasr plugin.
Why?
There is a custom cell formatting in WB table yasr plugin. All resource are present with short uri and every one has a button to copy link resource.
How?
Update version of ontotext-yasgui-web-component

GDB-7711: Extend table plugin

---

src/models/ontotext-yasgui/event-data-type.js
src/models/ontotext-yasgui/notification-message-type.js
src/models/ontotext-yasgui/yasr-plugin-name.js

Convert event type classed to just simple objects.

Convert event type classed to just simple objects.

---

src/js/angular/resources/chart-models/resource/heap-memory-chart.js
src/js/angular/resources/chart-models/resource/non-heap-memory-chart.js

Max memory for off heap memory usage should be visible if available
To be like on heap chart
- added common logic in the HeapMemoryChart class

GDB-7936 Show max off heap memory in monitor view

---

src/js/angular/core/services/jwt-auth.service.js
src/js/angular/resources/controllers.js
src/js/angular/utils/user-utils.js
src/pages/monitor/resources.html

Repo manager role has restriction to view performance tab
The permissions for the monitoring view are set by the backend by adding ROLE_MONITORING to the user roles
- removed condition from view

GDB-7941 Remove repo manager role restriction

---

package-lock.json
package.json

The version introduces the sesame-prefixes and sparql functions autocompleter.

GDB-7709 and GDB-8007 increased version of ontotext-yasgui component

---

src/js/angular/rest/autocomplete.rest.service.js
src/js/angular/sparql-editor/controllers.js

Implemented a local names autocompleter and registered in yasqe.
The autocompleter allows suggesting namespaces from the GDB instance to which the WB is connected.
Implemented the autocompleter and provided a new configuration allowing custom autocomplete functions to be provided by the component client.

GDB-7760 introduce local names autocomplete

---

Jenkinsfile
docker-compose.yml
package.json
test-cypress/cypress-flaky.config.js
test-cypress/cypress-reporter-config.json
test-cypress/cypress.config.js
test-cypress/package-lock.json
test-cypress/package.json
test-cypress/plugins/index.js

- enabled video recording
- added cypress-multi-reporters and mocha-junit-reporter to generate xml reports
- added uploading to jenkins of reports, screenshots and videos

GDB-7829 Add video recording and artefact upload to jenkins

---

package-lock.json
package.json
src/js/angular/sparql-editor/controllers.js
src/js/angular/utils/query-types.js
src/models/ontotext-yasgui/count-query-request-event.js
src/models/ontotext-yasgui/query-mode.js
src/models/ontotext-yasgui/query-request-event.js
src/models/ontotext-yasgui/query-type.js

Updates query headers with correct headers and values.
The different queries have a different Accept header.
Setting an appropriate Accept header value depends on the query mode and type.

GDB-8132: Add appropriate headers depending on query mode and type

---

src/js/lib/yasr.bundled.js
test-cypress/integration/sparql/sparql-language-change.spec.js

Chery-picked commits for issue GDB-8100

Cherry-pick gdb 8100

---

src/js/lib/yasr.bundled.js

- update the YASR bundle with latest changes until revision a63366e9364e9a5ac0822df7adfbf1a9491e4d4b from 18.04.2023

GDB-8154 Update YASR bundle with latest changes

---

src/js/lib/yasr.bundled.js

- update the YASR bundle with latest changes until revision a63366e9364e9a5ac0822df7adfbf1a9491e4d4b from 18.04.2023
(cherry picked from commit 030cb55ef1d4dc92572144c173e648ac981d2b9d)

Cherry-pick from master GDB-8154 Update YASR bundle with latest changes (#914)

---

package-lock.json
package.json
src/js/angular/security/templates/user.html
src/js/angular/sparql-editor/controllers.js
test-cypress/integration-flaky/sparql-editor/actions/execute-update-query.spec.js
test-cypress/integration-flaky/sparql-editor/lucene-connector.spec.js
test-cypress/integration-flaky/sparql/sparql-language-change.spec.js
test-cypress/integration/sparql-editor/actions/execute-update-query.spec.js
test-cypress/integration/sparql-editor/actions/expand-results-over-sameas.spec.js
test-cypress/integration/sparql-editor/actions/include-inferred-statements.spec.js
test-cypress/integration/sparql-editor/actions/share-query.spec.js
test-cypress/integration/sparql-editor/saved-query/abort-query.spec.js
test-cypress/integration/sparql-editor/yasgui-tabs.spec.js
test-cypress/integration/sparql/sparql-language-change.spec.js
test-cypress/package-lock.json
test-cypress/steps/lucene-connector-steps.js
test-cypress/steps/yasgui/yasqe-steps.js
test-cypress/steps/yasgui/yasr-steps.js
test-cypress/stubs/security-stubs.js
test-cypress/stubs/yasgui/query-stubs.js

The configuration "infer" and "sameAs" don't applied to "ontotext-yasgui-web-component" as default when open a new tab.
WB has such implementation.
Updates version of "ontotext-yasgui-web-component". Adds configuration for "infer" and "sameAs" depends on user settings.

GDB-8186: configure "infer" and "sameAs" depends on user settings

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/queryeditor/query-editor.controller.js
src/js/angular/core/directives/queryeditor/query-editor.directive.js
src/js/angular/graphexplore/controllers/graphs-config.controller.js
test-cypress/fixtures/locale-en.json

GDB-8199: Requesting explain plan via the Workbench doesn't work for DESCRIBE queries

Fix GDB-8199 explain plan for DESCRIBE queries

---

src/js/angular/repositories/ontop-repo.directive.js
test-cypress/integration/repository/ontop-repository.spec.js

When the user fills some fields in ontop create/edit form and changes the driver type, then filled data is not cleared.
Requirements were changed.
Clears the form data object when user changes the driver type. An exception is when user is open some repository for edit. If user changes the driver, all data wll be cleared, but if user return back to saved driver then all data will be filled again.

GDB-8349: Clear user input

---

src/js/angular/repositories/ontop-repo.directive.js
src/js/angular/repositories/templates/ontop-repo.html
src/models/ontop/jdbc-driver-type.js
src/models/ontop/ontop-driver-data.js
test-cypress/integration/explore/class.hierarchy.spec.js
test-cypress/integration/explore/class.relationships.spec.js
test-cypress/integration/repository/ontop-repository.spec.js
test-cypress/steps/class-views-steps.js
test-cypress/steps/ontop-repository-steps.js

The url of Snowflake driver is not populate properly.
When jdbc driver is Snowflake then url has different url template than other drivers and the generic calculation of url is not applicable to it.
Implemented different calculation function specific for Snowflake.

GDB-8419: Snowflake Account identifier is not properly mapped in the URL

---

src/js/angular/core/directives/yasgui-component/templates/yasgui-component.html
src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/core/services/event-emitter-service.js
src/js/angular/core/services/repositories.service.js
src/js/angular/core/services/translation.service.js
src/js/angular/jdbc/controllers.js
src/js/angular/sparql-editor/app.js
src/js/angular/sparql-editor/controllers.js
src/js/angular/sparql-template/controllers.js
src/models/connectors/connector-command.js
src/pages/sparql-editor.html
webpack.config.common.js

Wraps "ontotext-yasgui-web-component" with a directive.
Simplify integration of the component.
Creates a directive and refactoring the "Sparql" view to use it.

Create a directive that wraps ontotext-yasgui-web-component

---

src/js/angular/similarity/controllers/similarity-list.controller.js
src/pages/similarity-indexes.html

- Reorganize functions in "similarity-list.controller.js";
- Optimizes loading of view;
- Added repository change listener;
- Optimizes the checks can write active repo and is active repo GraphDB repo;
- Optimizes loading of similarity indexes.
Cleans the code before updating the yasgui. Reduces the changes that have to be made.
- Separates the functions depends on them usage and scope;
- The view is initialized when active repository is set.
- Added repository change listener. When the active repository is changed, the list has to be reloaded.
- Removes functions "getActiveRepository", "canWriteActiveRepo", "isActiveRepoOntopType" and "isActiveRepoFedXType" from the view template. Added property that holds the value of those functions. The values are calculated when component is loaded …

GEDB-8479 Refactoring of similarity indexes view

---

src/js/angular/models/similarity/similarity-index-status.js
src/js/angular/models/similarity/similarity-index-type.js
src/js/angular/models/similarity/similarity-result-type.js
src/js/angular/models/similarity/similarity-search-type.js
src/js/angular/similarity/controllers/similarity-list.controller.js
src/pages/similarity-indexes.html

Refactoring of similarity indexes view
- Defining the similarity "search type" type;
- Defining the "result type" type;
- Defining the "similarity index" status;
- Defining the "similarity index" type;
- Convert function to arrow function.
- Type Safety. Improved Code Quality. Performance Optimization.
- Extracts all possible values of similarity search type in a constant 'SimilaritySearchType';
- Extracts all possible values of similarity result type in a constant 'SimilarityResultType';
- Extracts all possible values of similarity index status in a constant 'SimilarityIndexStatus';
- Extracts all possible values of similarity index type in a constant 'SimilarityIndexType.

GDB-8479 clean old code before update yasgui

---

src/js/angular/models/similarity/similarity-index.js
src/js/angular/models/similarity/similarity-search.js
src/js/angular/rest/mappers/similarity-index-mapper.js
src/js/angular/similarity/controllers/similarity-list.controller.js
src/pages/similarity-indexes.html

- Defining the "similarity index" object definition;
- Defining the "similarity search" object definition;
- Rename some variable name:
  - "selected" => "selectedSimilarityIndex";
  - "index" => "similarityIndex";
  - "deleteIndex" => "deleteSimilarityIndex".
- Type Safety. Improved Code Quality. Performance Optimization.
- The name was а little ambiguous.
- Creates a class 'SimilarityIndex' that represents a similarity index;
- Creates a class 'SimilaritySearch' that represents a similarity search.

GDB-8479 Refactoring of similarity indexes view

---

src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/js/angular/rest/graph-data.rest.service.js
src/js/angular/utils/string-utils.js

Moving things around, fixing lint issues, formatting, changing the scope of functions and fields.
The controller needs to be tidied up in order to make it more maintainable and easier to integrate the yasgui component at the end.

GDB-7731 initial graphs visualization controller refactoring

---

src/js/angular/graphexplore/controllers/graphs-config.controller.js
src/pages/graph-config/saveGraphConfig.html

Moving things around, fixing lint issues, formatting, changing the scope of functions and fields.
The controller needs to be tidied up in order to make it more maintainable and easier to integrate the yasgui component at the end.

GDB-7731 graphs config controller and template cleanup

---

src/js/angular/clustermanagement/controllers.js

GDB-8369 Ascertaining whether the error is a 403 and calls getError(error.data, error.status) if it is

GDB-8369 Cluster View broken toast error for lack of user permissions

---

src/js/angular/clustermanagement/controllers.js

GDB-8369 Cluster View broken toast error when deleting a node

---

src/js/angular/clustermanagement/controllers.js

(cherry picked from commit da8347379a2a1cb5294ee79b76504c9b2dab0521)

GDB-8369 cherry pick into 2.2

---

src/css/graphs-config.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
src/js/angular/graphexplore/app.js
src/js/angular/graphexplore/controllers/graphs-config.controller.js
src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/js/angular/models/graphs/graphs-config.js
src/js/angular/models/repository/repository.js
src/js/angular/rest/graph-config.rest.service.js
src/js/angular/rest/mappers/graphs-config-mapper.js
src/pages/graph-config/saveGraphConfig.html
src/pages/graphs-visualizations.html
test-cypress/integration/explore/visual-graph/graphs-config.spec.js
test-cypress/integration/explore/visual-graph/visual.graph.spec.js
test-cypress/steps/visual-graph-steps.js
test-cypress/steps/yasgui/yasqe-steps.js
test-cypress/support/visual-graph-commands.js

Integrated the ontotext-yasgui component in the graphs config view.
According to the plans, old yasgui needs to be replaced with the latest version of the yasgui in order to mitigate vulnerability issues and allow easier upgrade in future.
* Refactored the graphs config controller and template in order to plug in the new component.
* Removed obsolete and redundant code.

GDB-7731 integrate yasgui in graphs config view

---

package-lock.json

Recreated the package-lock.json file.
For some reason the file was corrupted/de-synchronized from the package.json which made the release build to fail.
Deleted the file and reinstalled all dependencies and added the newly generated file again.

Recreate the package-lock.json file

---

src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/graphexplore/controllers/graphs-config.controller.js
src/js/angular/similarity/controllers/create-index.controller.js
src/js/angular/sparql-editor/controllers.js
test-cypress/integration-flaky/explore/visual.graph.spec.js
test-cypress/integration/explore/visual-graph/graphs-config.spec.js

The endpoint configuration has been converted to a function rather than a string.
When endpoint is a string it is persisted in browser local store. When a query is run the value is taken from the store, no matter that the endpoint configuration is changed. If endpoint is function then the function is called every time query is executed.
Changed endpoint to be function.

GDB-8516 Changed the endpoint configuration to be a function instead of a string.

---

src/css/export.css
src/pages/cluster-management/clusterInfo.html
src/pages/export.html
src/pages/home.html
src/pages/licenseInfo.html
src/pages/login.html

Change the position and order of some action buttons.
Those were forgotten during the overall redesign done with the GDB-8598 task.
Just reorder them in the html or style them to appear on the right.

GDB-8633 change order and position of buttons

---

docs/developers-guide.md
package-lock.json
package.json
src/css/bootstrap-graphdb-theme.css
src/css/clustermanagement.css
src/css/sparql-editor.css
src/js/angular/clustermanagement/cluster-drawing.service.js
src/js/angular/core/services/theme-service.js
src/themes/default/plugin.js
src/themes/onto-original/plugin.js

Applied multiple fixes in the sparql view and some other places like the main menu.
There were some inconsistencies in the colors and also differences between the old and the new yasgui in the WB. And as well as we wanted to be as close as possible to the old look we needed to apply some improvements.
Fixes applied in the visualiozation can be seen individually in the respective commits.

GDB-8626 visual improvements in sparql view

---

src/js/angular/guides/tour-lib-services/shepherd.service.js

The "Previous" button has been removed from the last dialog.
The requirements were changed, necessitating the update.
The "Previous" button has been removed from the last dialog.

GDB-8633 Missed buttons that need to be swapped to comply with new button redesign

---

package-lock.json
package.json
src/js/angular/jdbc/controllers.js
src/js/angular/similarity/controllers/create-index.controller.js
src/js/angular/similarity/controllers/similarity-list.controller.js
src/pages/create-index.html
src/pages/explore.html
src/pages/jdbc-create.html
src/pages/similarity-indexes.html
test-cypress/integration/setup/jdbc-create.spec.js
test-cypress/steps/yasgui/yasgui-loader.js

-All views with "ontotext-yasgui-web-component" is changed to use "ontotext-yasgui-web-component" loader.
We made this change to ensure a consistent loader experience across all pages featuring the "ontotext-yasgui-web-component".
- Upgraded the version of "ontotext-yasgui-web-component";
- Replaced the WB loader with the 'ontotext-yasgui-web-component' one.

GDB-8021 Updates loader when a query is executed.

---

package-lock.json
package.json
src/css/lib/ontotext-yasgui-web-component.css
src/js/angular/explore/controllers.js

[GDB-8684](https://ontotext.atlassian.net/browse/GDB-8684) Changed Minimum Height of the Container Holding the YASR Plugin Buttons;
[GDB-8191](https://ontotext.atlassian.net/browse/GDB-8191): Changed formatting of error message;
[GDB-8684](https://ontotext.atlassian.net/browse/GDB-8684): Added "filter query result" to resource view;
[GDB-8193](https://ontotext.atlassian.net/browse/GDB-8193): No Space Between "Visual" Button Icon and Label
- When [GDB-8684](https://ontotext.atlassian.net/browse/GDB-8684) was implemented, the component was configured to display result info that didn't have a result info message. As a result, the toolbar appeared small and unattractive;
- The error message has extra spaces;
- Added "filter query result" to resource view;
- There was no space between the …

Fixes visual issues 

---

.gitignore
package-lock.json
src/css/aclmanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/aclmanagement/app.js
src/js/angular/aclmanagement/controllers.js
src/js/angular/aclmanagement/model.js
src/js/angular/aclmanagement/plugin.js
src/js/angular/rest/aclmanagement.rest.service.js
src/js/angular/rest/mappers/aclmanagement-mapper.js
src/pages/aclmanagement.html
test-cypress/fixtures/locale-en.json
test-cypress/fixtures/setup/aclmanagement/get-rules.json
test-cypress/integration/setup/aclmanagement.spec.js
test-cypress/integration/sparql/main.menu.spec.js
test-cypress/steps/setup/acl-management-steps.js

Implemented an ACL management page.
By requirement.
* Implemented the page, services, tests.
* Recreated the package-lock.json due to inconsistencies.

GDB-8753 Implemented ACL management page

---

src/js/angular/import/controllers.js
src/js/angular/import/templates/urlImport.html
src/js/lib/yasr.bundled.js
test-cypress/integration/sparql/sparql.menu.spec.js

Added support for ND-JSONLD file formats in the library and updated
To enhance the download compatibility and usability, this commit introduces support for ND-JSONLD file format
- added support for ND-JSONLD file formats in the library and updated
- added the ND-JSONLD file format to the import RDF from snipped dialog and to the import from url

GDB-8281 add ND-JSONLD file format to download of SPARQL editor

---

src/css/backup-and-restore.css
src/pages/monitor/backup-and-restore.html

Removed the loader that indicates that the backup and restore page is being updated.
The team decided that this confuses clients, as they might think something is happening, but it never ends.
Removed the loader and cleaned up the code.

GDB-8759: Implement operations status component in the WB

---

src/css/aclmanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/aclmanagement/controllers.js
src/js/angular/aclmanagement/model.js
src/pages/aclmanagement.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/setup/aclmanagement.spec.js
test-cypress/steps/setup/acl-management-steps.js

Implemented the ACL rule creation functionality.
By requirement.
* Implemented the add rule and cancel operations in the controller.
* Extended the ACL management table component implementing an editable form with fields for each rule property.

GDB-8754 Implemented ACL rule creation functionality

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/aclmanagement/controllers.js
src/js/angular/core/templates/modal/modal-warning.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/setup/aclmanagement.spec.js
test-cypress/steps/setup/acl-management-steps.js

Implemented the delete ACL rule operation
By requirement users should be able to delete rules from the ACL list
* Implemented the action which raises a confirmation for the operation and deletes the rule from the list.
* Implemented a test.

GDB-8756 delete ACL rule operation

---

src/css/backup-and-restore.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/backup-and-restore/controllers.js
src/pages/monitor/backup-and-restore.html
test-cypress/fixtures/locale-en.json
test-cypress/support/repository-commands.js

Add a pause button to the 'Backup and Restore' view.
To be consistent with the 'Query and Update' view. When the pause button is pressed, the page should stop updating information.
Added a pause button. When the button is clicked, the page stops reloading.

GDB-8804: Add a pause button to the backup and restore view.

---

src/css/dependencies.css
src/css/rdf-class-hierarchy.css
src/pages/dependencies.html

Graphdb logo in upper left corner of WB is resizing when switching to various WB sections
Some page stylesheets override the styles for svg selector without being specific, which causes the logo (svg) to change it's size
- made the css selectors more specific for svg elements by adding a css class to the elements

GDB-8818 Fix inconsistency in GDB logo

---

src/pages/aclmanagement.html
src/pages/jdbc-create.html
src/pages/sparql-template-create.html

Fix the color to match the new color scheme
It was omitted in acl management, jdbc create and sparql template create views
Added appropriate color class

GDB-8910 fix info icon color in some views

---

src/app.js
src/css/aclmanagement.css
src/css/autocomplete-select.css
src/js/angular/aclmanagement/controllers.js
src/js/angular/core/directives/autocomplete/autocomplete.directive.js
src/js/angular/core/directives/autocomplete/templates/autocomplete.html
src/js/angular/rest/mappers/autocomplete-mapper.js
src/js/angular/rest/mappers/namespaces-mapper.js
src/pages/aclmanagement.html
test-cypress/integration/explore/similarity.spec.js
test-cypress/integration/setup/aclmanagement/create-rule.spec.js
test-cypress/integration/setup/aclmanagement/delete-rule.spec.js
test-cypress/integration/setup/aclmanagement/edit-rule.spec.js
test-cypress/integration/setup/aclmanagement/revert-rules.spec.js
test-cypress/integration/setup/aclmanagement/update-rules.spec.js
webpack.config.common.js

IRI autocomplete component is implemented and integrated it in the ACL management view.
This improves the user experience allowing easier completion of triples when editing acl rules.
Implemented the autocomplete component based on the rdf-resource-search component.
Integrated the component in the ACL management view.

GDB-8810 introduces iri autocomplete select and integrates it in the acl view

---

test-cypress/integration/explore/similarity.spec.js
test-cypress/integration/setup/my-settings.spec.js
test-cypress/integration/sparql/sparql.menu.spec.js
test-cypress/support/sparql-commands.js

Cherry-pick some cypress test fixes for flakyness from master

Cherry-pick some cypress test fixes for flakyness from master

---

src/css/lib/ontotext-yasgui-web-component.css

Fix styling of download as menu and visual graph button
Styling of the download as and visual graph buttons was a bit different than the old version.
Updated the styles to better match the old styling.

GDB-8677 fix styling of download as menu and visual graph button

---

src/js/angular/graphexplore/directives/dependencies-chord.directive.js
src/js/angular/graphexplore/directives/domain-range-graph.directive.js
src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
src/js/lib/common/svg-export.js

GDB-8986 Fix svg downloads

---

src/css/lib/ontotext-yasgui-web-component.css

Change position and size of yasqe buttons.
Try to match the existing workbench look and feel as much as possible,
Overriding the yasqe buttons styles.

GDB-8994 Change position and size of yasqe buttons

---

src/css/lib/ontotext-yasgui-web-component.css

Change the ask query result colors.
Try to match the existing workbench look and feel as much as possible.
Overriding of the yasr plugin colors for ask query

GDB-9001 Change the ask query result colors

---

src/css/bootstrap-graphdb-theme.css
src/css/lib/ontotext-yasgui-web-component.css

Change the line numbers color in yasqe.
Try to match the existing workbench look and feel as much as possible,
Remove the overriding of the yasqe line numbers colors.

GDB-8989 Change the line numbers color in yasqe

---

src/css/lib/ontotext-yasgui-web-component.css

Restyle the saved queries dialog in sparql editor.
Try to match the existing workbench look and feel as much as possible.
Overriding of the styles from ontotext-yasgui component to match more closely the once from the workbench.

GDB-9005 Restyle the saved queries dialog in sparql editor

---

src/js/angular/explore/statements.service.js

What
Trying to edit a resource gives a toast saying a syntax issue.
Why
Inabillity to escape a quotation mark inside a String.
How
Inserted check if there is a quotation mark present in the string and surround with single quotes rather than double quotes.

GDB-8336 WB edit of some context triples gives syntax toast errors

---

src/css/lib/ontotext-yasgui-web-component.css

Improve styling of yasr plugin tabs.
Make it consistent with the old yasgui.
Put some explicit margin-right on tabs to make it similar to old yasgui

GDB-8996 improve styling of yasr plugin tabs

---

src/js/angular/autocomplete/controllers.js
src/js/angular/clustermanagement/controllers/add-nodes.controller.js
src/js/angular/clustermanagement/controllers/edit-cluster.controller.js
src/js/angular/clustermanagement/controllers/remove-nodes.controller.js
src/js/angular/core/directives/queryeditor/query-editor.controller.js
src/js/angular/explore/controllers.js
src/js/angular/externalsync/controllers.js
src/js/angular/graphexplore/controllers/graphs-config.controller.js
src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
src/js/angular/graphexplore/directives/domain-range-graph.directive.js
src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
src/js/angular/guides/guides.service.js
src/js/angular/import/controllers.js
src/js/angular/import/templates/urlImport.html
src/js/angular/jdbc/controllers.js
src/js/angular/repositories/controllers.js
src/js/angular/repositories/ontop-repo.directive.js
src/js/angular/security/controllers.js
src/js/angular/similarity/controllers/create-index.controller.js
src/js/angular/sparql-template/controllers.js
src/pages/namespaces.html
test/lib/angularjs/1.3.8/angular-mocks.js

Remove/replace vulnerable code from reported vulnerabilities
So the WB is less vulnerable
- replace angular.copy() with _.cloneDeep()
- remove type from input type="url"

GDB-8975-remove-vulnerable-code

---

src/js/angular/resources/chart-models/chart-data.js
src/js/angular/resources/chart-models/resource/heap-memory-chart.js

Fix issues with charts when no series are selected
Causes the axis labels to show strange things
- added an if condition to not update chart if all series are disabled

GDB-9197 Fix issues with charts

---

src/css/lib/ontotext-yasgui-web-component.css

Fix spacing between icon and label in visual graph button.
It's needed for better user perception.
Added some gap between the icon and label in the button

GDB-8193 fix spacing between icon and label in visual graph button

---

package-lock.json
package.json
test-cypress/integration/sparql-editor/yasr/pagination.spec.js

Update ontotext-yasgui component version
There are a bunch of fixes in the component
Increased the version

Update ontotext-yasgui component version

---

src/pages/graph-config/saveGraphConfig.html

Reorder buttons in visual graph config page.
For consistency with other views in the workbench.
Just reordered the buttons in the template.

GDB-9175 reorder buttons in visual graph config page

---

package-lock.json
test-cypress/integration-flaky/sparql-editor/plugins/error-plugin.spec.js
test-cypress/integration-flaky/sparql-editor/yasr/table-plugin.spec.js
test-cypress/integration/sparql-editor/yasr/table-plugin.spec.js

Moving flaky tests in the flaky test suite.
We can't make them work reliably on CI server at the  moment and this makes the build break too often.
Moved them in the flaky suite.

Moving flaky tests in the flaky test suite

---

src/css/lib/ontotext-yasgui-web-component.css

Restyle yasqe autocomplete dropdown menu.
For consistency with current workbench.
Changed the css applied to it.

GDB-9004 restyle yasqe autocomplete dropdown menu

---

src/js/angular/core/services/jwt-auth.service.js

Get error and display in toast error message in Users and Access View
Error is not displayed
* Made toast message extract error text message from its data.
* Escaped close to immediate refreshing of security so toast message is visible.

GDB-9296 Improve error message when attempting to change security without total quorum

---

src/css/lib/ontotext-yasgui-web-component.css

Change the font size in yasgui dialog body
For consistency with the current workbench.
Extended the style overrides for the yasgui component.

GDB-9269 change yasgui dialog font size

---

src/css/lib/ontotext-yasgui-web-component.css

Fix styling of certain tags inside yasgui.
The tags and elements should have a consistent font size and match the current workbench.
Updated the styles to include the missed tags.

GDB-8247 fix styling of certain tags inside yasgui

---

package-lock.json
package.json
test-cypress/steps/yasgui/share-saved-query-dialog.js

Get latest ontotext-yasgui library version.
Get latest features and fixes incorporated in the library.
Increased the version to 1.1.13

Get latest ontotext-yasgui library version

---

src/css/lib/ontotext-yasgui-web-component.css

Increase ask query result font size.
Add font-size style to sparql ask query result element.

GDB-9001 increase ask query result font size

---

src/css/lib/ontotext-yasgui-web-component.css

Change background color of the yasr error plugin.
Add proper background color coming from the predefined theme

GDB-8677 change background color of the yasr error plugin

---

src/css/lib/ontotext-yasgui-web-component.css

Restyle query abort button.
Changed font, height, position.

GDB-9410 restyle query abort button

---

src/css/lib/ontotext-yasgui-web-component.css
src/css/sparql-editor.css

Restyle yasgui layout buttons.
Change font size, height, reposition orientation button, added media query to float buttons properly below the heading on small resolutions

GDB-9412 restyle yasgui layout buttons

---

package-lock.json
package.json
src/js/angular/core/directives/yasgui-component/templates/yasgui-component.html
src/js/angular/core/directives/yasgui-component/yasgui-component-directive.util.js
src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/models/ontotext-yasgui/event-data-type.js
src/js/angular/models/ontotext-yasgui/save-query-opened.js
src/js/angular/models/ontotext-yasgui/tab.js
src/js/angular/models/yasgui-component.js
src/js/angular/sparql-editor/controllers.js
src/js/angular/utils/yasgui-utils.js

Added a very brief highlighting of the tab name in red when a tab is opened from a saved query or via a URL parameter.
This functionality exists in the current Workbench.
Extended the highlighting when a new tab is opened from a saved query or via a URL parameter.

GDB-9338: When opening a saved query, there should be a very brief highlighting of the tab name in red

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/export/controllers.js
src/js/angular/export/templates/exportSettingsModal.html
src/js/angular/import/controllers.js
test-cypress/fixtures/locale-en.json

Address task comments.
In order to be completed the task.
Added context link when importing from text snippet and JSON-LD or NDJSON-LD is selected.
Removed the check for context/frame link in the export settings modal because it can be empty.

GDB-9211 and GDB-9198

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/export/controllers.js
src/js/angular/export/templates/exportSettingsModal.html
src/js/angular/import/controllers.js
test-cypress/fixtures/locale-en.json

Reverts Ontotext-AD/graphdb-workbench#1221

Revert "GDB-9211 and GDB-9198"

---

package-lock.json
src/css/aclmanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/pages/aclmanagement.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/setup/aclmanagement/scopes.spec.js
test-cypress/steps/setup/acl-management-steps.js

Fixing UI/UX issues in the ACL view.
For better perceiving and user experience.
* Changed the editable role field placeholder.
* Changed negated role text styling in preview mode to be consistent with the other properties in preview mode.
* Changed the blank role value styling in preview to be consistent with the blank value displayed for the other properties.
* Removed the fake button for save rule operation when there are invalid data in the rule. Now the actual save button is used for both states by just enabling/disabling it.
* Tooltip of Create rule button says “Add rule” - either remove it or add something more descriptive
* Tooltip of checkmark icon to end editing says “Apply rule”. Better something like “Confirm rule editing”
* Moved asterisk on tabs in front of the label and made …

GDB-9478 fixing UI/UX issues in the ACL view

---

package-lock.json
package.json

Update yasgui component version to 1.1.26
* GDB-8247 improve styling of yasr results containing long strings

Update yasgui component version to 1.1.26

---

src/css/aclmanagement.css
src/css/bootstrap-graphdb-theme.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/aclmanagement/controllers.js
src/js/angular/aclmanagement/model.js
src/js/angular/core/directives/autocomplete/autocomplete.directive.js
src/js/angular/core/directives/autocomplete/templates/autocomplete.html
src/pages/aclmanagement.html
src/template.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/setup/aclmanagement/scopes.spec.js
test-cypress/steps/setup/acl-management-steps.js

Fixing UI/UX issues in the ACL view.
For better perceiving and user experience.
- Adjust dropdown to align with the right edge of the table to enhance UI consistency.
- Increase error outline to 2px for better visibility of validation errors.
- Disable tab buttons in edit mode to prevent unintended tab switches.
- Align table content to the top for uniform presentation.
- Highlight the edit row in yellow (from `#ux-test1`) to clearly indicate the editable state.
- Change the 'X' icon in edit mode to gray for a subtler UI indication.
- Mark scope tabs with an exclamation icon to signify changes.
* fix notes, add basic validation, fix tests
* add default values description, add RDF star simple validation
* add clear graph asterisk special value
* Make the save/cancel buttons bar sticky and …

GDB-9493 Fix ACL UI/UX issues

---

src/js/angular/controllers.js

Saved SPARQL queries are not loaded when the user is logged in.
The authentication headers are still not set correctly when a request that loads saved queries is called and the $unauthorizedInterceptor rejects the request.
There was another issue (GDB-8091) with the same problem. Then, a setTimeout was added, which in this case is not enough for the authentication header to be properly set. The loading of saved queries was moved after the initialization of the authentication principal.
** Created GDB-9547 issue for tracking the effort for improving the implementation instead of just finding workarounds

GDB-9513: Saved queries are not displayed on the welcome page

---

src/js/angular/controllers.js

Saved SPARQL queries are not loaded when the user is logged in.
The authentication headers are still not set correctly when a request that loads saved queries is called and the $unauthorizedInterceptor rejects the request.
There was another issue (GDB-8091) with the same problem. Then, a setTimeout was added, which in this case is not enough for the authentication header to be properly set. The loading of saved queries was moved after the initialization of the authentication principal.

Cherry-pick from master GDB-9513: Saved queries are not displayed on the welcome page

---

sonar-project.js
test-cypress/package.json

Test run for comparison with main branch

improve-sonar-analysis

---

src/css/ux-test1.css
src/js/angular/controllers.js
src/pages/ux-test1.html

The majority of components in the Workbench have been added to `/ux-test1` page.
Having the components in one view will allow easier implementation and style matching when the new design system is being applied.
I extended the existing template and controller. I added a `.css` stylesheet to match some styles.

GDB-9561 - Extend UX test page with available components in WB

---

src/js/angular/sparql-editor/controllers.js

When the 'SPARQL' view is opened from the target link in the 'Resource' view, the url contains a parameter with a describe query of the source in the resource view. When the SPARQL view is loaded and the query is filled, the url parameters are not cleared.
There is a similar behavior when an item of the 'Home' page "Saved SPARQL queries" widget is clicked on. Clearing of URLs was implemented only for the 'Home' page, not for the 'Resource' view.
Refactoring the functionality to clear URL parameters in both scenarios

GDB-9881: YASQE - reopening a closed tab after page refresh

---

src/js/angular/import/controllers.js
src/js/angular/import/templates/settingsModal.html
test-cypress/integration/import/import.user.data.spec.js

Rename _isJSONLD_ flag used for checking if JSONLD context has to be displayed in the import settings modal.
QA report.
Renamed the variable.

GDB-9890 Incorrect name of flag in import payload

---

src/js/angular/models/import/import-parsing-settings.js
src/js/angular/models/import/import-resource-format.js
src/js/angular/models/import/import-resource-status.js
src/js/angular/models/import/import-resource-tree-element.js
src/js/angular/models/import/import-resource-type.js
src/js/angular/models/import/import-resource.js
src/js/angular/rest/mappers/import-mapper.js

Defines models for import server functionality.

GDB-9971: defines models for import server functionality

---

package-lock.json

Reverts Ontotext-AD/graphdb-workbench#1333

Revert "Bump express from 4.18.2 to 4.19.2"

---

package-lock.json
package.json

Revert - Bump the npm_and_yarn group with 3 updates https://github.com/Ontotext-AD/graphdb-workbench/pull/1339

Revert - Bump the npm_and_yarn group with 3 updates

---

src/js/angular/import/directives.js
src/js/angular/import/templates/settingsModal.html
src/js/angular/utils/uri-utils.js
test-cypress/integration/import/import-server-files.spec.js
test-cypress/integration/import/import-text-snippet.spec.js
test-cypress/integration/import/import-user-data-settings-dialog.spec.js

Reorganize and improve styles and validation in the import settings dialog.
This is expected to improve the user experience.
* Moved the base uri field in the advanced options section as it's rarely used.
* Aligned labels with tier respective checkboxes.
* Fixed IRI validation for the context, base iri and jsonld context link.
* Added tests for the settings modal

GDB-10070 improve import settings dialog

---

src/js/angular/clustermanagement/services/cluster-drawing.service.js

The messages for each cluster node during recovery will update correctly and according to the icons for that node.
The user needed to click the message for it to update. Hence, the icon would have changed on its own, but without user interaction, the message would remain out of date.
I removed the click listener and added some validation for the case with no message. I added the missing height attribute, preventing the messages from being seen without a page reload. The logic for shortening the message labels is altered. I also refactored some of the existing code.
(cherry picked from commit 0805060fdf1729a3da9a47bb50af49c49a28fce4)

Cherry pick GDB-10046 - Properly update recovery messages for cluster nodes

---

src/app.js
src/css/import-resource-tree.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/import/directives/import-resource-status-info.directive.js
src/js/angular/import/directives/import-resource-tree.directive.js
src/js/angular/import/templates/import-resource-status-info.html
src/js/angular/import/templates/import-resource-tree.html
src/js/angular/models/import/import-resource-tree-element.js
src/js/angular/rest/mappers/import-mapper.js
test-cypress/fixtures/locale-en.json

What:
When hovering over a resource's info icon, a popover dialog is displayed with more information about the importing process.
Why:
In table view, the user sees only a few details of the import data. Opening the dialog gives the user more information about the import process.
How:
The info icon and popover are implemented as a directive.

GDB-9971: Added import status popover.

---

src/css/import-resource-tree.css
src/js/angular/import/controllers.js
src/js/angular/import/directives/import-resource-tree.directive.js
src/js/angular/import/templates/import-resource-tree.html
src/js/angular/models/import/import-resource-tree-element.js
src/pages/import.html
test-cypress/integration/import/import-server-files.spec.js
test-cypress/integration/import/import-user-data-batch-operations.spec.js
test-cypress/integration/import/import-user-data-file-upload.spec.js
test-cypress/integration/import/import-user-data.spec.js
test-cypress/steps/import/import-steps.js

Implemented all batch operations on the user data tab in the import view. This includes import, delete, reset operations.
Batch operations on user data tab in the import view should work as expected.
Wired up all batch operations and implemented tests for them.

GDB-9970 user data batch operations

---

src/css/import-resource-tree.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/import/controllers.js
src/js/angular/import/templates/import-resource-tree.html
src/js/angular/models/import/import-resource-tree-element.js
src/js/angular/rest/mappers/import-mapper.js
src/pages/import.html
test-cypress/fixtures/graphdb-import/more-files/jsonld-file.jsonld
test-cypress/fixtures/graphdb-import/more-files/rdfxml.rdf
test-cypress/integration/import/import-server-files-batch-operations.spec.js
test-cypress/integration/import/import-server-files-operations.spec.js
test-cypress/integration/import/import-server-files.spec.js
test-cypress/integration/import/import-user-data-batch-operations.spec.js
test-cypress/integration/import/import-user-data-file-upload.spec.js
test-cypress/integration/import/import-user-data-settings-dialog.spec.js
test-cypress/integration/import/import-user-data-text-snippet.spec.js
test-cypress/integration/import/import-user-data-url.spec.js
test-cypress/integration/import/import-user-data.spec.js
test-cypress/integration/import/import-view.spec.js
test-cypress/integration/monitor/global-operation-statuses-component.spec.js
test-cypress/integration/repository/repositories.spec.js
test-cypress/integration/setup/sparql-template-create.js
test-cypress/steps/import/import-server-files-steps.js
test-cypress/steps/import/import-settings-dialog-steps.js
test-cypress/steps/import/import-steps.js
test-cypress/steps/import/import-user-data-steps.js

Completed implementation of operations on server files tab and updated tests.
After integration of the new resource list, actions and tests had to be changed to work again as expected.
* Wired the batch import operation.
* Refactored old server files tests.
* Implemented new tests to cover more of the functionality.

GDB-9971 complete server files tab

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/import/controllers/import-text-snippet.controller.js
src/js/angular/import/templates/textSnippet.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/repository/repositories.spec.js

Improve import text snippet dialog usability by setting a limit for the text that can be inserted in the text field by the user and adding a validator plus counter for the remaining characters.
This would prevent the cases where the user would try to paste too big rdf text which potentially can freeze the page or crash the browser.
Added a maxlength validator and limit to the textarea.
Added a count tracker.
Changed the label from the popover to an actual label.

GDB-10134 improve import text snippet dialog usability

---

src/js/angular/guides/guide-utils.js
src/js/angular/guides/guides.service.js
src/js/angular/guides/steps/complex/import-rdf-file/plugin.js
src/js/angular/guides/tour-lib-services/shepherd.service.js
src/js/angular/import/controllers/import-view.controller.js
src/js/angular/import/templates/import-resource-tree.html
test-cypress/integration/guides/movies-interactive-guide.spec.js
test-cypress/integration/guides/star-wars-interactive-guide.js
test-cypress/steps/guides/guide-steps.js
test-cypress/steps/import/import-steps.js

GDB-10120: Updates the user guides according to BE changes
Updates the import RDF steps in the user guides.
Changes were made to the import HTML elements and the import workflow.

Gdb 10120 update the user guides according to import rdf data changes

---

src/css/import-resource-tree.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/import/directives/import-resource-message.directive.js
src/js/angular/import/directives/import-resource-status-info.directive.js
src/js/angular/import/templates/import-resource-message.html
src/js/angular/import/templates/import-resource-status-info.html
src/js/angular/import/templates/import-resource-tree.html
src/js/angular/models/import/import-resource-tree-element.js
src/js/angular/models/import/import-resource.js
src/js/angular/rest/mappers/import-mapper.js
test-cypress/fixtures/locale-en.json
test-cypress/integration/repository/repositories.spec.js
test-cypress/steps/import/import-steps.js

Updated models to reflect changes in the backend.
The backend API now returns additional information about import resources.
The model has been updated.
- Fixes conditions when importedOn and modifiedOn have to be bolded;
- Changed icons based on the type of import resource.

GDB-10040-Update-server-responses-related-to-import-functionality

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/directives/cluster-graphical-view.directive.js
src/js/angular/clustermanagement/directives/cluster-legend.directive.js
src/js/angular/clustermanagement/services/cluster-drawing.service.js
src/js/angular/clustermanagement/services/cluster-view-context.service.js
src/js/angular/clustermanagement/templates/cluster-legend.html
src/js/angular/models/clustermanagement/cluster-management-constants.js
src/js/angular/models/clustermanagement/node-state.js
src/pages/cluster-management/clusterInfo.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/cluster/cluster-legend.spec.js
test-cypress/integration/cluster/cluster-states.spec.js
test-cypress/steps/cluster/cluster-page-steps.js

Redesigned the cluster view legend.
Current legend implementation doesn’t have enough surface area so that all the information represented inside it can be clearly visible and perceived by the user without any additional actions needed after opening it.
- A new "ClusterLegend" component has been implemented;
- Old legend has been replaced with the new component.

GDB-10159: Redesign the cluster view legend

---

src/js/angular/core/directives.js
src/js/angular/import/controllers/import-view.controller.js

This reverts commit 16a4db699c4014b595b61534e8db196468f76aaf.

Revert "GDB-8254: Import tab quickly flashes a wrong message (#1395)"

---

Jenkinsfile

Modified the 'Acceptance' stage in the Jenkinsfile to include a condition that checks if the source branch is not 'master'. This will prevent tests from running unnecessarily on the master branch.

Add condition to Jenkinsfile Acceptance stage

---

src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/export/controllers.js

What?
The rel attribute is missing the quotes.
Why?
according to IANA specification the rel attribute should look like rel="the_rel"
How?
Added the missing quotes in Link header's rel attribute.

GDB-10406 Added missing quotes in rel attribute

---

src/css/import.css
src/js/angular/import/controllers/import-view.controller.js
src/js/angular/rest/upload.rest.service.js
src/pages/import.html

Show a progress bar while file is uploading in import view.
If a big file is being uploaded, then it happens that the UI doesn't show any signs of what's happening during the file is uploaded to the server which then returns it's status in  the list with the files. This leads to a bad user experience.
Added a progress bar in the user data tab which is displayed while the file is being uploaded.

GDB-10392 show a progress bar while file is uploading in import view

---

package.json
packages/legacy-workbench/src/app.js
packages/root-config/webpack.config.js
scripts/build.sh
scripts/clean.sh

Removes hardcoded host and port from the legacy workbench's app.js file.

Removes hardcoded host and port

---

package.json
packages/legacy-workbench/src/index.js
packages/navbar/package-lock.json
packages/navbar/package.json
packages/navbar/src/navbar.css
packages/navbar/src/navbar.html
packages/navbar/src/navbar.js
packages/navbar/webpack.config.js
packages/root-config/src/index.ejs
packages/root-config/src/microfrontend-layout.html
scripts/build.sh
scripts/clean.sh
scripts/install.sh

Implemented navbar application and registered in the single-spa layout.
Our old workbench and new workbench applications expose only views and we need a new custom layout and navigation.
Created a new navbar application that is integrated in the single-spa layout.

GDB-10463 workbench lyaout and navigation

---

src/js/angular/import/controllers/import-view.controller.js

Fix for the selection of files for import on the server files import tab.
This also fixes the regress caused by the previous fix for the https://ontotext.atlassian.net/browse/GDB-10397 issue.
It appears that there are cases where files list maintained in the import view controller is not properly updated when a selection is made through the checkboxes in the resource tree which leads to wrong files sent for import.
Added subscription for the selectedFileNamesUpdated event and updated the selectedForImportFiles list in the import view controller. The subscription is implemented in the server import tab controller because it affects the import files selection and should not affect the user data tab.

GDB-10471 multi file upload fix

---

package.json
packages/components/README.md
packages/components/package-lock.json
packages/components/package.json
packages/components/src/footer/footer.css
packages/components/src/footer/footer.html
packages/components/src/footer/footer.js
packages/components/src/header/header.css
packages/components/src/header/header.html
packages/components/src/header/header.js
packages/components/src/index.js
packages/components/src/navbar/navbar.css
packages/components/src/navbar/navbar.html
packages/components/src/navbar/navbar.js
packages/components/webpack.config.js
packages/root-config/src/index.ejs
packages/root-config/src/microfrontend-layout.html
packages/root-config/src/ontotext-root-config.js
packages/root-config/src/styles/styles.css
scripts/install.sh

Introduce new module components which exports reusable components for the workbench layout and replaces the old navbar module.
To get the layout closer to the workbench original look.
Implemented new components module with the navbar, header and footer components and used them in the root application to build the layout.

GDB-10463 extended workbench layout with more components

---

src/js/angular/import/controllers/import-view.controller.js

Cherry-pick
Large upload files doesn't appear in the import list.
Files in the list are fetched from the backend and displayed in the UI without modification. If a file is not appearing in the list, it indicates there was an error during the upload process. We discovered that error handling was not functioning correctly; specifically, an empty error handling function was added alongside a function to calculate the upload percentage. We expected that the error handling function would be executed, but it was not.
Moved the error handling logic from the catch function to a dedicated error handling function. Added resetting of progressPercentage and uploadProgressMessage in the finally to ensure that the loader is hidden regardless of whether the upload fails or succeeds.
When attempting to …

Cherry-pick GDB-10610: Large Upload File Does not Appear in the Import List (#1486)

---

src/css/import-resource-tree.css
src/css/import.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/services/event-emitter-service.js
src/js/angular/import/controllers/import-view.controller.js
src/js/angular/import/controllers/tab.controller.js
src/js/angular/import/directives/import-resource-tree.directive.js
src/js/angular/import/services/import-context.service.js
src/js/angular/import/services/import-resource-tree.service.js
src/js/angular/import/templates/import-resource-message.html
src/js/angular/import/templates/import-resource-tree.html
src/js/angular/models/import/import-resource-status.js
src/js/angular/rest/mappers/import-mapper.js
test-cypress/fixtures/locale-en.json
test-cypress/steps/import/import-steps.js

Refactored Upload Progress Bar
Refactored the upload progress bar to improve user experience.
Previously, there was a single progress bar for all uploaded files, which was confusing for users as it did not clearly indicate the progress of individual files.
Added progress information next to each uploaded file to provide clearer and more specific feedback on the upload status.

Gdb 10610 file upload and progress improvements

---

src/js/angular/graphexplore/controllers/rdf-class-hierarchy.controller.js
src/pages/rdfClassHierarchyInfo.html

When using the scroll wheel over the Class hierarchy slider the values will change, as indicated in the slider's tooltip.
The slider scroll event wouldn't trigger, so the tooltip was misleading about this functionality.
I changed the way the slider is fetched in the DOM and the way the event listener is added.

GDB-10680 - Fix the scroll on the class hierarchy slider

---

test-cypress/integration/repository/ontop-repository.spec.js
test-cypress/integration/repository/repositories.spec.js
test-cypress/steps/ontop-repository-steps.js
test-cypress/steps/repository-steps.js
test-cypress/stubs/repositories/repositories-stubs.js

New tests added for the creation and edit of Ontop repositories.
The idea is to cover a few more cases in order to avoid missing bugs when creating and editing Ontop repositories.
Tests added.

GDB-10021 - Add Ontop create and edit tests

---

src/css/ttyg/agent-list.css
src/css/ttyg/chat-list.css
src/css/ttyg/ttyg.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/models/ttyg/agents.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/agent-list.directive.js
src/js/angular/ttyg/services/constants.js
src/js/angular/ttyg/templates/agent-list.html
src/js/angular/ttyg/templates/ttyg.html
test-cypress/fixtures/repositories/get-ttyg-repositories.json
test-cypress/integration/ttyg/agent-list.spec.js
test-cypress/steps/ttyg/ttyg-view-steps.js
test-cypress/stubs/repositories/repositories-stubs.js

Introduces an agent list filter in ttyg page.
This allows the user to filter the agent list by repository to which each agent is bound.
Implemented a filter menu in the agent list component and provided a filter model to it. 
Implemented tests.
Improved some other styling a bit.

GDB-10713 ttyg agent list filter

---

src/css/clustermanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/app.js
src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/controllers/update-cluster-group.controller.js
src/js/angular/clustermanagement/directives/cluster-list.directive.js
src/js/angular/clustermanagement/services/cluster-context.service.js
src/js/angular/clustermanagement/services/remote-locations.service.js
src/js/angular/clustermanagement/templates/cluster-list.html
src/js/angular/clustermanagement/templates/modal/update-cluster-group-dialog.html
src/js/angular/core/directives/validate-url.directive.js
src/js/angular/models/clustermanagement/cluster.js
src/js/angular/utils/url-utils.js
src/pages/cluster-management/clusterInfo.html
test-cypress/fixtures/locale-en.json

Implemented a new cluster management modal view where all actions related to creating, deleting, and replacing cluster nodes will take place
Requirement
- Refactored URL validation logic in url-utils.js
- Enhanced the validate-url directive to handle protocol exclusions and empty value validations
- Added support for updating cluster groups with a modal dialog in the cluster management UI.
- Improved error handling and state management in cluster-context.service.js and related components.
- Updated cluster-management.controller.js to handle user actions and ensure proper state transitions.
- Applied CSS improvements for the cluster management UI, including styles for autocomplete and error messages.

feat(GDB-10848) Implement Cluster Management View

---

src/js/angular/core/services/ttyg.service.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js

Moved TTYGService to js/angular/core/service module

Moved TTYGService to js/angular/core/service module

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/directives/cluster-list.directive.js
src/js/angular/clustermanagement/services/cluster-context.service.js
src/js/angular/clustermanagement/templates/cluster-list.html
src/js/angular/models/clustermanagement/cluster.js
test-cypress/fixtures/locale-en.json

- Added a modal confirmation for deleting nodes using ModalService in the deleteNode method.
- Adjusted ClusterContextService methods to handle both Node and Location objects for cluster modifications.
- Refactored the saveNode method to optimize the logic for adding, restoring, or creating nodes in the cluster.
- Introduced handleNodesUpdate to ensure sequential processing of adding and removing nodes.
- Updated JSDocs across functions to improve clarity.
To support node deletion from the cluster, providing confirmation dialogs and optimized logic for cluster node handling.
- Introduced handleNodesUpdate, a new utility function that handles adding/removing nodes in sequence using Promises.
- Added ModalService for confirmation dialogs when deleting nodes and linked it with …

feat(GDB-10850) Implement node remove functionality

---

src/css/ttyg/chat-panel.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/chat-panel.directive.js
src/js/angular/ttyg/services/ttyg-context.service.js
src/js/angular/ttyg/templates/chat-panel.html
src/js/angular/ttyg/templates/chat1.html
test-cypress/fixtures/locale-en.json
test-cypress/fixtures/ttyg/chats/get-chat-1.json
test-cypress/integration/ttyg/chat-panel.spec.js
test-cypress/steps/ttyg/chat-panel-steps.js
test-cypress/stubs/ttyg/ttyg-stubs.js

Updated the chat panel view to improve the layout and structure.
To meet the updated design requirements.
Created a responsive layout using flexbox to manage the display of chat questions and answers, ensuring the panel matches the specified requirements.

GDB-10716: Create Chat Panel Layout

---

src/css/import.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
test-cypress/fixtures/locale-en.json

Reverts Ontotext-AD/graphdb-workbench#1545

Revert "(cherry-pick) GDB-10888 - add missing label key and remove button right margin (#1543)"

---

src/css/ttyg/agent-list.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/services/ttyg.service.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/rest/ttyg.rest.service.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/agent-list.directive.js
src/js/angular/ttyg/services/ttyg-context.service.js
src/js/angular/ttyg/templates/agent-list.html
test-cypress/fixtures/locale-en.json
test-cypress/fixtures/ttyg/agent/get-agent-list-after-deleted.json
test-cypress/integration/ttyg/agent-list.spec.js
test-cypress/integration/ttyg/delete-agent.spec.js
test-cypress/steps/modal-dialog-steps.js
test-cypress/steps/ttyg/ttyg-view-steps.js
test-cypress/stubs/ttyg/ttyg-stubs.js

Introduce delete agent operation.
This operation allows the user of the workbench to delete an agent through the UI.
Implemented action handlers, service methods and events in the context service. Implemented tests.

GDB-10712 - introduce delete agent operation

---

src/js/angular/graphexplore/controllers/rdf-class-hierarchy.controller.js
src/pages/rdfClassHierarchyInfo.html

When using the scroll wheel over the Class hierarchy slider the values will change, as indicated in the slider's tooltip.
The slider scroll event wouldn't trigger, so the tooltip was misleading about this functionality.
I changed the way the slider is fetched in the DOM and the way the event listener is added.
(cherry picked from commit 0ff5fc41437f740addb3a8f5996605374b2158ad)

(cherry-pick) GDB-10680 - fix the scroll on the class hierarchy slider (#1517)

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/services/ttyg.service.js
src/js/angular/models/ttyg/agent-form.js
src/js/angular/models/ttyg/agents.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/rest/ttyg.rest.service.js
src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/agent-list.directive.js
src/js/angular/ttyg/services/agents.mapper.js
src/js/angular/ttyg/services/constants.js
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
src/js/angular/ttyg/templates/ttyg.html
test-cypress/fixtures/locale-en.json
test-cypress/fixtures/ttyg/agent/get-agent-list.json
test-cypress/integration/ttyg/edit-agent.spec.js
test-cypress/steps/ttyg/ttyg-agent-settings-modal.steps.js
test-cypress/stubs/ttyg/ttyg-stubs.js

Introduce agent edit action.
Users should be able to edit existing agents.
Implemented mapper from the agent model to agent form model using the default values as a base. Wired the edit agent and open the agent settings modal with the needed data.

GDB-10714 - introduce agent edit action

---

src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/controllers/update-cluster-group.controller.js
src/js/angular/clustermanagement/directives/cluster-list.directive.js
src/js/angular/clustermanagement/services/cluster-context.service.js
src/js/angular/clustermanagement/templates/cluster-list.html
src/js/angular/models/clustermanagement/cluster.js

- Implemented functionality to create a new cluster in the cluster management interface.
- Added a form to define the initial cluster configuration
- Introduced form validation to ensure that the cluster configuration is valid before saving.
- Added logic to distinguish between creating a new cluster and editing an existing cluster.
Requirements
- Extended the existing cluster management interface by adding a new form for defining a cluster's initial configuration.
- Implemented validation logic for essential cluster parameters.
- Updated the ClusterContextService and ClusterViewModel to handle the creation of new clusters and validate the configuration.
- Created new methods in the cluster-management.controller.js for handling the cluster creation process.
- Updated the UI to provide …

feat(GDB-10855) Implement Cluster Creation Functionality

---

src/css/cluster-list.css
src/css/clustermanagement.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/controllers/update-cluster-group.controller.js
src/js/angular/clustermanagement/directives/cluster-list.directive.js
src/js/angular/clustermanagement/services/cluster-context.service.js
src/js/angular/clustermanagement/templates/cluster-list.html
src/js/angular/clustermanagement/templates/modal/update-cluster-group-dialog.html
src/js/angular/models/clustermanagement/cluster.js
src/pages/cluster-management/clusterInfo.html
test-cypress/fixtures/locale-en.json

- Fixed UI and content-related requirements in the cluster configuration module.
- Updated css, labels, tooltips,
- improved cluster node management with a restore node action
Requirements
- Updated HTML for "Edit" and "Create" modes.
- Added logic to track unsaved changes.
- Implemented restore node functionality.
- Adjusted CSS

feat(GDB-10922): Apply visual changes

---

src/css/bootstrap-graphdb-theme.css
src/css/ttyg/agent-list.css
src/css/ttyg/agent-settings-modal.css
src/css/ttyg/chat-list.css
src/css/ttyg/chat-panel.css
src/css/ttyg/ttyg.css
src/js/angular/ttyg/templates/chat-list.html
src/js/angular/ttyg/templates/chat-panel.html
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
src/js/angular/ttyg/templates/ttyg.html

* Vertical scrollbars in the panels should be visible only on hover.
* Background color should be consistent with the rest of the application.
* Chat toolbar is moved inside the chat panel to align it with the chat panel contents. Also removed padding from the chat itself to align the content with the outside stuff.
Comply with the design.
Applied needed changes in the stylesheets and html.

GDB-10937 - improve styling of panels in the ttyg view

---

src/css/ttyg/chat-item-details.css
src/css/ttyg/chat-panel.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
src/js/angular/core/services/ttyg.service.js
src/js/angular/models/ttyg/agents.js
src/js/angular/models/ttyg/chat-item.js
src/js/angular/models/ttyg/explain-response.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/rest/ttyg.rest.service.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/chat-item-detail.directive.js
src/js/angular/ttyg/directives/chat-panel.directive.js
src/js/angular/ttyg/services/chat-message.mapper.js
src/js/angular/ttyg/services/explain.mapper.js
src/js/angular/ttyg/services/ttyg-context.service.js
src/js/angular/ttyg/templates/chat-item-detail.html
src/js/angular/ttyg/templates/chat-panel.html
test-cypress/fixtures/locale-en.json

Introduce the explain response action.
Users should be able to see how an answer was generated.
Extend the item chat detail component to display the explain response.

GDB-10716: Implement Explain Response Action

---

scripts/run-cypress-tests.sh
src/css/ttyg/agent-list.css
src/css/ttyg/chat-item-details.css
src/css/ttyg/chat-list.css
src/css/ttyg/chat-panel.css
src/js/angular/ttyg/directives/chat-list.directive.js
src/js/angular/ttyg/services/chat-message.mapper.js
src/js/angular/ttyg/templates/chat-item-detail.html
test-cypress/integration/ttyg/chat-list.spec.js

- Changed date in chat list to ISO format (yyyy-mm-dd)
- Process and display multiple consecutive agent messages in chats
- Adjusted spacing between messages to better reflect flows with multiple consecutive agent messages and a look that looks more like a dialog instead of a question/answer list
- Text wrap markdown pre to prevent content from spilling out of the box
- Changed color of date/today/yesterday in left sidebar to gray-color-dark
- Changed color of repo in right sidebar to gray-color-dark
- Fixed flaky test
- Improvements to run-cypress-tests.sh so it can be run directly and provide more flexibility
- Improve usability
- Fix some agent messages not being shown
- Reliable tests needed
- Some CSS/HTML changes
- Minor change in how chat messages are converted
- Minor test fix

Various TTYG fixes

---

Jenkinsfile
src/app.js
src/css/common.css
src/js/angular/core/directives/languageselector/language-selector.directive.js

- Refactored the process for preloading and applying translations in the app.
- Updated the moduleDefinition function to accept preloaded translations.
- Improved language preloading logic to load multiple languages before initializing the workbench.
- Applied the font-display: swap property to all font-face definitions in CSS.
- To ensure translations are loaded before the app starts
- The font-display: swap property was added to optimize web font rendering particularly on slower networks.
- Introduced a new loadTranslationsBeforeWorkbenchStart function that handles the preloading of translation files and stores them in a translations object.
- Updated the startWorkbench function to accept the preloaded translation data and apply them through $translateProvider.
- Added fallback logic in …

fix(GDB-10375) Refactor language loading

---

src/css/ttyg/agent-list.css
src/css/ttyg/agent-settings-modal.css
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
src/js/angular/ttyg/templates/agent-list.html
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
src/js/angular/ttyg/templates/ttyg.html
test-cypress/integration/ttyg/create-agent.spec.js

* Added a repository icon in front of the agent list filter menu.
* Added proper error message when agent creation fails.
* Decreased the length of the numeric fields in the agent settings dialog.
* Applied the font styles used in the sparql editor to the textareas in the agent settings modal as well as increased their size.
* Hid the `seed` property field from the agent settings modal because it's not used by the backend yet. It'll be reintroduced again later.
Comply with the design.
Applied the needed fixes.

GDB-10937 - ttyg view visual fixes and improvements

---

src/css/ttyg/agent-settings-modal.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/models/ttyg/agent-form.js
src/js/angular/ttyg/controllers/agent-settings-modal.controller.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/templates/chat-item-detail.html
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
src/js/angular/ttyg/templates/no-agents-view.html
src/js/angular/ttyg/templates/ttyg.html

Added all requested hints and tooltips to the view.
Comply with the requested design.
Added all necessary tooltip labels and applied in html templates. Added the help info message.
Add copy and reset buttons to system nd user instructions

GDB-10937 - add hints and tooltips to ttyg view

---

src/app.js
src/js/angular/controllers.js
src/js/angular/core/services/license.service.js
src/js/angular/settings/app.js
src/js/angular/settings/controllers.js
test-cypress/integration/home/workbench.home.spec.js
test-cypress/stubs/license-stubs.js

- Introduced tracking logic based on the type of license in use (Free, Evaluation, or Enterprise).
- Refactored the $licenseService to manage license statuses, types, and tracking permissions more effectively.
- Updated Cypress tests to cover different license types and ensure correct behavior of Google Tag Manager (GTM) injection.
- Modified the app’s initialization to check and update the license status on load.
- Added stubs for different license types in tests.
To enable Google Tag Manager (GTM) on the application for enhanced tracking and analytics capabilities.
- Refactored the $licenseService to handle the license information, product type, and tracking permissions.
- Added a method to dynamically inject or remove GTM scripts based on the license type and tracking allowance.
- …

feat(GDB-10629) Add GA4 tracking code in GDB Workbench

---

src/css/ttyg/chat-item-details.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/ttyg/templates/chat-item-detail.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/ttyg/chat-panel.spec.js

- The query method shows a label key instead of the actual label;
- There is a copy button, regardless of whether there is anything to copy;
- More vertical space should be added between rows.
- The backend and frontend were not synchronized;
- There may be cases where a raw query is missing; in such cases, the raw query visualization should not be visible in the panel;
- Some CSS settings were missing.
- Synchronized the backend and frontend;
- Added a check for the raw query and query before displaying them;
- Fixed the CSS.

Gdb 10937 fixes different issues

---

src/css/ttyg/agent-settings-modal.css
src/js/angular/core/services/ttyg.service.js
src/js/angular/models/ttyg/chat-answer.js
src/js/angular/models/ttyg/chat-item.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/chat-item-detail.directive.js
src/js/angular/ttyg/services/chat-message.mapper.js
src/js/angular/ttyg/templates/chat-item-detail.html
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
test-cypress/integration/ttyg/chat-panel.spec.js
test-cypress/integration/ttyg/edit-agent.spec.js
test-cypress/steps/ttyg/chat-panel-steps.js
test-cypress/stubs/ttyg/ttyg-stubs.js

Synchronize UI models with the backend (BE).
The backend models have been changed.
The UI models have been synchronized with the backend (BE).

GDB-10937 synchronize ask endpoint

---

src/css/ttyg/chat-item-details.css
src/css/ttyg/chat-panel.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/models/ttyg/explain-response.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/ttyg/directives/chat-item-detail.directive.js
src/js/angular/ttyg/services/explain.mapper.js
src/js/angular/ttyg/templates/chat-item-detail.html
test-cypress/fixtures/locale-en.json
test-cypress/fixtures/ttyg/chats/ask-question.json
test-cypress/fixtures/ttyg/chats/explain-response-1.json
test-cypress/fixtures/ttyg/chats/explain-response-2.json
test-cypress/fixtures/ttyg/chats/get-chat.json
test-cypress/integration/ttyg/chat-panel.spec.js
test-cypress/steps/ttyg/ttyg-view-steps.js
test-cypress/stubs/ttyg/ttyg-stubs.js

The explain response models have been updated.
The backend exposes new fields in the response, providing an opportunity for further UX improvements.
The UI models have been updated to reflect the changes.
- The actions remain visible until the explain response is expanded;
- The raw query is hidden if it is identical to the query;
- The raw query text ellipsis when the query is too long;
- Hide the "Copy SPARQL Query" button if the query in queryMethod is not SPARQL;
- Change the name of the query label depending on the query type: "JSON" or "SPARQL."

Gdb 10937 update explain functionality with the new model

---

scripts/run-cypress-tests.sh
scripts/validate-translations.js
src/css/bootstrap-graphdb-theme.css
src/css/ttyg/chat-item-details.css
src/css/ttyg/chat-panel.css
src/css/ttyg/ttyg.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/ttyg/templates/chat-item-detail.html
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
test-cypress/fixtures/locale-en.json
test-cypress/integration/explore/graphs.overview.spec.js
test-cypress/integration/home/workbench.home.spec.js
test-cypress/integration/import/import-view.spec.js
test-cypress/integration/ttyg/agent-list.spec.js
test-cypress/integration/ttyg/agent-select-menu.spec.js
test-cypress/integration/ttyg/chat-list.spec.js
test-cypress/integration/ttyg/chat-panel.spec.js
test-cypress/integration/ttyg/clone-agent.spec.js
test-cypress/integration/ttyg/create-agent.spec.js
test-cypress/integration/ttyg/delete-agent.spec.js
test-cypress/integration/ttyg/edit-agent.spec.js
test-cypress/integration/ttyg/ttyg-view.spec.js
test-cypress/steps/ttyg/ttyg-view-steps.js
test-cypress/stubs/license-stubs.js
test-cypress/stubs/repositories-stub.js
test-cypress/stubs/repositories/repositories-stubs.js
test-cypress/support/index.js

Explain:
- Added support for "no methods used" explain
General TTYG:
- Fixed various spacings that went off after recent changes with more stable ones
- Test fixes and stability
- Moved model/temperature/top p to a single row
- Reduced size of instruction boxes
General workbench:
- Added a class btn-link-only-icons to use on buttons composed of icon + space + icon to avoid underlined space
- Improvement to run-cypress-tests.sh
- Test fixes and stability
- Translation fixes + improvements to validate script

TTYG explain and general improvements

---

src/css/ttyg/chat-item-details.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/ttyg/plugin.js
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
test-cypress/fixtures/locale-en.json
test-cypress/steps/ttyg/ttyg-view-steps.js

- The tooltip of the "Refresh FTS button" is incorrect;
- There is horizontal scrolling when an answer contains images;
- The URL of the "Talk to Your Graph" page has been changed.
- The tooltip was incorrectly implemented;
- The image feature was not originally planned but was decided during implementation;
- The URL was set to "chatgpt," which is incorrect, as the page is titled "Talk to Your Graph."
- The tooltip for the Refresh FTS button has been updated;
- CSS styling has been added to ensure images in answers do not exceed the width of their parent container;
- The URL has been updated to "ttyg."

10937 ttyg improvements and fixes

---

src/css/import.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/copy-to-clipboard/copy-to-clipboard.directive.js
src/js/angular/ttyg/templates/modal/agent-settings-modal.html
src/js/angular/ttyg/templates/no-agents-view.html
test-cypress/fixtures/locale-en.json

* Fixed validation of the similarity search method form in agent settings dialog when the method is selected.
* Fixed the placeholder label key for a field.
* Improved the warning message that appears in the no agents view to allow gpt token property to be copied via button.
* Fixed slider positioning for the similarity index threshold field.
These will improve the usability.
Removed the incorrect dynamic css class added to the similarity method panel.
Fixed the label of a placeholder.
Extended the warning message that appears on the no agents view.

GDB-10937 create agent form validation fix and copy property btn

---

src/js/angular/ttyg/services/chats.mapper.js
test-cypress/fixtures/ttyg/chats/ask-question.json
test-cypress/fixtures/ttyg/chats/get-chat.json

- Show chat messages in the order the API returns them
- Avoid unnecessary reversal
- Removed call to reverse()
- Reversed order of messages in stubs

TTYG natural sorting for chat messages

---

Jenkinsfile
scripts/validate-translations.js
src/css/ttyg/chat-panel.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/ttyg/templates/chat-panel.html
test-cypress/fixtures/locale-en.json

- New hint message
- Center hint and input vertically close to each other
- Better focus on new chat
- CSS/HTML

TTYG centered intro message and input on new chat

---

scripts/validate-translations.js
src/css/bootstrap-graphdb-theme.css
src/css/ttyg/chat-panel.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/ttyg/templates/chat-panel.html
test-cypress/fixtures/locale-en.json

- New styling of the intro hint with colors
- Better visual branding
- CSS/HTML

TTYG intro message

---

docker-compose.yml
docker-rootfs/usr/local/bin/start-workbench.sh
src/pages/import.html
test-cypress/integration/import/import-user-data-file-upload.spec.js
test-cypress/integration/import/import-view.spec.js
test-cypress/integration/repository/repositories.spec.js
test-cypress/package.json
test-cypress/steps/import/import-steps.js
test-cypress/steps/repository-steps.js

- Test improvements
- Tests are flaky in various environments
- More cypressish approach
- Changed one `<div>` to `<label>` in import view - no visual changes
- Less clutter in what's printed on console when running on Jenkins
- Include ttyg tests in test:core

Test stability fixes

---

src/css/ttyg/chat-panel.css
src/css/ttyg/ttyg.css
src/js/angular/core/services/ttyg.service.js
src/js/angular/models/ttyg/chat-answer.js
src/js/angular/models/ttyg/chats.js
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/rest/ttyg.rest.service.js
src/js/angular/ttyg/controllers/ttyg-view.controller.js
src/js/angular/ttyg/directives/chat-panel.directive.js
src/js/angular/ttyg/services/chat-message.mapper.js
src/js/angular/ttyg/services/ttyg-context.service.js
src/js/angular/ttyg/templates/chat-panel.html
src/js/angular/ttyg/templates/ttyg.html

- Process chat answers step by step and provide immediate feedback to user
- Improved loader in chat list
- Cleaned up logic for new chat flow
- Small fixes here and there
- Better usability
- Better look
- Use new API endpoint for continuing a chat run
- CSS changes to align things properly
Note: needs backend changes from the ttyg-continue-chat-run branch to use the continue flow but will work as before with branches before that is merged.
Note: tests don't test the new continue flow yet.

TTYG process chat run step by step + UX improvements

---

src/js/angular/clustermanagement/controllers/cluster-management.controller.js
src/js/angular/clustermanagement/directives/cluster-nodes-configuration.directive.js
src/js/angular/clustermanagement/services/remote-locations.service.js
src/js/angular/models/clustermanagement/cluster.js

Refactored cluster-management.controller.js, cluster-nodes-configuration.directive.js, and related services to remove redundant location handling and clean up unnecessary logic for new location creation and error handling.
This logic created BE issues by creating or removing remote locations
- Removed clearUnusedLocations and deleteLocation calls, along with associated conditional checks for node existence in cluster-management.controller.js.
- Eliminated RemoteLocationsService.deleteLocation and error-handling functions in cluster-nodes-configuration.directive.js
- Updated Location model defaults and refactored RemoteLocationsService to remove unused deleteLocation and addNewLocation methods.

fix(GDB-11126) Removing Redundant Location Handling

---

src/pages/graphs-visualizations.html
test-cypress/integration/cluster/cluster-legend.spec.js
test-cypress/integration/explore/similariti-index-create.spec.js
test-cypress/integration/explore/similarity-index.spec.js
test-cypress/integration/explore/visual-graph/visual.graph.spec.js
test-cypress/integration/repository/attach-remote-location.spec.js
test-cypress/integration/setup/my-settings.spec.js
test-cypress/steps/visual-graph-steps.js
test-cypress/stubs/repositories/repositories-stubs.js

* GDB-10992 fixing regularly failing tests
* prevent repositories created by tests to remain after tests completes
* Fix cluster legend test where the cookie consent banner used to overlap the button for opening the legend and the test failed.
* Improve the graphs visualization tests
* Improve the graphs visualization tests
* Improve my settings tests
(cherry picked from commit 0a42a0050d14f2859faf7eac13cc29650eba8416)

GDB-10992 fixing regularly failing tests (#1643)

---

src/css/ttyg/agent-select-menu.css
src/css/ttyg/chat-panel.css
src/css/ttyg/ttyg.css
src/js/angular/rest/ttyg.rest.service.fake.backend.js
src/js/angular/ttyg/templates/agent-select-menu.html

Updated the styling of agent selection options.
Agent and repository names were overflowing when their lengths exceeded the available space.
Added ellipsis styling to the agent and repository names to handle long text gracefully.

Changes the styling of the agent selection options

---

package-lock.json
package.json
webpack.config.common.js

* Updated concurrently and the webpack-config-single-spa which also required additional configuration in webpack config.
* Updated html-loader and webpack config to account the changes in the loader's config.
To get the latest improvements and vulnerability fixes.

GDB-10673 Update dependent libraries and frameworks

---

packages/shared-components/src/components.d.ts
packages/shared-components/src/components/onto-dropdown/onto-dropdown.scss
packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
packages/shared-components/src/components/onto-dropdown/readme.md
packages/shared-components/src/components/onto-dropdown/test/onto-dropdown.e2e.ts
packages/shared-components/src/components/onto-dropdown/test/onto-dropdown.spec.tsx
packages/shared-components/src/models/dropdown/dropdown-item-alignment.ts
packages/shared-components/src/models/dropdown/dropdown-item.ts

Introduce a reusable dropdown component onto-dropdown, designed to provide a flexible, customizable dropdown menu that integrates seamlessly with other components. The dropdown supports features such as configurable labels, tooltips, icons, and item lists.
To enhance consistency and reduce repetitive code, a centralized and reusable dropdown component. Simplifies implementation of dropdowns across the application. Ensures uniform styling and behavior.
The onto-dropdown component was implemented using StencilJS. Key features include:

GDB-10570: Introduce dropdown component

---

test-cypress/integration/explore/class.hierarchy.spec.js
test-cypress/steps/class-views-steps.js

The class hierarchy spec has been refactored.
The refactoring was to demonstrate a solid understanding of advanced Cypress concepts and test writing best practices.
I updated the comments to match the convention, I simplified steps in each test and extracted DOM manipulation to an existing steps file.
Test class refactored.
N/A

FED-26 - Refactor class hierarchy test class

---

packages/api/src/services/language.service.ts
packages/legacy-workbench/src/app.js
packages/shared-components/cypress/e2e/header/language-selector.cy.js
packages/shared-components/cypress/steps/base-steps.js
packages/shared-components/cypress/steps/header/header-steps.js
packages/shared-components/src/assets/i18n/en.json
packages/shared-components/src/assets/i18n/fr.json
packages/shared-components/src/components.d.ts
packages/shared-components/src/components/onto-dropdown/onto-dropdown.scss
packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
packages/shared-components/src/components/onto-dropdown/readme.md
packages/shared-components/src/components/onto-header/onto-header.scss
packages/shared-components/src/components/onto-header/onto-header.tsx
packages/shared-components/src/components/onto-language-selector/onto-language-selector.scss
packages/shared-components/src/components/onto-language-selector/onto-language-selector.tsx
packages/shared-components/src/components/onto-language-selector/readme.md
packages/shared-components/src/components/onto-language-selector/test/onto-language-selector.e2e.ts
packages/shared-components/src/components/onto-language-selector/test/onto-language-selector.spec.tsx
packages/shared-components/src/components/onto-layout/readme.md

What
Added a language selector to the header.
Why
To provide the ability to change the language of the workbench.
How
Implemented it as a Stencil component.

GDB-10570: Introduce Language Selector

---

packages/shared-components/cypress/e2e/tooltip.cy.js
packages/shared-components/cypress/steps/tooltip-steps.js
packages/shared-components/package.json
packages/shared-components/src/components.d.ts
packages/shared-components/src/components/onto-dropdown/onto-dropdown.tsx
packages/shared-components/src/components/onto-layout/onto-layout.tsx
packages/shared-components/src/components/onto-layout/readme.md
packages/shared-components/src/components/onto-tooltip/models/onto-tooltip-configuration.ts
packages/shared-components/src/components/onto-tooltip/onto-tooltip.scss
packages/shared-components/src/components/onto-tooltip/onto-tooltip.tsx
packages/shared-components/src/components/onto-tooltip/readme.md
packages/shared-components/src/components/onto-tooltip/test/onto-tooltip.e2e.ts
packages/shared-components/src/components/onto-tooltip/test/onto-tooltip.spec.tsx
packages/shared-components/src/index.html
packages/shared-components/src/pages/header/index.html
packages/shared-components/src/pages/tooltip/index.html
packages/shared-components/src/pages/tooltip/main.js

A new tooltip component has been implemented.
The tooltip component is designed for use within the shared-components module, ensuring consistency and reusability.
Implemented a tooltip component that serves as a wrapper for the tippy.js library to provide a feature-rich and customizable tooltip solution.

GDB-11267: Implementation of Tooltip Component

---

src/js/angular/rest/monitoring.rest.service.js
test-cypress/integration/repository/repositories.spec.js
test-cypress/stubs/global-operations-statuses-stub.js

Updated the endpoint to fetch all active operations.
The API was changed in the backend.
Synchronized the URL with the changes in the backend

GDB-10900: The Repository Operations Endpoint Fails

---

packages/api/src/models/common/model-list.ts
packages/api/src/models/common/model.ts
packages/api/src/models/context/value-context.ts
packages/api/src/models/repositories/repository-list.ts
packages/api/src/models/repositories/repository.ts
packages/api/src/models/repository-location/repository-location.ts
packages/api/src/services/context.servce.spec.ts
packages/api/src/services/language/language-context.service.spec.ts
packages/api/src/services/language/language-context.service.ts
packages/api/src/services/language/language.service.spec.ts
packages/api/src/services/repository-location/repository-location-context.service.spec.ts
packages/api/src/services/repository-location/repository-location-rest.service.ts
packages/api/src/services/repository-location/repository-location.service.spec.ts
packages/api/src/services/repository-location/repository-location.service.ts
packages/api/src/services/repository/repository-context.service.spec.ts
packages/api/src/services/repository/repository-context.service.ts
packages/api/src/services/repository/repository-rest.service.ts
packages/api/src/services/repository/repository.mapper.ts
packages/api/src/services/repository/repository.service.spec.ts
packages/api/src/services/utils/object-util.spec.ts
packages/api/src/services/utils/object-util.ts
packages/api/src/services/utils/uri-util.spec.ts
packages/shared-components/src/components/onto-repository-selector/onto-repository-selector.tsx
packages/workbench/src/app/graphql/graphql.component.ts

Implement deep copy functionality.
We use subscriptions to handle changes to certain values. When a context property value is changed, all subscribers are notified of the change and retrieve the new value. To ensure that each subscriber works with an independent copy of the value, we use deep copies. This guarantees that there are no side effects when one subscriber modifies the value. If a value needs to be changed, the client modifies its copy and updates it through the corresponding model's context service.
Create an abstract model class that implements the Copyable interface. This class will provide a copy method. All application models must extend this base model class. The class will also include generic methods common to all models. Create an abstract ModelList class for managing …

GDB-10569: WB Migration: implement better deep copy functionality

---

Jenkinsfile
test-cypress/integration/explore/visual-graph/graphs-config.spec.js
test-cypress/integration/explore/visual-graph/visual.graph.spec.js
test-cypress/integration/home/rdf-resource-search.spec.js
test-cypress/integration/setup/plugins.spec.js
test-cypress/integration/setup/rdf-rank.spec.js
test-cypress/integration/sparql-editor/sparql-editor.spec.js
test-cypress/steps/setup/autocomplete-steps.js
test-cypress/steps/setup/plugins-steps.js
test-cypress/steps/setup/rdf-rank-steps.js
test-cypress/steps/visual-graph-steps.js
test-cypress/stubs/autocomplete/autocomplete-stubs.js

This improvement attempts to fix some of the test flake in a CI environment.
Flaky tests cause builds to fail too frequently.
I added checks to verify the view has fully loaded and responses handled before the test starts.
Test improvements
N/A

GDB-11133 - Improve test stability in CI

---

packages/api/jest.config.js
packages/api/src/models/http/http-options.ts
packages/api/src/providers/mapper/mapper.provider.spec.ts
packages/api/src/providers/service/service.provider.spec.ts
packages/api/src/services/authentication.service.spec.ts
packages/api/src/services/context.servce.spec.ts
packages/api/src/services/http/http.service.spec.ts
packages/api/src/services/http/http.service.ts
packages/api/src/services/repository-location/repository-location-rest.service.ts
packages/api/src/services/repository/mappers/repository-list.mapper.spec.ts
packages/api/src/services/repository/mappers/repository.mapper.spec.ts
packages/api/src/services/repository/repository-rest.service.ts
packages/api/src/services/repository/repository.service.spec.ts
packages/api/src/services/repository/test/repository-mock-provider.ts
packages/api/src/services/utils/object-util.spec.ts
packages/api/src/services/utils/test/test-util.ts
packages/api/src/services/utils/uri-util.spec.ts

Implement a service to manage REST API calls for the application.
Centralizing REST API logic improves maintainability and reusability.
- Create a dedicated service class to encapsulate HTTP request logic.
- Implement methods for all common HTTP verbs (GET, POST, PUT, DELETE).
- Add functionality to process responses, extract useful data, and handle errors.
- Include configurations for headers, query parameters, and timeouts.
- Write unit tests to verify the functionality of the service.

GDB-11297: Implement Service for REST API Integration

---

packages/legacy-workbench/src/js/angular/clustermanagement/directives/cluster-graphical-view.directive.js
packages/legacy-workbench/src/js/angular/clustermanagement/directives/cluster-legend.directive.js
packages/legacy-workbench/src/js/angular/clustermanagement/services/cluster-drawing.service.js
packages/legacy-workbench/src/js/angular/graphexplore/controllers/dependencies-chord.controller.js
packages/legacy-workbench/src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js
packages/legacy-workbench/src/js/angular/graphexplore/directives/dependencies-chord.directive.js
packages/legacy-workbench/src/js/angular/graphexplore/directives/domain-range-graph.directive.js
packages/legacy-workbench/src/js/angular/graphexplore/directives/rdf-class-hierarchy.directive.js
packages/legacy-workbench/src/js/angular/guides/guide-utils.js
packages/legacy-workbench/src/js/lib/common/d3-utils.js
packages/legacy-workbench/src/js/lib/common/svg-export.js
packages/legacy-workbench/src/js/lib/d3-ONTO-chord-patch.js
packages/legacy-workbench/src/js/lib/d3-tip/d3-tip-patch.js
packages/legacy-workbench/src/js/lib/d3.patch.js

Fix issues with d3
Previously, some files directly accessed the `d3` property, which was global. Now with ESM, that is no longer possible and Visual graph, Class relationships and Class hierarchy views are not loading due to that.
Added necessary import statements in the files, which use `d3` 
Added property to skip `onpopstate` event in `graphs-visualizations.controller.js` since it caused double loading of links
existing

GDB-11385 Fix issues with d3

---

src/css/bootstrap-graphdb-theme.css
src/css/graphql/graphql-playground.css

Styling graphiql component.
For consistency with the other workbench styles.
Overriding the styles of the component in our stylesheet.
NA

GDB-11298 styling graphql playground

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/graphql/templates/graphql-playground.html

Fixing some labels in the graphql playground view
Labels should be consistent with the mockups.
Changed the labels.
NA
NA

GDB-11298 fixing minor labeling issues in the playground

---

package-lock.json
package.json

Get latest ontotext-graphql-playground component version
There was an issue with the previous published version
Increased the dependency version package.json

GDB-11463 get latest ontotext-graphql-playground component version

---

src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
src/js/angular/graphql/services/graphql-context.service.js
src/js/angular/graphql/templates/graphql-endpoint-management.html
src/js/angular/models/graphql/graphql-endpoint-configuration.js

Add a create graphql endpoint action which starts the create endpoint process.
The user should be able to start the create endpoint process from the management view.
Wired the action button through the controller and the context service to trigger the create endpoint event and redirect to the create endpoint view which will be added with a next MR.
Will be added with a next MR.

GDB-11569 add a create graphql endpoint action

---

src/css/workbench-custom.css
src/js/angular/core/directives/multiselect-dropdown/multiselect-dropdown.directive.js
src/js/angular/core/directives/multiselect-dropdown/templates/multiselect-dropdown.html
webpack.config.common.js

- Adds a new directive multiselectDropdown along with its template
- Includes styles in workbench-custom.css to display a multi-select dropdown with checkboxes.
- Updates webpack.config.common.js to copy the new template to the correct build location.
- Needed a simple and reusable multi-select component for selecting multiple items
- Created multiselect-dropdown.directive.js
- Added custom styling and positioning rules
- Updated webpack.config.common.js to ensure the template files are copied when building the app

feat(GDB-11566) Introduce multi-select dropdown directive

---

src/app.js
src/css/shuttle-multiselect.css
src/js/angular/core/directives/shuttle-multiselect/shuttle-multiselect.directive.js
src/js/angular/core/directives/shuttle-multiselect/templates/shuttle-multiselect.html
src/js/angular/core/filters/search-filter.js
webpack.config.common.js

Implemented the shuttle multiselect component.
It is needed for some of the new graphql feature views.
Implemented a new reusable and configurable directive .
NA - will be added with the integration of the component

GDB-11573 shuttle multiselect component

---

Jenkinsfile
src/css/graphql/create-graphql-endpoint.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/services/graphql.service.js
src/js/angular/graphql/controllers/create-graphql-endpoint-view.controller.js
src/js/angular/graphql/directives/configure-endpoint.directive.js
src/js/angular/graphql/directives/generate-endpoint.directive.js
src/js/angular/graphql/directives/select-schema-sources.directive.js
src/js/angular/graphql/services/endpoint-generation-report.mapper.js
src/js/angular/graphql/services/graphql-context.service.js
src/js/angular/graphql/templates/step-generate-endpoint.html
src/js/angular/graphql/templates/step-select-schema-sources.html
src/js/angular/models/graphql/create-endpoint-from-owl-request.js
src/js/angular/models/graphql/create-endpoint-from-shapes-request.js
src/js/angular/models/graphql/create-endpoint-wizard-steps.js
src/js/angular/models/graphql/endpoint-generation-report.js
src/js/angular/models/graphql/graphql-endpoint-configuration-setting.js
src/js/angular/models/graphql/graphql-endpoint-configuration.js
src/js/angular/models/graphql/graphql-endpoint-overview-list.js
src/js/angular/models/graphql/graphql-schema-shapes.js
src/js/angular/models/graphs/graph-list-options.js
src/js/angular/rest/graphql.rest.service.js
test-cypress/integration/graphql/create-graphql-endpoint.spec.js

Implemented the endpoint generation overview and generate action.
This is the thrird and last step in the graphql endpoint generation workflow which allows the user to oversee and potentially correct the genration settings and data selected to be included in the endpoint generation.
Implemented a component that renders the generation overview and integrated a handler for the generate action.
Also improved the transition between workflow steps and maintaining the state between the steps.

GDB-11575 graphql endpoint overview and generate

---

src/css/graphql/graphql-endpoint-management.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/graphql/controllers/create-graphql-endpoint-view.controller.js
src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
src/js/angular/graphql/controllers/graphql-playground-view.controller.js
src/js/angular/graphql/directives/generate-endpoint.directive.js
src/js/angular/graphql/services/graphql-context.service.js
src/js/angular/graphql/templates/graphql-endpoint-management.html
src/js/angular/graphql/templates/modal/endpoint-generation-failure-result-modal.html
src/js/angular/graphql/templates/step-generate-endpoint.html
src/js/angular/models/form-fields.js
src/js/angular/models/graphql/create-endpoint-from-owl-request.js
src/js/angular/models/graphql/graphql-endpoint-configuration.js
src/js/angular/models/graphql/graphql-endpoints-info.js
src/js/angular/models/graphs/graph-list-options.js

Adds various changes and improvements to GraphQL endpoint management and generation.
Enhance the functionality of GraphQL endpoint management.
Improve user experience by adding more detailed status indicators and additional actions.
Refactor and clean up the code to ensure better maintainability and readability.
* Added status indicators for GraphQL endpoint creation in the CSS.
* Updated localization files.
* Modified controllers and directives to handle new events (EXPLORE_ENDPOINT_IN_PLAYGROUND and OPEN_ENDPOINT_GENERATION_REPORT), including the ability to open endpoints in the playground and view generation reports.
* Refactored methods in services to use the new event names and added polling for endpoint information in the management view.
Tests will be added in next MR
NA

GDB-11575-generate-endpoint-from-owl

---

package-lock.json
package.json
src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/models/sparql/tab-query-model.js
src/js/angular/rest/mappers/saved-query-mapper.js
test-cypress/integration/sparql-editor/saved-query/readonly-query.spec.js
test-cypress/steps/yasgui/saved-queries-dialog.js

An incorrect error message, "Query 'Shared with other users' doesn't exist", appears when attempting to delete or edit a query created by another user.
There are no restrictions on actions that the currently logged-in user can perform on a saved query.
Iterate over all saved queries and mark them as readonly if the query owner is different from the currently logged-in user.

GDB-11281: Trying to delete a other user's saved query results in an incorrect error

---

src/css/graphql/create-graphql-endpoint.css
src/css/graphql/graphql-endpoint-management.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/services/graphql.service.js
src/js/angular/graphql/controllers/graphql-endpoint-management-view.controller.js
src/js/angular/graphql/services/endpoint-info-list.mapper.js
src/js/angular/graphql/templates/graphql-endpoint-management.html
src/js/angular/graphql/templates/step-generate-endpoint.html
src/js/angular/models/graphql/graphql-endpoints-info.js
src/js/angular/models/graphql/update-endpoint-request.js
src/js/angular/rest/graphql.rest.service.js
test-cypress/fixtures/locale-en.json
test-cypress/integration/graphql/graphql-activate-deactivate-endpoint.spec.js
test-cypress/steps/graphql/graphql-endpoint-management-steps.js

Implemented action that allows changing the endpoint active state.
This allows the user to effectively disable the endpoint.
Implemented a toggle in the endpoint management page for each endpoint that allows switching the state.
Implemented tests.

GDB-11562 toggle endpoint active state

---

src/css/dynamic-form.css
src/css/graphql/create-graphql-endpoint.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/dynamic-form/templates/dynamic-form.html
src/js/angular/graphql/templates/create-graphql-endpoint.html
src/js/angular/graphql/templates/step-generate-endpoint.html
src/js/angular/graphql/templates/step-select-schema-sources.html
src/js/angular/models/graphql/graphql-endpoint-configuration.js
src/js/angular/models/graphql/graphql-endpoint-overview-list.js
test-cypress/integration/graphql/create-graphql-endpoint.spec.js
test-cypress/integration/graphql/import-graphql-endpoint-definitions.spec.js
test-cypress/steps/graphql/create-graphql-endpoint-steps.js

Improved some visual discrepancies in the create endpoint view.
To improve the user experience and solve som evisual bugs
* Add endpoint description field in the create endpoint configuration form and update tests.
* Improve layout of the endpoint configuration form. Labels and fields now have proportionate widths regardless the resolution.
* Improve the dynamic form layout so that it scale and shrink properly regarding screen resolution.
* Make the label bolder in the endpoint generation overview.
* Improve layout in the create endpoint wizard to be more flexible.
Updated tests where needed.

GDB-11770 improve create endpoint workflow view

---

src/css/dynamic-form.css
src/css/graphql/graphql-endpoint-management.css
src/i18n/locale-en.json
src/i18n/locale-fr.json
src/js/angular/core/directives/dynamic-form/dynamic-form.directive.js
src/js/angular/core/directives/dynamic-form/templates/dynamic-form.html
src/js/angular/graphql/plugin.js
src/js/angular/graphql/templates/graphql-endpoint-management.html
src/js/angular/graphql/templates/modal/endpoint-configuration-modal.html
src/js/angular/graphql/templates/step-configure-endpoint.html
src/js/angular/graphql/templates/step-generate-endpoint.html
src/js/angular/graphql/templates/step-select-schema-sources.html
src/js/angular/models/graphql/endpoint-definition-file.js

* The dynamic form component used to render configuration properties is extended to render proper labels and tooltips as well as error messages when a field goes invalid.
* Added more labels and help info messages to other views in the graphql module.
* Improve some styles.
To help users better understand and use the graphql module features.
Extended the dynamic form component by removing the placeholders and added error messages for the invalid state. Added proper labels rendering and tooltips, improved styling.
Added help infoo messages to other views in the module.
NA

GDB-11802 improve endpoint generation settings step

---

src/i18n/locale-en.json
test-cypress/fixtures/locale-en.json

Change label "Explain settings" in TTYG to "Review agent instructions"
Improve user expirence
Adding more clarity to the button label so that it accurately reflects its function
Change in existing one

GDB-11752-UX/UI-Change-the-label-Explain-settings-in-the-Agent-settings-modal

---

src/js/angular/core/directives/dynamic-form/dynamic-form-field.directive.js
src/js/angular/core/directives/dynamic-form/dynamic-form.directive.js
src/js/angular/core/directives/dynamic-form/field-type.js
src/js/angular/rest/mappers/dynamic-form-fied-mapper.js
test-cypress/integration/graphql/create-graphql-endpoint.spec.js
test-cypress/integration/graphql/edit-graphql-enpoint.spec.js

Fix compilation of dynamic form field directive in production build.
The way the dynamic form field directive was implemented was causing issues during production build because of the minification of the code which appeared to brake the injection of the scope property.
Changed the implementation of the directive with proper injecttion.
Un-skipped existing tests which were failing due to this problem.
NA

GDB-11856 fix compilation of dynamic form field directive in production build

---

package-lock.json

Perform vulnerability scan and update necessarry libraries.
Preparation for the WB3.0 (GDB11.0) release.

GDB-11891 WB3.0 dependency updates

---

package-lock.json
src/js/angular/rest/jdbc.rest.service.js
test-cypress/cypress.config.js
test-cypress/integration/graphql/edit-graphql-enpoint.spec.js
test-cypress/integration/repository/ontop-repository.spec.js
test-cypress/integration/repository/repository-commands.spec.js
test-cypress/integration/setup/namespaces.spec.js
test-cypress/steps/repository-steps.js
test-cypress/stubs/jdbc/jdbc-stubs.js
test-cypress/stubs/repositories/repositories-stubs.js
test-cypress/support/repository-commands.js

Fixing issues with http requests using API urls with trailing slash
After the spring boot upgrade in the backend, some issues appeared in the WB application due to the fact that the rest controller now doesn't expect REST API urls to end with a `/`. It appeared that there are issues with the cypress tests as well as some other with the application code as well.
Fixed request urls where needed to prevent having trailing slash.
Updated tests
NA

GDB-11994 Fixing issues with http requests using API urls with trailing slash

---

package-lock.json
src/js/angular/rest/jdbc.rest.service.js
test-cypress/cypress.config.js
test-cypress/integration/graphql/edit-graphql-enpoint.spec.js
test-cypress/integration/repository/ontop-repository.spec.js
test-cypress/integration/repository/repository-commands.spec.js
test-cypress/integration/setup/namespaces.spec.js
test-cypress/steps/repository-steps.js
test-cypress/stubs/jdbc/jdbc-stubs.js
test-cypress/stubs/repositories/repositories-stubs.js
test-cypress/support/repository-commands.js

Fixing issues with http requests using API urls with trailing slash
After the spring boot upgrade in the backend, some issues appeared in the WB application due to the fact that the rest controller now doesn't expect REST API urls to end with a `/`. It appeared that there are issues with the cypress tests as well as some other with the application code as well.
Fixed request urls where needed to prevent having trailing slash.
Updated tests
NA

GDB-11994 3.0 fixing issues with http request urls

---

package-lock.json
package.json

Reverts Ontotext-AD/graphdb-workbench#1896
Changes incorrect

Revert "GDB-10933 - Update Yasgui version with label update"

---

package-lock.json
package.json
test-cypress/integration/setup/namespaces.spec.js

Reverts https://github.com/Ontotext-AD/graphdb-workbench/pull/1896
Changes incorrect

(cherry-pick) Revert "GDB-10933 - Update Yasgui version with label update"

---

test-cypress/integration/setup/user-and-access.spec.js

Revert test added with commit
Added by mistake
- Revert

fix(GDB-11897) Migrate pipelines to new Jenkins revert test 2.8

---

package-lock.json
package.json
src/js/angular/core/directives/yasgui-component/yasgui-component.directive.js
src/js/angular/rest/mappers/saved-query-mapper.js
src/js/angular/rest/sparql.rest.service.js
test-cypress/integration/sparql-editor/saved-query/edit-query.spec.js
test-cypress/support/sparql-commands.js

When a user edits a saved query, they will be able to edit the name without getting an error.
Previously, only editing the body of the query was possible, because the BE searches for them by name.
I added the original query name in the payload, so the BE can process it.
Added, but skipped until BE release a server version with the changes.
N/A

GDB-12134 - Create a new payload for saved query update

---

e2e-tests/e2e-legacy/explore/graphs-overview/graphs.overview.spec.js
e2e-tests/e2e-legacy/explore/graphs-overview/initial-state/graphs-overview-with-selected-repository.spec.js
e2e-tests/e2e-legacy/explore/graphs-overview/initial-state/graphs-overview-without-selected-repository.spec.js
e2e-tests/e2e-legacy/import/initial-state/import-page-with-selected-repositor.js
e2e-tests/e2e-legacy/import/initial-state/import-page-with-selected-repository-without-imported-files.js
e2e-tests/e2e-legacy/import/initial-state/import-page-without-selected-repository.spec.js
e2e-tests/steps/explore/graphs-overview-steps.js
e2e-tests/steps/import/import-user-data-steps.js
e2e-tests/steps/main-menu-steps.js
packages/legacy-workbench/src/pages/export.html

Added tests to verify the initial state of the Import and Graphs overview views.
To ensure that the views load correctly and prevent navigation issues during the view migration process.
Added a test for the views that verifies:
N/A

GDB-12173: Make sure that all application views are accessible and have the expected initial state

---

e2e-tests/e2e-legacy/explore/class-hierarchy/class-hierarchy-with-selected-repository-without-class-hierarchy.js
e2e-tests/e2e-legacy/explore/class-hierarchy/class-hierarchy-with-selected-repository.js
e2e-tests/e2e-legacy/explore/class-hierarchy/class-hierarchy-without-selected-repository.js
e2e-tests/e2e-legacy/explore/class-hierarchy/class.hierarchy.spec.js
e2e-tests/steps/class-views-steps.js
e2e-tests/steps/explore/graphs-overview-steps.js
e2e-tests/steps/main-menu-steps.js
packages/legacy-workbench/src/pages/rdfClassHierarchyInfo.html

Added tests to verify the initial state of the Class hierarchy.

GDB-12173 Add initial state tests for the Class hierarchy view

---

packages/root-config/src/styles/main.scss
packages/shared-components/src/components/onto-layout/onto-layout.scss

Applies CSS reset to html and body elements.
html and body elements are collapsed when there is less content on the page. This makes child block containers without explicit height to be collapsed as well.
Applied height:100% to html and body elements and applied also height to wb-layout container.

GDB-12431 Apply CSS reset to html and body elements

---

package-lock.json
package.json

The new version includes:
GDB-10933 - Rename options in download list
Updated to see label changes.
Version updated.
N/A
N/A

GDB-10933 - Upgrade Yasgui version

---

packages/legacy-workbench/src/js/angular/guides/guides.service.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/class-hierarchy/plugin.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/execute-sparql-query/plugin.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/table-graph/plugin.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/edit-ttyg-agent/plugin.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/visual-graph/plugin.js
packages/legacy-workbench/src/js/angular/guides/tour-lib-services/shepherd.service.js

The Star Wars guide's previous flow was not working.
There were some issues with navigation after starting to use single-spa.
Updated the navigation to use single-spa navigation for the broken steps.
N/A
N/A

GDB-12484: Fixes previous flow of star wars guide

---

e2e-tests/e2e-legacy/home/home-page-without-repositories.spec.js
packages/api/src/models/app-lifecycle/index.ts
packages/api/src/models/app-lifecycle/lifecycle-state.ts
packages/api/src/models/events/event-name.ts
packages/api/src/ontotext-workbench-api.ts
packages/api/src/services/app-lifecycle/application-lifecycle-context.service.ts
packages/api/src/services/app-lifecycle/index.ts
packages/api/src/services/app-lifecycle/test/application-lifecycle.context.service.spec.ts
packages/api/src/services/security/security-rest.service.ts
packages/api/src/services/security/security.service.ts
packages/root-config/src/bootstrap/bootstrap.js
packages/root-config/src/bootstrap/repository/repository-bootstrap.js
packages/root-config/src/bootstrap/security/security-bootstrap.js
packages/root-config/src/ontotext-root-config.js
packages/shared-components/src/components/onto-header/onto-header.tsx
packages/shared-components/src/components/onto-navbar/onto-navbar.tsx

Refactor bootstrap functionality to sync initial requests
To ensure correct data is loaded, whenever it needs to be
The new flow is as follows:
1. Load language bundles, before single spa starts and custom components are defined
2. Load security config
3. Subscribe to security config change. Whenever this occurs, the app will request an authenticated user, if security is enabled.
4. Subscribe to authenticated user change. Whenever this happens, the application will load repositories and then the rest of the data
5. Start single spa and create custom elements
Also removed repository update in `onto-layout` as it causes unexpected behavior.
existing

GDB-12528 Refactor bootstrap functionality

---

e2e-tests/e2e-legacy/setup/aclmanagement/revert-rules.spec.js
e2e-tests/e2e-legacy/setup/aclmanagement/update-rules.spec.js
e2e-tests/e2e-legacy/setup/sparql-template-create.js
e2e-tests/e2e-legacy/sparql-editor/yasgui-tabs.spec.js
e2e-tests/steps/application-steps.js

Fixed and re-enabled the all skipped test suites due changes in the main menu.
The test suite was disabled due to migration caused issues
- re-enabled all tests

fix(GDB-11410): WBM Fix tests with problems from changes in the main menu

---

src/js/angular/core/directives/angulartooltips/angular-tooltips.js

Mozilla was crashing the Workbench with a "too much recursion" error.
We have an angular-tooltip directive that displays a tooltip on hover. When the user hovers over an element, the directive calculates the position where the tooltip should appear.
The issue arises because the tooltip's position may vary between the moment the mouse enters the element and when the tooltip is displayed. This is due to styles being applied to the tooltip on display, which can affect its size and position.
To handle this, the directive uses recursion to continuously check the top and left positions of the tooltip. If they change, a new position is calculated. However, since these positions are calculated in floating-point values, small differences (due to rounding) can cause the comparison to fail and the …

GDB-12591: Mozilla crashing WB with too much recursion

---

packages/root-config/src/index.ejs

Comment out CSP definition in `index.ejs`
Causes blockage with external auth services. TBD and decided where the CSP should be implemented.
- commented out the CSP definition in `index.ejs`

GDB-12615 Disable CSP

---

e2e-tests/e2e-legacy/ttyg/agent-list.spec.js
e2e-tests/steps/ttyg/ttyg-view-steps.js

Stabilize agent-list.spec.js
Broken due to migration
How
- added additional checks for the panel and agent to be visible
- added closing of the agent menu before opening another
cypress

GDB-11410 Stabilize agent-list.spec.js

---

src/js/angular/repositories/controllers.js
src/js/angular/sparql-template/controllers.js

Replaced self closing spans with closing tag
It caused the span to wrap the adjacent element and applying its style to it.
- refactored spans
before
after

GDB-12660: Fixes self closing spans wrapping adjacent element

---

e2e-tests/cypress-legacy.config.js
e2e-tests/e2e-legacy/graphql/import-graphql-endpoint-definitions.spec.js
e2e-tests/e2e-legacy/home/cookie-policy.spec.js
e2e-tests/e2e-legacy/home/documentation-link.spec.js
e2e-tests/e2e-legacy/home/google-analytics.spec.js
e2e-tests/e2e-legacy/setup/users-and-access/user-and-access.spec.js
e2e-tests/e2e-legacy/ttyg/ttyg-permission.spec.js
e2e-tests/steps/home-steps.js
e2e-tests/steps/setup/settings-steps.js
packages/api/src/services/cookie/cookie.service.ts
packages/legacy-workbench/src/js/angular/graphql/controllers/import-endpoint-definition-modal.controller.js
packages/legacy-workbench/src/js/angular/graphql/templates/modal/import-endpoint-definition-modal.html
packages/shared-components/src/components/dialogs/onto-cookie-policy-dialog/onto-cookie-policy-dialog.tsx
packages/shared-components/src/components/dialogs/onto-dialog.tsx
packages/shared-components/src/components/dialogs/readme.md

Fix and enable various specs
Broken due to migration
How
- enabled and fixed specs

GDB-11410 Fix and enable broken tests from migration

---

e2e-tests/fixtures/locale-en.json
packages/legacy-workbench/src/i18n/locale-en.json
packages/legacy-workbench/src/i18n/locale-fr.json

The title's info popover text, help box text and "No agents" info text has some minor changes.
The edits reflect the changes in the BE functionality.
I edited the language files.
N/A
N/A

GDB-12684 - Update text in TTYG view

---

src/i18n/locale-en.json
src/i18n/locale-fr.json
test-cypress/fixtures/locale-en.json

The title's info popover text, help box text and "No agents" info text has some minor changes.
The edits reflect the changes in the BE functionality.
I edited the language files.
N/A
N/A

(cherry-pick) GDB-12684 - Update text in TTYG view

---

packages/legacy-workbench/src/i18n/locale-en.json
packages/legacy-workbench/src/i18n/locale-fr.json
packages/legacy-workbench/src/js/angular/guides/guide-utils.js
packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/fts-search-method/plugin.js
packages/legacy-workbench/src/js/angular/ttyg/templates/modal/agent-settings-modal.html

Implement step for configuring agent using FTS extraction method and providing max number of triples value
Expand the interactive guides
How
- added new steps for configuring agent using FTS extraction method and providing max number of triples value
- changed logic if `GuideUtils.validateTextInput` to convert

GDB-12854 Add step to TTYG for FTS Method to set max number of triples

---

packages/legacy-workbench/src/js/angular/guides/steps/complex/enable-autocomplete/plugin.js

The `enable autocomplete` core steps have been extracted.
Extracting the steps allows developers to reuse them.

GDB-12885 - Extract enable-autocomplete steps

---

packages/legacy-workbench/src/js/angular/guides/steps/complex/enable-autocomplete/plugin.js

The enable autocomplete core steps have been extracted.
Extracting the steps allows developers to reuse them.

(cherry-pick) GDB-12885 - Extract enable-autocomplete steps

---

assets/.gitignore
assets/configuration.default.json
assets/env.template.json
packages/api/src/error/error-base.ts
packages/api/src/error/index.ts
packages/api/src/models/configuration/configuration.ts
packages/api/src/models/configuration/environment.ts
packages/api/src/models/configuration/index.ts
packages/api/src/ontotext-workbench-api.ts
packages/api/src/providers/index.ts
packages/api/src/providers/service/service-inject.ts
packages/api/src/services/configuration/configuration-context.service.ts
packages/api/src/services/configuration/configuration-rest.service.ts
packages/api/src/services/configuration/configuration.service.ts
packages/api/src/services/configuration/env.default.json
packages/api/src/services/configuration/index.ts
packages/api/src/services/configuration/missing-application-configuration-error.ts
packages/api/src/services/configuration/test/configuration-context.service.spec.ts
packages/api/src/services/configuration/test/configuration.service.spec.ts
packages/api/src/services/plugins/plugins-rest.service.ts
packages/api/src/services/plugins/plugins.service.ts
packages/api/src/services/plugins/test/plugins.service.spec.ts
packages/root-config/src/bootstrap/bootstrap.js
packages/root-config/src/bootstrap/configuration/configuration-bootstrap.js
webpack.config.common.js

This PR introduces a configuration system that allows the workbench application to accept configurations via JSON files in the public assets folder, making the application more flexible and customizable.
Unlocks the possibility to configure certain asspects of the application through external configuration file.
Adds configuration services to load and manage application settings from JSON files.
Implements a two-tier configuration system with environment files and configuration files.
Refactors plugin loading to use configurable manifest paths instead of hardcoded values.
Unit tests added.

GDB-12936 workbench configurations

---

packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/common/sparql-search-method/plugin.js

The `sparql-search-method` core steps have been extracted.
Extracting the steps allows developers to reuse them.

GDB-12885 - Extract SPARQL method steps

---

packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js

Allow the user to scroll and see the explanation result in TTYG, while on the guide
It's currently not possible, as the chat panel is readonly. This results in the user not being able to see the explanation
- Removed the readonly option for `hold-and-wait-until-hidden` steps
- Added events listeners for click and double-click on `show` and `hide`, which prevent user interaction. This way the user can scroll, but can't trigger anything else (click other buttons) and possibly break the guide.
n/a

GDB-12891 Allow user to scroll and read TTYG explanation

---

packages/legacy-workbench/src/js/angular/guides/steps/complex/ttyg/conversation-with-ttyg-agent/plugin.js

The `conversation-with-ttyg-agent` core steps have been extracted.
Extracting the steps allows developers to reuse them.

GDB-12885 - Extract Conversation with TTYG agent steps

---

assets/.gitignore
assets/configuration.default.json
assets/env.template.json
packages/api/src/error/error-base.ts
packages/api/src/error/index.ts
packages/api/src/models/configuration/configuration.ts
packages/api/src/models/configuration/environment.ts
packages/api/src/models/configuration/index.ts
packages/api/src/ontotext-workbench-api.ts
packages/api/src/providers/index.ts
packages/api/src/providers/service/service-inject.ts
packages/api/src/services/configuration/configuration-context.service.ts
packages/api/src/services/configuration/configuration-rest.service.ts
packages/api/src/services/configuration/configuration.service.ts
packages/api/src/services/configuration/env.default.json
packages/api/src/services/configuration/index.ts
packages/api/src/services/configuration/missing-application-configuration-error.ts
packages/api/src/services/configuration/test/configuration-context.service.spec.ts
packages/api/src/services/configuration/test/configuration.service.spec.ts
packages/api/src/services/plugins/plugins-rest.service.ts
packages/api/src/services/plugins/plugins.service.ts
packages/api/src/services/plugins/test/plugins.service.spec.ts
packages/root-config/src/bootstrap/bootstrap.js
packages/root-config/src/bootstrap/configuration/configuration-bootstrap.js
webpack.config.common.js

This PR introduces a configuration system that allows the workbench application to accept configurations via JSON files in the public assets folder, making the application more flexible and customizable.
Unlocks the possibility to configure certain asspects of the application through external configuration file.
Adds configuration services to load and manage application settings from JSON files.
Implements a two-tier configuration system with environment files and configuration files.
Refactors plugin loading to use configurable manifest paths instead of hardcoded values.
Unit tests added.

GDB-12936 (3.1) workbench configurations

---

packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js

Introduce a new core guide step type "scroll-only-element". It allows scrolling only within the selected element.
This is especially useful when displaying a scrollable element and restricting user interaction to scrolling or selecting its content.
The new step:
- Prevents non-scroll events while the step is active;
- Re-enables all events when the step is closed to restore default Workbench interactivity.
(cherry picked from commit cc5cc5aca209a39e40f13b5ef48cc2fdcb0f69fd)

Cherry-pick GDB-12981: Add new core guide step for scrolling inside selected element

---

package.json
packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js
scripts/copy-plugins.sh
webpack.config.dev.js

* Added scripts that would ease the plugin development.
* Updated the copy-plugins.sh 
* Preparation for the guide steps extraction from the workbench into the new plugins project.
* Changes in the copy-plugins script would allow dev server to watch and reload the application in case of changes in the folder.
* Implemented new npm scripts useful for the plugins development.
* Changed the copy-plugin.sh script to update the plugins folder instead of recreating it each time.
NA

GDB-12871 preparation for guide steps extraction

---

packages/legacy-workbench/src/js/angular/guides/guide-utils.js
packages/legacy-workbench/src/js/angular/guides/steps/core/plugin.js
packages/legacy-workbench/src/js/angular/utils/object-utils.js

Fix form not updating, when copying additional instructions from the TTYG guide
It wasn't being sent in the request to the backend. As a result the agent is created without them and behaves unexpectedly.
Dispatched an input event inside `validateTextInput`. This way angular triggers a digest cycle and the form is updated and sent in the request.
n/a

Cherry-pick GDB-12997 Fix form not updating, when additional instructions are copied during agent creation

---

packages/legacy-workbench/src/i18n/locale-en.json
packages/legacy-workbench/src/i18n/locale-fr.json
packages/legacy-workbench/src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js

Label of Maximum links to show toast info message is updated to be easier to understand. ESLint issues handled in the controller.
Previous message was confusing for users.
I updated the string and fixed most of the eslint issues in the controller.
N/A

GDB-6283 - Visual Graph connections info message update

---

packages/legacy-workbench/src/i18n/locale-en.json
packages/legacy-workbench/src/i18n/locale-fr.json
packages/legacy-workbench/src/js/angular/graphexplore/controllers/graphs-visualizations.controller.js

Label of Maximum links to show toast info message is updated to be easier to understand. ESLint issues handled in the controller.
Previous message was confusing for users.
I updated the string and fixed most of the eslint issues in the controller.
N/A

(cherry-pick) GDB-6283 - Visual Graph connections info message update
